### ISSUE TITLE
Socialite not working with Github or FB.

### ISSUE THREAD

**Issue by sdeering** [rappasoft/laravel-5-boilerplate#10]
Github gives 404.

FB gives missing param.

![image](https://cloud.githubusercontent.com/assets/1787454/7467716/1055d832-f342-11e4-9000-ea6269dbb763.png)

**Comment by rappasoft** [comment]
Im gonna close the socialite issues for now because no ones getting anywhere with them. I'll try again soon.

**Comment by sdeering** [comment]
@rappasoft  Ok thanks for the update. I have a decent bootstrap for L5 with some cool features I'll cross ref with yours and maybe it will solve it.

**Comment by rlabrovi** [comment]
here I would refer on twitter login. Since twitter api does not allow saving e-mail address, there is an error because the e-mail in the database is not null. The user should enter a mail after log in, with update of profile.
