### ISSUE TITLE
Visual Installer

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-5-boilerplate#100]
Finished permission dependencies feature.

Next feature is going to be a visual installer. So basically all you would have to do is upload the files, and the installer would check for php modules needed, folder permissions, create the keys, run composer, migrate, and seed. All through a series of steps much like all the other big applications.

Any ideas before I begin?

Oh course if you want you will still be able to do all of these things manually.

All it will really be doing is give a nice UI and run Artisan::run('command') in the background.

**Comment by rappasoft** [comment]
Done!

**Comment by blomdahldaniel** [comment]
Hey this is cool. I started a comment here earlier today but forgot to post it and now you are done xD Great stuff.

I havn't checked it out yet but want to include the following pointers of what i wrote earlier today:

* Configure whether you want email-activation upon registration.
* Configure roles and permissions and configure standard user rights.
* Create user and assign roles

This is some really cool stuff man, your on fire! And like you said in another issue, now its time to fine tune and find improvements of these great features. :+1:

**Comment by rappasoft** [comment]
The seeder sets everything in terms of default users/roles/permissions, which the installer runs. It's really not much. Didn't want to go overboard since I based it off of an existing package.
