### ISSUE TITLE
Remember me not working

### ISSUE THREAD

**Issue by lloricode** [rappasoft/laravel-5-boilerplate#1002]
Hi @rappasoft ! :)

I'm using latest of this project, then Ive noticed that the `remember me` is not work as expected,

Thanks Best regards :)

**Comment by poseso** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/blob/master/config/session.php#L34    true instead of false

**Comment by lloricode** [comment]
@poseso Thanks :+1:
