### ISSUE TITLE
Add API Routes with JWT Authentication

### ISSUE THREAD

**Issue by bambamboole** [rappasoft/laravel-5-boilerplate#1005]
Today API's are more relevant than ever before. That's why I thought it would be nice to have Api Routes for the user model with JWT Authentication. We could also leverage the new Laravel 5.5 Api Resources.

It would also be a nice feature to have a starting point for Api's with a working stateless Authentication in the boilerplate.

This could also be a starting point to make use of Vue.js in the Backend to have a more reactive User Administration.

What are your thoughts about this?

**Comment by bryanrscott** [comment]
+1 from me for adding api starting point.

**Comment by rappasoft** [comment]
It's fine as long as it's not getting in the way of what a 'boilerplate' should be, and also it would be nice if you could make a PR to the documentation to add docs/examples if you have time.

**Comment by bryanrscott** [comment]
Would a start be adding composer requirement for tymon/jwt-auth ?

**Comment by bambamboole** [comment]
@bryanrscott 
yeah this will be the dependency for that. But I don't find the time to tackle this.
Maybe in March will be more spare time to start this :-)

**Comment by aalaap** [comment]
I'm willing to take this up.

**Comment by bambamboole** [comment]
@aalaap that would be really nice.

**Comment by bingalls** [comment]
@aalaap Take a look at https://github.com/generationtux/jwt-artisan

**Comment by aalaap** [comment]
@bingalls Best. `README`. Ever.

This is nice, but I'm now exploring the benefit including Dingo's API features, instead of simply the JWT authentication bit. Dingo includes JWT authentication.

**Comment by gileneusz** [comment]
api examples are needed (with jwt or even passport)

**Comment by poseso** [comment]
there are tons of tutorials about it:

https://laravelcode.com/post/restful-api-in-laravel-55-using-jwt-authentication
https://medium.com/@mosesesan/tutorial-5-how-to-build-a-laravel-5-4-jwt-authentication-api-with-e-mail-verification-61d3f356f823

etc..
