### ISSUE TITLE
Timeout Error when running phpunit

### ISSUE THREAD

**Issue by vutrungduc7593** [rappasoft/laravel-5-boilerplate#1007]
I use boilerplate version 5.0.5, php 7.2.
When i run **composer phpunit**, it do nothing until showing timeout error.
Does anyone know how to fix or debug it (I run with --debug param but it didn't show anything)?

**Comment by bambamboole** [comment]
@vutrungduc7593 please try to run `./vendor/bin/phpunit` from the root of the project.
The project isn't tested on PHP 7.2 afaik.

**Comment by vutrungduc7593** [comment]
I tried to run ./vendor/bin/phpunit and used php 7.1.0 but it's still not working.
It's still ok when i use boilerplate for laravel 5.4 and template project 5.5 created from laravel.

**Comment by bambamboole** [comment]
hmm I just cloned the project and ran tests and they are running. When you set mail driver to log in .env then they are all green...
![phpunit](https://user-images.githubusercontent.com/8823695/35146741-35559c90-fd0c-11e7-8fe2-a5faade071c3.png)

**Comment by vutrungduc7593** [comment]
I forgot to tell that i'm using windows 10 and i directly downloaded php from official site, maybe it's because i missed some extensions when config php.ini. Do you know which extensions needed to run phpunit?

**Comment by bambamboole** [comment]
Just include the normal Laravel PHP Dependencies and you should be good to go.
https://laravel.com/docs/5.5#server-requirements

**Comment by excetera** [comment]
In my case, I can use vendor/bin/phpunit after I remove printerClass="Codedungeon\PHPUnitPrettyResultPrinter\Printer" from phpunit.xml. It's working, but of course there's no pretty display in test result.

**Comment by vutrungduc7593** [comment]
Wow, thank you @excetera, it's working now

**Comment by bambamboole** [comment]
I think this is related to [this issue](https://github.com/mikeerickson/phpunit-pretty-result-printer/issues/13) .
We have to wait until the next version of the result printer.

Another question would be if we really should support windows...

**Comment by vutrungduc7593** [comment]
@bambamboole i'm ok without result printer

**Comment by rappasoft** [comment]
No offense windows people but i'm not worried about supporting you guys :)

**Comment by irman** [comment]
Well I just installed this and found out you don't support windows? That's odd, considering: 
![image](https://user-images.githubusercontent.com/6107943/35382367-fb1ed63e-01f9-11e8-9a88-73d9cc849d23.png)
