### ISSUE TITLE
Error mcrypt_encrypt() at /install

### ISSUE THREAD

**Issue by blomdahldaniel** [rappasoft/laravel-5-boilerplate#101]
I got an error when I made a clean install and tried to enter the /install page.
Is there something i have to fix with my apache to be able to run this setup? Or what could be wrong? Is it something that need to be fixed before installation now when it is done by the GUI installer?

```
ErrorException in McryptEncrypter.php line 92:
mcrypt_encrypt(): Key of size 17 not supported by this algorithm. Only keys of sizes 16, 24 or 32 supported
```

**Comment by rappasoft** [comment]
Hmm. I don't get that problem. Make sure you composer install before you use it, the GUI installer can't run composer, its only for checking permissions and php extensions, migrations and seeds.

**Comment by blomdahldaniel** [comment]
both composer and npm completed successfully... Hm...

**Comment by blomdahldaniel** [comment]
Hm, as it turned out i had to do the php key:generate to get it to work properly. The mcrypt() was yelling att the `APP_KEY=WILL BE GENERATED`

So after clone i did:
`composer install`
`npm install`

Then I had to do a `php artisan key:generate``

Was this something that you missed perhaps working on it since you had the key from your old .env in there at the beginning?

**Comment by rappasoft** [comment]
Weird, no I have the key generate function run right before it migrates, I guess I need to have them do it before they even go to the install link.

**Comment by rappasoft** [comment]
Did you get it to work after that?

**Comment by rappasoft** [comment]
Ok I made a hotfix to the docs and the database installer step. Key should be generated before the user hits /install. I didn't get the error because I already had the key generated in my file as I built the module.
