### ISSUE TITLE
Dockerfile support feature 

### ISSUE THREAD

**Issue by mikimaine** [rappasoft/laravel-5-boilerplate#1015]
I am about to create a pull request with docker setup for development and production.

Before I do so I want to make sure if you can see the benefits.

Personally, I think it will be very important for this boilerplate to include a development and production docker configuration as it will make it a more CI and testing oriented project. I will also minimize the errors that are caused by environmental differences, as you can test you prod environment locally. Plus you will not need to setup PHP, Mysql, and Redis on your local computer.

@rappasoft if you agree I can make the pull request now.

**Comment by rappasoft** [comment]
Feel free to make it so I can look it over, thanks.

**Comment by rokde** [comment]
You can add [vessel](https://vessel.shippingdocker.com). It is done for this use case.

**Comment by bambamboole** [comment]
I think vessel is only for development and not for production @rokde

**Comment by mikimaine** [comment]
Yes, vessel is for development only. 
I am completing the configuration (I was a bit busy this week) I will make the PR over the weekend, you guys will look into it.

**Comment by bambamboole** [comment]
@mikimaine lookinf forward to it 👍

**Comment by rokde** [comment]
Yes, vessel is for development but with this docker-compose.yml version you are ready to go to production environment. It should be nearly the same for development and production. Another solution is our [rancherize](https://github.com/ipunkt/rancherize) package. It is a php package and/or a docker-based command to get development and various staging/production environments up and running. In case you have rancher for your cloud this is the right tool.
