### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Sogl** [rappasoft/laravel-5-boilerplate#102]
Hi!

I can help you with adding Russian translation, because Russian is my native language. 
So... what files I need to translate? And how to integrate it into web-app because I want to check before pull?

Now I copied `\resources\lang\en` folder and rename it to `ru`. Some files already translated.

**Comment by rappasoft** [comment]
You need to put ru here: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app%2FHttp%2FMiddleware%2FLocaleMiddleware.php#L15

As well as add it to the dropdown here: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/resources%2Fviews%2Ffrontend%2Fincludes%2Fnav.blade.php#L26

and:

https://github.com/rappasoft/laravel-5-boilerplate/blob/master/resources%2Fviews%2Fbackend%2Fincludes%2Fheader.blade.php#L23

and make sure to translate a ru version in assets/views/backend/lang/ru/welcome.blade.php

Thanks a lot!

**Comment by Sogl** [comment]
I did all what you say and it doesn't work:
![image](https://cloud.githubusercontent.com/assets/7556290/10066908/c85b98a6-62da-11e5-995c-2e85c1e05bbc.png)

Maybe I need to re-build app or something?

**Comment by Sogl** [comment]
Done.
https://github.com/rappasoft/laravel-5-boilerplate/pull/103

**Comment by blomdahldaniel** [comment]
The dropdown could just be a loop through the languages?

**Comment by Sogl** [comment]
Static list, not in every file.

**Comment by rappasoft** [comment]
Merged! Thanks!
