### ISSUE TITLE
Registration issue

### ISSUE THREAD

**Issue by ajitdas123** [rappasoft/laravel-5-boilerplate#1020]
I am trying to check the registration form with newly installed project of this but i am getting error saying

`Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required "`

What could be reason and wht are the fixes?
# What version?
I am using 5.5 version of this application

**Comment by poseso** [comment]
Configure the smtp settings in your .env

**Comment by ajitdas123** [comment]
yes i did,

```
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=465
MAIL_USERNAME=<my email address>
MAIL_PASSWORD=<my password>
MAIL_ENCRYPTION=null
```

**Comment by bambamboole** [comment]
@ajitdas123 can you please provide log output?
