### ISSUE TITLE
phpunit test fails on fresh install

### ISSUE THREAD

**Issue by idleup** [rappasoft/laravel-5-boilerplate#1023]
vagrant@homestead:/web/myproject.dev$ phpunit
PHPUnit 6.5.5 by Sebastian Bergmann and contributors.

 ==> Tests\Feature\Backend\AdminDashboardTest     ✓ ✓ ✓
 ==> Tests\Feature\Backend\Role\CreateRoleTest    ✓ ✖

Time: 1.59 seconds, Memory: 28.00MB

There was 1 failure:

1) Tests\Feature\Backend\Role\CreateRoleTest::the_name_is_required
Session is missing expected key [errors].
Failed asserting that false is true.

/web/myshowstudio.dev/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:635
/web/myshowstudio.dev/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:673
/web/myshowstudio.dev/tests/Feature/Backend/Role/CreateRoleTest.php:30

FAILURES!
Tests: 5, Assertions: 7, Failures: 1.
vagrant@homestead:/web/myproject.dev$

-----------------

This is a fresh install following the install guide with no changes. Version 5.5

**Comment by bambamboole** [comment]
Hi @idleup ,
I can't reproduce the issue when following these steps:

1. clone
2. composer install
3. cp .env.example .env
4. php artisan key:generate
5. ./vendor/bin/phpunit

What were your steps?

**Comment by idleup** [comment]
I followed these instructions exactly: http://laravel-boilerplate.com/5.5/start.html

Everything seemed to work fine I did the steps you mentioned above with the addition of "npm run dev" and seeding the database and all that. I am running in the latest homestead environment (7.1.2). 

One thing I did notice is the failure is on a line of code where it appears the first time the test is trying to create/read from a session. Is it something session related possibly like its not getting created?

**Comment by bambamboole** [comment]
did you generate a key?

**Comment by idleup** [comment]
Yes I did... "php artisan key:generate"

**Comment by bambamboole** [comment]
the session thing is that the assertion in the test get against keys in the session.
But I can't reproduce your error with fresh copy of the boilerplate. 

It would be nice if you could verify that the error still exists with the steps provided by me

**Comment by idleup** [comment]
I reinstalled and am still having failures on the Mac in homestead. But I set up another instance on a windows machine and phpunit completes without any errors. I still think it is session related but not sure how to resolve it.

**Comment by bambamboole** [comment]
@idleup are there any infos in the log files ?

**Comment by idleup** [comment]
What logs does phpunit use? nothing in laravel.log...

**Comment by bambamboole** [comment]
I thought about some kind of php logs...
But I am not able to reproduce this issue... for me everything works like a charm. sorry for that.

**Comment by idleup** [comment]
Yeah, it works for me too from Homestead on a PC, just not the exact same Homestead on a MAC.

**Comment by cleyan** [comment]
Hi
I got 4 errors
is a fresh install
i followed all steps on the readme file


==> Tests\Unit\UserRepositoryTest                ✓ ✓ ✓ ✓ ✓ ✓
 ==> Tests\Feature\Backend\AdminDashboardTest     ✓ ✓ ✓
 ==> Tests\Feature\Backend\Role\CreateRoleTest    ✓ ✓ ✓ ✓ ✓ ✓
 ==> Tests\Feature\Backend\Role\DeleteRoleTest    ✓ ✓ ✓
 ==> Tests\Feature\Backend\Role\ReadRolesTest     ✓
 ==> Tests\Feature\Backend\Role\UpdateRoleTest    ✓ ✓ ✓ ✓ ✓
 ==> ...ature\Backend\User\ChangeUserPasswordTest ✓ ✓ ✖
 ==> Tests\Feature\Backend\User\CreateUserTest    ✓ ✓ ✓ ✖ ✖
 ==> Tests\Backend\User\DeactivateUserTest        ✓ ✓ ✓ ✓
 ==> Tests\Feature\Backend\User\DeleteUserTest    ✓ ✓ ✖ ✓ ✓ ✓
 ==> ...\Feature\Backend\User\ImpersonateUserTest ✓ ✓ ✓
 ==> Tests\Feature\Backend\User\ReadUsersTest     ✓ ✓
 ==> Tests\Feature\Backend\User\UpdateUserTest    ✓ ✓ ✓
 ==> Tests\Feature\Frontend\ChangePasswordTest    ✓ ✓ ✓
 ==> Tests\Feature\Frontend\FillContactFormTest   ✓ ✓ ✓ ✓ ✓ ✓ ✓
 ==> Tests\Feature\Frontend\ResetPasswordTest     ✓ ✓ ✓ ✓ ✓
 ==> Tests\Feature\Frontend\UpdateUserAccountTest ✓ ✓ ✓ ✓ ✓ ✓ ✓ ✓ ✓ ✓
 ==> Tests\Feature\Frontend\UserDashboardTest     ✓
 ==> Tests\Feature\Frontend\UserLoginTest         ✓ ✓ ✓ ✓ ✓ ✓ ✓ ✓
 ==> Tests\Feature\Frontend\UserRegistrationTest  ✓ ✓ ✓ ✓ ✓ ✓ ✓ ✓ ✓ ✓ ✓ ✓ ✓ ✓ ✓
 ==> Tests\Feature\SwitchLanguageTest             ✓


Thank you in advanced


Carlos

**Comment by bambamboole** [comment]
ok, I installed homestead and run the tests... all green.
![bildschirmfoto 2018-02-18 um 04 09 18](https://user-images.githubusercontent.com/8823695/36347816-ad53f19e-1461-11e8-9b76-4e07a262ea3a.png)

**Comment by vduke** [comment]
Having this issue in valet on Mac when doing a fresh install. Followed steps exactly as described. Anyone have any ideas on this? I don't want to have to switch to homestead just to accomplish this. Anyone else have a solution that solves this besides using homestead? Key's are generated, Dependency's installed, Database migrated and seeded. 

<img width="786" alt="screenshot 2018-03-18 11 38 25" src="https://user-images.githubusercontent.com/4578171/37562357-22d26dd8-2aa1-11e8-8c8c-acaf70ef70cd.png">

`here was 1 error:

1) Tests\Feature\Frontend\UserRegistrationTest::a_user_can_register_an_account
Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [App\Models\Auth\User].

/Users/vincentduke/Code/radiastudio/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:416
/Users/vincentduke/Code/radiastudio/app/Repositories/BaseRepository.php:214
/Users/vincentduke/Code/radiastudio/tests/Feature/Frontend/UserRegistrationTest.php:64
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:205
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:153

--

There were 5 failures:

1) Tests\Feature\Backend\Role\UpdateRoleTest::an_admin_can_access_the_edit_role_page
Expected status code 200 but received 500.
Failed asserting that false is true.

/Users/vincentduke/Code/radiastudio/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:78
/Users/vincentduke/Code/radiastudio/tests/Feature/Backend/Role/UpdateRoleTest.php:21
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:205
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:153

2) Tests\Feature\Backend\User\UpdateUserTest::an_admin_can_access_the_edit_user_page
Expected status code 200 but received 500.
Failed asserting that false is true.

/Users/vincentduke/Code/radiastudio/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:78
/Users/vincentduke/Code/radiastudio/tests/Feature/Backend/User/UpdateUserTest.php:25
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:205
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:153

3) Tests\Feature\Frontend\UpdateUserAccountTest::a_user_can_update_his_profile
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Manuel'
+'John'

/Users/vincentduke/Code/radiastudio/tests/Feature/Frontend/UpdateUserAccountTest.php:55
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:205
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:153

4) Tests\Feature\Frontend\UserRegistrationTest::if_requires_approval_is_active_the_user_cant_login
Failed asserting that null matches expected 'Your account was successfully created and is pending approval. An e-mail will be sent when your account is approved.'.

/Users/vincentduke/Code/radiastudio/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:709
/Users/vincentduke/Code/radiastudio/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:727
/Users/vincentduke/Code/radiastudio/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:700
/Users/vincentduke/Code/radiastudio/tests/Feature/Frontend/UserRegistrationTest.php:115
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:205
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:153

5) Tests\Feature\Frontend\UserRegistrationTest::an_event_get_fired_on_registration
The expected [App\Events\Frontend\Auth\UserRegistered] event was not dispatched.
Failed asserting that false is true.

/Users/vincentduke/Code/radiastudio/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/EventFake.php:61
/Users/vincentduke/Code/radiastudio/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221
/Users/vincentduke/Code/radiastudio/tests/Feature/Frontend/UserRegistrationTest.php:131
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:205
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:153

ERRORS!
Tests: 100, Assertions: 198, Errors: 1, Failures: 5.`

**Comment by mattbartel** [comment]
I'm having the same issue in homestead on a Mac. I followed the install directions exactly but most tests are failing because of "Session is missing expected key [errors]." I've tried wiping the install and starting again, but nothing seems to work. 

 ==> Tests\Unit\UserRepositoryTest                ✓ ✓ ✓ ✓ ✓ ✓ 
 ==> Tests\Feature\Backend\AdminDashboardTest     ✓ ✓ ✓ 
 ==> Tests\Feature\Backend\Role\CreateRoleTest    ✓ ✖ ✖ ✖ ⚈ ✖ 
 ==> Tests\Feature\Backend\Role\DeleteRoleTest    ✖ ✖ ✖ 
 ==> Tests\Feature\Backend\Role\ReadRolesTest     ✓ 
 ==> Tests\Feature\Backend\Role\UpdateRoleTest    ✓ ✖ ✖ ✖ ✖ 
 ==> ...ure\Backend\User\ChangeUserPasswordTest   ✓ ✖ ✖ 
 ==> Tests\Backend\User\ConfirmUserTest           ✓ ✓ ✓ ✓ ✓ ✓ ✓ ✓ ✓ 
 ==> Tests\Feature\Backend\User\CreateUserTest    ✓ ✖ ✖ ✖ ✖ 
 ==> Tests\Backend\User\DeactivateUserTest        ✓ ✓ ✓ ✓ 
 ==> Tests\Feature\Backend\User\DeleteUserTest    ✓ ✓ ✓ ✓ ✓ ✖ 
 ==> ...eature\Backend\User\ImpersonateUserTest   ✓ ✓ ✓ 
 ==> Tests\Backend\User\ManageUserSocialTest      ✖ ✖ 
 ==> Tests\Feature\Backend\User\ReadUsersTest     ✓ ✓ 
 ==> Tests\Feature\Backend\User\UpdateUserTest    ✓ ✓ ✖ 
 ==> Tests\Feature\Frontend\ChangePasswordTest    ✖ ✖ ✖ 
 ==> Tests\Feature\Frontend\FillContactFormTest   ✓ ✖ ✖ ✖ ✖ ✖ ✖ 
 ==> Tests\Feature\Frontend\ResetPasswordTest     ✓ ✖ ✖ ✖ ✖ 
 ==> ...\Feature\Frontend\UpdateUserAccountTest   ✓ ✖ ✖ ✖ ✖ ✖ ✖ ✖ ✖ ✓ 
 ==> Tests\Feature\Frontend\UserDashboardTest     ✓ 
 ==> Tests\Feature\Frontend\UserLoginTest         ✓ ✖ ✖ ✖ ✖ ✖ ✖ ✓ 
 ==> ...s\Feature\Frontend\UserRegistrationTest   ✓ ✓ ⚈ ⚈ ✓ ✓ ✖ ✖ ✖ ✖ ✖ ✖ ✖ ✖ ✖ 
 ==> Tests\Feature\SwitchLanguageTest             ✓ 

Tests: 111, Assertions: 161, Errors: 3, Failures: 57.

**Comment by bambamboole** [comment]
I wasn't able to reproduce the bugs, so for fixing, I need a couple more infos.
Somewhat better error descriptions: Maybe someone can debug this problem why the session is not set.
I think it's all around the flash messages...

**Comment by cjmling** [comment]
I was having similar issues on Windows.

Error : Session is missing expected key [errors].

Spend sometime to debug and found out that it was related to this file caching issue in one of the package.

https://github.com/DivineOmega/DO-File-Cache/issues/4

Updated/replaced the vendor files to the latest version v2.0.6  fixed all the test failure.

Not sure why the latest release version were not installed in first time when running `composer install`. Or what is the proper way to install the latest release version.  If anyone know please let me know too.
Right now i'm just doing copy/paste which obviously will be lost if i have to reinstall *-*

**Comment by scottlaurent** [comment]
if anyone comes across this error, try running your phpunit call like this

```
sudo ./vendor/bin/phpunit
```
the issue is related to running phpunit as a user which does not have permissions to generate cache files.   This is a pretty bizarre issue and I'm unclear why it was closed.
