### ISSUE TITLE
PHP 7.2.1 with social login in Google+ count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by pnishank** [rappasoft/laravel-5-boilerplate#1028]
master branch of laravel-5-boilerplate
when using php 7.2.1 with google+ social login in giving following error
count(): Parameter must be an array or an object that implements Countable

this line of SocialLoginController.php gives error
`$fields = count(config("services.{$provider}.fields")) ? config("services.{$provider}.fields") : false; `

i guess this error is because of PHP 7.2.1

so did a workaround 

```
if (!is_null(config("services.{$provider}.fields")))
            $fields = count(config("services.{$provider}.fields")) ? config("services.{$provider}.fields") : false;
else
            $fields= false;
```

i suspected that Google's config array doesn't have fields key in it so count() function returns an error
hope this helps someone.

i'm new to git and laravel if i'm doing something wrong suggestions are welcomed 😃

**Comment by bryanrscott** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/pull/1027

**Comment by pnishank** [comment]
should i close this issue @bryanrscott ?

**Comment by bryanrscott** [comment]
I am not sure of the edicate.  Your code is slightly different than my submission so I would leave open for now, it is linked to the pull request.   That way the committer can review the options when deciding.

**Comment by rappasoft** [comment]
Being Merged
