### ISSUE TITLE
[Question] 'middleware' => 'access.routeNeedsPermission' many permissions

### ISSUE THREAD

**Issue by pmirandaarias** [rappasoft/laravel-5-boilerplate#1029]
On Laravel-Boilerplate 5.4

Is there a way to give multiple permissions in `routeNeedsPermission` ? For example, I need something like this (this doesn't work):

'middleware' => 'access.routeNeedsPermission:2,3,4,5,6',

**Comment by bambamboole** [comment]
@pmirandaarias 
Its using spatie/laravel-permission and here you find the solution [https://github.com/spatie/laravel-permission#using-a-middleware](https://github.com/spatie/laravel-permission#using-a-middleware)

**Comment by pmirandaarias** [comment]
Bah, it's using semicolons...

'middleware' => 'access.routeNeedsPermission:2;3;4;5;6',

Closed.
