### ISSUE TITLE
Suggestion: include hints for errors

### ISSUE THREAD

**Issue by rap2hpoutre** [rappasoft/laravel-5-boilerplate#1034]
Hi. Some times ago I [asked on reddit](https://www.reddit.com/r/laravel/comments/7vfwyw/im_building_this_do_you_think_it_could_be_useful/) if building a package for explaining common mistakes could be useful. 

This post had some positive feedbacks, so I started [to build one](https://github.com/rap2hpoutre/indice): this package silently turns some default exceptions to a learning-minded error page. Some people on reddit says that it would be useful if included in starter pack. 

That's why I ask: do you think this kind of package could be useful for your boilerplate? Feel free to close this issue if you think it's useless.

Thanks.

**Comment by rappasoft** [comment]
It is a very good idea, I don't think i'll add it now because people using this project should already have experience with those errors and know how to fix them, this is not a beginner boilerplate. But good work and thanks for contributing to the community.
