### ISSUE TITLE
Visual installer - experience, improvements and thoughts 

### ISSUE THREAD

**Issue by blomdahldaniel** [rappasoft/laravel-5-boilerplate#104]
So I just passed the earlier mcrypt() error.
Then i face the neat installer, good looking and simple. I press next and then faced this:
<img width="400" alt="skarmavbild 2015-09-24 kl 14 37 22" src="https://cloud.githubusercontent.com/assets/10044093/10073520/d708ccf4-62c9-11e5-842d-44d1ea8b4de5.png">

After some thoughts i understood that this is showing me what stuff that needs to be installed or something on the server to be able to run. Sure it said requirements but i want more. There should be *You have all the required programs installed*. 
**1.** **Add explanation for this** and also suggestion how to solve if they are not green, just say *Google it* or what ever, just give me something. **OR don't show this page at all if all is fine**, no needd to, maybe just confusing.
**2.** Say **Error** if error exists and then a explanation that *You need the following php blah blah..*

Next step also confused me at first.
<img width="400" alt="skarmavbild 2015-09-24 kl 14 35 09" src="https://cloud.githubusercontent.com/assets/10044093/10073561/27a6ffc8-62ca-11e5-8938-73dd860e4e83.png">

**3** **Add explanation for this** This one is easier, just show the exact `chmod 775 /path` for each error i so that this will be easy to fix. And just like the other one **Dont show at all if it passes**
**4.** **Another suggestion** if the user has to fix something before entering the next stage, **show disabled next buton** so that I understand that I should continue but cant as of right now. Right now i came to a page where I didnt even knew i wanted to push *Next*

Suddenly the installation is done, no information of what has happened and the buttons *View Frontend/View Backend* with the header *Database* or something was also very confusing. Much more information needs to be shown!
**5.** After showing a lot of information of what has happened there should only be one button, *Finish* and that should take you to the frontend **OR** backend that would be more clear.

# To sum up
**To be honest** I don't really get what you are trying to accomplish with this visual installer. The laravel user should be or will have to be comfortable with the terminal. Skipping those stages and not show exactly what is happening when you run the installer **only gets confusing**. There was no feedback at all that the migrations was done, no feedback for the seeding, no feedback of the standard user/admin to the backend, no feedback of standard roles/permissions.

I must say that either the installer should be, an installer that goes **all in** where you configure all the stuff you need **or there should be no installer at all**. If you really want the installer and think that that is the right approach then at least show the user what it is doing.

#### I gladly contribute 
Sorry if I come in with a hard tone here but I actually am a bit confused and a little upset.. I gladly contribute to this project, it is great and has big potential. **BUT** I really think you should consider carefully **what the visual installer should be doing**. Because this is just confusing I am afraid... In my honest opinion I would actually roll back this update, back to command line installation until you have figured stuff out.

**Comment by rappasoft** [comment]
Hmm. I suppose you're right. Sometimes I get caught up in whether or not I can accomplish something that I don't stop to think if I should.

**Comment by rappasoft** [comment]
Gone.

**Comment by blomdahldaniel** [comment]
:+1: 
Glad to hear, I understand the feeling you explain. And again I dont think that a visual installer is bad per say, I think you/we could come up with something that is great but it just should be a bit bigger in that case.

**Comment by rappasoft** [comment]
I don't think it needs it, just 20 extra files that are only going to be used once. I thought I was going to be able to do a lot more with it, but unless you move the install folder to the root, and program it without laravel, you can't really get much out of it.

It's much easier if you're going to be making freeware, to just ship with the vendor folder.
