### ISSUE TITLE
Cannot use my javascript code

### ISSUE THREAD

**Issue by ztioge** [rappasoft/laravel-5-boilerplate#1040]
Hi,

I want to use some javascript code to change some buttons when clicked: its just a **onClick()** i wrote it in the frontend.js file because the buttons are from the frontend, but the javascript isnt working.

Where can I write it?

Thanks.

**Comment by bambamboole** [comment]
you have to compile it with laravel mix. try `npm run dev` .
You can find it in the [docs](http://laravel-boilerplate.com/5.5/start.html)

**Comment by ztioge** [comment]
Now it works. Thanks!
