### ISSUE TITLE
Fresh install Laravel Valet PHP unit fail

### ISSUE THREAD

**Issue by vduke** [rappasoft/laravel-5-boilerplate#1042]
Having this issue in valet on Mac when doing a fresh install. Followed steps exactly as described. Anyone have any ideas on this? I don't want to have to switch to homestead just to accomplish this. Anyone else have a solution that solves this besides using homestead? Key's are generated, Dependency's installed, Database migrated and seeded. 

<img width="786" alt="screenshot 2018-03-18 11 38 25" src="https://user-images.githubusercontent.com/4578171/37562357-22d26dd8-2aa1-11e8-8c8c-acaf70ef70cd.png">

`here was 1 error:

1) Tests\Feature\Frontend\UserRegistrationTest::a_user_can_register_an_account
Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [App\Models\Auth\User].

/Users/vincentduke/Code/radiastudio/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:416
/Users/vincentduke/Code/radiastudio/app/Repositories/BaseRepository.php:214
/Users/vincentduke/Code/radiastudio/tests/Feature/Frontend/UserRegistrationTest.php:64
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:205
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:153

--

There were 5 failures:

1) Tests\Feature\Backend\Role\UpdateRoleTest::an_admin_can_access_the_edit_role_page
Expected status code 200 but received 500.
Failed asserting that false is true.

/Users/vincentduke/Code/radiastudio/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:78
/Users/vincentduke/Code/radiastudio/tests/Feature/Backend/Role/UpdateRoleTest.php:21
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:205
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:153

2) Tests\Feature\Backend\User\UpdateUserTest::an_admin_can_access_the_edit_user_page
Expected status code 200 but received 500.
Failed asserting that false is true.

/Users/vincentduke/Code/radiastudio/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:78
/Users/vincentduke/Code/radiastudio/tests/Feature/Backend/User/UpdateUserTest.php:25
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:205
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:153

3) Tests\Feature\Frontend\UpdateUserAccountTest::a_user_can_update_his_profile
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Manuel'
+'John'

/Users/vincentduke/Code/radiastudio/tests/Feature/Frontend/UpdateUserAccountTest.php:55
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:205
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:153

4) Tests\Feature\Frontend\UserRegistrationTest::if_requires_approval_is_active_the_user_cant_login
Failed asserting that null matches expected 'Your account was successfully created and is pending approval. An e-mail will be sent when your account is approved.'.

/Users/vincentduke/Code/radiastudio/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:709
/Users/vincentduke/Code/radiastudio/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:727
/Users/vincentduke/Code/radiastudio/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:700
/Users/vincentduke/Code/radiastudio/tests/Feature/Frontend/UserRegistrationTest.php:115
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:205
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:153

5) Tests\Feature\Frontend\UserRegistrationTest::an_event_get_fired_on_registration
The expected [App\Events\Frontend\Auth\UserRegistered] event was not dispatched.
Failed asserting that false is true.

/Users/vincentduke/Code/radiastudio/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/EventFake.php:61
/Users/vincentduke/Code/radiastudio/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221
/Users/vincentduke/Code/radiastudio/tests/Feature/Frontend/UserRegistrationTest.php:131
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:205
/Users/vincentduke/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:153

ERRORS!
Tests: 100, Assertions: 198, Errors: 1, Failures: 5.`

**Comment by bambamboole** [comment]
@vduke did you figure out the problem? I think it's session related, but I can't reproduce it.

**Comment by bambamboole** [comment]
I've got a similar setup but self written and not the official valet. But I can't remove my Environment just for testing this. That would be too time consuming.
