### ISSUE TITLE
boilerplate version 5.5 - has not compatibility with mongoDB

### ISSUE THREAD

**Issue by mashhoodrehman** [rappasoft/laravel-5-boilerplate#1043]
After integrate MongoDB package , on registration module it throws an exception
basic transaction on null

**Comment by bambamboole** [comment]
@mashhoodrehman thats not that much info.

If you provide additional infos, maybe someone will look into that.

**Comment by mashhoodrehman** [comment]
Sorry for late reply,
Ok i will ask question by giving briefly description .
I have one more question can we use mongoDB instead of mysql . As in
laravel authentication class they are using PDO which is not supported in
mongoDB.
Pardon me, if I am bad in english
Regards

**Comment by bambamboole** [comment]
This is a laravel boilerplate. So in my opinion it wont be that nice to rewrite ther authentication mechanism to fit monogodb needs.

**Comment by rappasoft** [comment]
Laravel does not seem to support mongo: https://laravel.com/docs/5.6/database
