### ISSUE TITLE
404 Error when unconfirm or unlink a deleted user.

### ISSUE THREAD

**Issue by JuanVillagran** [rappasoft/laravel-5-boilerplate#1044]
There is an error when it comes to unlink or unconfirm a user that has been deleted, it returns a 404 error, steps to reproduce the error:
- Delete a user
- Go to Deleted Users
- Try to confirm / unconfirm a user or unlink him from his social account

**Comment by rappasoft** [comment]
Fixed.

Change this: https://github.com/rappasoft/laravel-5-boilerplate/commit/bd885d5563fa242444aba3d2f070044c8757e7a9#diff-b467cc786635bd6945b17726282f1c64R37

And this: https://github.com/rappasoft/laravel-5-boilerplate/commit/bd885d5563fa242444aba3d2f070044c8757e7a9#diff-f982e939d9f916a968df2c1c4b74ee6c
