### ISSUE TITLE
Suggestions for Content submission and editor?

### ISSUE THREAD

**Issue by MACscr** [rappasoft/laravel-5-boilerplate#105]
Thank you so much for this great library that you have put together, its been extremely helpful and I have really enjoyed learning laravel in the process. With that said, I am working on a project where I need authenticated users to be able to create content (text, file upload) through a nice editor and edit the content later if needed as well. Im sure I can figure out how to accomplish this, but I am wondering if there are any shortcuts/packages, etc, that you might suggest that might work well with your boiler plate in order to accomplish this. Thanks for your time!

**Comment by rappasoft** [comment]
Hmm it depends I guess, would probably be easier to build it yourself. Doesn't sound too complex.

**Comment by MACscr** [comment]
Should I use a crud generator or something like that? Seems like most of the point of laravel is to not recreate the wheel, so trying to figure out best practices, etc.

All of this is completely new to me. Been simply doing mainly procedural based php coding up to this point or working with frameworks like Wordpress.

**Comment by MACscr** [comment]
Actually https://github.com/alnutile/l5scaffold seems to be almost perfect for getting the basics created fast, but right now its doesnt really work with the file structure of the boilerplate. Need to figure out of it can be modified for that, but man is it sweet and a huge time saver.

**Comment by rappasoft** [comment]
These are built in and speed up development: https://github.com/laracasts/Laravel-5-Generators-Extended

**Comment by MACscr** [comment]
That just sets up the scheme and a few files, right? Doesn't actually create a visual working crud. I watched a tutorial and while it seemed useful, it only does some of the job as far as I can tell.

- Mark

**Comment by rappasoft** [comment]
I'm not sure, I prefer making the crud myself, generate:resource is a big help.
