### ISSUE TITLE
Module pattern and better separation

### ISSUE THREAD

**Issue by goowikns** [rappasoft/laravel-5-boilerplate#1054]
Hi,

I was wondering if you guys have plans to introduce Modules: as in https://github.com/nWidart/laravel-modules.

This way there is a better separation between the Frontend and Backend. 

Best regards,

**Comment by bambamboole** [comment]
The Frontend and Backend are totally uncoupled in the boilerplate.

And we also try to stay as near as possible with the default Laravel Framework folder structure.

**Comment by bingalls** [comment]
Hmm. Thanks to Laravel MVC, the front & back are decoupled. I don't think the following is what @goowikns intended, but it would be nice to use modules to decouple custom user code from L5Bootstrap code. This will keep Bootstrap upgrades following the Laravel way, but users will likely need a documented example on how to adopt the laravel-modules way for their own code.
This would be better than the comment I made on Slack, regarding future-proof upgrades.

**Comment by rappasoft** [comment]
This project is meant to be a starter project, not a default installation with a pre installed package. That comes with the cost of having to keep up with updates if you want them. But most people start the project and then it gets customized to their needs and they don't even keep up with the commits.
