### ISSUE TITLE
[Question]Best way to bring in remaining core UI components

### ISSUE THREAD

**Issue by Mango-kid** [rappasoft/laravel-5-boilerplate#1057]
I am curious about the best way to pull in the latest components from coreUI without disrupting the existing infrastructure and maintaining a link to the coreUI repos.

**Comment by bambamboole** [comment]
There are "only" the SCSS files form core ui which you have to update and maybe some template stuff you have to port into the blade templates. 

We would appreciate it if you would send a PR with the latest core ui stuff ;-)
