### ISSUE TITLE
Feature request: docker

### ISSUE THREAD

**Issue by bingalls** [rappasoft/laravel-5-boilerplate#1068]
# Create a parallel fork, to maintain boilerplate with Docker
I expect that anyone in the community can also do this. I'd be interested in opinions comparing approaches, such as
- http://laradock.io/
- https://laravel-news.com/dockerized-version-of-laravel-homestead
Has anyone tried these? Perhaps just a setup document will suffice.

**Comment by bambamboole** [comment]
I think [vessel](https://github.com/shipping-docker/vessel) would be a good approach. Compose some containers is not that hard today, but a workflow to execute different kind of commands from outside in the container without starting a docker bash everytime is not that easy. 
But I think almost every adopter of this boilerplate need some kind of different setup, its not ideal to build in some kind of infrastructure.

**Comment by Shuyinsama** [comment]
This is something I have been looking at for a internal project that uses this boilerplate. I have a different Laravel Application (running 5.4 still) that has a DockerFile that works but was not made by me. I also personally don't really use Docker all that much. But it is something I can look at.

**Comment by bingalls** [comment]
Thanks for the feedback! Closing this, to shelve for future consideration.
