### ISSUE TITLE
Upgrade got impossibly complicated

### ISSUE THREAD

**Issue by Teranode** [rappasoft/laravel-5-boilerplate#107]
>_> so many things changed with like a week i cant even keep track.

**Comment by rappasoft** [comment]
Sorry I just refactored a lot. Its still fine to use whatever version you have.

**Comment by Teranode** [comment]
I'm almost up to date with your refactoring so its all good. It was just really a lot <_<.

**Comment by rappasoft** [comment]
Yeah I go on like week long binge updates. I think I'm done now minus security fixes if any. 

Anthony Rappa
