### ISSUE TITLE
Install Fails on Centos 7

### ISSUE THREAD

**Issue by EntrepreneurAJ** [rappasoft/laravel-5-boilerplate#1076]
`[mydigibiz@loc1 MyDigiBiz]$ npm install

> pngquant-bin@4.0.0 postinstall /home/mydigibiz/MyDigiBiz/node_modules/pngquant-bin
> node lib/install.js

  ⚠ The `/home/mydigibiz/MyDigiBiz/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/home/mydigibiz/MyDigiBiz/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
/home/mydigibiz/MyDigiBiz
├── UNMET PEER DEPENDENCY vue-template-compiler@^2.x
└── UNMET PEER DEPENDENCY vue-template-es2015-compiler@1.6.x

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.3 (node_modules/sane/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none was installed.
npm ERR! Linux 3.10.0-862.2.3.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install"
npm ERR! node v6.14.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script 'node lib/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pngquant-bin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pngquant-bin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pngquant-bin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mydigibiz/MyDigiBiz/npm-debug.log
npm ERR! code 1`

**Comment by EntrepreneurAJ** [comment]
I have installed the libpng-devel package with yum

**Comment by rappasoft** [comment]
I have never install laravel on centos, I stick to ubuntu, maybe someone else here can chime in.

**Comment by pmirandaarias** [comment]
I had do it in centos 6 and 7 without problems, not sure what is happen there

**Comment by dieselfunaila** [comment]
I ran into this problem long time ago. Apparently there is some issue building the package when running npm install.

As @EntrepreneurAJ mentoined, make sure to have the `libpng-devel` package installed.
Simply rebuilding the package fixes the issue: `npm rebuild pngquant-bin`. Don't forget to add `--no-bin-links` if you're running on a vagrant box on a Windows host.
