### ISSUE TITLE
Can't create source map file

### ISSUE THREAD

**Issue by gamevnlc** [rappasoft/laravel-5-boilerplate#1078]
I want to create source map in laravel boilerplate version 5.6 . But there is no file was generated. 
I have follow the instruction from here https://laravel.com/docs/5.6/mix#css-source-maps

**Comment by rappasoft** [comment]
You're right, but I don't know if this is a mix issue or a boilerplate issue.

**Comment by gamevnlc** [comment]
it might be mix issue. I create sample laravel project and source files was not generated

**Comment by lukecurtis93** [comment]
Had the same issue, I'm unsure of the issue but the following fixes it:
```
if (!mix.inProduction()) {
    mix.webpackConfig({
        devtool: 'source-map'
    })
    .sourceMaps()
```

in the bottom of my webpack file.

**Comment by gamevnlc** [comment]
I tried but not work

**Comment by rappasoft** [comment]
i'm going to assume this is not a BP issue and close it for now but if you figure it out let us know.
