### ISSUE TITLE
Unidentified index: dependancies

### ISSUE THREAD

**Issue by Teranode** [rappasoft/laravel-5-boilerplate#108]
im getting this error:
![](http://i.imgur.com/WUcAl60.png)

**Comment by Teranode** [comment]
and every time i update a permission it doesn't sync with the roles it's attached too :(

**Comment by Teranode** [comment]
Update 3: Fixed the Dependencies error:

changed all instances of 
```
count($input['dependencies'])

to 

```
isset($input['dependencies'])
```

in Bacend/EloquentPermissionsRepository

**Comment by rappasoft** [comment]
Weird i'm not getting the error. Was it just from that one file?

**Comment by Teranode** [comment]
yes, just that one.

**Comment by rappasoft** [comment]
Though I couldn't replicate. I updated the code anyway.
