### ISSUE TITLE
Permissions table add column

### ISSUE THREAD

**Issue by volkankurt2** [rappasoft/laravel-5-boilerplate#1082]
I want to add a comment column to the Permissions table. How can I do that?

While adding new permissions via the interface, I want to enter the permission name and description. I guess I could not.

I did the editing events, but I could not created do it.

![image](https://user-images.githubusercontent.com/11972311/40578744-28ec7ada-6122-11e8-9382-b84eddfbbbf1.png)

![image](https://user-images.githubusercontent.com/11972311/40578753-478b59b6-6122-11e8-817e-7d517a4bb78e.png)

![image](https://user-images.githubusercontent.com/11972311/40578758-69f6096a-6122-11e8-9d3d-0eb5b4cc1c54.png)

**Comment by rappasoft** [comment]
I mean you have to add it to the model, request classes, and repositories.
