### ISSUE TITLE
what is $pending_approval variable?

### ISSUE THREAD

**Issue by saeedmie85** [rappasoft/laravel-5-boilerplate#1086]
what is $pending_approval variable on the sidebar.
and where is it defined?

**Comment by JuanVillagran** [comment]
Hey saeedmie85, the variable $pending_approval is used in the sidebar to show the administrator if a user has registered and it's registration needs approval by the admin itself, it works when "REQUIRES_APPROVAL" in the .env file is set to true, also to find where it is defined you could perform a search in your IDE with the term "requires_approval" to see where it is defined.
