### ISSUE TITLE
Gitignore generated public assets

### ISSUE THREAD

**Issue by bingalls** [rappasoft/laravel-5-boilerplate#1087]
For v5.1.6, the following should be added to .gitignore:
/public/css/*.css
/public/js/*.js
/public/mix-manifest.json

As well, those existing files (backend.* , frontend.*) should be removed from the git cache.

**Comment by rappasoft** [comment]
Not everyone compiles assets on server. For this reason we keep them in version control.

**Comment by bingalls** [comment]
I appreciate that a few of your users want you to take on extra maintenance work, so that they don't have to (for them) run a one-time only step of npm install.
BTW, github markup removed the leading asterisk from ***.css & ***.js.
Closing this issue, makes it harder on contributors: validating files under git control is harder, and any new submissions require you to check that no deleted/extraneous code has been compiled into *.css nor *.js files.
Ultimately, this decision says that you value your users more than your contributors.
On the other hand, if you wish to deviate from standard practice, consider an install script. As long as the script is simple, there won't be much magic to debug, if & when things go wrong.

**Comment by rappasoft** [comment]
What is the process you use when pushing to production that requires new assets, just running npm or yarn on the production server? Or you do have a separate server all together handle the assets. There is no one right way to do it hence why I let everyone choose. I for one, compile locally and just pull to production and i've never had a problem.

**Comment by bingalls** [comment]
When I run npm/yarn, on my development (or any) server, git status shows that I have untracked files. Sure, I can ignore git warnings, but this leads to a path of madness. After all, I can also ignore build warnings, unit test warnings, compile warnings, downtimes, server outages, customer complaints, etc.
This comes off as a bit glib, because I am trying to be concise. Sure, the real world has warnings, but it's likely a good message for your _springboard_ to be clean.
