### ISSUE TITLE
Registration Improvement

### ISSUE THREAD

**Issue by MACscr** [rappasoft/laravel-5-boilerplate#109]
How about making is so that users do not set a password until they click on the confirmation email url and it sends them to a page where they can set it. This way you only have to collect their email address and maybe name when they initially register. Any suggestions on how I might be able to accomplish this?

**Comment by rappasoft** [comment]
What would be the benefit to this?

**Comment by MACscr** [comment]
Typically the less a user has to fill out when they register for a site, the more likely they are to complete the registration. Plus no point in creating a password for someone that hasn't confirmed their account yet.

**Comment by strainovic** [comment]
I agree with you MACscr, the less fillable fields, the more registered users :)

**Comment by Gsearch** [comment]
I agree as well. Just collect the most basic and relevant information needed. The registered user can just add the optional details after they registered if they want.

**Comment by rappasoft** [comment]
This would be a pretty large update. In a perfect world I would add a config item to switch between the two, but I think that would add a lot of conditional checks and more code than its worth. It should be one or the other.

**Comment by blomdahldaniel** [comment]
I think it would be natural to enter the password after confirmation as well. 

As you say @rappasoft there should only be one or the other. But I vote +1 for password after confirmation aswell.

**Comment by rappasoft** [comment]
I have a feeling it will be more of a pain in the butt to implement than we think. But i'll throw it into the next update.

**Comment by blomdahldaniel** [comment]
Hm.. Yes that is probably true, especially since it should be configurable
to select if users even should have to confirm their account.. Maybe think
twice about this if it is that much work.
Den 2 okt 2015 3:18 em skrev "Anthony Rappa" <notifications@github.com>:

**Comment by rappasoft** [comment]
I'm all for configurability but I'm not sure if statements all over the place checking config options is the right way to go.

**Comment by MACscr** [comment]
Closed with a response of what?

**Comment by rappasoft** [comment]
That i'll configure it into the next major release.

**Comment by rappasoft** [comment]
I actually thought about it and its a good idea, registration/email confirmation in one.

**Comment by clin407** [comment]
Just curious, was this ever done? Can't find the option if it was..
