### ISSUE TITLE
Activate CoreUI PRO License

### ISSUE THREAD

**Issue by raduladans** [rappasoft/laravel-5-boilerplate#1092]
I have just bought the CoreUI PRO license, as suggested in the admin template and I have no clue how to activate it and "get access to all the components"....

 Could you please help me with an advice? I have been struggling for 3 hours now and there is really no documentation anywhere for this. 

PS: I am a beginner at Laravel, please forgive my lack of knowledge. Many thanks!

**Comment by rappasoft** [comment]
The current version only comes with the base layouts and what you see, anything else you have to add in.

**Comment by nasirkhan** [comment]
the CoreUI PRO version have support for a number of libraries and new set to css classes. 

So you have download the Pro version and replace the existing CoreUI resources and need to add a number of libraries. For example the Select2 is not available on free version. As you have the pro version you have to follow their doc to add the Select2 library.
