### ISSUE TITLE
Default administrator role in auth route file bug

### ISSUE THREAD

**Issue by lukecurtis93** [rappasoft/laravel-5-boilerplate#1093]
At the following location for the user management routes: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/routes/backend/auth.php#L11

It checks that the role is 'administrator'

I was in the position that my default role was actually called 'management', so naturally I edited in the `access.php` config file and added the following:
```
/*
* The name of the super administrator role
*/
'admin_role' => 'management',
```

But obviously the middleware on the routes file doesn't look here. Should this be changed to find the default admin role instead of `administrator`?

**Comment by gamevnlc** [comment]
You need to clean the DB and run `php artisan db:seed again`.

**Comment by lukecurtis93** [comment]
Thanks for your reply, I have already done this but the `auth.php` routes file keeps the `middleware` as `administrator` when I've changed it to `management`

**Comment by gamevnlc** [comment]
mmm so weird, Did you clear config cache ?

**Comment by rappasoft** [comment]
Clear your cache. Also I don't know why you'd want to change administrator to anything else, its universally known as the all permissions role. If anything i'd add management as a separate role.

**Comment by lukecurtis93** [comment]
thats a fair suggestion - i just saw the option in the config file to change the default `admin_role` name and figured it would've changed that value globally. No worries, thanks for clearing that up.
