### ISSUE TITLE
[SUGGESTION] Make a build with public_html in the root

### ISSUE THREAD

**Issue by Doomkyn** [rappasoft/laravel-5-boilerplate#1095]
Dear fellow devs,

I really wanted to try out this boilerplate, but I'm stucked with a hosting that needs to have the public_html folder in the root of the website, so my setup is the following:
```
/root
    /public_html
        /css
        /js
        /index.php
        /etc...
    /laravel (with everything else inside)
```
I already developed quite few project with this setup, I know what to edit in the config to make it work, but since I think this is a pretty common setup, and since a boilerplate is meant to be fast setup, what do you think about making a boilerplate archive for people that use laravel in a hosting like I do?

Thanks!

Note: I don't know if this is the right place to make a suggestion. Feel free to point me to the right place and I'll delete this.

**Comment by rappasoft** [comment]
There is no reason you should have to change the structure of default laravel to fit the needs of your host. Ive hosted projects on dozens of different hosts for different clients and they always have the option to set the document root to /public.

You might be able to get more help from the slack channel but I think you're the 1% on this one.
