### ISSUE TITLE
PHP Debug not working correctly?

### ISSUE THREAD

**Issue by sdeering** [rappasoft/laravel-5-boilerplate#11]
Also it seems even with APP_DEBUG=true the debugging doesn't work as expected. ie - if you do a dd('die and dump'); this is not output, it seems to be ignored.

**Comment by Krubb** [comment]
I replaced the App\Exceptions\Handler.php with laravels own and that did the trick for me. Have you tried that?

**Comment by sdeering** [comment]
You legend thanks mate it worked!
