### ISSUE TITLE
Maximum function nesting level of '100' reached, aborting!

### ISSUE THREAD

**Issue by taka0o** [rappasoft/laravel-5-boilerplate#110]
When I try to open macros page (http://localhost/laravel-5-boilerplate/public/macros) once logged in, I get this error:

**FatalErrorException in AliasLoader.php line 63:
Maximum function nesting level of '100' reached, aborting!**

Everything is fine when the page is viewed as a guest.

Am I missing something?

Thank you!

**Comment by rappasoft** [comment]
See if this pertains to you: https://github.com/rappasoft/laravel-5-boilerplate/issues/87

**Comment by taka0o** [comment]
Hi,

So far, neither of these commands seem to fix the problem.

Thank you!

**Comment by taka0o** [comment]
It's working now, had to add xdebug.max_nesting_level=500 to php.ini file.

Thanks again! :+1:

**Comment by mahanteshpolicepatil** [comment]
Please tell me the path of  php.ini in laravel5.2 project work space..
In addition i am using wamp 2.5.. do i need to change anything in wamps php.ini??

**Comment by monkad** [comment]
this is the path you will find him here : C:\wamp\bin\php\php5.5.12
