### ISSUE TITLE
[Feature request] Standard Exceptions

### ISSUE THREAD

**Issue by robertmain** [rappasoft/laravel-5-boilerplate#1101]
Just found out about this project from reddit. However, I noticed you added your own custom exceptions...

Are there any plans to integrate [this](https://github.com/crazycodr/standard-exceptions) in the future? I've used it in personal projects, and it's nice to be able to throw a `HTTP_NOT_FOUND` exception rather than just a general exception with "Not found" as the message.

**Comment by robertmain** [comment]
> Maybe you just need to edit you ExceptionHandler:

I'm not entirely sure what you mean by this? What are you suggesting?

>But I think there is no chance to implement this into the boilerplate because you don't need this kind of package in a laravel app.

How do you figure? Surely it's better to throw more descriptive exceptions, rather than just a generic exception, no?

**Comment by robertmain** [comment]
Perhaps I could put a PR together to demonstrate what I mean?

**Comment by bambamboole** [comment]
But why depend on a extra dependency instead of writing only the exceptions you need?

**Comment by robertmain** [comment]
Why reinvent the wheel if there's a documented and working implementation on packagist? I don't know about you, but I'd rather have my code throw a `FormatException` if I give an argument in the wrong format that I can listen for and catch. Or how about a `Data\NotFound` exception if my file reader class can't find the file on disk? Otherwise, you're just catching `Exception` and then trying to somehow parse the exception message and code. 

Sure, you can setup constants for those...but why not just use a set of standard type-safe exceptions?

**Comment by robertmain** [comment]
I notice there's a lot of calls to `GeneralException` in there. If I spend the time to factor that out into specific exceptions, am I wasting my time?

**Comment by rappasoft** [comment]
I'm not opposed to this but I definitely don't have the time to figure out which to be swapped. Nor am I positive i'd like it once it was done and don't want you to waste your time. If you want to make a PR with a few examples I might get a better idea but that's up to you.
