### ISSUE TITLE
customising new type of users and view pages, and permissions

### ISSUE THREAD

**Issue by flowser** [rappasoft/laravel-5-boilerplate#1108]
# customising new type of users and view pages, and permissions:
 I am working on some project using your software boilerplate, I have managed to modify a few things on new users, and including their profile picture when logged in. but I am lost on how to create their default view pages. As you created the initial ones having:
Superadmin, orgadmin, bureauadmin, househelp, the client. The project should be that superadmin can create orgnadmin, orgadmin can create bureauadmins, and bureauadmins can create their own hsuser (just any other user, but these ones are known are househelps), but lastly, the clients who will hire househelp register on their own and search any househelp from any bureau and hire them.  The changes I have made are;
Arranged in levels;

Administrator        => superadmin                         =>     (views both frontend, backend)
Executive               =>orgadmin                               =>  (views only some parts of backend, can include front end)
Creatednew user => bureauadmin                      =>   (views only some parts of backend, can include front end)
Creatednew user  => hsuser (househelp)             => (views only front end)
 User                       =>client (Default registering) => (views only frontend only)

# My Challenge
 Now my challenge is how and where to edit so I can link the permissions in database like ‘view backend’ to syncronise to the pages I will be modifying, also where can add such users I have created to be redirected to the respective pages (backend, frontend etc), 
I will be glad if you can assist me with such tutorial. 

# What version?
am using laravel 5.6 boilerplate

**Comment by davidsivocha** [comment]
This isn't an issue so much as it is a tutorial request. 

That being said, the Permissions package being use is the Spatie Laravel permissions package. 

The documentation available [here](https://github.com/spatie/laravel-permission) indicates how you can add permissions to routes etc to check to see if the user has the appropriate permission. Additionally in Laravel's auth package you can check when hitting a route what the users permission is and then depending on the assigned role, you can call `redirect('/home');` to redirect to the URL specified. 

I'd suggest having a good read over the Spatie documentation on how it's permissions package works with Laravel's Auth structure.

**Comment by flowser** [comment]
thanks, Rappa, was inquiring, i tried to run commands on making new modelattribute jut as you did with roleattribute, userattribute scope, method, relationshiop etcs, traits but i got errors, is there a way to do it. thee are no commands registered. kindly assist am stuck somewhere

**Comment by flowser** [comment]
i have used hariadi/laravel-boilerplate-generator but i modified the root urls when generating the files to the unified folders for easy access when coding and editing if anyone needs the configuration i can share.
