### ISSUE TITLE
User and Roles Based DataTables no longer working after update to "yajra/laravel-datatables-oracle": "^8.0"

### ISSUE THREAD

**Issue by mitcks** [rappasoft/laravel-5-boilerplate#1110]
I have a project that was started with boilerplate 5.4.  When updating it to Laravel 5.5 it was also necessary to update DataTables to "yajra/laravel-datatables-oracle": "^8.0".

I followed the Yajra Upgrade Guide (https://yajrabox.com/docs/laravel-datatables/master/upgrade) and that fixed all of the datatables we use in pages we have added.  However, I still get the generic "DataTables warning: table id=users-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7" error on the boilerplate User Management and Role Management pages.  We never modified the UserTableController or related code and I'm at a loss trying to track down the problem (note that I did update Datatable to DataTable in the UserTableController).

I see that you have abandoned DataTables in boilerplate version 5.5, but we'd like to keep using it.  Did anyone else run into this issue when upgrading from Laravel 5.4 to 5.5?  How did you fix it?

**Comment by bryanrscott** [comment]
Um, it could be CSRF middleware.   Have you inspected what is being returned by the datatables ajax call using network tab under developer tools?
Are you adding something like this to your data-tables initialisation?   
    data: function (d) {
                            d._token = '{!! csrf_token() !!}';
    }

**Comment by mitcks** [comment]
I think the problem is that the UserTableController (the one that came with boilerplate 5.4) no longer returns data.  But I don't understand why, it worked prior to upgrade.  The only thing I changed was the new capitalization for DataTable (was Datatable).

I get this in the network tab: backend.b594ac7370eaf9bbfe99.js:24 POST http://127.0.0.1:8000/admin/access/user/get 500 (Internal Server Error)

This is the function from the controller:
public function __invoke(ManageUserRequest $request)
    {
        return DataTables::of($this->users->getForDataTable($request->get('status'), $request->get('trashed')))
        ->escapeColumns(['first_name', 'last_name', 'middle_name', 'phone', 'email'])
        ->editColumn('confirmed', function ($user) {
            return $user->confirmed_label;
        })
            ->addColumn('roles', function ($user) {
                return $user->roles->count() ?
                    implode('<br/>', $user->roles->pluck('name')->toArray()) :
                    trans('labels.general.none');
            })
            ->addColumn('actions', function ($user) {
                return $user->action_buttons;
            })
            ->withTrashed()
            ->orderBy('last_name')
            ->orderBy('first_name')
            ->orderBy('email')
            ->make(true);
    }
}

**Comment by bryanrscott** [comment]
Ok, network tab of the developer tools window in chrome.   If you select the url that failed, on the right side will be a series of tabs on of which will be response.   Laravel generally gives fairly informative descriptions of failures in debug mode.

**Comment by mitcks** [comment]
If anyone else runs into this, the solution is to remove ->withTrashed() parameter in the UserTableController.

//            ->withTrashed()

Per vendor (https://yajrabox.com/docs/laravel-datatables/master/upgrade#trashed)
[v8] Functionalities Removed
Removed filterColumn api magic query method in favor of closure.
Removed support on older snake_case methods.
Removed silly implementation of proxying query builder calls via magic method.
Removed unused methods.
Removed withTrashed and onlyTrashed api.
