### ISSUE TITLE
Inconsistent urls after switch to https

### ISSUE THREAD

**Issue by MACscr** [rappasoft/laravel-5-boilerplate#112]
I initially setup my app without https and now I have enabled it within apache, setup the correct configs there, then adjusted my .env. Seemed I had to adjust some of the settings in .htaccess as well. Ever since then I haven't been able to confirm an account or reset passwords. Im also sometimes getting redirected to /index.php or /index.php/about vs / and /about. Sometimes the routes are fine and other times they are not. When I do click on a reset or confirm link, it seems to redirect me to example.com/index.php with no message on if i was confirmed or the password was reset. Am I missing a setting I should have changed?

Side question: should the password reset take me to a page where i can set a new password or is one randomly generated and emailed to me?

**Comment by FusionDesign** [comment]
Can you verify for me the results of config('app.url'). Could you also paste your public/.htaccess file and have a look at http://stackoverflow.com/questions/19967788/laravel-redirect-all-requests-to-https -- I'm almost certain this is a general error.
