### ISSUE TITLE
middleware => 'role' is not allowing the administrador

### ISSUE THREAD

**Issue by pmirandaarias** [rappasoft/laravel-5-boilerplate#1130]
Version 5.6.

In the previous version (5.4) I used to restrict route access with:

'middleware' => 'access.routeNeedsPermission:2;3;4',

But now, in 5.6 I want to restrict the access with roles in this way:

'middleware' => 'role:some_role',

It's working fine, the users with role 'some_role' can access to those routes and the user without that role don't, but also the administrator can't access to those routes. Why is happen that? Should the administrator role have access to every route?

**Comment by rappasoft** [comment]
This uses a different library and you need to explicitly assign every permission to the administrator here: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/database/seeds/Auth/PermissionRoleTableSeeder.php#L36
