### ISSUE TITLE
MongoDB Integration Error : Call To member function prepare() on null

### ISSUE THREAD

**Issue by Asifali121** [rappasoft/laravel-5-boilerplate#1133]
I have intalled Jensegger/mongo-db package and done all the setup as suggested.
Updated the User.php for Mongodb Authenticable.

But I am facing an error in Connection.php Line: 325
Call to a member function prepare() on null.

Please help.

**Comment by rappasoft** [comment]
Don't think its BP issue: https://github.com/jenssegers/laravel-mongodb/issues/1341#issuecomment-339260226
