### ISSUE TITLE
Webpack.mix.js may require updating resource references

### ISSUE THREAD

**Issue by CodeSpatial** [rappasoft/laravel-5-boilerplate#1138]
Not sure if this was part of the plan here, but it probably should be. The [now flattened resources](https://laravel-news.com/laravel-5-7-resources-directory-changes) folder as of Laravel 5.7 is still being referenced by webpack.mix.js in BP. Fixing these references by removing /assets solves npm build issues.

**Comment by rappasoft** [comment]
Yes. Fixed thanks.
