### ISSUE TITLE
Issue with twitter login

### ISSUE THREAD

**Issue by coding-sunshine** [rappasoft/laravel-5-boilerplate#114]
Hi,
I tried to login with twitter but it gives me following error?

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null (SQL: insert into `users` (`name`, `email`, `password`, `confirmation_code`, `confirmed`, `updated_at`, `created_at`) values ('TWITTER NAME', , 'TWITTER PASSWORD', 'TWITTER KEY', 0, 2015-10-02 07:51:19, 2015-10-02 07:51:19))
```
The reason seems that twitter doesn't return 'email' of the user

Am I doing something wrong here?

Thanks

**Comment by coding-sunshine** [comment]
Same issue happens with Github as github doesn't return name.

I think we need to have a middle page where we can ask for pending informations before adding it to the DB

**Comment by truejay** [comment]
you need to set your db email field to allow null.

**Comment by sitesense** [comment]
@coding-sunshine Twitter 'can' return the email address but you need to have your app whitelisted here: https://dev.twitter.com/rest/reference/get/account/verify_credentials

**Comment by rappasoft** [comment]
I finally got around to reviewing this (i'm sorry), it seems like the answer above this is the correct one. It does not seem to be a scope issue.

**Comment by rappasoft** [comment]
I added it to the Wiki: https://github.com/rappasoft/laravel-5-boilerplate/wiki/3.-Socialite
