### ISSUE TITLE
Can't get the input submit value in request

### ISSUE THREAD

**Issue by error500** [rappasoft/laravel-5-boilerplate#1142]
After a form submission,  in controller i would like to know which button xas choosen. But when trying to get values of button chosen, i can't recive any value.

    <form method="POST" action="{{ route('frontend.command.store') }}">
        {{ csrf_field() }}
        ... some inputs...
        <button type="submit" name="button" value="save" >Draft</button>
        <button type="submit" name="button" value="transmit" >Transmit</button>
    </form>

    public function store( $id = null, Request $commandRequest) {
        dd($commandRequest->all());
    }

Brings all input values but nothing for $commandRequest->button

Is there any "boiler plate effect" ?

**Comment by rappasoft** [comment]
Use javascript to set a hidden field with whatever value you want based on which submit button is pressed.
