### ISSUE TITLE
Simple Line Icons font URLs in CSS aren't relative to APP_URL

### ISSUE THREAD

**Issue by aalaap** [rappasoft/laravel-5-boilerplate#1148]
# Issue

After logging in to the backend, no icons are displayed. After viewing the source of the `css/backend.css` file, I found that the URLs for Simple Line Icons font files are relative to root, not the app root:

    @font-face {
      font-family: "simple-line-icons";
      src: url(/fonts/vendor/simple-line-icons/Simple-Line-Icons.eot?f33df365d6d0255b586f2920355e94d7);
      src: url(/fonts/vendor/simple-line-icons/Simple-Line-Icons.eot?f33df365d6d0255b586f2920355e94d7) format("embedded-opentype"), url(/fonts/vendor/simple-line-icons/Simple-Line-Icons.woff2?0cb0b9c589c0624c9c78dd3d83e946f6) format("woff2"), url(/fonts/vendor/simple-line-icons/Simple-Line-Icons.ttf?d2285965fe34b05465047401b8595dd0) format("truetype"), url(/fonts/vendor/simple-line-icons/Simple-Line-Icons.woff?78f07e2c2a535c26ef21d95e41bd7175) format("woff"), url(/fonts/vendor/simple-line-icons/Simple-Line-Icons.svg?2fe2efe63441d830b1acd106c1fe8734) format("svg");
      font-weight: normal;
      font-style: normal;
    }

This results in a 404 for those font files and causes the browser to not display any icons in the CoreUI dashboard.

My `APP_URL` is set to `http://localhost/myname/myapp/public`, so I would expect this URL to get used in the CSS `url()` methods.

I have run `npm run dev` and compiled the assets, so the aforementioned WOFF files are emitted into the `public` folder. The CSS file paths are not processed accordingly.

# Steps to reproduce

1. Download Laravel 5.7 Boilerplate.
1. `composer install`.
1. `npm install`.
1. Copy `.env.example` as `.env` and set up `APP_URL` to `http://localhost/myname/myapp/public` or any path that is not simply `http://localhost`.
1. `php artisan storage:link`.
1. `php artisan key:generate`.
1. `php artisan migrate`.
1. `php artisan db:seed`.
1. `npm run dev`.
1. Open the app and login to the backend as user `admin@admin.com` and password `secret`.
 
# Workaround

You can set a resource root path in Mix to work around the problem. Open `webpack.mix.js` and add this line after the `setPublicPath` line:

    mix.setResourceRoot('/myname/myapp/public/');

This should be path to the root "public" folder relative to the `localhost` server - basically the same as the `APP_URL`.

However, this will make an additional step be required while deploying the application. Just like the way SCSS files are preprocessed, is there any way to direct Mix to use the `APP_URL` value instead of hard-coding it?

# What version?

Laravel 5.7 Boilerplate.

Not sure if it's relevant, but I am using XAMPP on Windows 10 to host the app, but I am running all the commands mentioned above in a WSL Ubuntu 18.04 prompt.

**Comment by Shuyinsama** [comment]
Are you correctly setting the root url? Laravel applications are not supposed be accessed from the public folder. It should use a htaccess to serve the files of public as root. If I run this on a normal server or through Valet this works perfectly fine.

**Comment by aalaap** [comment]
@Shuyinsama Good point. I am using the public URL, because I want to serve multiple applications on the same host, without having to individually configure virtual hosts, something like this:

- http://localhost/myname/myapp
- http://localhost/myname/awesomeapp
- http://localhost/myname/testingsomething

Having `/public` isn't ideal, but I didn't want to mess with any hacks to get just the app root working, as mentioned [here](https://laravel.io/forum/03-11-2014-removing-public-from-url) (none of which work, by the way). However, my methods are just too dirty and it's probably a saner decision to simply create a virtual host and be on your way. I tried this and it works.

Thank you and sorry for the confusion!
