### ISSUE TITLE
social logged users doesn't have default role

### ISSUE THREAD

**Issue by noecodjo** [rappasoft/laravel-5-boilerplate#1159]
# Before you create an issue make sure that:
- Your issue is **strictly related to the boilerplate** itself. Questions about Laravel in general belongs to the [laracasts](https://laracasts.com/discuss/) or [laravel](http://laravel.io/forum) forums.
- You have read the [wiki](https://github.com/rappasoft/laravel-5-boilerplate/wiki) thoroughly.
- You have searched for a similar issues among all the former issues (even closed ones).
- You have tried to replicate the issue with a clean install of the project.

# Be explicit
Try to be as explicit as you can when you ask anything.

# What version?
Please when it's necessary, provide the version of your copy of the boilerplate. You can find the version number in the original README.md.

**Comment by belzaaron** [comment]
@noecodjo could you please fill the information out for this issue via an edit or close the issue/try again?

**Comment by noecodjo** [comment]
Hi @belzaaron,
FIrstly i want to thank you for this project. It's very helpfull,
During my using i just remarks that social logged iusers doesn't not have default role.

Additionally for contribution an option to require social logged to complete here profile information at first connection will be ecellent.

**Comment by zorca** [comment]
> 
> 
> Hi @belzaaron,
> FIrstly i want to thank you for this project. It's very helpfull,
> During my using i just remarks that social logged iusers doesn't not have default role.
> 
> Additionally for contribution an option to require social logged to complete here profile information at first connection will be ecellent.

Solution:
https://bitbucket.org/newconomy/community/commits/0699b7707517c9de9989a71085c8b83650f7657f

**Comment by noecodjo** [comment]
Thanks @zorca
