### ISSUE TITLE
Any stripe examples?

### ISSUE THREAD

**Issue by MACscr** [rappasoft/laravel-5-boilerplate#116]
I want charge users a one time fee to "upgrade" to a different user Role/Group. I see that have a class for stripe and settings in the .env, but not much more in form of documentation or examples of its use within your boilerplate. Any suggestions?

**Comment by rappasoft** [comment]
The API pretty much mirrors the Stripe API, for example: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Services/Billing/StripeGateway.php#L205
 is just a wrapper around: https://stripe.com/docs/api#charges

**Comment by LunarDevelopment** [comment]
Hey, This is an old Q&A and I've noticed that Service is no longer in the project, is there a way to use stripe in the boilerplate that I'm missing or do I need to integrate cashier from scratch?
