### ISSUE TITLE
Add Ukrainian language pack

### ISSUE THREAD

**Issue by baronkoko** [rappasoft/laravel-5-boilerplate#1164]
Hello! Can we add Ukrainian language to Laravel 5.7 Boilerplate?
I already create branch with this pack in forked rep. https://github.com/baronkoko/laravel-5-boilerplate/tree/ukrainianlanguage.

**Comment by error500** [comment]
You should create a pull request now

**Comment by baronkoko** [comment]
Done https://github.com/rappasoft/laravel-5-boilerplate/pull/1169

**Comment by rappasoft** [comment]
Just check my comments on that before I can merge (theres conflicts).
