### ISSUE TITLE
Reset Password enhancement : Corner Case.

### ISSUE THREAD

**Issue by bryanrscott** [rappasoft/laravel-5-boilerplate#1166]
# Scenario
A user has forgotten their password as it has been a long time since they logged in.   They use the "forgotten password" feature to reset their password.   When they logged in they are presented with a change password again as they also have an expired password.

# Issue
When updating password via the "forgotten password" feature the password_changed_at time is not updated.

# Possible Resolutions
a) In App\Http\Controllers\Frontend\Auth\ResetPasswordController method resetPassword
      $user->password_changed_at = Carbon::now();

b) in App\Models\Auth\Traits\Attribute\UserAttribute method setPasswordAttribute
     $this->attributes['password_changed_at']  = Carbon::now();

**Comment by rappasoft** [comment]
Definitely something to fix.

**Comment by rappasoft** [comment]
Would this be the fix you're talking about: https://github.com/rappasoft/laravel-5-boilerplate/commit/e50f207b7976c4141b6d8fe62f1a7b7c3baa0d30

**Comment by rappasoft** [comment]
I tested it and it will be included in the next release.
