### ISSUE TITLE
Delete user button shows user instead of deleting it with Datatables ajax sourced data.

### ISSUE THREAD

**Issue by ravasaurio** [rappasoft/laravel-5-boilerplate#1167]
I am using the Datatables plugin on the users table on ```resources/views/backend/auth/user/index.blade.php``` with Ajax sourced data. Here's where I get the data from:

```
$users = $this->userRepository->getActiveNoPagination('id','asc');

      $data = collect();

      foreach($users as $user) {
        $data->push([
          'last_name'   =>  $user->last_name,
          'first_name'  =>  $user->first_name,
          'email'       =>  $user->email,
          'confirmed'   =>  $user->confirmed_label,
          'type'        =>  $user->type,
          'created_at'  =>  $user->updated_at->diffForHumans(),
          'actions'     =>  $user->action_buttons,
        ]);
      }

      return Datatables::of($data)->escapeColumns()->rawColumns(['actions','confirmed'])->make(true);
```
The method ```getActiveNoPagination``` :
```
    public function getActiveNoPagination($orderBy = 'created_at', $sort = 'desc')
    {
        return User::with('roles', 'permissions', 'providers')
            ->active()
            ->orderBy($orderBy, $sort)
            ->get();
    }
```

The buttons are correctly displayed and they all work as intended, except of the delete button which instead of prompting the "Are you sure message", just shows the users profile. Since I have not touched anything from the ```UserAttribute.php``` trait, I don't know where the problem may be.

**Comment by ravasaurio** [comment]
Here you can see how all the buttons are correctly displayed. They all work as intended except the delete one.
![image](https://user-images.githubusercontent.com/14269893/49867194-f7c76200-fe09-11e8-89ac-589f40957d5c.png)

**Comment by bryanrscott** [comment]
Hi . This might not help exactly with your problem but might help expose the issue.  I think it might be todo with javascript, specifically the app/resources/js/plugins.js and addDeleteForms function. Maybe as your loading via ajax the items are not initialised on page load?

1) Are you seeing a "Are you sure you want to delete this item?" confirmation dialog?
2) Can you use postman and do the delete call and it work.

**Comment by poseso** [comment]
I think your problem is that your are not sending the CSRF token as header to the pages:

https://github.com/rappasoft/laravel-5-boilerplate/blob/master/resources/js/plugins.js#L1

add before line 1:

/*
 * Place the CSRF token as a header on all pages for access in AJAX requests
 */

$.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    },
    complete: function(response, status, xhr){
        addDeleteForms();
    }
});

and re compile, that should fix your problem.

**Comment by ravasaurio** [comment]
Thank you very much poseso, that did fixed the problem.
