### ISSUE TITLE
Laravel 5.7 validation exception for API prefixes post routes redirects to home route.

### ISSUE THREAD

**Issue by adnanmayo** [rappasoft/laravel-5-boilerplate#1168]
Hi I am trying to call the `api/register` it works when there is no validation exception but it also redirects to home route when there is a validation exception. how to solve this issue?

**Comment by rappasoft** [comment]
Can you give a better example?

**Comment by adnanmayo** [comment]
@rappasoft it is already solved. It was not related to boilerplate in fact it was related to laravel itself.

**Comment by rappasoft** [comment]
Ok cool thanks.
