### ISSUE TITLE
BaseRepository count() is calling unnecessary and resource consuming "select *"

### ISSUE THREAD

**Issue by komarnicki** [rappasoft/laravel-5-boilerplate#1179]
I'm using recent version of the package.

In BaseRepository [the count()](https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Repositories/BaseRepository.php#L125) method uses:

`return $this->get()->count();` to get the quantity of records.

This is extremely resource consuming (especially on a large tables) and redundant as it simply counts the number of records in returned collection. 

**Called query**: `select * from my_table` ⁉️

Instead this line could be replaced with:

`return $this->model->count()` to simply count on the query level. 

**Called query**: `select count(*) as aggregate from my_table` ✅

Please let me know if you want me to create a PR for this or the author of this package is going to fix it by himself?

**Comment by poseso** [comment]
Feel free to make a PR for this

**Comment by rappasoft** [comment]
I did it for the next release: https://github.com/rappasoft/laravel-5-boilerplate/commit/cbb758aaf349538d47c6d1da66632a19a7fb7c7c

But i'm not sure if i'm keeping this base repository to begin with right now, but i'll keep it until I don't.

Thanks.
