### ISSUE TITLE
JS Library - Sweetalert2 Update

### ISSUE THREAD

**Issue by bryanrscott** [rappasoft/laravel-5-boilerplate#1189]
Sweetalert2 JS Library has updated to version 8.  Would be nice to use latest version L5BP.

Changes needed
1) packages.json update version
2) file /resources/js/bootstrap.js, update line 
import swal from 'sweetalert2';
to
import Swal from 'sweetalert2';

and line
window.swal = swal;
to
window.Swal = Swal;

3) file /resources/js/plugins.js, update line
swal({
to
Swal.fire({

cheers

**Comment by rappasoft** [comment]
Feel free to make a pull request.
