### ISSUE TITLE
Suggestion: make the setting use env

### ISSUE THREAD

**Issue by rabol** [rappasoft/laravel-5-boilerplate#1191]
Can i suggest to change this:

`return [

    /*
    |--------------------------------------------------------------------------
    | Google Analytics
    |--------------------------------------------------------------------------
    |
    | Found in views/includes/partials/ga.blade.php
    */
    'google-analytics' => 'UA-XXXXX-X',
];`

to

`return [

    /*
    |--------------------------------------------------------------------------
    | Google Analytics
    |--------------------------------------------------------------------------
    |
    | Found in views/includes/partials/ga.blade.php
    */
    env('google-analytics', 'UA-XXXXX-X'),
];`

that way one does not need to edit 'core' files

**Comment by rappasoft** [comment]
Next release: https://github.com/rappasoft/laravel-5-boilerplate/commit/5b8bd35e92ffc363eb1ddad8d96010770f9a99da
