### ISSUE TITLE
Disable Password Expire 

### ISSUE THREAD

**Issue by pc-mon** [rappasoft/laravel-5-boilerplate#1192]
Hello guys 
I just need to disable Password Expire Feature 
Thank you

**Comment by bryanrscott** [comment]
One possible way might be to edit your .env and add/edit PASSWORD_EXPIRES_DAYS
PASSWORD_EXPIRES_DAYS=DISABLED

relies on the following code in \App\Http\Middleware\PasswordExpires line 23
if (is_numeric(config('access.users.password_expires_days')) && $user->canChangePassword()) {

**Comment by pc-mon** [comment]
thank you so mcuh

**Comment by miqbalhakim** [comment]
Instead of that, you can also use PASSWORD_EXPIRES_DAYS=false in your .env file too.
