### ISSUE TITLE
Phone not rendered in the contact mail

### ISSUE THREAD

**Issue by rabol** [rappasoft/laravel-5-boilerplate#1193]
When sending mail from the default Contact form, the phone number is not included in the mail that is send 

`<p><strong>@lang('validation.attributes.frontend.phone'):</strong> {{ $request->phone or "N/A" }}</p>`
and

`@lang('validation.attributes.frontend.phone'): {{ $request->phone or "N/A" }}`

does not work

to fix it, remove the 'or "N/A"'

**Comment by bryanrscott** [comment]
or update to
@lang('validation.attributes.frontend.phone'): {{ $request->phone ?? "N/A" }}

**Comment by rappasoft** [comment]
- Fixed: https://github.com/rappasoft/laravel-5-boilerplate/commit/c3fb3ceb5c4c5b060ef0b6b52024dbe4460ffa6e
