### ISSUE TITLE
Solved: ca-certs.json not found in data directory

### ISSUE THREAD

**Issue by jason-guru** [rappasoft/laravel-5-boilerplate#1194]
## Issue
When running ChangeUserPasswordTest and ChangePasswordTest tests after fresh installation, I was getting an exception `ca-certs.json not found in data directory.`

## Solution that worked for me
Updated
`"divineomega/laravel-password-exposed-validation-rule": "^2.0.1",`
from
`"divineomega/laravel-password-exposed-validation-rule": "^1.2",`
in composer.json and ran composer update  **fixed the issue**.

Hope this helps someone out there 👍

**Comment by rappasoft** [comment]
Done: https://github.com/rappasoft/laravel-5-boilerplate/commit/a623a88ef01bf5154675752e979ad6c29a8e85c4
