### ISSUE TITLE
HTML not being rendered in message

### ISSUE THREAD

**Issue by vool** [rappasoft/laravel-5-boilerplate#1195]
HTML not being rendered in flash messages, eg on the login page when user is not verified, which means the link is not rendered:

![image](https://user-images.githubusercontent.com/441840/53575603-cc7f2400-3b69-11e9-9c85-ed3eaf0f8ebb.png)

Seems to have been introduced with commit fa344c9c488255a6a7589e481d9cb2645b176454, surely there is no risk here as string are not user generated.

Propose reverting fa344c9c488255a6a7589e481d9cb2645b176454 ?

**Comment by rappasoft** [comment]
Reverted: https://github.com/rappasoft/laravel-5-boilerplate/commit/194c2e9e814684b0d4b48a9a7c5db06972f86291
