### ISSUE TITLE
Laravel 5.8

### ISSUE THREAD

**Issue by jaroslavas** [rappasoft/laravel-5-boilerplate#1197]
Do you have plants to update boilerplate to laravel v5.8? Or maybe it's compatible and we can just update our site ourselves?
https://laravel.com/docs/5.8/upgrade#upgrade-5.8.0

**Comment by rappasoft** [comment]
I do have plans to upgrade, I wanted to do a ground up rebuild but I don't think I have the time right now, so i'll probably just go through the upgrade guide or pay for Laravel Shift. I'll try to get it done soon.

**Comment by bringrainfire** [comment]
part of the upgrade to laravel 5.8 will entail updating the tests to work with phpunit 8. An article by Sebastian Bergmann February 12, 2019 details some of the things that need to be done. https://thephp.cc/news/2019/02/help-my-tests-stopped-working

**Comment by rappasoft** [comment]
Unfinished, but includes phpunit 8: https://github.com/rappasoft/laravel-5-boilerplate/commit/e5d003b7aeb941b4c2413b57b809ad0e2694e9fd

I have a bunch more to do on my list but feel free to use this as a template for your upgrade.
