### ISSUE TITLE
Laravel Debugbar not showing

### ISSUE THREAD

**Issue by horsebuzz** [rappasoft/laravel-5-boilerplate#1198]
Hello!

I am using Laravel 5.7 Boilerplate.

I have enabled the debugbar in `.env` with following variable

     APP_ENV=local
     APP_DEBUG=true
     DEBUGBAR_ENABLED=true

It is also enabled in `config/debugbar.php`

    'enabled' => env('DEBUGBAR_ENABLED', env('APP_DEBUG', false)),

Debugbar is still not showing. What am I doing wrong here?

**Comment by rappasoft** [comment]
It's working fine for me, make sure it's not collapsed into its little icon:

<img width="123" alt="Screen Shot 2019-03-23 at 17 51 50" src="https://user-images.githubusercontent.com/6026504/54872047-61092a80-4d94-11e9-9425-382a06211877.png">
