### ISSUE TITLE
Link tag is htmlencoded in "Account not confirmed" exception message

### ISSUE THREAD

**Issue by jaroslavas** [rappasoft/laravel-5-boilerplate#1199]
If you try to login before confirming your email, it shows error message with htmlencoded link that is not clickable.
To fix this you can change [56 line in messages.blade.php](https://github.com/rappasoft/laravel-5-boilerplate/blob/d643ab022ddd46726688225cf8c28a23ff1ca19a/resources/views/includes/partials/messages.blade.php#L56) file to:
`{!! session()->get('flash_danger') !!}`

I'm not sure, but maybe all the lines echoing messages should be changed like that?

**Comment by rappasoft** [comment]
Reverted: https://github.com/rappasoft/laravel-5-boilerplate/commit/194c2e9e814684b0d4b48a9a7c5db06972f86291
