### ISSUE TITLE
Laravel 5.8 upgrade

### ISSUE THREAD

**Issue by bringrainfire** [rappasoft/laravel-5-boilerplate#1200]
1. I updated laravel version in composer.json to 5.8
2. Then commented out App\Providers\BladeServiceProvider::class, in config/app.php since composer autoconfigures it now.
3. run composer update
4. In tests/unit/UserRepositoryTest.php, changed setUp() to setUp(): void on line 24
5. Then since it doesn't recongize the @langrtl blade directive.
    a. I commented out rtl support in view/backend/layouts/app.blade.php
    b. and again on the frontend

After that all tests should pass.

So the rtl support will need fixing.

**Comment by bringrainfire** [comment]
the fix for @langrtl
1. run php artisan view:clear
2. insert the following code block into AppServiceProvider.php after the rtl session variable block
`/*
         * The block of code inside this directive indicates
         * the chosen language requests RTL support.
         */
        Blade::if('langrtl', function ($session_identifier = 'lang-rtl') {
            return session()->has($session_identifier);
        });`
3. put "use Blade;" at the top of the file above "use Carbon/Carbon;"
4. update composer.json with the following "appstract/laravel-blade-directives": "^1.4.0",
5. run composer update, it should work without errors
6. run phpunit, it should pass all tests now and have rtl support

**Comment by bringrainfire** [comment]
For the update to phpunit to version 8
1. update "codedungeon/phpunit-result-printer": "^0.26.1", in composer.json
2. update phpunit to "phpunit/phpunit": "^8.0"
3. run composer update
4. run phpunit, the tests should pass with 4 warnings.

the warnings are all the same and say:

> Using assertContains() with string haystacks is deprecated and will not be supported in PHPUnit 9. Refactor your test to use assertStringContainsString() or assertStringContainsStringIgnoringCase() instead.

**Comment by rappasoft** [comment]
Thanks was actually doing this over the last couple days: https://github.com/rappasoft/laravel-5-boilerplate/commit/e5d003b7aeb941b4c2413b57b809ad0e2694e9fd
