### ISSUE TITLE
Laravel 5.8

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-5-boilerplate#1204]
So far this is what's queued up for the Laravel 5.8 Boilerplate Release:

- [x] Upgrade to Laravel 5.8
- [x] Upgrade to phpunit 8.0
- [x] Upgrade to phpunit-results-printer 0.26.1
- [x] Upgrade to log viewer 4.7
- [x] Upgrade to nocaptcha 9.*
- [x] Upgrade to socialite 4.1
- [x] Upgrade to spatie/permission to 2.36
- [x] Upgrade to Laravel Dump Server 1.2
- [x] Upgrade to debugbar 3.2
- [x] Upgrade to ide-helper 2.6
- [x] Upgrade password validation rule to fix ca-cert.json issue
- [x] Upgrade SweetAlert
- [x] Update to Laravel commit: 4997f08105d6fb941b1ed2c749ebd2f55fba5a74
- [x] Remove BladeServiceProvider and register in the boot method of AppServiceProvider as per 5.8 docs
- [x] Use assertStringContainsString instead of assertContains to make all current tests pass
- [x] Laravel 5.8 uses bigIncrements as default for the users table so the foreign keys had to be converted to bigIntegers
- [x] Remove webpatser/laravel-uuid and convert UUID functions to Laravel 5.8’s built in UUID package from Ramsey
- [x] Remove unneeded laravel-blade directives package
- [x] Set resource root in webpack
- [x] Remove withInput parameter in GeneralException since it is covered by the dontReport property of the parent class
- [x] Don’t report GeneralException errors
- [x] Add new ReportableException class to throw when you want it to be logged, one of the two can be extended to add new exceptions that you either do or do not want logged. Both still redirect with the flash message.
- [x] Replace recaptcha with invisible recaptcha
- [x] Added optional captcha to contact form
- [x] Updated single login to use features with AuthenticateMiddleware to work with every driver as well as logout users on other devices
- [x] Remove Session model because it’s only good for one driver and the user can create it if they need it
- [x] Include redis by default
- [x] Add laravel auditing to certain models, UI is up to person creating the project
- [x] Change Clear Session button to be driver agnostic, sets a flag that triggers part of the web middleware to force the user to log out
- [x] Remove boilerplate html from CoreUI
- [x] Fix: Socially logged in users get assigned the default role
- [x] Load helpers with service provider instead of composer which allows better organization,  give all existing helper files a Helper postfix
- [x] Use casts property on User model and refactor

Let me know if there's anymore requests over the next couple days while I tidy things up.

**Comment by netwrkx** [comment]
Any luck with the history functionality, I think it would be a great addition

**Comment by rappasoft** [comment]
@netwrkx I was thinking of adding this: http://laravel-auditing.com

But only as a base install without any UI, and leaving the UI up to the person building the project.

**Comment by poseso** [comment]
How about getting back DataTables? it's very useful for any kind of project

**Comment by rappasoft** [comment]
Datatables caused me nothing but headaches. Plus I didn't want to handcuff people to it. Though I haven't really made a decision.

**Comment by Shuyinsama** [comment]
I agree on the Datatables part. Normal tables are fine for this boilerplate. It's up to the user to implement their own Datatables or something else. I understand having it implemented is really handy but it bloats the boilerplate for something that might not be used for every project.

**Comment by poseso** [comment]
@Shuyinsama I agree with you, but it doesn't force the user to use it, it can be used in normal stuff the boilerplate has, and everything else is up to the user to implement their own stuff or using normal tables, it's like some people i know that uses the boilerplate that doesnt even work with repositories and just use the kickstart of the bp to start working since it has an admin template and user permissions/roles, anyways i always implement it in all my projects but it's ok if you guys think it would be a pain in the ass hehe

**Comment by Shuyinsama** [comment]
It’s not that it’s a pain in the ass perse (altough maintaining the updates and all takes time) But more of a “use case” thing.

The purpose of datatables is to provide a nice and fast way to browse large sets of data inside tables with the use of search/filtering and pagination.

Now while I think Datatables is awesome and I still use it in most of my projects when I need to, this boilerplate does not provide any large sets of data, so there is no incentive from the boilerplates viewpoint to keep using it.

We just can’t keep assuming that anyone who forks this and uses the boilerplate will start to work with big sets of data. With that in mind it makes more sense to not add it to the boilerplate but leave it up to the user to implement their own idea of displaying lrge datatsets.

**Comment by poseso** [comment]
Agree

**Comment by rivajunior** [comment]
> @Shuyinsama I agree with you, but it doesn't force the user to use it, it can be used in normal stuff the boilerplate has, and everything else is up to the user to implement their own stuff or using normal tables, it's like some people i know that uses the boilerplate that doesnt even work with repositories and just use the kickstart of the bp to start working since it has an admin template and user permissions/roles, anyways i always implement it in all my projects but it's ok if you guys think it would be a pain in the ass hehe

[Bootstrap is dropping their use of jQuery](https://blog.getbootstrap.com/2019/02/11/bootstrap-4-3-0/#branches-hugo-and-jquery) in the next major release. So, on this package we use [CoreUI](https://coreui.io/) that uses Bootstrap. It means when Bootstrap gets upgraded on CoreUI template, we will not need to use jQuery anymore. But DataTables is heavily based on jQuery and I haven't seen they planning to drop jQuery too.

Which means that DataTables in addiction to the other negative points, of use it on this boilerplate, will bring one extra dependence (jQuery).

That is only my point of view.

**Comment by rappasoft** [comment]
Maybe unpopular opinion: am I the only one who doesn't like CoreUI?

Are there any other open source BS4 admin templates you guys know of?

I just found this one: https://github.com/tabler/tabler

**Comment by poseso** [comment]
I don't like it either,  haven't tested tabler but what about https://adminlte.io/themes/dev/AdminLTE/index.html

AdminLTE3 ?

**Comment by rappasoft** [comment]
@poseso Is it BS4? It would also be nice if theres an NPM package for it. As well as it has to be sass not less.

**Comment by bringrainfire** [comment]
could ditch boostrap altogether and go with metro ui https://builder.metroui.org.ua/

**Comment by poseso** [comment]
> @poseso Is it BS4? It would also be nice if theres an NPM package for it. As well as it has to be sass not less.

Tabler doesnt look good hehe

yes it's BS4 but i can check if there are any other good options since is not officially released yet

**Comment by rivajunior** [comment]
@rappasoft I found this one: [stisla-theme](https://www.npmjs.com/package/stisla-theme) that can be used by importing from `node_modules`.

And [Material Dashboard](https://www.producthunt.com/posts/material-dashboard) who is the one most voted Bootstrap admin template on [Product Hunt](https://www.producthunt.com/search?q=bootstrap%20admin). But it is from Creative Tim and all of his templates aren't downloadable by npm.

**Comment by rappasoft** [comment]
@rivajunior They're both nice but i'll be honest they might be a little too material for me haha.

I wish I could think of a way to swap themes.

**Comment by bringrainfire** [comment]
@rappasoft There's a good article about multiple theming here ->
 https://z900collector.wordpress.com/2017/08/29/laravel-5-implementing-themes/

**Comment by bringrainfire** [comment]
I found this package https://github.com/igaster/laravel-theme
It appears to have been updated to work with laravel 5.8

> This is a Laravel package that adds basic support for managing themes. It allows you to build your views & your assets in seperate folders, and supports for theme extending! Awesome :)

Features:

Views & Asset separation in theme folders
Theme inheritance: Extend any theme and create Theme hierarchies (WordPress style!)
Integrates Orchestra/Asset to provide Asset dependencies managment
Your App & Views remain theme-agnostic. Include new themes with (almost) no modifications
Themes are distributable! Create a single-file theme Package and install it on any Laravel application.
Ships with console commands to manage themes

**Comment by rivajunior** [comment]
@bringrainfire  It seams to me very painful to do on first time, but it can worth it

**Comment by cytech** [comment]
@rappasoft  I don't mind coreui (or others) if you could just set color themes.
in the past i created a "skin" composer in laravel which set backgorund colors from the exposed bs4 colors and navbar class, set from a stored config item, and overwrote the navbar-light/navbar-dark and bg-{{$color}} when loading the blade template.
its a hack but its fairly simple and at least  gives an option other than dark grey...
