### ISSUE TITLE
5.8 Suggestion : improve package.json compatibility with yarn

### ISSUE THREAD

**Issue by bryanrscott** [rappasoft/laravel-5-boilerplate#1216]
I would have put in a pull but I already have one open.

Suggestion is to improve package.json compatibility with yarn

In the scripts section of package.json replace npm calls with $npm_execpath
eg
  "dev": "npm run development",
becomes
  "dev": "$npm_execpath run development",

if your using npm it runs unchanged.   if your using yarn in your original call it will utilise yarn instead of npm

**Comment by rivajunior** [comment]
Nice tipe!

I didn't know that `$npm_execpath` variable. I always changed `npm` for `yarn` in my projects

**Comment by rappasoft** [comment]
To my I feel like package.json has a bunch of stuff we don't need. If anyone has the time to look and see if we can thin it at all it would be appreciated.

**Comment by rappasoft** [comment]
@bryanrscott I like the tip but I found this: https://stackoverflow.com/a/53897160/1741608

Might cause an issue for some people if I change it one way or the other.

**Comment by rivajunior** [comment]
> To my I feel like package.json has a bunch of stuff we don't need. If anyone has the time to look and see if we can thin it at all it would be appreciated.

I'll do that.

**Comment by rivajunior** [comment]
> @rappasoft @bryanrscott I like the tip but I found this: https://stackoverflow.com/a/53897160/1741608
> Might cause an issue for some people if I change it one way or the other.

I think that using cross-env it can solve that problem.

I'll try that too.

**Comment by bryanrscott** [comment]
@rappasoft agree it might cause an issue.
