### ISSUE TITLE
Problem with npm install on ubuntu 18.04

### ISSUE THREAD

**Issue by moonbyt3** [rappasoft/laravel-5-boilerplate#1218]
Hello, im trying to install boilerplate on my ubuntu i get this error 
When i run sudo npm install --unsafe-perm=true
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/simple-line-icons-37315752/fonts/Simple-Line-Icons.eot'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/yargs-c32f7298/completion.sh.hbs'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/yargs-c32f7298/index.js'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/yargs-1368bdf0/completion.sh.hbs'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/cross-spawn-7d695a8a/lib/util/escapeArgument.js'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/yargs-c32f7298/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/yargs-1368bdf0/index.js'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/cross-spawn-7d695a8a/lib/util/escapeCommand.js'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/yargs-c32f7298/README.md'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/yargs-1368bdf0/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/cross-spawn-7d695a8a/lib/util/hasEmptyArgumentBug.js'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/yargs-c32f7298/yargs.js'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/yargs-1368bdf0/README.md'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/vue-template-compiler-376e9f7f/index.js'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/cross-spawn-7d695a8a/lib/util/readShebang.js'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/yargs-1368bdf0/yargs.js'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/vue-template-compiler-376e9f7f/README.md'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/@vue/test-utils-7584c495/dist/vue-test-utils.iife.js'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/cross-spawn-7d695a8a/lib/util/resolveCommand.js'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/vue-a7fafc01/dist/vue.esm.js'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/jquery-13b25636/dist/jquery.min.js'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/@coreui/coreui-a1f07df3/dist/css/bootstrap.css.map'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/sass-71114505/sass.js'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/popper.js-511b558e/dist/esm/popper-utils.js'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/resolve-url-loader-4523e38c/tmp/1536277707/webpack2-sassloader6-sass4/rework/nested-import-mixed-quotes/absolute--production-normal/main.eefbda84170eb1ce3ed070f4f37ebea9.css'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/resolve-url-loader-4523e38c/tmp/1536277707/webpack2-sassloader6-sass4/rework/nested-import-mixed-quotes/absolute--production-normal/main.eefbda84170eb1ce3ed070f4f37ebea9.css.map'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/resolve-url-loader-4523e38c/tmp/1536277707/webpack2-sassloader6-sass4/rework/nested-import-mixed-quotes/absolute--production-normal/main.js'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/resolve-url-loader-4523e38c/tmp/1536277707/webpack2-sassloader6-sass4/rework/nested-import-mixed-quotes/absolute--production-normal/main.js.map'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/resolve-url-loader-4523e38c/tmp/1536277707/webpack2-sassloader6-sass4/rework/nested-import-mixed-quotes/absolute--production-normal/stderr.txt'
npm WARN tar ENOENT: no such file or directory, open '/var/www/html/laravel/node_modules/.staging/resolve-url-loader-4523e38c/tmp/1536277707/webpack2-sassloader6-sass4/rework/nested-import-mixed-quotes/absolute--production-normal/stdout.txt'
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/HubSpot/pace.git
npm ERR! 
npm ERR! fatal: failed to stat '/var/www/html/laravel': Permission denied
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/moonbyt3/.npm/_logs/2019-03-29T13_37_56_212Z-debug.log

These are last lines of debug.log:

verbose stack Error: exited with error code: 128
2563 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12:19)
2563 verbose stack     at ChildProcess.emit (events.js:197:13)
2563 verbose stack     at maybeClose (internal/child_process.js:988:16)
2563 verbose stack     at Socket.stream.socket.on (internal/child_process.js:404:11)
2563 verbose stack     at Socket.emit (events.js:197:13)
2563 verbose stack     at Pipe._handle.close (net.js:611:12)
2564 verbose cwd /var/www/html/laravel
2565 verbose Linux 4.15.0-46-generic
2566 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--unsafe-perm=true"
2567 verbose node v11.12.0
2568 verbose npm  v6.7.0
2569 error Error while executing:
2569 error /usr/bin/git ls-remote -h -t ssh://git@github.com/HubSpot/pace.git
2569 error
2569 error fatal: failed to stat '/var/www/html/laravel': Permission denied
2569 error
2569 error exited with error code: 128
2570 verbose exit [ 1, true ]

I resolved this by deleting pace dependency from package.json, but i guess it will break some loaders in app. 
EDIT: It does break app, when i type npm run watch it throws me this error: 
ERROR in ./resources/js/backend/before.js
Module not found: Error: Can't resolve 'pace' in '/var/www/html/laravel/resources/js/backend'
 @ ./resources/js/backend/before.js 8:0-14
 @ multi ./resources/js/backend/before.js ./resources/js/backend/app.js ./resources/js/backend/after.js

**Comment by bringrainfire** [comment]
try 
`npm cache clean --force

npm install`

you also may need to do this with sudo
