### ISSUE TITLE
LocaleMiddleware executes after SubstituteBindings middleware

### ISSUE THREAD

**Issue by andrrr** [rappasoft/laravel-5-boilerplate#1229]
LocaleMiddleware executes after SubstituteBindings middleware. This causes issues in case of using route model binding. 
Say, I have global scope in a model using app()->getLocale() for filtering. Having model binding in a controller this scope will always filter by default app locale, not by user locale.
I've fixed this just by moving LocaleMiddleware up in Kernel.php so it could execute before SubstituteBindings middleware.  
# What version?
5.8 and, probably, prior versions.

**Comment by rappasoft** [comment]
Can you make a PR?

**Comment by rappasoft** [comment]
I'll fix next release.
