### ISSUE TITLE
Google analytics does not work in v5.8

### ISSUE THREAD

**Issue by rabol** [rappasoft/laravel-5-boilerplate#1232]
In a fresh v5.8 I have added my GA id to /config/analytics.php

Nothing happens, the code is not included

If I then add a key in mv .env

google-analytics="UA-xxxx-x" then the rendering of the page is stopped and I only get a blank page.

with a value in /config/analytics.php
if I do a dd(config("analytics.google-analytics")) i get 'null' as a result

if I add google-analytics="UA-xxxx-x" in my .env the processing of the page stops

**Comment by rabol** [comment]
Got a step further by adding the key 'google-analytics' in the config file
```
<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Google Analytics
    |--------------------------------------------------------------------------
    |
    | Found in views/includes/partials/ga.blade.php
    */
    'google-analytics' => env('google_analytics', 'UA-xxx-x'),
];
```

now the code is included, but like this

```

@script
--
  | (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]\|\|(b[l]=
  | function(){(b[l].q=b[l].q\|\|[]).push(arguments)});b[l].l=+new Date;
  | e=o.createElement(i);r=o.getElementsByTagName(i)[0];
  | e.src='//www.google-analytics.com/analytics.js';
  | r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
  | ga('create','UA-xxxx-x','auto');ga('send','pageview');
  | @endscript


```

**Comment by rabol** [comment]
Added this to AppServiceProvider.php

in the boot() method
```
        Blade::directive('script', function () {
            return "<script>";
        });
        Blade::directive('endscript', function () {
            return "</script>";
        });

```

**Comment by rappasoft** [comment]
Fixed thanks: https://github.com/rappasoft/laravel-5-boilerplate/commit/d70dc5ce2dbb94231bd780f1271d9e9025fec7da
