### ISSUE TITLE
Bug: Redis is now a requirement

### ISSUE THREAD

**Issue by rabol** [rappasoft/laravel-5-boilerplate#1234]
php artisan db:seed fail if Redis is not installed

**Comment by shehzada72** [comment]
Same issue. How to disable redis

**Comment by poseso** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/blob/4787bcd67218d053a392c4430fdd7ce13ce61791/.env.example#L22

You can just change it to file instead of redis if you dont want to use it

**Comment by rappasoft** [comment]
Fixed
