### ISSUE TITLE
Use custom js per view

### ISSUE THREAD

**Issue by jerearaujo03** [rappasoft/laravel-5-boilerplate#1235]
How can I use a custom JS code block for every different view?
There is a specific way to include the JS file in the blade view? Or maybe just with a `<script>` tag inside blade file?
In that case, should I put my custom js files under /public folder, isn't?

**Comment by sitesense** [comment]
Read about how to do that here:
https://laravel.com/docs/5.8/blade#stacks

You can see an example of how it is used in the boilerplate here:
/resources/views/frontend/user/account/tabs/edit.blade.php
`@push('after-scripts')`
