### ISSUE TITLE
License including CoreUI?

### ISSUE THREAD

**Issue by LMCom** [rappasoft/laravel-5-boilerplate#1244]
Prior to using Laravel Boilerplate, I checked the license to be sure, it could be used freely for commercial purposes.
The following is a screenshot of http://laravel-boilerplate.com/license.html

![grafik](https://user-images.githubusercontent.com/14162803/59036867-68f34980-8870-11e9-9d03-7067fa7401e0.png)

But what about this line: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/resources/sass/backend/app.scss#L7

As you can see, CoreUI is imported. Due to our use case, it would be very expensive, see https://coreui.io/#buy.

CoreUI should be mentioned on the license page of Laravel Boilerplate. And there should be a clear warning, that Laravel Boilerplate can not be used in commercial software for free. Or can it?
Another guy had the same question one and a half year ago, but nobody answered: https://laracasts.com/discuss/channels/laravel/is-laravel-boilerplate-free-for-commercial-use

**Comment by poseso** [comment]
CoreUI free version can be used in whatever you need or want to do, on their website https://coreui.io/ just check the part that says CoreUI vs CoreUI Pro, that's the only difference, components, anyways you can extend your own stuff The Boilerplate can be used in commercial and non commercial projects

**Comment by LMCom** [comment]
Thank you.
