### ISSUE TITLE
 RoleDoesNotExist There is no role named `user`

### ISSUE THREAD

**Issue by sandidmariam** [rappasoft/laravel-5-boilerplate#1252]
# Before you create an issue make sure that:
- Your issue is **strictly related to the boilerplate** itself. Questions about Laravel in general belongs to the [laravel](http://laravel.io/forum) or [laracasts](https://laracasts.com/discuss/) forums.
- You have read the [documentation](http://laravel-boilerplate.com) thoroughly.
- You have searched for a similar issues among all the former issues (even closed ones).
- You have tried to replicate the issue with a clean install of the project.

# Be explicit
Try to be as explicit as you can when you ask anything.

# What version?
Please when it's necessary, provide the version of your copy of the boilerplate. You can find the version number in the original README.md.

**Comment by rappasoft** [comment]
Not enough info.
