### ISSUE TITLE
I think its might help us to add below featues

### ISSUE THREAD

**Issue by MamunHoque** [rappasoft/laravel-5-boilerplate#126]
1) Datagrid
2) Drug n drop Module Generator (Model, View, Datagrid, Migration, Controller etc)

**Comment by truejay** [comment]
This "Boiler plate" is getting over-blown with features. Let's keep it as a boiler plate and not a fully blown application! If you want to add features, branch off do it yourself.

**Comment by MamunHoque** [comment]
ok thanks :+1:

**Comment by Sogl** [comment]
@MamunHoque , Can you emplement it? =)
