### ISSUE TITLE
Default Role

### ISSUE THREAD

**Issue by MACscr** [rappasoft/laravel-5-boilerplate#127]
Should Default Role ("default_role") in the config/access.php be set to an actual role ID number instead of the name? This makes the system much more flexible and allows for name to change at any time without breaking the system.

**Comment by rappasoft** [comment]
I can change it to be either or in the next release. Prob in the next couple days when I have time.

**Comment by rappasoft** [comment]
Done: https://github.com/rappasoft/laravel-5-boilerplate/commit/c8dbee13fa9e4ec6a5e434e02d162ba206e1f19e
