### ISSUE TITLE
Users not confirming

### ISSUE THREAD

**Issue by MACscr** [rappasoft/laravel-5-boilerplate#128]
When I click on a confirmation email, it takes the user to the home page, no message is displayed, and the user is never confirmed in the database. Where should I start looking in the code?

**Comment by rappasoft** [comment]
Was this: https://github.com/rappasoft/laravel-5-boilerplate/issues/129 the solution to this problem?

**Comment by rappasoft** [comment]
I have tested this, the user is definitely confirmed, though for some reason the session message is not being flashed. Working on that now.

**Comment by rappasoft** [comment]
Fixed: https://github.com/rappasoft/laravel-5-boilerplate/commit/955cc78200b7c5fa8e79d09aebc5570b44490689
