### ISSUE TITLE
Confirmation Email template bug

### ISSUE THREAD

**Issue by MACscr** [rappasoft/laravel-5-boilerplate#129]
Had to create a space between the url and the translated string in order for the full url to be converted to a hyperlink in apple mail:

```{{ trans('strings.click_here_to_confirm_account') .' '. url('account/confirm/' . $token) }}```

**Comment by MACscr** [comment]
I did the same with the password.blade.php as well.

**Comment by rappasoft** [comment]
What problem did this solve?

**Comment by MACscr** [comment]
My explanation is pretty clear. The spacing in the email template between the url and the translated text was missing, thus the url would not be properly converted to a hyperlink by AppleMail.

- Mark

**Comment by rappasoft** [comment]
Ah, okay thank you. Will fix soon.

**Comment by rappasoft** [comment]
Fixed: https://github.com/rappasoft/laravel-5-boilerplate/commit/be26991ccecf8ec73ac1f49fdbf6341ce7684a17
