### ISSUE TITLE
Role Permissions Doesn't Save 

### ISSUE THREAD

**Issue by Teranode** [rappasoft/laravel-5-boilerplate#130]
This has been happening for a while but whenever I try to save a role with permissions, it doesnt save. But when i go to the permissions and attach it to a role it saves. Vice versa it undos the permissions settings.

**Comment by parabol** [comment]
+1

**Comment by rappasoft** [comment]
Hmm, I just tried creating a new role with custom permissions and it worked, than edited the role and changed the permission and it reflected the changes. Are you using the most recent version?

**Comment by parabol** [comment]
well, 
im updating or creating new roles with checked "Permission Groups", and i hit save..

on the 	app/Repositories/Backend/Role/EloquentRoleRepository@update() at line 145

dd($input['permissions'],$current);

"j1_11,j1_12,j1_13,j1_14,j1_15,j1_16"

array:6 [▼
  0 => "j1_11"
  1 => "j1_12"
  2 => "j1_13"
  3 => "j1_14"
  4 => "j1_15"
  5 => "j1_16"
]

and obviously $role->attachPermissions($permissions) is returning null..

**Comment by parabol** [comment]
my bad. there is a problem with ui between user ;) .. the perm groups and permissions are different on jstree.. i created permgroup and i try to save.. but actually there is no permission to save i think.. so we can improve that views to notify this... i think i can help you with that.

by the way, thank you so much for that.

**Comment by rappasoft** [comment]
No problem thanks.

**Comment by Teranode** [comment]
i have no idea what just happened here

**Comment by rappasoft** [comment]
Oh what did I do, I though he made this and fixed it on his own.

**Comment by rappasoft** [comment]
Trying really hard to find the time to get to these

**Comment by rappasoft** [comment]
I'm not sure what version you're running, but as of now if you create a new role with permissions, it works well each time.
