### ISSUE TITLE
Login with socialite

### ISSUE THREAD

**Issue by jefferson-andrade** [rappasoft/laravel-5-boilerplate#132]
How to define escopes to login with socialite?

**Comment by rappasoft** [comment]
Example?

Anthony Rappa

**Comment by jefferson-andrade** [comment]
I want to set the scope to connect with Facebook, for example.

'scope' => ['email', 'public_profile', 'user_birthday']

Facebook permissions v2.5 https://developers.facebook.com/docs/facebook-login/permissions/v2.5

What part do I set the scope?

Thank you

**Comment by rappasoft** [comment]
Does socialite have this ability by default?

**Comment by jefferson-andrade** [comment]
The documentation is as follows:

return Socialite::driver('github')->scopes(['scope1', 'scope2'])->redirect();

Scopes could be configured in .env file?

**Comment by jefferson-andrade** [comment]
?

**Comment by rappasoft** [comment]
Added: https://github.com/rappasoft/laravel-5-boilerplate/commit/aae146b22318e5f30730584349a319197c54ae3e
