### ISSUE TITLE
Auth redirect if not loged in Log Viewer

### ISSUE THREAD

**Issue by blomdahldaniel** [rappasoft/laravel-5-boilerplate#133]
I dont know if this has been patched in a new update but if, for example, my session times out and I was in the log/viewer i did not get redirected to the auth/login page. I only saw the text `Unauthorized`

I have been trying to find out where the routes and controllers are for the log-viewer but cant find them. 

#### Request
Be redirected to auth/login then to redirect()->intended() if not authorized for the log-viewer pages.

**Comment by rappasoft** [comment]
Because i'm working within the package config file's middleware option, it's not giving the desired results. I'm not sure why. At least it's locking the person out.

**Comment by blomdahldaniel** [comment]
So therefore your just closing it…?

**Comment by rappasoft** [comment]
I might need help figuring out a solution, at least the user stays locked out. I landed on that when I was theming it because I can't control a lot of the functionality. I'll leave it open to see if anyone has any ideas.

**Comment by rappasoft** [comment]
So I was trying to replicate this again, don't know if I was doing it the way it was happening to you.

I'd load the log viewer in 2 tabs, log out on the second one, and refresh the first one.

Each time it would redirect me home telling me I didn't have permission.

Is that the same effect as the session expiring?

**Comment by blomdahldaniel** [comment]
Wow! I dont know the result of expired session but i can try it out later. 

Either way, using the technique with 2 tabs did yield the same `Unauthorized` string. So now it works better. Have you done some work around it? Maybe added the auth to the routes as middleware for the log views? 

In my older version of the repo i get the `Unautorized` response when i set it up with the 2 tabs.

So, this might be fixed now!  :) Just gonna wait for the session to expire to be absolute certain! :p
Then we can close down this issue.

**Comment by rappasoft** [comment]
Got a response from the developer so I'm gonna check that out. Also spent the entire day yesterday reworking socialite, and logging in successfully with all 6 providers. The wiki for socialite now had all the quirks I came across for all of the providers.

**Comment by rappasoft** [comment]
Fixed! https://github.com/rappasoft/laravel-5-boilerplate/commit/4c19656c22881ebe3014acdd7ce2e2dfe51afeaf

**Comment by arcanedev-maroc** [comment]
See: https://github.com/ARCANEDEV/LogViewer/issues/26#issuecomment-162331615

**Comment by blomdahldaniel** [comment]
AWESOME!
i scanned through your socialite work and dude it is amazing! Great job!
Let's hope that you have burried socialite once and for all!
Den 6 dec 2015 6:51 em skrev "ARCANEDEV" <notifications@github.com>:

**Comment by blomdahldaniel** [comment]
I just have to add that the suggested solution of pulling updates from the repo seems like a great way of doing it. Guess that it oftens require a whole lot of diffing to ensure that nothing breakes. And a nightmare to update a lot. But still. I wish to be able to try this out in my next project. 

Great stuff!
