### ISSUE TITLE
Action Buttons in access/index.blade.php

### ISSUE THREAD

**Issue by vangelis183** [rappasoft/laravel-5-boilerplate#134]
Hi,

sorry about the silly question:
You are using this: {!! $user->action_buttons !!}

How is this being generated and how could someone add more functions (buttons)?

Greets

**Comment by rappasoft** [comment]
The actions come from the models, this one specifically here: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Models/Access/User/Traits/Attribute/UserAttribute.php#L112
