### ISSUE TITLE
Route permissions based on model data

### ISSUE THREAD

**Issue by tduval** [rappasoft/laravel-5-boilerplate#137]
Hi,

I would like to restrict authenticated users to not access some data owned by other users.
I have an **App\Account** model which belongs to one **User** model and a router like this:
```php
$router->group(['prefix' => 'account/{id}', 'where' => ['id' => '[0-9]+']], function ($id) use ($router) {
		get('/', 'AccountController@index')->name('frontend.account');
		get('delete', 'AccountController@deleteAccount')->name('frontend.account');
});
```
If someone try to access the url http://localhost/account/2 and that the Account ID#2 is owned by someone else, he can access it.

Do you know if it's possible to prevent this to happen ?

**Comment by rappasoft** [comment]
Why even have the id in the route than? Just use /account and use the user in the access()->user() session variable in the views and actions. Unless i'm misunderstanding.

**Comment by rappasoft** [comment]
Did you figure this out?
