### ISSUE TITLE
Some News Module to explain bit more

### ISSUE THREAD

**Issue by wasiqaftab** [rappasoft/laravel-5-boilerplate#138]
HI 

it will be great if you can make a news module in admin so that we have a better idea how to create a module. i think so its good for beginners like me.

Second if you can add Media section like dropzone.js that will be really awsome

@rappasoft really appricate your quick response.

**Comment by rappasoft** [comment]
Create what kind of module? The reason I haven't added functionality like dropzone is that it's easy to implement in itself, and I don't want to clutter everything up, that's what differentiates a boiletplate from a full blown project.

**Comment by wasiqaftab** [comment]
@rappasoft thanks for your reply. i understand the difference but its good if you have some thing in description for example of adding a new migration or controller and how it link to permission for the beginners like me. as i see quite few project which give a small example to start with. 
Its just a suggestion for the new commers in laravel

**Comment by rappasoft** [comment]
Hmm ok I will work on something, but look at the code for the view of the frontend index, there are quite a few examples on how to use the access system. Gonna close this to clean up the issues list, but it is on my list.

**Comment by blomdahldaniel** [comment]
Hm.. I must say that the boilerplate should not have to be an introduction to laravel, we have laravel docs and laracasts for that.
