### ISSUE TITLE
Banning and deactivating a socialite user

### ISSUE THREAD

**Issue by brentkozjak** [rappasoft/laravel-5-boilerplate#141]
Hi,

Awesome work on this boilerplate!  I've noticed a permission issue for users that are created through socialite.  When I log in as an administrator and ban or deactivate a social user, they are still able to login.  If I ban a 'local' user, I get the error "Your account is currently deactivated." which is obviously expected.  Has anyone run into this issue?

Cheers!
Brent

**Comment by ChristianGiupponi** [comment]
Same for me
