### ISSUE TITLE
composer error when installing or updating

### ISSUE THREAD

**Issue by MACscr** [rappasoft/laravel-5-boilerplate#142]
Any ideas why I might be getting this? I havent messed with Illuminate afaik.

root@foo:/var/www/html/laravel-5-boilerplate# composer require aws/aws-sdk-php-laravel
Using version ^3.0 for aws/aws-sdk-php-laravel
./composer.json has been updated
> php artisan clear-compiled
PHP Fatal error:  Class 'Laracasts\Utilities\JavaScript\JavascriptServiceProvider' not found in /var/www/html/laravel-5-boilerplate/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Laracasts\Utilities\JavaScript\JavascriptServiceProvider' not found

Script php artisan clear-compiled handling the pre-update-cmd event returned with an error

  [RuntimeException]
  Error Output: PHP Fatal error:  Class 'Laracasts\Utilities\JavaScript\JavascriptServiceProvider' not found in /var/www/html/laravel-5-boilerplate/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [packages1] ... [packagesN]

root@foo:/var/www/html/laravel-5-boilerplate#

**Comment by rappasoft** [comment]
Yes, there was a fix a few days ago, theres a typo in the service provider in app.php, it should be ```JavaScriptServiceProvider```

**Comment by zile-lhs** [comment]
The name of the file you are referencing in vendor folder is JavascriptServiceProvider.php so I think you should rename that file... JavaScriptServiceProvider.php (with capital S in word JavaScript).

**Comment by rappasoft** [comment]
Yeah sorry about that! For some reasons some systems didn't care so I never caught it.

**Comment by ameenross** [comment]
I think this happens because Windows case insensitivity regarding filesystems. Opening "Java*s*criptServiceProvider.php" matches Java*S*criptServiceProvider.php on Windows but not on Linux, giving the error
