### ISSUE TITLE
Feature request: Switch illuminate\html to the LaravelCollective\html

### ISSUE THREAD

**Issue by wink-** [rappasoft/laravel-5-boilerplate#145]
I was wondering if it would be possible to switch from the old unsupported Illuminate\Html form builder to the Laravel Collectives form builder. I switched in my app, however it broke the macros in the process. I've tinkered around for 2 days trying to figure out why with no luck.

**Comment by rappasoft** [comment]
Your wish is my command! See this commit for which files to change: https://github.com/rappasoft/laravel-5-boilerplate/commit/2bee517ef94c41b12812ad9e06beaff954b51222
