### ISSUE TITLE
[Bug] Routes/Global/Lang.php should not use closure 

### ISSUE THREAD

**Issue by timgws** [rappasoft/laravel-5-boilerplate#146]
Currently, thanks to the `lang/{lang}` route being a closure, it is impossible to run `route:cache`:

```bash
# ./artisan route:cache
Route cache cleared!

  [LogicException]
  Unable to prepare route [lang/{lang}] for serialization. Uses Closure.
```

Making a new controller and setting the route to go to the controller, instead of the closure allows the routes to be cached.

**Comment by rappasoft** [comment]
Merged your fix thank you!
