### ISSUE TITLE
Not actually an issue

### ISSUE THREAD

**Issue by num3thod** [rappasoft/laravel-5-boilerplate#148]
Just a word of praise for @rappasoft and everyone else pitching in here for being so awesome and on the ball. This repo has wheels, baby! Love this project.

**Comment by rappasoft** [comment]
Haha woo thanks! Trying to chip away at the issues one by one in my spare time, sorry it's taking so long.

**Comment by rappasoft** [comment]
Btw good job guys we are featured here: https://github.com/chiraggude/awesome-laravel#starter-projects

**Comment by truejay** [comment]
I'd like to say thank you to @rappasoft and all the contributors as well.
Great work guys!

**Comment by blomdahldaniel** [comment]
Yes this is really awesome! I hope i will get the time soon and try to help out even more. :)

**Comment by jarod51** [comment]
@rappasoft keep on the good work ! This is so useful !

**Comment by krishnaguragain** [comment]
@rappasoft awesome work.

**Comment by rappasoft** [comment]
Thanks everyone!
