### ISSUE TITLE
A question about Twitter Bootstrap

### ISSUE THREAD

**Issue by jarod51** [rappasoft/laravel-5-boilerplate#149]
@rappasoft i see that TBS is installed twice. First time by Composer and then by NPM. Is this useful ?

**Comment by rappasoft** [comment]
It's merely an option of choice of where you want to pull the files from in gulp, I was thinking about just keeping the composer version and losing the npm version. It was a pull request someone gave me in the early stages but I completely forgot about it. It's probably easier to just remove so there's no conflicts in the future. What do you think?

**Comment by jarod51** [comment]
I love to keep my composer only for framework purposes (i mean PHP stuff). In my opinion every other client side libraries (CSS, JS, etc...) should be managed by NPM

Npm is fine for me (there's a lot of libraries available @npmjs !)

**Comment by jarod51** [comment]
in my opinion, font-awesome should also be moved to package.json

**Comment by safoorsafdar** [comment]
well, agree with @jarod51 , (css, js) should handle with build tool like gulp etc with npm and php packages should handle with Composer.

**Comment by rappasoft** [comment]
Done: https://github.com/rappasoft/laravel-5-boilerplate/commit/fa4be38a7498ed46514bb63c87fb7f3393454ed9
