### ISSUE TITLE
Getting Bad Request on Amazon EC2.

### ISSUE THREAD

**Issue by cypherzam** [rappasoft/laravel-5-boilerplate#15]
Hi I'm getting this Bad Request from facebook on amazon ec2 during login via FB. Everything works fine on my local machine. When I debugged the bad request error it seems that facebook is saying the token has already been used. Please help.

**Comment by rappasoft** [comment]
Try a new token?

**Comment by cypherzam** [comment]
the problem is it seems to fire getAccessToken from socialite twice with a second interval using the same access token provided by FB thru redirect.

**Comment by rappasoft** [comment]
I doubt that was done by something I did, I assume it is a socialite problem? Though I have successfully logged in through facebook using this bp.

**Comment by cypherzam** [comment]
Found the issue... It seems its an HHVM/nginx issue with socialite...

//ty
