### ISSUE TITLE
permission dependencies check js issue

### ISSUE THREAD

**Issue by zxishere** [rappasoft/laravel-5-boilerplate#150]
Sorry for my bad english first.
When access Edit Role - > Grouped Permissions
if i click User **group**(not child nodes) ,the whole user permissions tree  will checked , But  **View Backend** and **View Access Management**  will not checked.
Only i need uncheck  **Create Users**  and check it again ,the above permission dependencies will checked.

I found js in public/js/backend/access/roles/script.js line 34-52 , maybe if check one empty group node, it need recursion fo find  all it's children and  check children's permission dependencies , but sorry for my poor ability i can't fix it 

```
}).on('changed.jstree', function (event, object) {
    //Check all dependency nodes and disable
    if (check_dependencies) {
        if (!!object.node) {
            if (!!object.node.data.dependencies) {
                if (object.node.data.dependencies.length) {
                    var checked = tree.jstree('is_checked', object.node);

                    for (var i = 0; i < object.node.data.dependencies.length; i++) {
                        if (checked) {
                            tree.jstree('check_node', object.node.data.dependencies[i]);
                            checkUngrouped(object.node.data.dependencies[i]);
                        }
                    }
                }
            }
        }
    }
});
```

**Comment by rappasoft** [comment]
I believe this may have been fixed in a version after this issue, because I can not replicate it no matter how hard I try.
