### ISSUE TITLE
Language Switiching

### ISSUE THREAD

**Issue by krishnaguragain** [rappasoft/laravel-5-boilerplate#151]
I think the language switch should be like this :-
 http://iridadesign.com/starter-public-edition-4/www/

for e.g:- /contact (default language)
             /br/contact(after changing language)

**Comment by rappasoft** [comment]
What is the benefit of doing this way? (Honestly, I don't know. SEO maybe?)

**Comment by krishnaguragain** [comment]
yes man, actually i am new on laravel and befor this i use above codeigniter which help me to boost sites, and i request it to be feature of this boilerplate too.

**Comment by rappasoft** [comment]
I too used to use codeigniter. I wonder if it can be as easy as making it a config option? Is there an example on how to do it via URL?

**Comment by krishnaguragain** [comment]
I think this one will be superb, if we can implement:-
https://github.com/mcamara/laravel-localization

**Comment by rappasoft** [comment]
Added to my research/to-do list.
