### ISSUE TITLE
Please also add testing.

### ISSUE THREAD

**Issue by safoorsafdar** [rappasoft/laravel-5-boilerplate#152]

**Comment by rappasoft** [comment]
I'm really not great at testing, there is a branch for it, I just have done nothing with it. If anyone is more versed please feel free to help.

**Comment by safoorsafdar** [comment]
all right, not a big problem, I will start implementation in my spare time. and I will start from Auth.

**Comment by rappasoft** [comment]
Would be greatly appreciated, people can use it as a learning tool as well. And it will probably find bugs.

**Comment by jarod51** [comment]
I'm also a "great noob" at testing. I will follow your work on this branch for sure :+1:

**Comment by rappasoft** [comment]
Thanks I know theres some I have to merge in and will try to do today.
