### ISSUE TITLE
npm install throwing loads of errors

### ISSUE THREAD

**Issue by datune** [rappasoft/laravel-5-boilerplate#153]
Hi, 

using laravel homestead

![image](https://cloud.githubusercontent.com/assets/2123730/11124178/06e70e16-8964-11e5-9885-ad8be20d65d7.png)

It takes about 30 minutes or more until the command npm install finished, I also tried running it with sudo npm install, but it made no difference. Any ideas why this is happening?

[npm-debug.log.a54a7c7f27206bd3d63c74d3040621b3.txt](https://github.com/rappasoft/laravel-5-boilerplate/files/33076/npm-debug.log.a54a7c7f27206bd3d63c74d3040621b3.txt)

**Comment by num3thod** [comment]
Most likely a vagrant and npm issue.

try this https://harvsworld.com/2015/how-to-fix-npm-install-errors-on-vagrant-on-windows-because-the-paths-are-too-long/

or this https://github.com/npm/npm/issues/7308

**Comment by jarod51** [comment]
+1 on windows homestead is not your friend :) Perfect on linux and mac

Have you tried the little software called Laragon, it's perfect for quick development on windows. It has a command line called cmdr which is good.

Also, check your version of node and npm, rm your node_modules and start from fresh

**Comment by rappasoft** [comment]
I don't use windows so I've never had this problem. Have installed a hundred times on OSX. Someone on windows is going to have to shed some light.

**Comment by num3thod** [comment]
+1 for Laragon. Great little stack to going with this project on Windows.

http://laragon.org/

**Comment by blomdahldaniel** [comment]
Glad to hear that Laragon works just fine, maybe I'll finally dust of my gaming pc and give the windows environment a go. Would you guys say that it is painless with laragon, cause when i tried to start fiddle with cygwin, vagrant and all that nothing went right....

**Comment by num3thod** [comment]
@blomdahldaniel Based on my last experience with Laragon, few months ago, it worked flawlessly. Probably the most enjoyable amp stack I've encountered on Windows.

**Comment by krishnaguragain** [comment]
hello guys please check for gulp, it isn't working on my laragon.

**Comment by num3thod** [comment]
@krishnaguragain Can you post the output/error message you are getting when running gulp in your LB5.1 Laragon installation?

**Comment by rappasoft** [comment]
Is this still an active issue or can we close it?
