### ISSUE TITLE
Help Regarding new Module

### ISSUE THREAD

**Issue by wasiqaftab** [rappasoft/laravel-5-boilerplate#156]
HI

I need little help . i am trying to make a news section in admin i use laravel generator to make the migration, and create Model and controller and view to show it. 

Is there any specific pattern which i have to follow or i am doing right ?
If i need to assign permission to news section so i need to create new permission in admin or something i have to do with repositories

Any help will be appreciated . As i am a beginner in laravel so try to learn things using the standards

Regards
Wasiq

**Comment by rappasoft** [comment]
The repositories are specifically my way of organizing my code, and are usually database specific. I create the contract and implementation, as well as a service provider to bind them, then inject them into the controller.

You will have to make permissions and roles for your module, then reference them in the controllers/request classes/views based on what you want to show. 

I prefer making a request class for most controller action and having them resolved out of the IoC container, and give access to the method through access in the request class.

Don't forget to add the new permissions to the seeder classes for when you launch the app.
