### ISSUE TITLE
052715_1514 is for Laravel 5.0?

### ISSUE THREAD

**Issue by yizhihou2** [rappasoft/laravel-5-boilerplate#159]
@rappasoft is the tag 052715_1514 built on Laravel 5.0? I am looking for a compatible version for Laravel 5.0. Thanks.

**Comment by yizhihou2** [comment]
@rappasoft I found that 051415_1430 is for Laravel 5.0. Thanks.

**Comment by rappasoft** [comment]
Awesome, i'll mark it in case anyone asks!
