### ISSUE TITLE
Class 'Illuminate\Html\HtmlServiceProvider' not found

### ISSUE THREAD

**Issue by fragonik** [rappasoft/laravel-5-boilerplate#160]
when trying login with facebook, google, etc the following error apears:

FatalErrorException in ProviderRepository.php line 146:
Class 'Illuminate\Html\HtmlServiceProvider' not found

thanks

**Comment by rappasoft** [comment]
Did you somehow grab a version where it was using that service provider before it was switched to the newer one? https://github.com/rappasoft/laravel-5-boilerplate/commit/1f103c557054e865679ed81136bad14cee5095c5

Doesn't make sense but that's the only thing I can think of.

**Comment by fragonik** [comment]
No, the problem was that I forgot to change the *_REDIRECT values in my .env file... and the browser was redirected in the old version of code in another directory!!!
sorry to bother for that stupid mistake I made...

thank you for your help and for the superb boilerplate!

**Comment by rappasoft** [comment]
No problem!
