### ISSUE TITLE
[Question] Stripe api update

### ISSUE THREAD

**Issue by ninjaparade** [rappasoft/laravel-5-boilerplate#162]
Hey @rappasoft, 

do you have any interest in possibly bumping the `stripe/stripe-php` version to `3.4.*`?

if so would you be interested in a PR to do so?

**Comment by rappasoft** [comment]
I haven't used stripe since the version thats there. But if the api updated and you would like, then of course!

Anthony Rappa

**Comment by ninjaparade** [comment]
@rappasoft ya, its changed for the better, much cleaner. I'll put something together and send your way in the next couple of days.  :dancer:

**Comment by rappasoft** [comment]
Yes please do, I will merge it in!
