### ISSUE TITLE
Default Authorizarion for role and permission

### ISSUE THREAD

**Issue by nasirkhan** [rappasoft/laravel-5-boilerplate#163]
Do you have any plan to integrate the Laravel default Authorizarion for role and permission? if so, when will i be able to get that?

**Comment by rappasoft** [comment]
I looked at it, and it looks like too much of a pain to merge because of name and class naming conflicts. Plus I think the access library in the boilerplate is much more feature packed. Is there something the default one does that mine doesn't?

**Comment by nasirkhan** [comment]
It is true that the Boilerplate is feature rich. But my point was not on the feature. For most of the product/framework i use, i try to stay with the default as much close as possible. That is the reason i asked you.

**Comment by rappasoft** [comment]
I know what you mean, but it's not a matter of just throwing it in, they do a lot of the same stuff and use a lot of the same class names. The only way to do it properly would be to start the access portion over using the laravel version as the base and add the rest of the stuff on, which seems like more work than its worth.
