### ISSUE TITLE
Feature Request :: System And User Key-Value Set

### ISSUE THREAD

**Issue by krishnaguragain** [rappasoft/laravel-5-boilerplate#164]
I think if we implement this feature in this boilerplate, it will make more easy to develope app.

**Comment by rappasoft** [comment]
Example?

Anthony Rappa

**Comment by krishnaguragain** [comment]
https://github.com/emreakay/CodeIgniter-Aauth#user-parametersvariables

Have a look,

**Comment by rappasoft** [comment]
I've added this to my todo/wish list to research, it can be a possibility in the future.
