### ISSUE TITLE
Question about EloquentUserRepository.php

### ISSUE THREAD

**Issue by andyjessop** [rappasoft/laravel-5-boilerplate#17]
I'm trying to figure out where this code is used - or is it just a helper class that *could* be used in development?

**Comment by rappasoft** [comment]
There are two. One for the front end and one for the back. Without looking I believe both are dependencies in front and backend controllers.

**Comment by rappasoft** [comment]
Also that class isn't instantiated by itself. The contacts are. The bindings are in AccessServiceProvider.php

**Comment by andyjessop** [comment]
Ah I can see those bindings now. I'm not sure exactly what that's doing, so I'll have to do some research. Thanks for the help!

**Comment by rappasoft** [comment]
It extracts the logic to be eloquent specific, if you had a different database setup, you would create OtherDatabaseRepository.php, and bind it to UserContract, then the application would use that version instead.

This is how you can change large parts of applications without editing a thousand files, just one.
