### ISSUE TITLE
Request: Sortable columns in Access Management

### ISSUE THREAD

**Issue by blomdahldaniel** [rappasoft/laravel-5-boilerplate#170]
### Request
I would like to have the ability to sort the Access Management tables. This would make it easier to scan through the users, sorting on:
* name
* email
* activation
* roles permission
* created
* last updated

-------------------
#### Suggestion of JS Library to handle it 
I like to use this library for sorting tables: [tristen/tablesort](https://github.com/tristen/tablesort)
It is easy to set `<th class='no-sort'>Actions</th>` to disable sorting for a specific column or row.

-------------------

Let me know what you think. Then we can discuss further premisses.
I am willing to do the implementation if you would like.

**Comment by rappasoft** [comment]
I was also thinking maybe dataTables AJAX methods? Example: http://datatables.net/manual/ajax

I've accomplished it before in Laravel using: https://github.com/yajra/laravel-datatables which works well.

Ends up looking like: http://datatables.net/examples/ajax/simple.html

And has all of the available dataTables methods available, could be overkill, but it also allows for searching.

Thoughts?

Would be a significant undertaking.

**Comment by blomdahldaniel** [comment]
Cool laravel-plugin for the ajax stuff! I have worked a bit with datatables but not with their ajax method. And I have not worked with that laravel-datatables either. Seems nice though.

#### Thoughts
Fetching data via ajax from a database table is easy and all. And the laravel-plugin you mentioned seems to make that very slim and easy. But, after a quick look through the different index.blade.php files, i saw that a lot of values in the tables are not just columns from a database. It is relations and all that stuff. So if you would like to send that data from the `DatatablesController` you would have to return all kinds of muddy and big arrays like:
`````
// for the access.roles.index view
return [
trans('crud.roles.role') => $role->name,
trans('crud.roles.permissions') => // this need logic to display the permissions
trans('crud.roles.number_of_users') ?> => $role->users()->count(),
trans('crud.roles.sort') => $role->sort,
trans('crud.actions') => $role->action_buttons,

]
`````
Because i guess that you at some point would have to return a specific array like this?
And in my humble opinion that is not a step in the right direction for this repo.
<hr>
#### Use datatables but not through ajax
To use ajax calls like this is nice and slick, but it abstracts out the logic of the table. Something that might look good in private/company code. But in this repo, in my opinion, it must be prioritized to display as much of the logic as possible. So, instead we could use datatables but not fetch the data via ajax.

**Ajax pros**
* The great feeling of ajax
* Slick and beautiful from an architecture perspective
* The *right way* to do it in the long run for private or company projects.

**Non ajax pros**
* Easy to understand what the table displays
  * Logic
  * Relations
  * No abstractions that cause confusion and complexity
* Easy to modify the tables with custom content
* No need for another required composer package
* **No need to remake ANY backend controllers or repositories!**
  * Will make this whole thing much easier to accomplish 
* No need for wiki dokumentation
* Simplicity


#### My final thoughts
I think that you have a great eye for structure and abstraction of code. And i do think that the ajax way would be the right choice in a lot of cases. But for a boilerplate that is suposed to be used by all kinds of users all over the world, the need of simplicity and transparency takes over. I think that all the required backend work to accomplish the ajax responds, in this case, only would make it harder to understand for the users.

I say, keep simplicity, keep all the backend controllers and repositories as it is and use DataTables on the already generated html `<tbody>`.

**Comment by rappasoft** [comment]
The only issue that I see with putting the datatables on the pagination object is you can only sort/search on the page you are on. So if you search for Anthony on page 1, and it is on page 2, it will say no results found.

**Comment by blomdahldaniel** [comment]
yes, but DataTables has its own pagination that works without ajax. So yes, some editing in the backend to remove the pagination stuff.

**Comment by rappasoft** [comment]
Yeah but then you have to load everything at once, if the site has 10,000 users the page will take forever to load everytime.

**Comment by blomdahldaniel** [comment]
Hm.. I didnt see that one coming..
Den 3 dec 2015 5:59 em skrev "Anthony Rappa" <notifications@github.com>:

**Comment by blomdahldaniel** [comment]
I dont know what your aiming for but I guess that most of the targeted people that use and build from this repo is small-medium sized projects. 10 000 would be an exception or am I wrong there?

**Comment by rappasoft** [comment]
I have large scale projects running well on this. Millions of database rows. Pagination is just a best practice because its best to deal with it up front than have to worry about it later. I'm sure there's ways to make the tables more useful without loading all of the rows at once. There are other table plugins, I don't think it would be out of the scope of the project to include them, because it is helping make it a better product as well as giving users a foundation for best practices. DataTables is just the one I'm used to, i'm sure theres other ones.

**Comment by rappasoft** [comment]
Example:

![screen shot 2015-12-03 at 12 17 10 pm](https://cloud.githubusercontent.com/assets/6026504/11567994/d7879ff0-99b7-11e5-8996-dabf5f88bc4d.png)

**Comment by blomdahldaniel** [comment]
Well, then either a fully backend url sorting structure is needed or something like datatables to ajax. 

Maybe that is the better solution after all…

**Comment by rappasoft** [comment]
I think it's the more modern solution. A recent project I've been developing also gave me more ideas for that section to organize better, so i'll try to implement those as soon as I can chop away at the issue list.

Seems every time I complete 5, 10 more are added in a day.

**Comment by blomdahldaniel** [comment]
Haha! xD Youre awesome man! You need to fix "buy me a beer" button soon..
;) Should i close this one then?

2015-12-03 18:22 GMT+01:00 Anthony Rappa <notifications@github.com>:

**Comment by rappasoft** [comment]
Yeah I have a notepad with everyones requests that I try to visit at least once a week and work on.

**Comment by rappasoft** [comment]
Thanks for all your contributions as well!

**Comment by blomdahldaniel** [comment]
Awesome! :+1: 
I will update the Swedish translation soon aswell.
