### ISSUE TITLE
Your account has been banned or deactivated.

### ISSUE THREAD

**Issue by mrgwilliam** [rappasoft/laravel-5-boilerplate#171]
Might be related to #165, when attempting to login with Facebook the following message is rendered "Your account has been banned or deactivated." This is upon first registration!

Even though everything is successfully created in the backend, but no successful message is given to the user.

User can then login successfully

**Comment by rappasoft** [comment]
Socialite will be the end of me.

**Comment by mrgwilliam** [comment]
Could this be due to the fact that it is checking the status before the user is created? When the isBannedOrDeactivated function is called?

**Comment by rappasoft** [comment]
Fixed: https://github.com/rappasoft/laravel-5-boilerplate/commit/aae146b22318e5f30730584349a319197c54ae3e
