### ISSUE TITLE
Cannot register a new user

### ISSUE THREAD

**Issue by vladvisinescu** [rappasoft/laravel-5-boilerplate#174]
so this happens. 

Swift_RfcComplianceException in MailboxHeader.php line 348:
Address in mailbox given [] does not comply with RFC 2822, 3.6.2.

and I tried disabling confimation emails, and this happened:

QueryException in Connection.php line 651:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'users_email_unique' (SQL: insert into `users` (`updated_at`, `created_at`) values (2015-12-07 08:09:58, 2015-12-07 08:09:58))

What can done in such a situation ?

Thanks :)

**Comment by rappasoft** [comment]
The exception itself says there is something wrong in email address fields such as From, Sender or Reply-To fields. Swift Mailer strictly follow RFC standard to avoid emails being caught by spam checker tools. 

Make sure all mail env variables are set.

**Comment by rappasoft** [comment]
Did you get a chance to look an test the above?

**Comment by vladvisinescu** [comment]
yeah sorry. my bad. I messed with the fillable fields on the User model. Hence the QueryException.

**Comment by vladvisinescu** [comment]
I still can`t figure out the mail errors though, but it`s ok, I don`t use e-mail verification anyway. 
Note: I can send any other email from any other controller.
