### ISSUE TITLE
.gitignore and assets

### ISSUE THREAD

**Issue by eleftrik** [rappasoft/laravel-5-boilerplate#178]
Why these folders/files are not in .gitignore?

public/build
public/css/frontend.css
public/css/frontend.css.map
public/css/backend.css
public/css/backend.css.map
public/js/frontend.js
public/js/backend.js

Everytime gulp runs, they are overwritten, so having them not versioned could be useful.
Thank you

**Comment by rappasoft** [comment]
I might be able to understand some, but gulp is meant to be run on development, not productions, so gitignoring the build folder would mean your assets won't be available on your production application.

**Comment by eleftrik** [comment]
@rappasoft Yes, you're right about the build folder.
I can gitignore it by my own, once I have cloned your repository.
In my case, I would gitignore the build folder too, because we're developing in a team, so we constantly swap our build files.
Thank you

**Comment by rappasoft** [comment]
I'm open to other people opinions as well.

**Comment by num3thod** [comment]
Our team needs them tracked for deployment to production (forge). I imagine that would be the norm.

**Comment by rappasoft** [comment]
Yeah I think that's still currently the best option.

**Comment by eleftrik** [comment]
@rappasoft Build folder is ok, what do you think about the other files?

**Comment by rappasoft** [comment]
I suppose they don't need to be tracked? What do you think @num3thod?

**Comment by num3thod** [comment]
Actually, y'all are right. Only the build folder needs to be tracked. Makes sense.

**Comment by rappasoft** [comment]
I'll try it locally and see if it makes sense.

**Comment by num3thod** [comment]
Same

**Comment by rappasoft** [comment]
Worked fine for me: https://github.com/rappasoft/laravel-5-boilerplate/commit/062e24f6b682f5d5f77c787b53b6f38195288f6c

**Comment by eleftrik** [comment]
Thank you @rappasoft!
