### ISSUE TITLE
Access Control @roles(['a','b']) not working

### ISSUE THREAD

**Issue by binaryk** [rappasoft/laravel-5-boilerplate#179]
@rappasoft primarily thanks for boilerplate.

But In my views not functioning:
@roles
@needsroles
@permissions
etc.
==> They are interpreted as text.

Only @role and @permission work great. 

Thx.

**Comment by binaryk** [comment]
I had the last version for AccessServiceProvider. 

:)

**Comment by rappasoft** [comment]
Ah yes it was updated :)
