### ISSUE TITLE
Field repetition in role creation

### ISSUE THREAD

**Issue by jpmurray** [rappasoft/laravel-5-boilerplate#184]
As seen in [this screenshot](http://i.imgur.com/KqHP3pi.png), it seems that fields are repeated in the role creation. Either it's not supposed to, or I misunterstand something.

**Comment by rappasoft** [comment]
How in the hell...

**Comment by rappasoft** [comment]
It's on my master copy too, I don't know how the hell I did that.

**Comment by rappasoft** [comment]
Just delete the last set of 3 form groups, i'll make a hotfix.

**Comment by rappasoft** [comment]
Good catch: https://github.com/rappasoft/laravel-5-boilerplate/commit/fce534d8d3c604c8f732147a9fad9406549ffd06

**Comment by jpmurray** [comment]
Haha, that's my kind of contribution ;-) I should have done a PR :P
