### ISSUE TITLE
Require IDE helper by default

### ISSUE THREAD

**Issue by jmversteeg** [rappasoft/laravel-5-boilerplate#185]
Have you considered requiring https://github.com/barryvdh/laravel-ide-helper by default? I would propose adding it because it offers the ability to generate an excellent IDE helper file that facilitates autocompletion for models, facades, etc.. in most IDEs.

**Comment by jmversteeg** [comment]
I see it has been discussed before in #185 but the advantage of this package is it doesn't do anything by default, running the ide-helper:generate command is optional

**Comment by blomdahldaniel** [comment]
I dont think the purpose of this boilerplate is to include all possibly good packages. I must say it is better to keep the boilerplate as clean as possibly, only include stuff that supports the boilerplate core. If you would have to run `ide-helper:generate` to use it, it wouldnt be a hard to require it by hand as well. Therefore I think this boilerplate should stay as an open boilerplate that does not force unnecessary packages to the users.

**Comment by rappasoft** [comment]
I agree with @blomdahldaniel as it will add vendor files that are unnecessary. Maybe instead we can create a wiki page for suggested packages?

**Comment by blomdahldaniel** [comment]
That is a great suggestion!

**Comment by jmversteeg** [comment]
@blomdahldaniel fair enough. @rappasoft that sounds like a great idea.

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/wiki/8.-Suggested-Packages
