### ISSUE TITLE
Best way to update from 5.1? 

### ISSUE THREAD

**Issue by stephenahiggins** [rappasoft/laravel-5-boilerplate#186]
Hi, 

This may sound like a ridiculous question, but what is the best way to update from 5.1? 

Keep up the good work. It's a great project!

**Comment by rappasoft** [comment]
From 5.1 to what?

**Comment by shiruken1** [comment]
5.2, maybe?

**Comment by stephenahiggins** [comment]
To 5.1.26. 

I've created a live project around 5.1.0 inn August. I've noticed that you've made quite a few updates. 
I was wondering if theres an easy way to update the core files? 

Obviously without starting a fresh and re-integrating all of the work I've created.

**Comment by rappasoft** [comment]
Not really, it's kind of an as is project. There's no easy way for me to push updates out.

As for 5.2, which was just released, i'll check the upgrade docs and see if it's feasible or if i'd have to do the whole thing over.

**Comment by jekinney** [comment]
Just did it.

I would suggest:
Go to github page for 5.2.
Route class has changed so copy and past the new conf/app.php default providers.
Copy/Paste the new Auth cfg too,
Routes file make sure everything has Route:: not just get() etc.
Add New AuthServiceProvider in app/Providers.

Run composer update

**Comment by stephenahiggins** [comment]
No probs.

Thanks for the responses.

**Comment by rappasoft** [comment]
I'll try to update it tonight as long as nothing goes terribly wrong.

**Comment by rappasoft** [comment]
@jekinney what did you do about the laravelcollective/html requirement for illuminate/support 5.1.*?

**Comment by rappasoft** [comment]
Seems laravelcollective/html is not yet compatible with 5.2, but I assume it will be shortly, as soon as it is I will upgrade the project (I don't think I need to start over)

https://github.com/LaravelCollective/html/issues/133

**Comment by ChristianGiupponi** [comment]
Are you sure to update to 5.2?
5.1.x is LTS while 5.2 don't

**Comment by rappasoft** [comment]
Which makes no sense to me, but I want the new features like everyone else.

**Comment by rappasoft** [comment]
I have it working locally, it's going to be kind of a pain for anyone trying to update from the 5.1 version, but it shouldn't be THAT bad. A lot has changed, I almost want to start this over from a fresh 5.1 install. But that's a massive amount of work and I believe another update comes out in June of this year.

**Comment by rappasoft** [comment]
Before I merge it is does anyone want to try?

https://github.com/rappasoft/laravel-5-boilerplate/tree/feature/5.2_upgrade

**Comment by rappasoft** [comment]
Done
