### ISSUE TITLE
problem in php artisan db:seed

### ISSUE THREAD

**Issue by texnika01** [rappasoft/laravel-5-boilerplate#189]
[Illuminate\Database\Que
SQLSTATE[42000]: Syntax
n your SQL syntax; check
 version for the right s
E TABLE users CASCADE)

**Comment by ChristianGiupponi** [comment]
post your migration code

**Comment by rappasoft** [comment]
Which driver are you using?

**Comment by texnika01** [comment]
Driver Mysql.I deleted rows  postgreSQL and worc.

**Comment by rappasoft** [comment]
Yeah that happens sometimes. I'll figure something else out when I remake it.
