### ISSUE TITLE
role for blade extension has failure

### ISSUE THREAD

**Issue by error500** [rappasoft/laravel-5-boilerplate#190]
While this works :
```
    @role('Administrator')
        <p>Hello</p>
    @endauth
```
This use case extends admin.layout  for any role
```
    @role('Administrator')
         @extends ('admin.layout') 
     @endauth
```

Also :
Could  be nice to have an @elseauth use case :
```
    @role('Administrator')
         <p>Danger</p>
    @elseauth
         <p>Everything is allright</p>
    @endauth
```

**Comment by rappasoft** [comment]
It would be more appropriate to pick which view to render from the controller if it's completely different, i'm not sure you can wrap the extends in an if statement by any means.

**Comment by error500** [comment]
Yes i'm sure. But does it mean that @Role is not supporting any @... directive ?

**Comment by rappasoft** [comment]
These are just helper statements around

```if (access()->hasRole('Role'))```

So you have to be weary not to put anything inside it that you wouldn't a normal if, if you need more control to to the controller level:

```
if (access()->hasRole('Admin'))
    return view('admin.dashboard');
else
    return view('user.dashboard');
```

**Comment by rappasoft** [comment]
Also as fat as '@elseauth' is concerned, you should be able to use the default '@else' as it just prints ":else", I haven't tried it, but it works in theory.

**Comment by error500** [comment]
ok i'll try and give you a feedback.
Maybe could you put this infos in the wiki ?

**Comment by rappasoft** [comment]
Will do!

**Comment by rappasoft** [comment]
The else thing is already in there, but I added clarification about what to put inside.
