### ISSUE TITLE
.env.example spaces in values

### ISSUE THREAD

**Issue by jimserio** [rappasoft/laravel-5-boilerplate#192]
Looks like 5.2 updated  [vlucas/phpdotenv] (https://github.com/vlucas/phpdotenv) from 1.1.1 to 2.1.0 which causes problems with spaces in the values within .env. Currently, with:

APP_KEY=WILL BE GENERATED

artisan key:generate will not update .env with the new key, nor will any changes made to .env be read (for example, artisan migrate will still read the DB_ info from database.conf). Recommend replacing spaces with underscores. Here's a similar (but relevant) thread on StackOverflow:

http://stackoverflow.com/questions/34420761/laravel-5-2-not-reading-env-file

**Comment by rappasoft** [comment]
Fixed thank you.
