### ISSUE TITLE
artisan optimze isssue on first install

### ISSUE THREAD

**Issue by jimserio** [rappasoft/laravel-5-boilerplate#193]
Not sure how to explain this so here are the steps:

1.) clone boilerplate into new directory
2.) run composer install

The following error occurs during the post-install-cmd:

-----
Compiling common classes

  [ErrorException]                                                                   
  php_strip_whitespace(/home/vagrant/laravel/uwtmp): failed to open stream: Success  
                  
Script php artisan optimize handling the post-install-cmd event returned with an error
    
  [RuntimeException]  
  Error Output:
-----

According to this [post] (https://laracasts.com/discuss/channels/laravel/laravel-optimize-error) on Laracasts, the problem can be resolved by removing the additional compiled classes from config/compile.php. This allowed me to perform the install. Interestingly enough, after a successful composer install, if I restore those deleted lines from compile.php, any composer updates work.

P.S. There is no error output. Sorry for the poor formatting - not used to using markdown :)

**Comment by mrgwilliam** [comment]
Can confirm this occurs with the release zip and git clone

**Comment by rappasoft** [comment]
I did a fresh install and didn't get any errors. Could just be my dev environment.

**Comment by mrgwilliam** [comment]
I was using ScotchBox Vagrant box when I ran the composer install command.

**Comment by rappasoft** [comment]
So this is resolved by just deleting the compiled.php file?

**Comment by jimserio** [comment]
I'm using Vagrant Homestead on Windows (Homestead-7). Everything is up to date. Yes for me, deleting compile.php resolves the issue but I wonder what repercussions there are?

**Comment by rappasoft** [comment]
Fixed here: https://github.com/rappasoft/laravel-5-boilerplate/commit/57525ea71c59df8b31680c781a7ee0f30b248404
