### ISSUE TITLE
Migrations errors after upgrade to 5.2

### ISSUE THREAD

**Issue by R00118189** [rappasoft/laravel-5-boilerplate#194]
I think it may be related to config auth.PHP change in 5.2
Fresh clone and migrate unsucesfull
I know it is not package rwlated but after update .env file on homestead is not seen by framework
Artisan key:generate does not change existing .env file (Dec 17th commit works no problem)

**Comment by rappasoft** [comment]
Fixed: https://github.com/rappasoft/laravel-5-boilerplate/commit/828c7356de5bcf1a0d6f12e38c60e6fd4227d645
