### ISSUE TITLE
artisan migrate error message

### ISSUE THREAD

**Issue by altafhussain10** [rappasoft/laravel-5-boilerplate#196]
Hi, 
I just installed your application from git. After that when i ran php composer.phar install command, it gave me the error shown in attached screenshot 1. 

![screenshot 1](https://cloud.githubusercontent.com/assets/4163772/11995006/3173b186-aa5a-11e5-9b11-d6a1e636fd72.png)

Then i ran the install command again and it was fine. 
The php artisan key:generate was also fine. 
I setup .env file and setup database details properly and then i ran php artisan-migrate and now it give me error shown in attached screenshot 2. 

![screenshot 2](https://cloud.githubusercontent.com/assets/4163772/11995005/316f288c-aa5a-11e5-8ddf-531d98c70218.png)

Can you please give some advice about this issue? 

Thank you

**Comment by rappasoft** [comment]
I've never seen that one, have you thought about installing Laravel Homestead?

**Comment by altafhussain10** [comment]
No, i have tried that once, but i did not liked personally :P . I am also not sure what is causing the above problem. I checked migrations folder, and all files are there.

**Comment by rappasoft** [comment]
I only ask because I developed the whole thing on it. Why don't you like? It has everything you need and the server you will run on production will most likely have all of the same stuff.

**Comment by altafhussain10** [comment]
I used it for something, and it was hard for me to manage it properly. But i guess i will give it a try.

**Comment by altafhussain10** [comment]
Now i have setup homestead and it is running fine, but i still got the same problem with boilerplate :(

**Comment by altafhussain10** [comment]
I just checked laravel version and it is 5.2.3, and as i know you had some problems with this version. Is there any way to move back to 5.1?

**Comment by rappasoft** [comment]
I'm probably going to revert everything back to this, but this is the last stable 5.1: https://github.com/rappasoft/laravel-5-boilerplate/releases/tag/1.12.6

**Comment by altafhussain10** [comment]
Thanks for all the details and your help. I have installed homestead and everything is working fine.
I really appreciate your hard work on this project. 
Thanks for everything.
