### ISSUE TITLE
Ability to propose npm OR bower

### ISSUE THREAD

**Issue by error500** [rappasoft/laravel-5-boilerplate#197]
Anthony, you merged recently from composer to npm for all of front end stuff. Does it suppose that all of other front end stuff has to be also managed thru npm ?
I used bower also but i'm not sure that depencies ar not beeing in confilct...

**Comment by rappasoft** [comment]
Laravel 5.2 now uses npm to install bootstrap sass, so I think they'll be going that route and it's good to keep on track with them.

**Comment by error500** [comment]
ok. Let's go on npm

**Comment by rappasoft** [comment]
Yeah it's best bet for now.
