### ISSUE TITLE
[Question] Assigning (editing) users role(s)

### ISSUE THREAD

**Issue by ninjaparade** [rappasoft/laravel-5-boilerplate#199]
I've noticed that currently there is no method within the admin to assign a user to a role or edit that users role via the admin. The only time such action is available is during user creation.

Is this feature omitted for a reason or would this feature be something you'd be okay with seeing in this boilerplate?

I know you're thinking of rebuilding for 5.2 but wondered if this would be a worthwhile PR to send to the to the 5.1 build.

**Comment by rappasoft** [comment]
What?

<img width="1440" alt="screen shot 2015-12-28 at 11 44 36 pm" src="https://cloud.githubusercontent.com/assets/6026504/12029609/0649488e-adbd-11e5-8040-5d6ef384c4a5.png">

**Comment by ninjaparade** [comment]
@rappasoft my bad, I don't see the full edit screen if I am trying to "edit" my own user that i am currently logged in as.

**Comment by rappasoft** [comment]
The only user that differs is the first administrator, you can only change the name and email because the other options have to be set in stone for the system to work correctly. As the admin has rights to everything.
