### ISSUE TITLE
Strategy when additional user fields are needed 

### ISSUE THREAD

**Issue by error500** [rappasoft/laravel-5-boilerplate#200]
Can be done : add fields to user table and modify User model. But upgrading can be difficult 
Or :  create a table with a one to one relation to user. This is less intrusive and upgrades easier.
Also : for relations from user to other tables of the project, is it  better to build a model with extends user model ?

**Comment by rappasoft** [comment]
What you would have to do would be:

1. Add database fields
2. Add fields to user create methods
3. Update request classes
4. Add fields to views

I think this would make it less flexible as the developer would be locked into doing it this way, storing the fields in a table is something that full CMS like wordpress or magento would do.

I don't know if I understand the other part.

**Comment by error500** [comment]
Ok Anthony, what you say is that developer can widely override the user table and user controller.
I fear that the update would be difficult when upstream code and user project code are too much mixed...

**Comment by rappasoft** [comment]
Generally this project is used as an as-is start, and is not really meant to be updated with each commit I make. So if you started a new project now you would get 2.0 features, but if you had an old one I wouldn't try to update each time I make a change because it would be too much work.

**Comment by error500** [comment]
Ok understood. 
I'll try however to maintain it by fetch/merge..

**Comment by blomdahldaniel** [comment]
I just wanna ad to the *to do* points in @rappasoft's list from above to be more explicit of the process. Something i often happens to forget:
* Add the new fields to the models `$fillable[]`
