### ISSUE TITLE
Socialite - Twitter does not provide email

### ISSUE THREAD

**Issue by mrgwilliam** [rappasoft/laravel-5-boilerplate#201]
Twitter OAuth does not provide an email when using the OAuth. This leads to an error as the email field cannot be null.

**Comment by error500** [comment]
Hi
See issue and wiki section in https://github.com/rappasoft/laravel-5-boilerplate/issues/114
Your app need to be whitelisted at twitter.

**Comment by mrgwilliam** [comment]
Ah thank you, totally missed that section.
