### ISSUE TITLE
Back-end view issue when the main language (APP_LOCALE) is not EN

### ISSUE THREAD

**Issue by Arrakeen** [rappasoft/laravel-5-boilerplate#205]
There is a small issue when the main APP language is not EN (English). 
I get an error when I try to access the back-end (/admin/*):

![image](https://cloud.githubusercontent.com/assets/10560326/12071478/c9ed3878-b0af-11e5-9e4b-5f22d096e938.png)

I know we are supposed to create the missing file (using the correct language code), but a default statement could be added to check if the main language file is missing.
In that case the APP_FALLBACK_LOCALE file (that should always be EN by default) could be displayed.

Everything runs well on the front-end side.

**Comment by error500** [comment]
Your default language should be FR-FR and not just fr

**Comment by rappasoft** [comment]
I agree with you I can try to make a helper function as soon as I can.

**Comment by rappasoft** [comment]
Fixed. https://github.com/rappasoft/laravel-5-boilerplate/wiki/10.-Helpers
