### ISSUE TITLE
Role save problem

### ISSUE THREAD

**Issue by hawkefly** [rappasoft/laravel-5-boilerplate#21]
Select a role, and click the edit button , and then save. repeat this action ,The permissions will duplicate each time in the list.
![71eabc96-46ec-4f7b-be32-16b8edfa8e65](https://cloud.githubusercontent.com/assets/12472105/7728252/b624d9c0-ff40-11e4-9f70-07f0ab74771c.png)

**Comment by rappasoft** [comment]
This is fixed in the upcoming 5.1 release. But you can fix it by going to EloquentRoleRepository.php to the update method and replacing it with this:

```
public function update($id, $input, $permissions) {
		$role = $this->findOrThrowException($id);

		//Validate
		if (strlen($input['name']) == 0)
			throw new GeneralException('You must specify the role name.');

		//See if the role must contain a permission as per config
		if (config('access.roles.role_must_contain_permission') && count($permissions['role_permissions']) == 0)
			throw new GeneralException('You must select at least one permission for this role.');

		$role->name = $input['name'];

		if ($role->save()) {
			//Remove all permissions
			$role->detachPermissions($role->permissions);

			//Attach permissions, if any
			if (count($permissions['role_permissions']) > 0)
				$role->attachPermissions($permissions['role_permissions']);

			return true;
		}

		throw new GeneralException('There was a problem updating this role. Please try again.');
	}
```

**Comment by rappasoft** [comment]
Delete that role and clear the permissions from it in the database as well to make sure its working properly.

**Comment by hawkefly** [comment]
Yes , it works perfect now, thank you.

**Comment by rappasoft** [comment]
No problem sorry mean to make a hotfix but was in the middle of the 5.1 conversion and didn't want to lose track of where I was.

**Comment by dhb52** [comment]
It seems that with Firefox, I refresh the page(/admin/dashboard) several times, then I get a  TokenMismatchException in compiled.php.

But with IE, chrome, it works well.

**Comment by rappasoft** [comment]
Weird, it could be something to do with the way firefox handles sessions.

**Comment by rappasoft** [comment]
Though Laravel has been known to have Token exceptions on rapid refresh, just like on multiple AJAX calls at the same time. I don't know if there is a solution. But  why are you refreshing several times on the dashboard?

**Comment by dhb52** [comment]
Another fatal problem to me, it seems form submit fails more often than never.

**Comment by dhb52** [comment]
Sorry for the OT above.

Why not use Role::savePermissions for patch of this issue?

**Comment by rappasoft** [comment]
Good question, that's a better solution. Good call, i'll commit it.
