### ISSUE TITLE
Encoding format for language pack and JS messages

### ISSUE THREAD

**Issue by error500** [rappasoft/laravel-5-boilerplate#213]
I used UTF-8 for all resources files containing messages.
On strings.php, the 'delete_user_confirm' message is brought to the user through javascript. The message is transformed with html entities.

**Comment by rappasoft** [comment]
Is there an error of some sort?

**Comment by error500** [comment]
No ,  it's just that html entities are not rendered :
http://prntscr.com/9m2fqw

**Comment by AlexandreBeauduin** [comment]
same problem here :)

normally it should have been : "Veuillez renseigner au moins un critère de recherche"

![capture d ecran 2016-01-12 a 12 44 24](https://cloud.githubusercontent.com/assets/6662875/12262792/5361d370-b92a-11e5-9cb0-732f38a20bc5.png)

**Comment by AlexandreBeauduin** [comment]
problem solved using {!! trans(...) !!}} instead of {{ trans(...) }}

**Comment by rappasoft** [comment]
Should we just use {!! !!} for trans globally?

**Comment by error500** [comment]
The reason to use {{}} is for protecting language files against  injecting html tags is it ? If so, since files canot be injected we can effectively use {!! !!} ? Am I wrong ?

**Comment by rappasoft** [comment]
No you're right, there has to be a solution we can't be the first to notice this.

**Comment by vjandrea** [comment]
My 2cts: you should use {!! trans(...) !!} only when planning to display the string in javascript dialogs, in particular alert() and confirm(). With tooltips and other content {{ trans(...) }} should work correctly, but i'll make some tests to be 100% sure.
Anyway i agree with @error500 that with hardcoded language strings the risks for injection are minimized.

**Comment by rappasoft** [comment]
Anyone know off hand which views the ones that need to be modified are in? Or can make a PR?
