### ISSUE TITLE
French language encoding scheme issue

### ISSUE THREAD

**Issue by Arrakeen** [rappasoft/laravel-5-boilerplate#216]
There is a problem with the encoding scheme used in the French language pack:

![selection_008](https://cloud.githubusercontent.com/assets/10560326/12104934/5c7b1082-b350-11e5-9422-01ab41139957.png)

Php files should **always** be saved with the UTF-8 **without BOM** encoding scheme.
It creates some issues in the HTML code when using the French language:

![selection_009](https://cloud.githubusercontent.com/assets/10560326/12104962/97314eb2-b350-11e5-9ec6-008ffada51b6.png)

The source:

![selection_010](https://cloud.githubusercontent.com/assets/10560326/12104964/9f7f6842-b350-11e5-9b4f-6cbacd286b38.png)

As you can see, **"&#65279"** appears in the source code. This has been discussed here: http://stackoverflow.com/questions/9691771/why-is-65279-appearing-in-my-html

With the English language, everything is fine:
![selection_011](https://cloud.githubusercontent.com/assets/10560326/12104984/db2f48e4-b350-11e5-9e82-3b2885e3986b.png)

**Comment by error500** [comment]
yes i've seen this problem. I deed something already. I'll pull a request soon

**Comment by rappasoft** [comment]
I believe this was fixed by a recent pull request from @error500. Thank you sir.
