### ISSUE TITLE
Donate button

### ISSUE THREAD

**Issue by blomdahldaniel** [rappasoft/laravel-5-boilerplate#217]
This issue is meant to be like a little annoying kid. Poking and nagging at you until you set up some kind of way that we can donate a couple of bucks, a beer or two to you... Especially now that we have reached 2.0 and how awesome it is!

**So Anthony, please give us a way to give some of it back to you.**

**Comment by limatheus** [comment]
:+1:

**Comment by Arrakeen** [comment]
I strongly agree :clap:

**Comment by krishnaguragain** [comment]
:+1:

**Comment by rappasoft** [comment]
You guys are crazy and it's completely unnecessary but try this link if you insist: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=JJWUZ4E9S9SFG&lc=US&item_name=Laravel%205%20Boilerplate&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted

**Comment by error500** [comment]
just done

**Comment by petergit67** [comment]
I just made an payment to show my gratitude.

Keep up your great work.

**Comment by rappasoft** [comment]
Thanks guys its greatly appreciated.

**Comment by blomdahldaniel** [comment]
Glad this finally made you do it. This issue has served its cause. :)

**Comment by rappasoft** [comment]
This has served its purpose thanks fellas :+1: Cleaning up the issue list.
