### ISSUE TITLE
db:seed error

### ISSUE THREAD

**Issue by krishnaguragain** [rappasoft/laravel-5-boilerplate#218]
![capture](https://cloud.githubusercontent.com/assets/6104245/12135431/82563570-b463-11e5-9f18-b63c1c1c1191.PNG)

**Comment by rappasoft** [comment]
Try commenting out the conditionals at the tops of the seeders until one works, if you're using the mysql driver, just delete all the non mysql related code in the seeders and try again.

**Comment by error500** [comment]
Can you check if you have this line in your .env file ?
DB_CONNECTION=mysql

in 5.1, it was 
DB_DRIVER=mysql

**Comment by rappasoft** [comment]
What driver are you using? You seem to be hitting the 'else' of those statements.

**Comment by rappasoft** [comment]
I've never heard of MariaDB, you may have to alter the syntax to fit that system.

**Comment by krishnaguragain** [comment]
![capture](https://cloud.githubusercontent.com/assets/6104245/12160360/5e818db0-b513-11e5-9a9f-4ebc3dec641d.PNG)

**Comment by krishnaguragain** [comment]
i have just comment the line and copy paste the above code, it fixes these errors in seeders.

**Comment by rappasoft** [comment]
What is your DB_CONNECTION set to? Is it mariadb?

**Comment by krishnaguragain** [comment]
it's mysql

**Comment by rappasoft** [comment]
Then it should be hitting the first clause of the if statement but for some reason it's not.

**Comment by krishnaguragain** [comment]
yes man. i think @error500  might be right

**Comment by rappasoft** [comment]
Did you have DB_DRIVER instead of DB_CONNECTION?

**Comment by krishnaguragain** [comment]
I have DB_DRIVER=mysql.

**Comment by rappasoft** [comment]
Should be DB_CONNECTION=mysql in 5.2, that is most likely your problem.
