### ISSUE TITLE
page(/admin/dashboard)  seems not working with firefox well

### ISSUE THREAD

**Issue by dhb52** [rappasoft/laravel-5-boilerplate#22]
It seems that with Firefox, I refresh the page(/admin/dashboard) several times, then redirect to /dashboard(the homepage),
sometimes, summit from a from then I get a TokenMismatchException in compiled.php.

But with IE, chrome, it works well.

**Comment by rappasoft** [comment]
Though Laravel has been known to have Token exceptions on rapid refresh, just like on multiple AJAX calls at the same time. I don't know if there is a solution. But why are you refreshing several times on the dashboard?
