### ISSUE TITLE
Issue when updating user's informations?

### ISSUE THREAD

**Issue by Arrakeen** [rappasoft/laravel-5-boilerplate#220]
There is an issue with the `ProfileController@update` method.
Both of the columns **created_at** and **updated_at** are being updated when editing and saving user's informations from the frontend dashboard.
I just wanna be sure that this odd behaviour comes from your code and not from mine.

**Comment by rappasoft** [comment]
No you are correct, I have no idea why that's happening. It's not from the update method because there's nothing in there that would cause that. It has to be happening somewhere else.

**Comment by rappasoft** [comment]
Oh I figured it out. The created_at column has an ```on update CURRENT_TIMESTAMP``` attribute which it shouldn't. I'm not adding that anywhere, does anyone see where it is coming from?

**Comment by rappasoft** [comment]
It seems this was an issue in the past, but i'm not sure how to fix it without changing all of the migrations:

https://github.com/laravel/framework/issues/1260

**Comment by petergit67** [comment]
Can't reproduce, works correct in both frontend and backend.

**Comment by rappasoft** [comment]
I can re-produce, if you do a fresh migrate, all created_at have an ```on update CURRENT_TIMESTAMP``` as an extra. It may have something to do with the mysql version.

**Comment by rappasoft** [comment]
What i'm going to do, which will have no effect on anything but fix for all versions, is to replace

```
$table->timestamps();
```

with

```
$table->timestamp('created_at')->default(DB::raw('CURRENT_TIMESTAMP'));
$table->timestamp('updated_at')->default('0000-00-00 00:00');
```

Which fixes the problem and has the same result.

Any opposed?

**Comment by petergit67** [comment]
So the con in 2014_10_12_100000_create_users_table.php should be:

<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('email')->unique();
            $table->string('password', 60)->nullable();
            $table->string('confirmation_code');
            $table->boolean('confirmed')->default(config('access.users.confirm_email') ? false : true);
            $table->rememberToken();
            $table->timestamp('created_at')->default(DB::raw('CURRENT_TIMESTAMP'));
            $table->timestamp('updated_at')->default('0000-00-00 00:00');
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('users');
    }
}


I added use Illuminate\Support\Facades\DB; was that correct?

**Comment by rappasoft** [comment]
Yes, you shouldn't need to import the facade as it's in the global namespace. This: https://github.com/rappasoft/laravel-5-boilerplate/commit/647548ee98394c11525a808c2bea9f979df9b414

works fine on my end.

**Comment by rappasoft** [comment]
You can add them for good measure and for your IDE not to complain though.

**Comment by rappasoft** [comment]
Seems to only happens for some versions of mysql, so i'll just keep it since that fix will work for all versions since its more explicit.

**Comment by blomdahldaniel** [comment]
I would prefer that **updated_at** also get the current timestamp on creation. That is how it works with timestamps() by default in laravel right? Doesn't make sense to put a 000.. date?
So instead as well?
`$table->timestamp('updated_at')->default(DB::raw('CURRENT_TIMESTAMP'));`

**Comment by Arrakeen** [comment]
I'm using 10.0.22-MariaDB-0ubuntu0.15.10.1 - (Ubuntu) in my development environment. I'm checking if your solution resolves the problem. Thanks!
