### ISSUE TITLE
locale possible duplicate in /exceptions.php ?

### ISSUE THREAD

**Issue by blomdahldaniel** [rappasoft/laravel-5-boilerplate#222]
I wonder if this is a typo or some kind of misstake. Or what should this error say? It is the exact same as `update_error`. Should it be the exact same response?
````
// lang/*/exceptions.php
'users' => [
...
'mark_error' => 'There was a problem updating this user. Please try again.',
...
];
````

**Comment by rappasoft** [comment]
Yeah I believe that is the exception thrown when you activate/deactivate a user, the other is when you edit a users information. I separated them in case people wanted different messages.

**Comment by blomdahldaniel** [comment]
Splendid sir!
