### ISSUE TITLE
Add pluralization to translations

### ISSUE THREAD

**Issue by blomdahldaniel** [rappasoft/laravel-5-boilerplate#230]
Since it is pretty easy to add pluralization to translations I see no use in having translations like this:
````
'total' => 'permissions(s) total',
````

With the pipe function (see [/docs/5.2/localization#pluralization](https://laravel.com/docs/5.2/localization#pluralization) )

````
'total' => 'permission total|permissions total ',
````

In the view:
````
// From:
{{ $roles->total() }} {{ trans('labels.backend.access.roles.table.total') }}

// To:
{{ $roles->total() }} {{ trans_choice('labels.backend.access.roles.table.total', $roles->total() ) }}
````

I could do this PR if you think it is an improvement that should be done.
I guess this would be the same for 
* User(s)
* Permission(s)
* Role(s)

I can take a look and search for more pluralizations and fix them as well. **It is easy now before there comes in more translations.**

**Comment by rappasoft** [comment]
Yeah i'd say let me pull the french changes and your swedish pack and after that's all pushed if you wouldn't mind doing all three that would be great.

**Comment by rappasoft** [comment]
Merged!
