### ISSUE TITLE
Rename the French language ISO code

### ISSUE THREAD

**Issue by Arrakeen** [rappasoft/laravel-5-boilerplate#235]
I really think the French language pack should be renamed to "fr" only.

I've never seen any Laravel or Symfony applications using the "fr-FR" format.
If that were the case then we should use "en-GB" and "en-US" for the English language too.

Right?

**Comment by error500** [comment]
I used fr-FR because it was written like that in the previous version of boilerplate. Effectively, I've seen already en-GB and en-US...

**Comment by vjandrea** [comment]
I would specify fr-FR only once we have another French translation, like fr-CH, fr-BE or fr-CH. At the moment I think that 'fr' is enough, and this would also simplify the use of other localization packages.

**Comment by rappasoft** [comment]
Yeah but I wouldn't want to cut corners if there is a more 'future-proof' way of handling it. Right?

**Comment by Arrakeen** [comment]
Why is the original lang is "en" and not "en-US"?
https://laravel.com/docs/5.2/localization

fr-CH, fr-BE, fr-CA are basically the same.
What are the differences between en-US or en-GB?

**Comment by rappasoft** [comment]
My knowledge of localization was slim to none when I started this. 

Anthony Rappa

**Comment by error500** [comment]
There is language code and country code. Wordpress uses a mix: see here https://make.wordpress.org/polyglots/teams/ 

http://www.gnu.org/software/gettext/manual/html_chapter/gettext_16.html#Usual-Language-Codes

**Comment by vjandrea** [comment]
@Arrakeen you can find a quick list of differences between en-US and en-GB here: https://localize.drupal.org/node/420, same (more or less) goes between the different versions of French.
@rappasoft There's a package that contains many languages for Laravel, as you can notice the distinctions are made only for Portuguese/Brazilian and Chinese. The rest is handled with two letter codes: https://github.com/caouecs/Laravel-lang

**Comment by rappasoft** [comment]
Good enough evidence for me to change it to the 2 letter version.

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/commit/9d00dfc700ecf91bc00bd7878d9ba96d58d845a2
