### ISSUE TITLE
config/locale.php managing localization

### ISSUE THREAD

**Issue by blomdahldaniel** [rappasoft/laravel-5-boilerplate#240]
First and foremost, I understand that you have a lot on your plate as of now @rappasoft. I am therefore willing to create this refactor and feature by my self and then make a PR. But I need to get input from you and others before I start.

## What I want
* Manage locales in one place
* **default locale** - The ability to set what language that should be default/active by default. (ofc shown in the dropdown as well)
* **only selected languages** - In the config you can comment out the languages that you don't need. Then only the active languages will appear in the dropdown. (I guess that everyone doesn't need the ability to chose Swedish for example..)
* **support for only one language** - If only one language is present in the languages array, the locale dropdown in the views should not be visible/usable at all.
* **date format** - just like @error500 has been talking about, we could also add a specific date format together with each locale. It has nothing to do with timezones. Just the format of displaying a date. Since that can be different from language to language.

## Suggested refactoring around `config/locale.php`
If we like the fact of a `config/locale.php` file. This could mean quite a few changes
* All configuration and selecting/deselecting languages is done in  `config/locale.php`
* The **$languages** array in `LocaleMiddleware` will be removed (not needed when languages array is in config file)
* The `lang.blade.php` will be generated through `@foreach(config(locale.languages) as $language )`. This will improve the process of adding a language.
* **Conditional 1** - `navbar.blade.php` the lang dropdown wll only be included (shown) for both frontend/backend
```if ( count(config('locale.languages')) > 1 )```
* **Conditional 2** - `LocaleMiddleware` would also need some sort of conditional for this i assume. Will take a look at that.

#### Suggestion of format for `'languages'` array
Here I think we could put our great brains together and find a nice way to structure the different parameters of the language. 

```
// config/locale.php
return [
    'languages' => [
       'en' => ['carbon_lang' => 'en', 'php_lang' => 'en', 'date_format' => 'm/d/Y'],
        'sv' => ['carbon_lang' => 'sv', 'php_lang' => 'sv', 'date_format' => 'Y-m-d'],
        'fr_FR' => ['carbon_lang' => 'fr', 'php_lang' => 'fr_FR', 'date_format' => 'd/m/Y'],
    ]
];
```
##### My thouhgts of the array structure
**Keep it simple** - `'carbon_lang'` and `'php_lang'` is descriptive and easy to understand. It is important that every person that puts in the new language understands what to codes mean and why they are needed. In the documentation we can refer to the lists that can guide. What I do want to think about though is if `php_lang` should be called `gnu_lang` instead since that is the format of the codes used there.. I am not sure since the purpose in this case is for the php locale setting.

**Comment by petergit67** [comment]
Sounds great Daniel.

**Comment by blomdahldaniel** [comment]
This will btw include and improve #233 and also make some of the stuff in #239 redundant.

**Comment by rappasoft** [comment]
local config file

- Set default locale
- Select which language to support
- Support for only one language - if only one language is selected than no language picker is needed
- Ability to change the way the date is shown for different locales.
— Or would probably be a better idea to have timezone and date format options on the user dashboard, much like wordpress does it.
— This would also eliminate the timezone issue as well.

<img width="1110" alt="screen shot 2016-01-15 at 2 30 16 pm" src="https://cloud.githubusercontent.com/assets/6026504/12363053/89d53944-bb94-11e5-9004-fd7209a3ef23.png">

**Comment by rappasoft** [comment]
Ok I did some work, put it on a feature branch for now: https://github.com/rappasoft/laravel-5-boilerplate/commit/b3a8491fd761c1e5c9fded4b8e1815777a13eed2

- Refactored the languages to a locale file.
- Status to turn language switching on or off.
- Automatically generate language dropdown menu.

Gonna take it one step at a time. (Do timezones and date formats separately)

To default a language, I think you will have to comment out all languages in locale config, and then set the remaining language to the default in the config file.

**Comment by blomdahldaniel** [comment]
Great work! Seems very nice as of right now! :)
Just wanna tell you for the next time, I said I could do it, you don't have to do it all by yourself. But then you also get it just the way you want it, so I see maybe why you did it. ;) 

Don't forger to put in the setLocale() for php and carbon. just like in #233 
And when you do that you will have to deal with the whole php-lang-stuff where you'll need es_ES and that jazz...

**Comment by rappasoft** [comment]
Oh I didn't see that part. You're more than welcome to take over the branch if you have time! I'm kind of tight on time this month.

**Comment by rappasoft** [comment]
I have carbons localization working as of this commit on the branch: https://github.com/rappasoft/laravel-5-boilerplate/commit/8e42d6e84f03f8e2de2d7679874c1869014561bf

**Comment by rappasoft** [comment]
@blomdahldaniel I don't remember what you mean by that last part:

"And when you do that you will have to deal with the whole php-lang-stuff where you'll need es_ES and that jazz..."

This conversation is lengthy in like 2 different issues and a pull request so i'm getting confused.

I set the carbon locale here in the last commit in the above comment.

The languages array might be wrong though, I didn't know which type to set for the key of the array to use for laravel, so I went with the 2 letter code.

**Comment by rappasoft** [comment]
Added php default locale to config, as well as setting it on the app boot method, which will be overridden by session locale if set. https://github.com/rappasoft/laravel-5-boilerplate/commit/edd233fe5cded6ee98630203fb44413f7eadd4b4

Not sure if I love how it's coming along, probably because I can't exactly explain it to myself in my head. I'm just not versed on localization, so i'm not sure if i'm doing it the correct way.

**Comment by rappasoft** [comment]
Anyone have time to give me some pointers on how to go about this the correct way?

**Comment by blomdahldaniel** [comment]
Hi @rappasoft 
Now I have taken the time to look att this, have been a busy week.

First, to explain:
"And when you do that you will have to deal with the whole php-lang-stuff where you'll need es_ES and that jazz..."
All I meant was that you would have to decide what language cody system you would want to use for the naming of the language directories and the key-name for the languages. And it seems like you decided for 2 letter code?

Both the commits on the feature/locale_config branch (8e42d6e) and (edd233f) looks good. 
Seems like pretty thorough documentation of what I can see, I like that. I have been browsing around the project and it seems just fine.

#### Language selector :white_check_mark: 
All of what I can see it works perfectly. The dropdown only shows if the locale.status is true and if there is more than 1 language enabled (not commented out) in the locale array. Just splendid sir!

#### Default language :white_check_mark:
The default language works correctly. Maybe have to state explicitly to remind the developer to set the default language in the `.env` file.

### A reminder:
#### `setLocale()`
the locale_php enables `formatLocalized()`:
```
Carbon\Carbon::now()->formatLocalized('%e %B')
// en: 22 January
// fr: 22 janvier
// sv: 22 Januari
```
(note, `formatLocalized()` is not a Carbon method, it is a php method)

#### `Carbon::setLocale()`
the carbon locale enables `diffForHumans()`
```
$user->updated_at->diffForHumans()
// en:  2 weeks ago
// fr: il y a 2 semaines
// sv: 2 veckor sedan
``` 

## time zone & locale format
Your idea of having it in the dashboard seems nice. But on the other hand, the formats are often bound to the language. Which, in my head, would mean that it could/should be set together inside the `config.locale.php` file. And then some extra nice stuff would be if the user could set a specific format? 

So just the time format, if we want to be so thorough and make that specifically localized, should be set
```
// config.locale.php
'languages' => [
        'en' => ['en', 'en_US', 'm/d/Y'],
        'sv' => ['sv', 'sv_SE', 'Y-m-d'],
        'fr_FR' => ['fr', 'fr_FR', 'd/m/Y'],
]
```

### BUT!
But I actually think that this could wait, I don't know but I dont think that this has that big of a impact..? And then go for dashboard option to change/set default format.

**Comment by rappasoft** [comment]
Do you think this is the correct place to set these defaults? And will it work?

https://github.com/rappasoft/laravel-5-boilerplate/blob/edd233fe5cded6ee98630203fb44413f7eadd4b4/app/Providers/AppServiceProvider.php#L15

**Comment by blomdahldaniel** [comment]
Yes! :+1: 
When I used it before I added it there in the boot() method inside `AppServiceProvider` just as you have done. And it worked for me when I tested it.
So, now the defaults is first set and then LocaleMiddleware overrides the language if active.

**Comment by rappasoft** [comment]
Merged this. Will tackle dates and timezones next.

**Comment by blomdahldaniel** [comment]
Beautiful!
