### ISSUE TITLE
'Call to a member function toArray() on null' in FormBuilder.php:1110

### ISSUE THREAD

**Issue by Kazako** [rappasoft/laravel-5-boilerplate#241]
I get this error message when I try to open login page (before submitting form)

'Call to a member function toArray() on null' in /path/to/vendor/laravelcollective/html/src/FormBuilder.php:1110

I can overcome this problem when I remove the remember me checkbox... 
What is the solution to this? and to keep remember me functionality ?

**Comment by blomdahldaniel** [comment]
This is a fresh install?
 You have runned `composer install` successfully?

**Comment by karlisabe** [comment]
I ran into the same error after 
<pre><code>composer update</code></pre>
It is possible that one of the dependencies changed something and this package no longer can handle it.

**Comment by rappasoft** [comment]
I just ran a composer update and can't replicate the error.

**Comment by Kazako** [comment]
If this helps, I ran composer update --no-dev --prefer-dist

**Comment by rappasoft** [comment]
Still can't replicate. Gonna close for now until someone else has the issue or can provide more details on how to replicate.
