### ISSUE TITLE
Issue with logger

### ISSUE THREAD

**Issue by ChadTaljaardt** [rappasoft/laravel-5-boilerplate#242]
Hello, This update is causing issues with this application 

https://github.com/ARCANEDEV/LogViewer/commit/301134e3658b6f8d5317b35fb3918d95eaf5b3bc

Is there anything i can change to fix this?

**Comment by drparham** [comment]
I updated the logger to ~3.7.0 to get it to resolve the conflict with the support package, however I'm now getting errors in the actual view for viewing the logs.

```
Route [] not defined. (View: /home/vagrant/octo/resources/views/vendor/log-viewer/_partials/menu.blade.php) (View: /home/vagrant/octo/resources/views/vendor/log-viewer/_partials/menu.blade.php)
```

```
Route [] not defined. (View: /home/vagrant/octo/resources/views/vendor/log-viewer/_partials/menu.blade.php)
```

```
InvalidArgumentException in UrlGenerator.php line 307: Route [] not defined.
```

**Comment by rappasoft** [comment]
View the latest commit this was fixed. 

Anthony Rappa

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/commit/78ba39cf527ef1455715bf0e7f6fa337d4612ca9

Specifically the update to the config file for the route issue.
