### ISSUE TITLE
Socialite route update in wiki

### ISSUE THREAD

**Issue by brentkozjak** [rappasoft/laravel-5-boilerplate#243]
Hi,

Since the recent auth route structure change, Socialite redirect URLs in the .env file must follow a new convention.  It should now be http://mysite.com/login/SERVICE and no longer http://mysite.com/auth/login/SERVICE

Can you please update the wiki?  I got hit by this on a fresh boilerplate installation and it works by implementing this change.

Cheers!

**Comment by rappasoft** [comment]
Sorry about that. Fixed.
