### ISSUE TITLE
Lock intem during edit

### ISSUE THREAD

**Issue by petergit67** [rappasoft/laravel-5-boilerplate#244]
Dont know if this is the right place to ask this but as an former Joomla guy i miss the lock function on items so only one person can edit at time.

Is this an existing Laravel function or do i have to do it my self?

**Comment by rappasoft** [comment]
Not an existing laravel function that I know of. Maybe you can make a model property called $editable and if set to false can kick back an error if someone else is working on it when you go to edit?

**Comment by petergit67** [comment]
When user 1 opens an item the timestamp and user id get inputted in locked_at and locked_by for this item.

When user 2 open the item list the edit link on this item is replaced with an padlock width tool tip containing locked_at and locked_by data.

Make any sense?

**Comment by rappasoft** [comment]
It does and would be really easy to implement, the only downfall is having 2 more columns on each of you model tables.

**Comment by vjandrea** [comment]
I was thinking if it could be possible to develop a separate package for this. In particular, instead of modifying every table, maybe it would be easier to have a new "locks" table with a dedicated model, event listeners and a model trait. IMHO would be more "transparent" and easier to add to existing projects: you add the package, publish the assets and add the trait to the models you want to lock.

**Comment by petergit67** [comment]
Sounds great Andrea. Since im new to Laravel this is way out of my league but to have an separate lock function and use it with selected items would be great.

The lock function is not necessary for quick edit item like categories and so on but it is very useful when editing items with a lot of data and you dont want any other user to start messing with the same item until you are done.

Here i also have adapted the Joomla button/function way of edit/create item. I have these buttons in create/edit item page:

Apply
This button saves changes but redirect back to edit/create item since i have form items that are dynamic depending on for ex. type of project item and so on. Also the lock function will not unlock on Apply

Save & Close
This button saves changes and redirect back to list item and unlock the item.

Save & New
This button saves changes and redirect to create item and unlock the item.

Save as copy
This button creates an new item by copying this item. Unlocking this item and redirect to the new item that is locked and ready to edit.

Cancel
This button dont save changes and redirect to list item and unlock the item.
 
Does this make any sense to you Laravel guys?

**Comment by rappasoft** [comment]
It makes sense and that's a little more complicated, but most of it is probably out of the scope of this project. I agree with @vjandrea that it would probably work better as a plugin. Could have a single table for lock with columns such as model, model_id, locked_by, locked_on and if it exists for something someone is trying to edit, just kick back a message. And to ```unlock``` just delete the row.

**Comment by rappasoft** [comment]
Gonna close it for now, but I kind of like the idea so I may do something with it in the near future.

**Comment by vjandrea** [comment]
@rappasoft i am trying to sketch out the trait, it's not my usual piece of cake so i'm studying how to do it in the cleanest way. I'll write again in this thread once i have something that we may try.

**Comment by petergit67** [comment]
@vjandrea, sweet.

**Comment by minedun6** [comment]
Logically it makes complete sense but can someone make out a sort of diagram or graph to showcase the steps that needs to be done in order to implement this kind of functionality.
