### ISSUE TITLE
Token-Based Authentication?

### ISSUE THREAD

**Issue by hopewise** [rappasoft/laravel-5-boilerplate#247]
Hello,

As I started to learn about JWT, is there any plan to support this type of authentication? what would be your instructions to start using Token-Based Authentication within your lovely boilerplate?

**Comment by krishnaguragain** [comment]
implement https://scotch.io/tutorials/token-based-authentication-for-angularjs-and-laravel-apps in this laravel boilerplate

**Comment by hopewise** [comment]
Thanks for the hint..

**Comment by rappasoft** [comment]
I've added a tutorials section to this page: https://github.com/rappasoft/laravel-5-boilerplate/wiki/8.-Suggested-Packages-&-Tutorials
