### ISSUE TITLE
release notes?

### ISSUE THREAD

**Issue by hopewise** [rappasoft/laravel-5-boilerplate#248]
Hi,

Its been awhile sense I have visited your repo, I've noticed that its version 2 now, but where can I read about the release notes? at least, major update notes if any?

**Comment by rappasoft** [comment]
Theres no true release notes, but there is a changelog which is pretty much the same: https://github.com/rappasoft/laravel-5-boilerplate/wiki/6.-Changelog

**Comment by hopewise** [comment]
ah, ok, I've seen it now..
