### ISSUE TITLE
php artisan db:seed   returns Errors, any help?

### ISSUE THREAD

**Issue by chris-fung** [rappasoft/laravel-5-boilerplate#249]
[Illuminate\Database\QueryException]
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'confirmation_code'
  in 'field list' (SQL: insert into `users` (`confirmation_code`, `confirmed`
  , `created_at`, `email`, `name`, `password`, `updated_at`) values (53af5e20
  6eb8743c22e8bdb28ca379b1, 1, 2016-01-21 04:39:46, admin@admin.com, Chris Fe
  ng, y$oqj4z5OiPzjk0Ub//YrpVuDbG7f74wkTxBamiZBwWq6F09wUj8Tya, 2016-01-21 04:
  39:46), (ec5e8245f838801b1fcac6fe27bd25cb, 1, 2016-01-21 04:39:46, user@use
  r.com, Default User, y$QyX5i/3Q/qeDw2XEJcRHAeZeYV91X7leH0q7yzCHBPc1lVL/8pMg
  2, 2016-01-21 04:39:46))

[PDOException]
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'confirmation_code'
  in 'field list'

**Comment by devillom** [comment]
Check users table , has column confirmation_code ?

**Comment by chris-fung** [comment]
I made it pass by dropping the database "homestead" and re-migrate it, thanks any way~

**Comment by rappasoft** [comment]
So resolved?

**Comment by chris-fung** [comment]
Yes, resolved. Thank you.
