### ISSUE TITLE
Problem DB_CONNECTION=pgsql

### ISSUE THREAD

**Issue by devillom** [rappasoft/laravel-5-boilerplate#250]
After migrate tables i have error date/time and fix it remove columns default values in migration files
After db:seed i have new problem 
```
[Illuminate\Database\QueryException]
  SQLSTATE[23503]: Foreign key violation: 7 ERROR:  insert or update on table "permission
  _dependencies" violates foreign key constraint "permission_dependencies_permission_id_f
  oreign"
  DETAIL:  Key (permission_id)=(22) is not present in table "permissions". (SQL: insert i
  nto "permission_dependencies" ("permission_id", "dependency_id", "created_at", "updated
  _at") values (22, 1, 2016-01-21 07:48:15, 2016-01-21 07:48:15))



  [PDOException]
  SQLSTATE[23503]: Foreign key violation: 7 ERROR:  insert or update on table "permission
  _dependencies" violates foreign key constraint "permission_dependencies_permission_id_f
  oreign"
  DETAIL:  Key (permission_id)=(22) is not present in table "permissions".
```
How to fix that?

**Comment by blomdahldaniel** [comment]
Are your tables empty before seeding?

**Comment by devillom** [comment]
Yes, I think this problem laravel core.

**Comment by blomdahldaniel** [comment]
So it has to do with laravel core working with pgsql ?

**Comment by devillom** [comment]
laravel has some bugs pgsql

**Comment by rappasoft** [comment]
I don't think theres any good way for me to deal with the quirks on each connection type :(

**Comment by error500** [comment]
Does it mean that the way is to turn off contraints as it is done in mysql ?
```
BEGIN
SET CONSTRAINTS ALL  DEFERRED 
... run seeders
COMMIT

**Comment by blomdahldaniel** [comment]
I am going to close this issue as of now, it is out of hands for us to solve. Hope you found your way of solving this.

**Comment by error500** [comment]
I just remove the defaults value. It seems to be unecessary to set this as eloquent push the current timestamp while create action on both fields
PR if you wish to make this change
