### ISSUE TITLE
Quick about language packs

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-5-boilerplate#254]
Let me start by saying I appreciate all of you translating this!

Just one thing I've noticed as I merge them in.

Please remember to add your language to all other language menus in the other language packs.

It should be: **Native Language (English Translation)**

If you don't know the how it is written in each language just add it as English and put a //TODO marker next to it so other people know.

I have gone through all language menus and currently added TODO markers so everyone knows what has to be done.

Thanks again!

**Comment by limatheus** [comment]
:+1:  

Understood.

**Comment by limatheus** [comment]
@rappasoft, on the Changelog at tag 2.1.3

The correct credit is for @bsh314, not for me.

Thx

**Comment by bsh314** [comment]
Thanks, that commits was a quick and urgly, sorry for problems. I was distracted with some other projects bugs.
Well done @limatheus !
