### ISSUE TITLE
Dynamic rules/validation

### ISSUE THREAD

**Issue by petergit67** [rappasoft/laravel-5-boilerplate#256]
/**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'projectdate'  => 'required|min:3',
            'machinetype'  => 'required|min:3',
            'customer'  => 'required|min:3',
        ];
    }
Depending on project type i need to validate different inputs.

I need to handle these dynamicly, is there a way for that or do i have to do this in EloquentProjectRepository?

**Comment by blomdahldaniel** [comment]
I think you'll have to be more specific. 
What do you mean by dynamically?

The key `sometimes` allows the following rules take place only if the form contains the input. Is that what you are looking for?
See the docs [laravel.com/docs/5.1/validation#conditionally-adding-rules](https://laravel.com/docs/5.1/validation#conditionally-adding-rules).

**Comment by petergit67** [comment]
Well basically i want to build the validation based on input data. For ex. if input a is 3 then input b needs 'required|min:3' and if input a is 5 input b needs 'required|min:5'.

Hope you see what i mean.

**Comment by blomdahldaniel** [comment]
What you are looking for is `required_if` check out the documentation: [/docs/5.1/validation#rule-required-if](https://laravel.com/docs/5.1/validation#rule-required-if)

But in your example you have a lot of conditionals so it will be a bit tricky but i think you could do something like this. Or you could stack it.. Im not sure how it reacts with so many conditionals but I thinkt
```
'inputA' => 'required|min:3',
'inputB' => 'required_if:inputA,min:3,min:3 | required_if:inputA,min:5,min:5',
```
Or at least the first conditional should be like this:
```
'inputB' => 'required_if:inputA,min:3 | min:3 ',
```

Then about error messages, you can specify exactly what error messages you want. So, inside your validation (Request) file:
```
public function rules()
{
    return [
        'fname' => 'required|min:2',
    ];
}

public function messages()
{
    return [
        'fname.required' => 'The field first name is required.',
        'fname.min' => 'The first name has to be at least 2 characters long.',

    ];
}
```

But then if you want this to be localized into different languages you would not print the messages here, instead use the `trans()` and point to your locale files.

**Comment by petergit67** [comment]
Thank you so much Daniel, this will get me going.

**Comment by petergit67** [comment]
This work
'serial' => 'required_if:machinetype,1', (if the vaule is 1)

but not this
'serial' => 'required_if:machinetype,min:3 | min:3', (if the value is more than 2 digits)

what am i doing wrong?

**Comment by petergit67** [comment]
This worked

'serial' => 'required_with_all:machinetype|min:3',

this is to require min 3 digits in serial if anything is entered in machinetype.

Am i doing this correct?

**Comment by blomdahldaniel** [comment]
**required_with_all**
`'inputD' => 'required_with_all:inputA, inputB, inputC | min:3'`
mekes the field required only if all of the selected fields is present in the form. Then the pipe (`|`) separates the different rules. You could also write it:
`'inputD' => ['required_with_all:inputA, inputB, inputC', 'min:3']`

**required_if**
This should work, but in your comment you might have gotten a spell mistake because it says at least 3 and not 2 as you wrote. This should work so that if `machinetype` has a value with at least 3 characters, the field `serial` will be required. And `serial` always need at least 3 characters independent of `machinetype`
`'serial' => 'required_if:machinetype,min:3 | min:3',`

I am not sure but what happens if you try
`'serial' => 'required_if:machinetype,min:3,min:3',` 
Will the second `min:3` be added if the conditional is true and otherwise no minimum requirement? I dont have the ability to try this out right now. I am not sure.

What do you want to accomplish now? Have this solved any of your problems so far?

**Comment by petergit67** [comment]
This has solved all of my problems :)

I wanted to accomplish this:
If user dont type anything in machinetype input then nothing is required but if user types anything in machinetype input then machinetype will require at least 3 digits an also serial input will require 10 digits.

This is how i accompliched that:
'machinetype' => 'required|min:3',
 'machinetype' => 'required_with_all:machinetype|min:3',
 'serial' => 'required_with_all:machinetype|min:10',

Did i do it right?

**Comment by blomdahldaniel** [comment]
In my head, the second row `'machinetype' => 'required_with_all:machinetype|min:3',`does nothing at all in this case. 
Or was that just a typo and the second row should have been for `'projectdate'`?
First you say that machinetype is required and with minimun of 3 characters.
Then you say that if machinetype is present in the form then it should have min 3 characters.

I would rewrite the first and second row and replace with one row. And then rewrite 3d row for readability:
```
'machinetype' => 'sometimes|required|min:3
'serial' => 'required_with:machinetype|min:10',
```
You can think of **sometimes** as in *sometimes required*.

If you think it is easier to understand you could also write it like this:
```
'serial' => 'required_if:machinetype,NotNull|min:10'
```

**This would result in:**
* If `machinetype` is set (not empty) it will be required and has to have at least 3 characters.
* if `machinetype` is set, then `serial` will be required and it then has to be at least 10 characters long.

**Comment by petergit67** [comment]
No typo i wanted the machinetype input to be visable at all time so sometimes wont do the trick. I want the requirements ti kick in only if you type anything in machinetype input:
<pre><code>'machinetype' => 'required_with_all:machinetype|min:3',
</code></pre>
did the same as
<pre><code>'machinetype' => 'required_if:machinetype,NotNull|min:3',
</code></pre>
but i will use
<pre><code>'machinetype' => 'required_if:machinetype,NotNull|min:3',
</code></pre>
as it is probably more correct code wise.

However 
<pre><code>'serial' => 'required_if:machinetype,NotNull|min:10',
</code></pre>
should require 10 in serial if anything is typed in machinetype but i doesn work, it only require if you type anything i serial

this however does the trick
<pre><code>'serial' => 'required_with_all:machinetype|min:10',
</code></pre>

**Comment by blomdahldaniel** [comment]
Okey then I fully understand. One fix though is that i would remove the `_all` just because of readability.
```
'serial' => 'required_with:machinetype|min:10',
```
Is read "Serial is required together with machinetype".  And that would be just one notch nicer.

**Comment by blomdahldaniel** [comment]
But hey, I do not follow.
Machinetype should always be required?
And it should always be required at least 3 characters?
Then this would make the most sence. 
```
'machinetype' => 'required|min:3',
```
It does the same since you are refering to the same input.

**Comment by petergit67** [comment]
No machinetype should not always be required, only if there is an machine involved in the current service job and they start typing in the machinetype input.

**Comment by petergit67** [comment]
So what is the different between:
<pre><code>'machinetype' => 'required_if:machinetype,NotNull|min:3',
</code></pre>
and
<pre><code>'machinetype' => 'required_with:machinetype|min:3',
</code></pre>

Of course i have messages telling user that they need to input an serialnumber width  10 digits if they type anything in machinetype input.

**Comment by blomdahldaniel** [comment]
Okey then I see what you want with the machinetype. The reason of why I was a little bit confused is because you said that the **sometimes** did not work in your case. What I now realize is that you did not know that sometimes can be used without `required`. I give you a proper way to do this further down.

**First, the difference about the two.**
In the **_if** you check the value of an input. This can refer to the value of the input. So inputA is only required if inputB has the value true for example.

And **required_with** let us know that if the selected inputB is present, (has a value) then inputA also should be required. 

So if you would use required_with and inputB is either true or false, inputA would be required.


The functionality that you are looking for can be done in a very simple and elegant way: 
(Which is why I pointed to the **sometimes** docs at first.)
```
'machinetype' => 'sometimes|min:3',
```

Read it like this: *Sometimes the input has a value, only then apply the following rules* this will give you the same result as the above explained.

**Comment by petergit67** [comment]
for some reason the sometimes didn't gave me that effect earlier but now i does and of course this is much easier code wise.

Now i works but i have to be able to combine many rules like this:

machinetype should only have rule applied if status is 1 or 2
machinetype is allways allowed to be filled in but if you do then min3
if type is 4 or 5 then you have to fill in machinetype

So: 
sometimes|min:3 should always be active in case someone start to fill this field
required_if:type,4,5|min:3 should only be active if status is 1 or 2

How can i combine all this?

**Comment by petergit67** [comment]
How can i get input vars to play with inside rules function or is there som other way of disable all requirements if status is 0 ?

<pre><code>    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules($some_input_vars)
    {
if ($some_input_vars->status != '0'){
        return [
                'type' => 'required',
        ];
    } else {
     return [
                //
        ];
   }
}</code></pre>

**Comment by blomdahldaniel** [comment]
I have not done this by my self but i suggest that you take a look in the laravel documentation. You can find a lot there including some of my recent answers as well. So read the documentation thoroughly.
This is the specified section that handles advanced conditional rules [/docs/5.1/validation#conditionally-adding-rules](https://laravel.com/docs/5.1/validation#conditionally-adding-rules).

**Comment by petergit67** [comment]
This is how i solved it:
<pre><code> public function rules(ProjectRequest $request) {

        if ($request->status != '0') {
            return [
                    'type' => 'required',
                    'projectdate' => 'required|date|after:today',
                    'machinetype' => 'required|min:3',
                    'serial' => 'required_with:machinetype|min:10',
                    'customer' => 'required|min:3',
                    'address1' => 'required_if:type,1,2,3,4,5,6|min:3',
                    'address2' => 'sometimes|min:3',
                    'zip' => 'required_if:type,1,2,3,4,5,6|digits:5',
                    'city' => 'required_if:type,1,2,3,4,5,6|min:3',
                    'contact' => 'required_if:type,1,2,3,4,5,6|min:3',
                    'phone1' => 'required_without:phone2|digits_between:6,12',
                    'phone2' => 'required_without:phone1|digits_between:6,12',
                    'email' => 'required_if:type,1,2,3,4,5,6|email',
            ];
        } else {
            return [
                    'type' => 'required',
                    'projectdate' => 'sometimes|date|after:today',
                    'machinetype' => 'sometimes|min:3',
                    'serial' => 'sometimes|min:10',
                    'customer' => 'sometimes|min:3',
                    'address1' => 'sometimes|min:3',
                    'address2' => 'sometimes|min:3',
                    'zip' => 'sometimes|digits:5',
                    'city' => 'sometimes|min:3',
                    'contact' => 'sometimes|min:3',
                    'phone1' => 'sometimes|digits_between:6,12',
                    'phone2' => 'sometimes|digits_between:6,12',
                    'email' => 'sometimes|email',
            ];
        }
    }</code></pre>

**Comment by rappasoft** [comment]
I'm confused, is this boilerplate related?

**Comment by petergit67** [comment]
Probably not, sorry. 

Since im new to Laravel i have some difficulties to see what is Laravel std and what is BP specific.

**Comment by rappasoft** [comment]
All good I just need to keep track of what I have to do/fix. Feel free to ask questions.
