### ISSUE TITLE
Postgre 9.5 doesn't like $table->timestamp('updated_at')->default('0000-00-00 00:00');

### ISSUE THREAD

**Issue by error500** [rappasoft/laravel-5-boilerplate#257]
While doing migrate on a pgsql database mode, I get this error
```
 [PDOException]
SQLSTATE[22008]: Datetime field overflow: 7 ERREUR:  valeur du champ date/time 
en dehors des limites : ┬½ 0000-00-00 00:00
```
Could we turn updated default value to
```
->default(DB::raw('CURRENT_TIMESTAMP'));
```
Wich doesn't mean exactly the same, i agree.

**Comment by rappasoft** [comment]
Does anyone know if the default ```$table->timestamps()``` method does a current timestamp for both on row create?

**Comment by blomdahldaniel** [comment]
Is this some pgsql errors that has to do with laravel or to this repository?

**Comment by error500** [comment]
I just remove the defaults value. It seems to be unecessary to set this as eloquent push the current timestamp while create action on both fields
PR if you wish to make this change

**Comment by blomdahldaniel** [comment]
@rappasoft How come the default values was added in the first place? Was it something about another DB-driver?

Here is the PR from @error500 #273 where we could go back to the default laravel stuff. But I want to figure out if we are safe to go on and do that right now.

**Comment by error500** [comment]
The other way is to use the same syntax for default value on created_at and updated_at:

    $table->timestamp('created_at')->default(DB::raw('CURRENT_TIMESTAMP'));

This DB::raw('CURRENT_TIMESTAMP') works fine in Mysql and Postgres as well. It's just not doing the same results as the '0000-00-00 00:00:00' value.

**Comment by blomdahldaniel** [comment]
so is `DB::raw('CURRENT_TIMESTAMP')` needed for Postgres? Because why would we use it at all when we have the Laravel function?

**Comment by rappasoft** [comment]
Fixed: https://github.com/rappasoft/laravel-5-boilerplate/commit/ce3f51f0a15d1397ee824a2eaba66fbfbaa3e50e
