### ISSUE TITLE
UserController.php Still uses Registrar

### ISSUE THREAD

**Issue by Teranode** [rappasoft/laravel-5-boilerplate#26]
since your use of AuthenticationContract
the Usercontroller for the backend is still uses Registrar when it doesnt exist.

**Comment by Teranode** [comment]
also when i prss save for the roles this happens:
http://prntscr.com/7a1mna

it savel multiple instances of the permissions

**Comment by rappasoft** [comment]
Fixed that second problem here: https://github.com/rappasoft/laravel-5-boilerplate/issues/21

It will be merged in as a fix when 5.1 is released. Which is taking forever.

**Comment by rappasoft** [comment]
Actually, I think i'm going to merge it right now add just change the minimum stability when it releases.

**Comment by rappasoft** [comment]
Fixed, released, yadda yadda.
