### ISSUE TITLE
Redirect if token miss match

### ISSUE THREAD

**Issue by petergit67** [rappasoft/laravel-5-boilerplate#264]
I added:
<pre><code>/**
         * Redirect if token miss match error
         */
        if($e instanceof TokenMismatchException){
            return redirect('/login');
        }</code></pre>
in App\Exceptions\Handler render function so the user gets redirected to login in stead of getting the error page for TokenMismatchException.

Is this an valid solution?

**Comment by blomdahldaniel** [comment]
You could instead apply the acces middleware to the specified route. The middleware will then take care of the redirecting and all that. Take a look in the [wiki - Access-Control#route_middleware](https://github.com/rappasoft/laravel-5-boilerplate/wiki/2.-Access-Control#route_middleware).

**Comment by blomdahldaniel** [comment]
Sorry for my last post, i had read your question badly so I removed the comment. 

Regarding TokenMismatchException I do not have that much experience. But it seems just about right i guess. Does it work?

**Comment by petergit67** [comment]
Like a charm.

The reason for me doing this is that when a user session has died the error appears and this would have caused my customer to call me. There for i think it is better to be redirected to login. I actually redirect to /logout and then i didnt have to reload the page to get an valid new token.

**Comment by blomdahldaniel** [comment]
Oh, that was a neat trick to redirect to /logout! :)

**Comment by rappasoft** [comment]
Fixed: https://github.com/rappasoft/laravel-5-boilerplate/commit/3f352b1c8a4504f040b6457f48c8292a075d4941
