### ISSUE TITLE
[Question] Social Logins Table

### ISSUE THREAD

**Issue by ninjaparade** [rappasoft/laravel-5-boilerplate#265]
@rappasoft would you have any interest in storing more information in the social logins table?
I build a lot of apps that need signed requests which require the users token once authed.

It would require altering the `social_logins` table and updating the `findOrCreateSocial` method

If you're okay with it I'll send a PR.

**Comment by rappasoft** [comment]
Does this work for any provider?

**Comment by ninjaparade** [comment]
@rappasoft every provider would return a token. 

Socialite uses this in OAuth 2

https://github.com/laravel/socialite/blob/2.0/src/Two/User.php

and for OAuth 1

https://github.com/laravel/socialite/blob/2.0/src/One/User.php

so the token is available and returned for all providers.

**Comment by rappasoft** [comment]
If you think it's something everyone would need and can take advantage of, as well as it won't change anything for the frontend user, then yeah make a PR.

**Comment by blomdahldaniel** [comment]
@ninjaparade are you working on a PR for this? Or should i close this issue for now?

**Comment by ninjaparade** [comment]
@blomdahldaniel I am going to submit one, sorry I am bogged down with a couple projects.
I have a couple with this implemented so it won't be much effort to submit this.

sorry its taken so long :dancer: :dancer:

**Comment by blomdahldaniel** [comment]
No problem dude, we all got things on our plate outside of this project. No worries, I was just wondering so that we can try to keep the issue-list clean. :)

**Comment by rappasoft** [comment]
Merged.

**Comment by ninjaparade** [comment]
:dancer: :dancer: :dancer: :heart:
