### ISSUE TITLE
Laravel 5 Boilerplate for building REST API based application

### ISSUE THREAD

**Issue by nasirkhan** [rappasoft/laravel-5-boilerplate#266]
I am planning to build an application where i want to use Boilerplate as backend and for the fronend i would use either Angular or Vue. Does it support right now?

**Comment by blomdahldaniel** [comment]
This boilerplate of course support the ability to add what ever frontend JS you would like. But it is not shipped with any specific framework. Every separate user have to implement the JS-framework of choice by themselves.

**Comment by R00118189** [comment]
Suggestion:

Would adding dingo/api or similar be the option for this repo? Than we have fronted backend and api boilerplate for web and mobile all together.

**Comment by blomdahldaniel** [comment]
Hm.. No idéa what @rappasoft thinks. I guess that if a lot of people would want it, it might be added depending on what @rappasoft thinks. But in my head it is too specific to add for this boilerplate since it is a pretty specific usage for that?

**Comment by cliffon** [comment]
@nasirkhan have you added dingo api to this , can we have rest API along with this  boilerplate ? thank you. @blomdahldaniel @R00118189 @jonphipps @TheClonker

**Comment by nasirkhan** [comment]
@cliffon no i have not used the dingo package.

**Comment by cliffon** [comment]
@nasirkhan thank you
