### ISSUE TITLE
Pagination Render

### ISSUE THREAD

**Issue by Teranode** [rappasoft/laravel-5-boilerplate#27]
in resources/views/backend/access/index.blade.php

change:
```
    <div class="pull-left">
        {{ $users->total() }} user(s) total
    </div>

    <div class="pull-right">
        {{ $users->render() }}
    </div>
```
to
```
    <div class="pull-left">
        {!! $users->total() !!} user(s) total
    </div>

    <div class="pull-right">
        {!! $users->render() !!}
    </div>

**Comment by Teranode** [comment]
Also im running into the problem where when a user registers,the confirmation email gets sent however the user is already confirmed.

**Comment by Teranode** [comment]
so im guessing this is no longer being maintained.

**Comment by rappasoft** [comment]
It is I fixed the pagination. I haven't had a chance to look into the second comment. If you wanted to look into it and make a pull request I would gladly merge it.

**Comment by Teranode** [comment]
i have been trying to fix it but i dont think its workingas all the tests ive been doing still end up the same. A confirmed account while email gets sent.

**Comment by Teranode** [comment]
Got it to work by creating a separate role with no permissions, then when a user confirms their account they get transferred into to User Role upon activation.
