### ISSUE TITLE
Simple start component

### ISSUE THREAD

**Issue by petergit67** [rappasoft/laravel-5-boilerplate#271]
I think it would be great with an simple component for let say Blogs in the BP as most people like to "convert" an working component for their own purpose, that's the whole idea with an BP right?

Now one has to "convert" some of the user/ auth components and they are much to complicated than an simple blog component.

Sorry if component is the wrong term but i hope you see what i mean.

**Comment by blomdahldaniel** [comment]
The purpose of a boilerplate for most, I believe, is to get a structure to build on. Use the available functionality and in som way also customize. 

What I think is bad for a boilerplate is if you add too specific stuff that big parts of the users dont want or need. Users should not have to remove stuff that they dont need. 

I do not understand exactly what you mean with the blog component. How far would it go? Frontend display with list of all posts then be able to view specific posts? And then backend managing? WYSIWYG? 

I do think that this kind of blog implementation would be too specific for this boilerplate. But it would be cool to try to set up some system so this kind of feature could be pulled in as a plugin. Cause its a good functionality but does not fit perfectly to this boilerplate base.

**Comment by petergit67** [comment]
Well as an newbie i much rather remove than try to figure out how i can use the complex ed user function for my own function.

Complete frontend and backend functionality.

Pull in/attach other functions than BP core as plugins sounds great. This is exactly how i am going to work with the BP. The ability to "separate" my functions in some kind of plugins/packages that wont interfere with the BP core would be super great :)

**Comment by blomdahldaniel** [comment]
You are very much welcome to create such a plugin. Me and Anthony have discussed a similar CMS functionality earlier and he then found it that that kind of logic should not belong in this boilerplate as of now.

Both me and Anthony will keep on working for such a plugin/component solution for the future.
