### ISSUE TITLE
trans_choice more than 0 or 1 in value

### ISSUE THREAD

**Issue by petergit67** [rappasoft/laravel-5-boilerplate#272]
`trans_choice('strings.backend.general.you_have.tasks', 7) `

should give me "You have 7 tasks" but i get "You have :number tasks"

Is there something wrong with this code:
`'tasks' => '{0} You don\'t have tasks|{1} You have 1 task|[2,Inf] You have :number tasks',`

**Comment by blomdahldaniel** [comment]
The problem was that the call from the view did not send the variable `number` to the trans() func

This is correct
```php
// header.blade.php
{{ trans_choice('strings.backend.general.you_have.tasks', 1, ['number' => 1]) }}
```
