### ISSUE TITLE
Model Factories is missing?

### ISSUE THREAD

**Issue by blomdahldaniel** [rappasoft/laravel-5-boilerplate#28]
Hi again @rappasoft 
Now I have finally gotten the time to dig into your repo and I am using it in one of my current projects.

I have a question though.. 
How come the ``database/factories`` is not in your repo? Haven't updated from dev branch to the current 5.1?

If I knew how to make a pull request about this I would have. I have no clue of what you need to do to include it or how I even can import it to my own projekt? Cause I really want it!

**Comment by rappasoft** [comment]
Since I did not start from scratch when 5.1 was released, It was not merged in because I didn't know it existed. The framework works without it I assume so it wasn't part of the upgrade docs. I'll add it in now.
