### ISSUE TITLE
Hardcoded Text in /resources/assets/js/plugins.js

### ISSUE THREAD

**Issue by poseso** [rappasoft/laravel-5-boilerplate#285]
Line 48
  $('body').on('submit', 'form[name=delete_item]', function(e){
        e.preventDefault();
        var form = this;

        swal({
            title: "Warning",
            text: "Are you sure you want to delete this item?",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes, delete it!",
            closeOnConfirm: true
        }, function(confirmed) {
            if (confirmed)
                form.submit();
        });
    });

Is there a way to pass translation to swal ?

When you delete a user in /admin/access/users a swal pop outs only in english no matter if you are in spanish, but when you are in /admin/access/users/deleted and restore the deleted user you get the swal translated

**Comment by poseso** [comment]
also, is it possible to translate /admin/access/roles/permissions? permissions , roles and groups?

**Comment by blomdahldaniel** [comment]
@poseso what file is it that you refer to in the first comment? (Line 48).

permissions , roles and groups in the url is quite easy to change. But there is no good way of changing the url depending on languages by yourself. 

@rappasoft has done a good setting route names. Therefore you can change the route urls as mutch as you would like. And if your goal is to change the urls "hard coded" to spanish you can do the following:
* Go through the routes and change those wo also has a `->name()` to it` they are quite safe.
* Go through `sidebar.blade.php` and look to change the `Aktive::` classes for when a link in the sidebar should stay active. I know that  the latest version, 3.0 of [laravel-active](https://www.hieule.info/tag/laravel-active/) it is possible to point to route names. Which we should look to upgrade as well.

And take it step by step, dont do all the routes without checking out if it all works. So step by step.

**Comment by poseso** [comment]
i refer to the file /resources/assets/js/plugins.js line 48

**Comment by blomdahldaniel** [comment]
Great, thank you! I will start to look at a fix for this soon.

**Comment by vpratfr** [comment]
There are a few packages out there to provide multilang route names. Maybe that could be worth having a look at.

**Comment by blomdahldaniel** [comment]
This is fixed through 1ce0eb8.
Thanks for reporting it in

**Comment by rappasoft** [comment]
I believe I already did :)

**Comment by blomdahldaniel** [comment]
You are correct! I linked to the wrong commit.

This commit: 95af225a9fe7940f5a5d54b67025d50d9b993ac5 was added to the development branch. It is this commit that solves this issue. My bad

**Comment by rappasoft** [comment]
Merged.
