### ISSUE TITLE
Eloquent/DB Query get only certain roles in a query

### ISSUE THREAD

**Issue by jonathan-bird** [rappasoft/laravel-5-boilerplate#286]
I've got a query to get all users by search to be used for autocomplete and works great however it gets all users, and not just certain roles.

User::select('id', DB::raw('CONCAT(first_name, " ", last_name) as text'))
                            ->where('last_name', 'LIKE', '%'.$contributor.'%')
                            ->orWhere('first_name', 'LIKE', '%'.$contributor.'%')
                            ->simplePaginate(20);

Any ideas on how to write the query to allow certain roles such as Administrator ?

**Comment by rappasoft** [comment]
I'd say make your own method , or use whereHas()

```
User::select('id', DB::raw('CONCAT(first_name, " ", last_name) as text'))
->whereHas('role', function($query) {
    $query->where('name', 'like', 'Administrator');
})
->where('last_name', 'LIKE', '%'.$contributor.'%')
->orWhere('first_name', 'LIKE', '%'.$contributor.'%')
->simplePaginate(20);
```

Untested, but you get the idea.

**Comment by jonathan-bird** [comment]
That doesn't work because there's no foreign key in the users table - I'm still learning but I'm pretty sure to use that statement, there has to be a foreign key link.

What I did was actually join them. So because assigned roles had 'user_id' and 'roles_id' and I needed to check the roles table and assigned roles table to just check if Contributor was linked to that user id, this is what I came up with:

`User::select('users.id', DB::raw('CONCAT(first_name, " ", last_name) as text'))
                            ->leftJoin('assigned_roles', function($join) {
                                $join->on('users.id', '=', 'assigned_roles.user_id');
                            })
                            ->leftJoin('roles', function ($join) {
                                $join->on('assigned_roles.role_id', '=', 'roles.id');
                            })
                            ->where('roles.name', 'Contributor')
                            ->where(function ($query) {
                                $contributor = Request::get('term');
                                $query->where('last_name', 'LIKE', '%'.$contributor.'%');
                                $query->orWhere('first_name', 'LIKE', '%'.$contributor.'%');
                            })
                            ->simplePaginate(20);`

**Comment by jonathan-bird** [comment]
I'll clean it up and see if I can move it out into some sort of method (not sure what yet) or Model method that I can just call "roles" within Users model. I'll probably figure it out but any suggestions?

**Comment by blomdahldaniel** [comment]
Any progress on this one @jonathan-bird ?

**Comment by jonathan-bird** [comment]
I did indeed @blomdahldaniel 

This was my end method in the User Model:

`public function contributorsByName($contributor)
    {
        // Split the terms into an array
        $pieces      = explode(" ", $contributor);
        $results     = [];

        // Loop over each term and add to an array
        foreach ($pieces as $term) {
            $query = $this->select('users.id', DB::raw('CONCAT(first_name, " ", last_name) as text'))
                        ->take(20)
                        ->leftJoin('assigned_roles', function($join) {
                            $join->on('users.id', '=', 'assigned_roles.user_id');
                        })
                        ->leftJoin('roles', function ($join) {
                            $join->on('assigned_roles.role_id', '=', 'roles.id');
                        })
                        ->where('roles.name', 'Contributor')
                        ->where(function ($query) use ($term) {
                            $query->where('last_name', 'LIKE', '%'.$term.'%');
                            $query->orWhere('first_name', 'LIKE', '%'.$term.'%');
                        })
                        ->get();

            // Add to array
            $results += $query->all();
        }

        return $results;
    }`

Took a bit of working but it takes 20, checks the role allowed is the role of the user (e.g. contributor in this case), and then checks against first name and last name and pushes into an array).

**Comment by blomdahldaniel** [comment]
Glad to see that you solved it. 

You might want to look at [Adam Wathans blog article about refactoring] (http://adamwathan.me/2015/01/01/refactoring-loops-and-conditionals/). You could use a functional approach instead of using `foreach()` but that migt be a matter of taste. :smiley: 

I assume I can close this issue as of now.

**Comment by amandasaffer** [comment]
Hi,
I'm pretty new to Laravel and working with MySQL as a whole, so maybe someone in this thread can help me. I have a pretty simple search method on the back-end for admins to use to find certain members. It looks like this at the moment:

```
$input = $request->input('q');
$results = User::where(
      'email', 'LIKE', '%'.$input.'%'
   )->orWhere(
      'name', 'LIKE', '%'.$input.'%'
   )->orWhere(
      'sub_plan', 'LIKE', '%'.$input.'%'
   )->get();

return view('backend.search')->with([
   'results' => $results,
   'input' => $input
]);
```

I would like to simply add to this code an ability to type in "Administrator" and get a list of users with the role "Administrator". I tried editing `$results` to look like this and variations on this, but I'm not sure what I'm doing wrong:

```
$results = User::select()->leftJoin('assigned_roles', function($join) {
        $join->on('users.id', '=', 'assigned_roles.user_id');
   })->leftJoin('roles', function ($join) {
        $join->on('assigned_roles.role_name', '=', 'roles.name');
   })->where('roles.name', '%'.$input.'%')
   ->where(function ($results) use ($input) {
        $results->where('email', 'LIKE', '%'.$input.'%');
        $results->orWhere('name', 'LIKE', '%'.$input.'%');
        $results->orWhere('sub_plan', 'LIKE', '%'.$input.'%');
   })->get();
```

I get an error:
```
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'name' in where clause is ambiguous
```

I don't think I'm going about this the right way. Any help from you that know more than me? Thanks. :smile:

**Comment by rappasoft** [comment]
Your error is stemming from you trying to select 2 columns with the same name from multiple tables and mysql doesn't know what to do. You should explicitly state table1.name, table2.name.
