### ISSUE TITLE
Make application name configurable

### ISSUE THREAD

**Issue by steenrabol** [rappasoft/laravel-5-boilerplate#288]
Hi

Just a small thing: It would be nice if the name off the application could be set in .env

e.g. in .env APP_NAME="My New Awesome App"

that could be done by changing line 25 in /config/app.php to 'name' => env('APP_NAME', 'Laravel 5 Bootstrap');

I know it is easy to do, but it makes it easier to update the boilerplate :)

**Comment by rappasoft** [comment]
That implies the name of your application would change on each of your environments? Why would it be different on development and production?

**Comment by steenrabol** [comment]
No, that was not my point :)

I have to create the .env file, so I was just saying that it would be easier to have the application name in there as well

**Comment by rappasoft** [comment]
Any string can be an environment variable. Not sure if it's useful in this case, unless you need to append 'Testing' or something to the name so everyone knows in that case. Luckily its easy to do this, you already wrote it above. :)

**Comment by blomdahldaniel** [comment]
Yes this is a easy fix for you in your case @steenrabol but I agree with Anthonys point where, for this project, only environment variables should be set in the `.env` file.
