### ISSUE TITLE
502 on return view('backend.dashboard')

### ISSUE THREAD

**Issue by bsh314** [rappasoft/laravel-5-boilerplate#291]
Recently I was working in some blog functionality for this boilerplate and after making some models/seedes/migrations, I started with breadcrumbs/controllers/routes. 
And there was a problem: 
After adding breadcrumbs and wtiting a resource controller with empty functions, I tried to return view('backend.dashboard'), but it throws me nginx 502 page. 
If I put some "dd" stuff before return the view, it works perfectly, as well as returning any value. 
Error logs of nginx/php-fpm/laravel are cristal clear, none of other views works for this controller, but for other controllers they works.

I have struggles with this 502 and don't know how to solve it. Anyone can help me?

**Comment by petergit67** [comment]
When i got `502 Bad Gateway nginx/1.9.` i had an incorrect use path in model.

Hope it can help you figure out this.

**Comment by bsh314** [comment]
i've migrated all the stuff to new copy of boilerplate & now it's work.

**Comment by blomdahldaniel** [comment]
Glad to hear that you solved it.
