### ISSUE TITLE
Need help with flash messages

### ISSUE THREAD

**Issue by Roemerb** [rappasoft/laravel-5-boilerplate#292]
Hi,

I'm adding noCaptcha to several pages and I want to write a custom error message for when the user didn't complete it. I can't find the code where the messages in alerts.php are loaded. Could someone explain?

**Comment by petergit67** [comment]
I use this for messages but this is maybe not what you are looking for?

`return redirect()->route('admin.customer.project.index')->withFlashInfo(trans('projects.backend.alerts.no_item_selected'))`

**Comment by blomdahldaniel** [comment]
Yes I also flash stuff like that. Sometimes i even include html:
```php
return redirect()->back()->withFlashDanger('<h2>Danger!</h2>Something went wrong!');
```

**Comment by Roemerb** [comment]
@petergit67 @blomdahldaniel Thanks guys. This would work in some cases. Thing is though, I also added it to the register page for users. This uses `RegisterRequest` and I added the noCaptcha to the rules array. Do any of you know how I can add a custom error message for these rules? 

Sorry I'm one of those annoying people who doesn't know everything about Laravel ;)

**Comment by blomdahldaniel** [comment]
No worries, we all have been there.

YEs

**Comment by blomdahldaniel** [comment]
No worries we all have been there.

Okey then I understand what you want.
Take a look in the [Laravel docs about #custom-error-messages](https://laravel.com/docs/5.2/validation#custom-error-messages)

So inside the `RegisterRequest` you can change it like this:
```php
public function rules()
	{
		return [
			'name' 		=> 'required|max:255',
			'email' 	=> 'required|email|max:255|unique:users',
			'password'  => 'required|confirmed|min:6',
			'my_field'  => 'required',
		];
	}

public function messages()
	{
		return [
			'my_field.required'  => 'This will be custom message for the rule required',
		];
	}
``` 

So in the messages function you add `name_of_field.rule` and then your string.
Do you understand what I mean?

**Comment by blomdahldaniel** [comment]
You can use this to override the standard validation strings.

**Comment by Roemerb** [comment]
@blomdahldaniel Awesome! Thank you :) 

PS: I checked out your website listed on your profile and I believe `I want to dig down and is always hungry to learn more.` on the about page should be `I want to dig down and am always hungry to learn more.`

**Comment by blomdahldaniel** [comment]
Dude! Thank you man!
