### ISSUE TITLE
Structure question

### ISSUE THREAD

**Issue by digitalit** [rappasoft/laravel-5-boilerplate#293]
Controllers, Models, Requests are placed in specific folders under Access but Repositories are not.
Is there an reason for that?

**Comment by blomdahldaniel** [comment]
Just as Controllers, Models and Requests are directories of its own, Repositories also is such a category that it should have its own parent directory. So all the repositories should therefore be gathered within the Repositories directory. Do you understand what I mean?

**Comment by petergit67** [comment]
Yes but there are sub directories under Controllers, Models, Requests and not under Repositories.

That was what i didn't understand.

**Comment by blomdahldaniel** [comment]
Hm.. Do you have the latest version of the boilerplate?
Because in this repo as of now the directory [Repositories](https://github.com/rappasoft/laravel-5-boilerplate/tree/master/app/Repositories) has sub directories. Backend and Frontend, and for Backend:
```
/Repositories
    /Backend
        /Permission 
        /Role
        /User
```

**Comment by petergit67** [comment]
Yes but shouldn't it be:
<pre>
`/Repositories
    /Backend
        /Access
            /Permission 
            /Role
            /User`</pre>

As it is with Controllers, Models, Requests ?

**Comment by blomdahldaniel** [comment]
Aaah now i see your point. Yes, sure at least in my head that would make sense for consistency. What does @rappasoft think?

**Comment by rappasoft** [comment]
Fine by me if someone wants to update all the namespaces.

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/commit/fe9a5adc0df0c53770b6a0bf2aafd11ce8d99ba1
