### ISSUE TITLE
Firbug console error: ReferenceError: PhpDebugBar is not defined

### ISSUE THREAD

**Issue by LarryEitel** [rappasoft/laravel-5-boilerplate#296]
[screen shot](https://farm2.staticflickr.com/1693/24708854349_bf27e5efdd.jpg)

This is occurring on DigitalOcean deploy whereas my local Vagrant VM is running fine.

npm installed fine.
gulp ran fine except for:
```
[18:29:06] gulp-notify: [Error in notifier] Error in plugin 'gulp-notify'
Message:
    notify-send must be installed on the system.
```

**Comment by rappasoft** [comment]
Seems like a package error, should go away on production since it isn't enabled when not testing.

That gulp warning is something I get too but doesn't seem to effect anything, I haven't researched a solution though since it doesn't seem to be harming anything.

**Comment by LarryEitel** [comment]
Thank you for the input. :) 

I will leave this issue open unless a moderator decides otherwise since it is a bit disconcerting.
