### ISSUE TITLE
Erro on migrate

### ISSUE THREAD

**Issue by netopvh** [rappasoft/laravel-5-boilerplate#299]
It appeared an error message when I made the migration.

[Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1293 Incorrect table definition; there can be only
  one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause (SQL: cr
  eate table `users` (`id` int unsigned not null auto_increment primary key, `name` v
  archar(255) not null, `email` varchar(255) not null, `password` varchar(60) null, `
  confirmation_code` varchar(255) not null, `confirmed` tinyint(1) not null default '
  0', `remember_token` varchar(100) null, `created_at` timestamp not null default CUR
  RENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP, `deleted
  _at` timestamp null) default character set utf8 collate utf8_unicode_ci)

  [PDOException]
  SQLSTATE[HY000]: General error: 1293 Incorrect table definition; there can be only
  one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

Can someone help me?

**Comment by natchiketa** [comment]
Here it is again for easier readability:

```sql
CREATE TABLE users (
  id int unsigned NOT NULL auto_increment PRIMARY KEY,
  name varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  password varchar(60) NULL,
  confirmation_code varchar(255) NOT NULL,
  confirmed tinyint(1) NOT NULL DEFAULT '0',
  remember_token varchar(100) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL
) DEFAULT character SET utf8 COLLATE utf8_unicode_ci
```

This will work with MySQL 5.6.5 and later. See the release notes for that version in the [Data Type Notes](http://dev.mysql.com/doc/relnotes/mysql/5.6/en/news-5-6-5.html#mysqld-5-6-5-data-types) section.

**Comment by rappasoft** [comment]
See this patch: https://github.com/rappasoft/laravel-5-boilerplate/commit/2ba70eee2a2894b1d4c217ac1cfb7c2f899311d2
