### ISSUE TITLE
Debugg not working

### ISSUE THREAD

**Issue by Krubb** [rappasoft/laravel-5-boilerplate#3]
Hi!
I was verry glad to see your sweet repo with this stuff. Really like it!

But, i seem to have some trouble with my debugging.
I have done 3 resets of my project to get my head around this but i get the same error.

When i have an error in my code and a error message/debugg msg should show, I instead get the source code of the jQuery lib. The url looks like this: '/_debugbar/assets/javascript?1423122680'
but in my browser i only show the minified jquery.js file. At the bottom i can see what I believe is the source code for the debugger.

Like i said I have tried this 3 times and I now need your help to figure this out, or is this a bug in the setup right now?

**Comment by rappasoft** [comment]
Hmm, the debug bar seems to be working fine for me. What code is the error in?

**Comment by Krubb** [comment]
Hm.. What should I expect with an error?

I placed my error inside on the FrontendController, i just tried to write `return 'test string'` without an closing semi-colon.

I am on Ubuntu 12.0.4 btw and I have made sure to chmod the directories as well..

**Comment by rappasoft** [comment]
Maybe read the debugbar docs to see if the way you're using it is the correct way?

https://github.com/barryvdh/laravel-debugbar

**Comment by Krubb** [comment]
I did yet another install but didnt mess with the config/app this time. Now it works, so it must be an error somewhere, i will take a look in their docs. Thank you for your help, and like i said, love the repo!

**Comment by rappasoft** [comment]
No problem glad you like it!

**Comment by Krubb** [comment]
Bah @rappasoft 
I actually never solved this issue earlier. I started looking in my laravel log files instead.
But now i have a new projekt and I would really like this to start working.

Ok, so 3 times i have done clean installations from your repo and fallowed your docs. 
As soon as i hav run my gulp file and checked out so that the site works. I edit a line in FrontendController index method. I add $foo = $bar; And since $bar is not declared i should get an error.

And every time, just like last time, i get sent to this url myapp.dev/_debugbar/assets/stylesheets?1426689627 (the same result on a "real" (not wamp) server. The only thing i see is the raw js of all of my js files. First font-awesome and then it continues. 

I run OSX Yosemite. 
Is it something with permission to acces the debuggbar logg files?
This is reallt frustrating, have been searching my way in these docs:
https://github.com/barryvdh/laravel-debugbar

but no success.
Hope you can help me fix this so that i can enjoy your sweet reop.

**Comment by Krubb** [comment]
So my problem is that not even the "old" laravel error report is showing, that would be good enough. Do you know how i can disable the not working plain error msgs?
I made a pure plain laravel installation now, pulled in debuggbar and then i still got my laravel-error messages. 
I love your setup of the project with the frontend and backend structure. Would love to get it to work with your stuff.  Have a clue?

**Comment by rappasoft** [comment]
Go to the laravel repo and get a fresh copy of the app/Exceptions/Handler.php file and replace the one that's in there. See if your error reporting starts working, if so there's something wrong with my global exception handler.

**Comment by Krubb** [comment]
Thanks for the quick answer, i will try that tomorow, (Im from Sweden so night time here.)

(Off topic but earlier this day when i started my own bare laravel repo, i really understood how nice your repo is. I figured it would take some time to try to reedo it. It is great!)

**Comment by rappasoft** [comment]
Haha good to hear. I think laravel 5.1 is coming out soon and depending on how different is I may start this over, but I hope I don't have to. I also purchased laravel-boilerplate.com in hope's of making it a better more well known project, and get people to help me out with it.

**Comment by Krubb** [comment]
NICE! I did copy paste in the fresh copy of app/Exceptions/Handler.php and now i see the normal error messages again, sweet!! :dancer: 

Oh, that sounds like a really fun project! I really wish that i knew more about programing and laravel, that would have been a fun project to be a little part of! Looking forward to your upcoming work. How is it going with the socialite things? I look to use that in this project Im on right now. Is it working?
