### ISSUE TITLE
Description of Sort and System

### ISSUE THREAD

**Issue by KongrooDev** [rappasoft/laravel-5-boilerplate#303]
Can we add a description of sort and system for permissions and roles to the documentation?

**Comment by rappasoft** [comment]
Sure, for now sort is the order in which they are displayed in the backend.

System serves almost no purpose, other than that if it is flagged to true, you can't accidentally delete that permission.

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/wiki/2.-Access-Control#other
