### ISSUE TITLE
Ignore .vagrant

### ISSUE THREAD

**Issue by vpratfr** [rappasoft/laravel-5-boilerplate#304]
.vagrant folder should be in .gitignore too

3 issues I have submitted, and I still did not tell you that I like your project. I'll give it a go on a project of mine and may submit a few pull requests once I get used to it.

Thanks a lot for creating that. This is more or less what I was looking for. OctoberCMS and other such initiatives are too far away from the raw Laravel approach. Your project is a great starting point and keeps everything organized the Laravel way.

**Comment by rappasoft** [comment]
Is it in the root? Am I ignoring ```/.vagrant```?

**Comment by vpratfr** [comment]
If you run homestead globally no worries. However I prefer to have 1 homestead per project. When I start the VM via vagrant up, I get that folder at the root of the project. That should be ignored.

**Comment by rappasoft** [comment]
Did this manually.
