### ISSUE TITLE
Breach in MVC model

### ISSUE THREAD

**Issue by vpratfr** [rappasoft/laravel-5-boilerplate#305]
You are mixing the M and V in some classes.

For example in `Models\Access\Permission\Traits\Attribute\PermissionAttribute` you have methods which return an HTML link along with additional markup (with font awesome icons).

I guess the cleanest way to do that would be to have a few helper functions or a facade which would replicate the functions.

But that code for sure does not belong to the Model namespace.

**Comment by blomdahldaniel** [comment]
This is a interesting point. I am not so strict in my ways but I guess that this is a pretty good idéa.

**Comment by rappasoft** [comment]
Suggested solution?

**Comment by vpratfr** [comment]
Move that into partial views to be included into the templates which are currently using the functions.

**Comment by blomdahldaniel** [comment]
If you would like to mak a PR for this @vpratfr then you are very welcome. Othervice I guess we add this to the to-do-list for version 3. I will close this issue now. Reopen if you want to discuss this further.
