### ISSUE TITLE
DB Choice

### ISSUE THREAD

**Issue by petergit67** [rappasoft/laravel-5-boilerplate#308]
Homestead now supports MariaDB and so does my hosting.

What is your opinion on MariaDB vs MySQL?

Will the BP work with MariaDB and do you recommend  switching to MariaDB?

**Comment by jpgnz** [comment]
This question isn't really in the scope of a laravel boilerplate. MariaDB is a drop in replacement for MySQL, whether or not you should use it depends on your individual application use cases.

https://mariadb.com/kb/en/mariadb/mariadb-vs-mysql-features/

Check here for differences.

**Comment by blomdahldaniel** [comment]
I have no experience with MariaDB.

And I will agree with @jpgnz and say that this question would be more suitable in the Laravel forums or maybe some place else. I will be a bit boring and close this one down. We have gotten a lot of issues lately and need to keep the issues clean and more strict around questions related to this project.
