### ISSUE TITLE
Email help

### ISSUE THREAD

**Issue by srmishra** [rappasoft/laravel-5-boilerplate#309]
I don't get any reset password mail after submitting the forgot password form(using gmail account).
Please help.

Thanks
Sam

**Comment by rappasoft** [comment]
Do you get an email from any other method that sends an email?

**Comment by srmishra** [comment]
o.o. that was fast !!
no, no mails from any page

**Comment by srmishra** [comment]
but i should say...this is the best boilerplate app..exactly what i was expecting
please help me with mail issue

**Comment by rappasoft** [comment]
Sounds like a configuration problem. I would create a script to send a mail in vanilla PHP on the same development environment to see if it has something to do with anything else.

Make sure you have the right mail driver set in the .env file.
By default it's php mail()
Make sure all the configurations in mail.php config file are set.
Make a script to send an email not in the laravel application.

**Comment by srmishra** [comment]
here i am putting in .env file
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=xyz@gmail.com
MAIL_PASSWORD=password
MAIL_FROM=xyz@gmail.com
MAIL_NAME=My Name

**Comment by srmishra** [comment]
sorry, it's all working now. Thanks for your response. :)
