### ISSUE TITLE
Question, master administrator

### ISSUE THREAD

**Issue by AlehBY** [rappasoft/laravel-5-boilerplate#310]
How to separate master administrator from the table user...???
Pls... Example...

**Comment by blomdahldaniel** [comment]
Hm.. You will have to be more descriptive, I do not understand what you want. What do you mean by master administrator? Are you looking for `access()->user()->hasRole('Administrator')` ? This will return true if the active, loged in user has the role **Administrator**.

**Comment by AlehBY** [comment]
Sorry, but I do not understand yet:
User can delete or create Administrator???
Video example: https://youtu.be/NVvMfBLu-5s
