### ISSUE TITLE
Error after composer update??

### ISSUE THREAD

**Issue by mikimaine** [rappasoft/laravel-5-boilerplate#311]
hey after update composer this happened

PHP Fatal error:  Declaration of Arcanedev\LogViewer\Providers\RouteServiceProvider::map() must be compatible with Arcanedev\Support\Providers\RouteServiceProvider::map(Illuminate\Contracts\Routing\Registrar $router) in C:\wamp\www\ecommerce\vendor\arcanedev\log-viewer\src\Providers\RouteServiceProvider.php on line 15

the application is not working any more! 
do you have any fix?

**Comment by rappasoft** [comment]
You don't have the latest version of of that plugin. Use ```"arcanedev/log-viewer": "~3.0"```

**Comment by mikimaine** [comment]
never mind i just solved it buy statically changing the version of "arcanedev/log-viewer" in composer to 3.7.0 and runing the ommand composer update --no-scripts

**Comment by mikimaine** [comment]
And also this suddenly happen when loading this page  http://localhost:8888/admin/log-viewer

Route [] not defined. (View: PATH_TO_PROJECT\resources\views\vendor\log-viewer\_partials\menu.blade.php) (View: PATH_TO_PROJECT\resources\views\vendor\log-viewer\_partials\menu.blade.php)

**Comment by rappasoft** [comment]
It's the same issue: https://github.com/ARCANEDEV/LogViewer/issues/31

**Comment by mikimaine** [comment]
Thanks that solved the problem!

**Comment by rappasoft** [comment]
No problem.
