### ISSUE TITLE
Binding Javascript Vars to *.layouts.master views results in render issue

### ISSUE THREAD

**Issue by PunchRockgroin** [rappasoft/laravel-5-boilerplate#312]
When binding Javascript vars to a view layout master, the plugin prepends the script tag to the view. 

https://github.com/laracasts/PHP-Vars-To-Js-Transformer/issues/59

https://github.com/rappasoft/laravel-5-boilerplate/blob/master/config/javascript.php#L16
Here, the js vars are added to 'frontend.layouts.master' which doesn't initially trip you up until you try to do the same to the backend by adding 'backend.layouts.master', which results in:

![2016-02-26 12_02_04-hopper _ visit management _ edit](https://cloud.githubusercontent.com/assets/1855836/13362472/0504f5e2-dc82-11e5-8921-de80ca2010f4.jpg)

This is because the script tag gets added before the doctype.

I'm unsure if there's a better way, but solved for myself by adding an empty view partial 'head' and setting the javascript config to add the variable to this empty view.

**Comment by primeinc** [comment]
Have you tried this already?
https://github.com/rappasoft/laravel-5-boilerplate/wiki/4.-PHP-to-Javascript-Transformer

**Comment by PunchRockgroin** [comment]
I viewed that, and testing it locally using a super master layout worked using a blank super.blade.php and keeping the doctype in the front and backend master layouts e.g:
```
@extends('super')
<!DOCTYPE html>
@section('supercontent')
```

However, my usage didn't need a "frontend" other than a login, all activity happens in the "backend". So my config/javascript.php code looked like:

`'bind_js_vars_to_this_view' => 'backend.layouts.master',`

**Comment by blomdahldaniel** [comment]
Glad that this was solved, it was kind of a weird bug, nothing that I could replicate. So I will close this for now since you seem to have solved it. :)
