### ISSUE TITLE
[Question] Mail Gun transactional emails

### ISSUE THREAD

**Issue by ninjaparade** [rappasoft/laravel-5-boilerplate#316]
Hey everyone,

Would there be any interest in adding (integrating) Mailgun's transactional email templates into the boilerplate?

https://github.com/mailgun/transactional-email-templates

If there is interest, I can PR this feature. If not totally cool :dancer: :dancer:

**Comment by blomdahldaniel** [comment]
Hm.. I am not so sure if this should be included in here. I think that this should be up to the user to style the emails. 

BUT, this was a great suggestion so I definitely think that this should be added to the wiki [8. Suggested Packages & Tutorials] (https://github.com/rappasoft/laravel-5-boilerplate/wiki/8.-Suggested-Packages-&-Tutorials)

Great stuff!

**Comment by ninjaparade** [comment]
:dancer: sounds good. close if you want :dancers: :dash:

**Comment by blomdahldaniel** [comment]
Nice :smile: 
I added it to the [wiki](https://github.com/rappasoft/laravel-5-boilerplate/wiki/8.-Suggested-Packages-&-Tutorials).
Thanks!
