### ISSUE TITLE
Update password not encrypted

### ISSUE THREAD

**Issue by lspedalieri** [rappasoft/laravel-5-boilerplate#317]
Hi,
When i change a user password from "/admin/access/user/{id}/password/change", the updated password isn't encrypted

the method updatePassword in UserController doesn't provide the bcrypt encryption

I just modified the method in 

 

> 

    public function updatePassword($id, UpdateUserPasswordRequest $request)
    {
        $results = $request->all();
        $this->users->updatePassword($id, ['password' => bcrypt($results['password'])]);
        return redirect()->route('admin.access.users.index')->withFlashSuccess(trans('alerts.backend.users.updated_password'));
    }

And now it works.
I'm not sure if Laravel should encrypt the password automatically.

**Comment by rappasoft** [comment]
You are correct, fixed: https://github.com/rappasoft/laravel-5-boilerplate/commit/3db2d2119fe8ceab6e074f85fee3a795c76a1011
