### ISSUE TITLE
Security Issue in all installs since v2.

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-5-boilerplate#318]
There was a bug where changing the users password from the backend wasn't being hashed.

Reason being I reused code from v1, where the passwords were hashed on model. This is no longer the case, and I forgot to bcrypt. Here's a fix: https://github.com/rappasoft/laravel-5-boilerplate/commit/3db2d2119fe8ceab6e074f85fee3a795c76a1011

I would just double check your users tables for plaintext passwords.

Sorry about that.

**Will keep this here for a little while until everyone sees it.**

**Comment by ninjaparade** [comment]
@rappasoft thanks for this, appreciate your quick fix :dancer:
