### ISSUE TITLE
Any idea how to seed a Postgres DB?

### ISSUE THREAD

**Issue by num3thod** [rappasoft/laravel-5-boilerplate#32]
I'm getting the following error:
QLSTATE[42704]: Undefined object: 7 ERROR:  unrecognized configuration parameter "foreign_key_checks" (SQL: SET FOREIGN_KEY_CHECKS=0;)

Tried various things found here 
https://gist.github.com/isimmons/8202227
here
http://espadav8.co.uk/2015/03/04/laravel-database-seeding-with-postgresql/
and here
http://www.estelnetcomputing.com/index.php?/archives/7-Postgresql-equivalent-of-SET-FOREIGN_KEY_CHECKS-in-mysql.html

Still struggling. Any tips would be greatly appreciated.

**Comment by num3thod** [comment]
Fixed, but keeping open for a little visibility and hopefully, feedback.

1- comment out ```DB::statement('SET FOREIGN_KEY_CHECKS=0;');``` and ```DB::statement('SET FOREIGN_KEY_CHECKS=1;');```

2- follow this guide for the truncate statements http://espadav8.co.uk/2015/03/04/laravel-database-seeding-with-postgresql/

**Comment by rappasoft** [comment]
Maybe I can do a check for the default driver and enable/disable those lines.

**Comment by num3thod** [comment]
Yeah that could work. But I am also seeing some other odd behaviour, even after a successful migration and seeding. For example, the seeded users are banned by default.

I'm abandoning my Postgres efforts for now. Will revisit in a few weeks.

**Comment by brunocs86** [comment]
> 2- follow this guide for the truncate statements http://espadav8.co.uk/2015/03/04/laravel-database-seeding-with-postgresql/

this page is down
