### ISSUE TITLE
hasPermission invalid

### ISSUE THREAD

**Issue by yuta2** [rappasoft/laravel-5-boilerplate#320]
Hi,
function hasPermissions() always return false;

**Comment by blomdahldaniel** [comment]
Hm.. Yes this is not working properly for me either. 

@rappasoft I actually think there is quit a major issue here. I tried to, quickly, wrap my head around this but without success.

I also noticed that the allow() method that is called upon *hasPermission()* always return true even if the permission does not exist when the role is the administrator. Seems not quit right by me..? Or do you think that is an important way of having it?

if logged in as admin@admin.com
```
access()->user()->hasPermission('Not a permission') // returns true
```

**Comment by rappasoft** [comment]
Weird, this is new, an old update may have broken it, Seems the user object is returning null therefore everything will be false.

**Comment by rappasoft** [comment]
I got it, because you're using admin, it doesn't matter if the permission exists or not, because before it checks permissions on the allow() method, it checks roles, and the admin has the:

```
if ($role->all) {
    return true;
}
```

Which will validate the user regardless, since it didn't even get to the part where it checked the permission or not.

If I log out and use user@user.com, it returns false as it should.

**Comment by rappasoft** [comment]
Also if you are using access(), make sure you are in middleware group 'web' or user will return null.

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Models/Access/User/Traits/UserAccess.php#L83

**Comment by rappasoft** [comment]
Also don't forget the the admin middleware inherits web: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Http/Kernel.php#L40

So you don't have to specify both.

**Comment by tianissimo** [comment]
@rappasoft I have the same problem for `hasPermissions()` as @yuta2's too. The problem is inside the `allowMultiple()`. It should calls `allow()` instead of `can()` on the user object for checking permission.

**Comment by rappasoft** [comment]
You are correct, that was the old BP method that laravel took over and I never changed.

**Comment by rappasoft** [comment]
Fixed: https://github.com/rappasoft/laravel-5-boilerplate/commit/b45cf3757a32a51d06daf2e4fc5a6aa7f39d9395

**Comment by rappasoft** [comment]
Good catch @yuta2: https://github.com/rappasoft/laravel-5-boilerplate/issues/331
