### ISSUE TITLE
[Question] Store settings in DB instead of in file

### ISSUE THREAD

**Issue by digitalit** [rappasoft/laravel-5-boilerplate#321]
Hi,
Some settings might want to be changed by user in browser.

I found: https://github.com/anlutro/laravel-settings

What is your opinion on store settings in DB instead of in file?

Thanks guys!

**Comment by rappasoft** [comment]
Which settings do you think this would be good for?

**Comment by mmakhno** [comment]
Hi!
I think this is good idea!

For example contact information (phone numbers, social network links etc), emails where to send reports, number of items per page or even default meta-tags or images.

But there is some questions about its architecture.
Here is example from one our project, built with Laravel 5.1: http://web-castle.com/files/settings-example.jpg

Thanks for your project! :)

**Comment by digitalit** [comment]
easy switch between debug false/true

**Comment by blomdahldaniel** [comment]
Hm.. Kind of nice but I almost think that this would only make things unnecessary complex and complecated for this project? I don't know but I think this kind of package should end up in the [wiki - Suggested Packages & Tutorials](https://github.com/rappasoft/laravel-5-boilerplate/wiki/8.-Suggested-Packages-&-Tutorials) rather in the project?

**Comment by rappasoft** [comment]
Yeah I think so, the next version is going to simplify a lot of what's going on anyway.

**Comment by rappasoft** [comment]
Added to: https://github.com/rappasoft/laravel-5-boilerplate/wiki/8.-Suggested-Packages-&-Tutorials
