### ISSUE TITLE
why the new version number is 5.2.16?

### ISSUE THREAD

**Issue by dizzying** [rappasoft/laravel-5-boilerplate#322]
I guess the version should be 2.2.16......

**Comment by blomdahldaniel** [comment]
Haha yeah! I just saw that one now as well. Ofc it should be 2.2.16. But Im gonna wait and let @rappasoft sort out how to go about it.

**Comment by rappasoft** [comment]
Oh shit I have no idea how I did that. Haha we jumped ahead a few years!

**Comment by rappasoft** [comment]
It was because I changed the laravel version number and working fast.

**Comment by rappasoft** [comment]
I got rid of the tag and retagged but it doesn't seem to be changing. Anyone know better than me?

**Comment by rappasoft** [comment]
Fixed!

**Comment by blomdahldaniel** [comment]
:+1:
