### ISSUE TITLE
support for timezones

### ISSUE THREAD

**Issue by Remo** [rappasoft/laravel-5-boilerplate#324]
I've seen that there were a few discussions about timezones. Below is part of a patch. I can create a pull request, but since I've change a few more things I'll have to do it manually and before I do that I'd like to talk about the approach.

* I added a timezone selection to the profile.
* I created a new model called `BaseModel` inheriting from `Model`
* By overriding `asDateTime` I was able to set the timzone

I can't like to override the `Model` class, but so far this is the only approach I was able to get working without having to change the output of every date.

```
diff --git a/app/Models/Access/User/User.php b/app/Models/Access/User/User.php
index e20fad5..5ac58bc 100644
--- a/app/Models/Access/User/User.php
+++ b/app/Models/Access/User/User.php
@@ -3,19 +3,28 @@
 namespace App\Models\Access\User;
 
 use App\Models\Access\User\Traits\UserAccess;
+use App\Models\BaseModel;
 use Illuminate\Database\Eloquent\SoftDeletes;
-use Illuminate\Foundation\Auth\User as Authenticatable;
+use Illuminate\Auth\Authenticatable;
+use Illuminate\Foundation\Auth\Access\Authorizable;
+use Illuminate\Auth\Passwords\CanResetPassword;
 use App\Models\Access\User\Traits\Attribute\UserAttribute;
 use App\Models\Access\User\Traits\Relationship\UserRelationship;
+use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
+use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
+use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
 
 /**
  * Class User
  * @package App\Models\Access\User
  */
-class User extends Authenticatable
+class User extends BaseModel implements
+    AuthenticatableContract,
+    AuthorizableContract,
+    CanResetPasswordContract
 {
 
-    use SoftDeletes, UserAccess, UserAttribute, UserRelationship;
+    use SoftDeletes, UserAccess, UserAttribute, UserRelationship, Authenticatable, Authorizable, CanResetPassword;
 
     /**
      * The attributes that are not mass assignable.
diff --git a/app/Models/BaseModel.php b/app/Models/BaseModel.php
new file mode 100644
index 0000000..10af611
--- /dev/null
+++ b/app/Models/BaseModel.php
@@ -0,0 +1,26 @@
+<?php
+
+namespace App\Models;
+
+use Illuminate\Database\Eloquent\Model;
*use Auth;
+
+class BaseModel extends Model
+{
+    /**
+     * Display timestamps in user's timezone
+     */
+    protected function asDateTime($value)
+    {
+        if ($value instanceof Carbon) {
+            return $value;
+        }
+
+        $value = parent::asDateTime($value);
+        $value->timezone = Auth::user()->timezone;
+
+        return $value;
+    }
+}
\ No newline at end of file
diff --git a/app/Repositories/Frontend/User/EloquentUserRepository.php b/app/Repositories/Frontend/User/EloquentUserRepository.php
index 908dd57..8caeaa0 100644
--- a/app/Repositories/Frontend/User/EloquentUserRepository.php
+++ b/app/Repositories/Frontend/User/EloquentUserRepository.php
@@ -212,6 +212,7 @@ class EloquentUserRepository implements UserContract
     {
         $user = $this->find($id);
         $user->name = $input['name'];
+        $user->timezone = $input['timezone'];
 
         if ($user->canChangeEmail()) {
             //Address is not current address
diff --git a/config/app.php b/config/app.php
index 9fd3e47..3a8c5c2 100644
--- a/config/app.php
+++ b/config/app.php
@@ -196,6 +196,7 @@ return [
         App\Providers\MacroServiceProvider::class,
         Potsky\LaravelLocalizationHelpers\LaravelLocalizationHelpersServiceProvider::class,
         Cartalyst\DataGrid\Laravel\DataGridServiceProvider::class,
+        Camroncade\Timezone\TimezoneServiceProvider::class,
     ],
 
     /*
diff --git a/database/migrations/2016_03_18_115817_add_timezone_to_users.php b/database/migrations/2016_03_18_115817_add_timezone_to_users.php
new file mode 100644
index 0000000..5a3867e
--- /dev/null
+++ b/database/migrations/2016_03_18_115817_add_timezone_to_users.php
@@ -0,0 +1,32 @@
+<?php
+
+use Illuminate\Database\Schema\Blueprint;
+use Illuminate\Database\Migrations\Migration;
+
+class AddTimezoneToUsers extends Migration
+{
+    /**
+     * Run the migrations.
+     *
+     * @return void
+     */
+    public function up()
+    {
+        Schema::table(config('access.users_table'), function ($table) {
+            $table->string('timezone')->nullable();
+        });
+
+    }
+
+    /**
+     * Reverse the migrations.
+     *
+     * @return void
+     */
+    public function down()
+    {
+        Schema::table(config('access.users_table'), function (Blueprint $table) {
+            $table->dropColumn('timezone');
+        });
+    }
+}
diff --git a/resources/views/frontend/user/dashboard.blade.php b/resources/views/frontend/user/dashboard.blade.php
index 4b81ce4..2c6e401 100644
--- a/resources/views/frontend/user/dashboard.blade.php
+++ b/resources/views/frontend/user/dashboard.blade.php
@@ -35,6 +35,10 @@
                                         <td>{!! $user->email !!}</td>
                                     </tr>
                                     <tr>
+                                        <th>{{ trans('labels.frontend.user.profile.timezone') }}</th>
+                                        <td>{!! $user->timezone !!}</td>
+                                    </tr>
+                                    <tr>
                                         <th>{{ trans('labels.frontend.user.profile.created_at') }}</th>
                                         <td>{!! $user->created_at !!} ({!! $user->created_at->diffForHumans() !!})</td>
                                     </tr>
diff --git a/resources/views/frontend/user/profile/edit.blade.php b/resources/views/frontend/user/profile/edit.blade.php
index a464d68..e75e194 100644
--- a/resources/views/frontend/user/profile/edit.blade.php
+++ b/resources/views/frontend/user/profile/edit.blade.php
@@ -19,6 +19,13 @@
                             </div>
                         </div>
 
+                        <div class="form-group">
+                            {!! Form::label('timezone', trans('validation.attributes.frontend.timezone'), ['class' => 'col-md-4 control-label']) !!}
+                            <div class="col-md-6">
+                                {!! Timezone::selectForm($user->timezone, null, array('class' => 'form-control', 'name' => 'timezone')) !!}
+                            </div>
+                        </div>
+
                         @if ($user->canChangeEmail())
                             <div class="form-group">
                                 {!! Form::label('email', trans('validation.attributes.frontend.email'), ['class' => 'col-md-4 control-label']) !!}
-- 


```

**Comment by blomdahldaniel** [comment]
Hey!

Glad to hear that you want to contribute!
I think the reason to why no one has responded to this is that it is pretty hard/takes time to read a git diff in this format.

So I would actually suggest that you make a pull request of what you have. That makes it easier for us to pull it down and try it out.

So refactor it to what you think is good and then make a PR so that we can take a look at it.

**Comment by Remo** [comment]
my own fork is heavily modified, I can't easily create a PR without rewriting the whole thing and sorry, my time is too limited to do that without knowing is anyone will actually there.

I know the diff is a bit ugly, but at the end it's not really that complicated, there are basically just three things

* a new timezone field in the users table
* a dropdown in the profile based on the values from Camroncade/Timezone
* the ugly base model which all others would have to inherit from

```php
class BaseModel extends Model
{
    /**
     * Display timestamps in user's timezone
     */
    protected function asDateTime($value)
    {
        if ($value instanceof Carbon) {
            return $value;
        }

        $value = parent::asDateTime($value);
        $value->timezone = Auth::user()->timezone;

        return $value;
    }
}
```

**Comment by blomdahldaniel** [comment]
Hm.. Okey I understand your point. I have now taken a look at it and I think this issue should be takled in another way.

To fit in more with the current structure of the boilerplate we should first add a config file for timezones. 
In the config we can:
* enable/disable the entire functionality.
* set a default timezone
* declare (in an array) what timezones that should show in the dropdown

Then there should be a middleware that checks for the settings set in the config, and if it should, then set the current timezone as the users selected timezone.

And add the new column to the users table and skip the `BaseModel` if possible and instead integrate into current User class.

I think that @rappasoft have been toying or at least planing to make this option. I myself has also thought of doing it. So if anyone would make a suggested fix with a good solution I think that would be welcomed. But it needs to be a bit more abstracted and planned than this suggestion I think.

**Comment by Remo** [comment]
Thanks! The `BaseModel` can't be put in the `User` class. You'll need this to convert all date fields in your models. Let's assume we've got `created_at` in a model, you'd have to process the proper timezone. You could do that in your view, but I'm pretty sure most people would simply forget that, that's why I wanted to be "auto-magically".

**Comment by blomdahldaniel** [comment]
Hm.. But how do you plan on using the timezone? Because if you would ad it to created_at, history stuff, you would be able to create something in Europe and at the same time for the users in America it looks like it was created in the future..? Or how do you plan on displaying "historical time"? Will you always include the time code like CET, PST etc. when showing time? Hm..

**Comment by Remo** [comment]
No, you just save it as UTC and convert it to the local timezone when showing the time. I create it at 08:00, but for someone who's an hour ahead it will look as if it's created at 09:00, that's not the future for that person, that's the present.

**Comment by blomdahldaniel** [comment]
Gah, of course, I'm stupid!

**Comment by Remo** [comment]
I don't think so ;-)
What I did is basically this http://andrew.cool/blog/49/Easy-timezones-in-Laravel-with-Carbon
We could also use mutators `getCreatedAtAttribute`, but that we'd have to do for every model unless we have a common base model or trait.
To me, this is the ugliest part, but I haven't found a better way to set the timezone of a date object.

**Comment by blomdahldaniel** [comment]
Hm.. You are right, that part is a bit tricky..

**Comment by blomdahldaniel** [comment]
Time zones are on the To-do-list for version 3.0. I am going to close this issue now to keep the issue list cleaner. :)

**Comment by kmukku** [comment]
Did you tackle this? I can't find anything from the changelog.
