### ISSUE TITLE
Getting error "LOG.error: exception 'InvalidArgumentException' with message 'File public/js/frontend.js not defined in asset manifest.' in /home/lyhong/webroot/projects/insite/office-list/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:287"

### ISSUE THREAD

**Issue by lyhongpon** [rappasoft/laravel-5-boilerplate#326]

**Comment by blomdahldaniel** [comment]
Can you describe more in what situation this has occurred? Was it from a clean install? What route is it that yield this error?

What happens if you run `gulp` in your terminal?

**Comment by lyhongpon** [comment]
I followed all the instruction but I got this message. After I removed the whole project, and upgraded nodejs, and I do the new installation, it worked.

I don't know what why it happened.  

Thanks for your reply.

**Comment by rappasoft** [comment]
The asset manifest refers to the file that tells Elixir what versions and filenames are currently in use, something probably went wrong, and a recompile usually does it for me. In your case seem to be the version number.
