### ISSUE TITLE
Make unique email & morphTo composite key

### ISSUE THREAD

**Issue by shafihuzaib** [rappasoft/laravel-5-boilerplate#327]
I have a User model, which can be a user of any of the three other models, hence has a polymorphic relation to them.

So I added _accessor_type [String] & accessor_id [Integer]_ to your defined User Model.

Now when it comes to authentication, I would like to allow a given model have unique user. So that means I can have two users with same email but accessing different models.

To elaborate, please consider the following scenario.

```
User (id, name,email,accessor_type, accessor_id)
Manager(id, address)
Operator (id, computer_id)

User Model{
         public function accessor(){
               return $this->morphTo();
   }
}

Manager Model{
             public function users(){
                     return $this->morphMany("App\Models\Access\User\User",'accessor');
   }
}

//Same goes for Operator Model.
```

Now what I want is that, I can have two users with same email address, but different _accessor_type [& accessor_id]_. In other words, email,_ accessor_type, accessor_id_ make a composite key.
For authentication, I want to use _email,password,accessor_.

So please suggest where I'll need to make changes.

Note: I really need to create different profile_tables for Manager & Operator as their data (to be stored) varies greatly from eachother.

**Comment by blomdahldaniel** [comment]
I'm sorry that no one has answered this. It seems to be a very narrow and complex case which is hard to both explain and solve through a forum like this one. 

Have you found your solution to this or did you go another way about it?
I will close this issue now as of lack of activity. Reopen if you can cast new light on this one.
