### ISSUE TITLE
[Question] Move debug/testing package bindings to dedicated service provider.

### ISSUE THREAD

**Issue by ninjaparade** [rappasoft/laravel-5-boilerplate#330]
Hey guys,

so I am curious how you all feel about moving this https://github.com/rappasoft/laravel-5-boilerplate/blob/master/config/app.php#L184 to something like this https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Providers/AppServiceProvider.php

Not sure what your workflows are like, but I don't tend to install dev dependancy's on my production servers and in doing that, the Debugbar ends up breaking. (for example)

https://github.com/rappasoft/laravel-5-boilerplate/blob/master/composer.json#L19-L26

How do you all feel about moving these bindings to a dedicated dev/testing service provider where we can add logic around if we should or shouldn't bind and boot the package providers?

**Comment by rappasoft** [comment]
Yes we can move all dev service providers into that if statement, should speed up production requests as well. I'll add it to my list or you're welcome to make a pull request.

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/commit/fe9a5adc0df0c53770b6a0bf2aafd11ce8d99ba1

**Comment by vpratfr** [comment]
https://laracasts.com/discuss/channels/general-discussion/load-service-providers-depending-on-environment/replies/42026

Seems to me that the approach given above would be better than just using the App provider from what they say.

Additionally, you forgot to move an alias declaration (debugbar) to that place too.

**Comment by rappasoft** [comment]
I'm gonna fix the alias, but I don't know if the thing you linked to is really necessary, seems like a lot of extra code for one little thing, but that's just me.
