### ISSUE TITLE
Security Patch for all boilerplates v2 or greater

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-5-boilerplate#331]
In the last version of the boilerplate I was using can/cannot for permission checking. When Laravel 5.1 came out with built in auth, they started using those which were interfering with mine.

So I changed mine to allow/allowMultiple/has/hasMultiple.

I missed one of the instances of ```can``` that should have been ```allow``` caught by @yuta2.

Which was causing hasMultiple to always return false:

Heres the fix: https://github.com/rappasoft/laravel-5-boilerplate/commit/b45cf3757a32a51d06daf2e4fc5a6aa7f39d9395

**Comment by yuta2** [comment]
Thanks for your help.
