### ISSUE TITLE
How to update the laravel 5 boilerplate

### ISSUE THREAD

**Issue by nasirkhan** [rappasoft/laravel-5-boilerplate#332]
Hi, 
Can you please tell me how can i update the laravel 5 boilerplate? for example i started a project based on 5.1 and now the latest version is 5.2.*. is there any way to update the boilerplate version?

**Comment by rappasoft** [comment]
There is no way to since it's not a composer package. The only way to would be to update commit by commit.

**Comment by faisaljawad1** [comment]
@rappasoft Can you guide me a little about how to update commit by commit within my personal project?
