### ISSUE TITLE
UserContract not named properly

### ISSUE THREAD

**Issue by vpratfr** [rappasoft/laravel-5-boilerplate#334]
It should be `UserRepositoryContract`, in both namespaces `Backend` and `Frontend` in the repositories.

**Comment by rappasoft** [comment]
What files?

**Comment by rappasoft** [comment]
Oh you're saying the naming convention is off. I will fix it.

**Comment by vpratfr** [comment]
Yep, file name + class name for the interface `UserContract` should be `UserRepositoryContract` instead (same mistake both for frontend and backend interfaces)

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/commit/fe9a5adc0df0c53770b6a0bf2aafd11ce8d99ba1
