### ISSUE TITLE
Question: updated migrations

### ISSUE THREAD

**Issue by eleftrik** [rappasoft/laravel-5-boilerplate#335]
@rappasoft I noticed you updated some existing migrations. For example, you added 

```php
                $table->string('token')->nullable();
                $table->string('avatar')->nullable();
```

in CreateSocialLoginsTable.

In such a scenario, why don't you write a new migration which adds the new columns, instead of updating the existing ones?

**Comment by rappasoft** [comment]
If this was an existing project that I already had in production it would have been a separate migration, but since this project is meant to be used from scratch I added it to the table create.

**Comment by eleftrik** [comment]
@rappasoft I cloned your repository some month ago, I'm using it for a project, which is on a private repo on BitBucket. But, sometimes, I pull from your repo to stay updated with the boilerplate.
Since it's now used in production, this is case. I think that several developers use it or will use it in production, sooner or later...

**Comment by rappasoft** [comment]
Many are, but unfortunately there is no way to keep this up to date, as it is not a composer package, I'd say most things you can copy from the commits, but stuff like that you would just know to make a new migration for instead of append to what I did. It should work exactly the same.

**Comment by eleftrik** [comment]
I don't understand your point of view. If you always create new migration, there should not be any problem: changes will be reflected for all users, starting from the scratch or not.

**Comment by rappasoft** [comment]
Since this is meant to be an as-is project, and installed fresh, there's no point to have 100 migrations, when we update database structure, we keep it in the create methods so the next person to do it has fresh tables.

What i'm saying is as you using it on production, wouldn't add to the create method, you would add a new migration in your application to keep the order chronological.

**Comment by blomdahldaniel** [comment]
I totally agree with @rappasoft. This is not a a backend-provider. This is a boilerplate that comes "as-is". One thing that might merge these two thoughts/needs together would be to add new migrations appending the tables within a specific version. So lets say when we are on 2.3.* we add new migrations separately. But when we move on to 2.4 we merge those migrations together to be single create but would also mean more work for us/rappa. Something we have to keep in mind. 

Just a suggestion of how we could get both of the worlds. However I might favor the thought that the best way is just to keep it simple, always keep it as one migration and then let the changelog speak and inform when needed.

**Comment by eleftrik** [comment]
Thanks for your opinion, guys.You're right, this is an as-is project and not a backend-provider, and keeping my project up to date with this boilerplate, it's up to me.
I'm just saying that writing a new migration can save both worlds and doesn't require any additional effort (only requiring _doctrine/dbal_ to update existing columns) and it doesn't add complexity. It's only tedious :)

**Comment by vpratfr** [comment]
+1 with eleftrik, new migrations would allow pulling changes easily when syncing projects. As long as the migration class is documented I don't see any problem with having lots of migrations.

**Comment by rappasoft** [comment]
I don't want someone new to the boilerplate to have to look at 4 migrations for the users table to see what it will be once migrated, you know? Luckily migration changes don't happen too often in this project.
