### ISSUE TITLE
Resend confirmation email reveal secret token

### ISSUE THREAD

**Issue by therezor** [rappasoft/laravel-5-boilerplate#336]
I can confirm my email just using token from resend confirmation link

` public function resendConfirmationEmail($token) {
        return $this->sendConfirmationEmail($this->findByToken($token));
    }`

Should not be findByToken.  $token is secret and should be displayed in email only.

Suggest use user id,login or email in resend link

**Comment by rappasoft** [comment]
Where else would you see it?

**Comment by therezor** [comment]
Steps to reproduce (register with fake email):
1. Register as usual
2. Try to log in, you'll get message "Your account is not confirmed. Please click the confirmation link in your e-mail, or click here to resend the confirmation e-mail."
3. Copy link "http://test.dev/account/confirm/resend/1866048e9c87542268fab2be49e679ad"
4. Remove "resend" from it -> http://test.dev/account/confirm/1866048e9c87542268fab2be49e679ad
5. Go to this url (http://test.dev/account/confirm/resend/1866048e9c87542268fab2be49e679ad)
6. You've got confirmed fake email

**Comment by rappasoft** [comment]
If you have time can you fix and make a PR? I just made a big update and have to go for the day.

**Comment by therezor** [comment]
@rappasoft Yes, Created pull request

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/commit/3cf794c56dc2b2d9575f5c44785e4fb42e8e8a8f
