### ISSUE TITLE
Quick question: attaching a role to a user from a controller

### ISSUE THREAD

**Issue by num3thod** [rappasoft/laravel-5-boilerplate#339]
Greetings,

I'm really struggling to simply attach a role to the authenticated user from within a controller. Getting a Integrity constraint violation when attempting ``` Auth::user()->attachRole('myRole'); ```

Same applies to attachPermission().

Any advice would be greatly appreciated. thanks.

**Comment by num3thod** [comment]
Got it Auth::user()->roles()->attach($roleId);

**Comment by blomdahldaniel** [comment]
Glad you found your way! 

If you do not want to use the static facade function you could also call the helper function:
```
access()->user()
// same as
Auth::user()
```
