### ISSUE TITLE
Getting BadMethodCallException when a new user registers with confirm_email setting is false.

### ISSUE THREAD

**Issue by ssalama** [rappasoft/laravel-5-boilerplate#34]
Hi, I am getting this error `BadMethodCallException in Builder.php line 1992:Call to undefined method Illuminate\Database\Query\Builder::only()` when i try to register a new user with confirm_email setting is false. I deleted composer.lock and ran (dumpautoload -o), but still getting the same error.

Here's my error stack trace: 
![stack20062015](https://cloud.githubusercontent.com/assets/2440732/8265999/84a07034-1715-11e5-9e8d-3021d75bf6f7.PNG)

btw thanks for the awesome boilerplate :+1:

**Comment by rappasoft** [comment]
I will take a look.

**Comment by rappasoft** [comment]
Still looking, hang tight.

**Comment by ssalama** [comment]
Thanks. i changed the code so confirmation mail won't be sent for now.

**Comment by rappasoft** [comment]
Fixed. change App\Http\Controllers\Frontend\Auth\AuthController line 44 from:

```$this->auth->login($this->auth->create($request->all()));```

to:

```auth()->login($this->auth->create($request->all()));```
