### ISSUE TITLE
How to create an admin account

### ISSUE THREAD

**Issue by ohid** [rappasoft/laravel-5-boilerplate#341]
How to create an admin account and give all the roles and permissions? Now anyone can register for an account with no roles and permissions. But I want to give any role and permission to any user that's why I need a admin account.

**Comment by rappasoft** [comment]
Look at the UserTableSeeder

Anthony Rappa

**Comment by ohid** [comment]
Got it, Thanks

**Comment by vernard** [comment]
In my opinion, this needs to be on README.
