### ISSUE TITLE
Small bug in translations

### ISSUE THREAD

**Issue by mmakhno** [rappasoft/laravel-5-boilerplate#342]
Hi!
I've found small bug in exception translations.
**File:** /resourses/lang/{your-language}/exceptions.php 
**Line 69:** 'resend' => 'Your account is not confirmed. Please click the confirmation link in your e-mail, or <a href="' . route('account.confirm.resend', ':user_id') . '">click here</a> to resend the confirmation e-mail.',

route('account.confirm.resend', ':user_id') shoud be replaced with route('**admin.**account.confirm.resend', ':user_id')

**Comment by rappasoft** [comment]
Can you make a PR?

**Comment by mmakhno** [comment]
Ok
