### ISSUE TITLE
how the app.css are created?

### ISSUE THREAD

**Issue by nasirkhan** [rappasoft/laravel-5-boilerplate#347]
can you please tell how the `app.css` files are created? 
https://github.com/rappasoft/laravel-5-boilerplate/blob/master/resources/assets/css/backend/app.css

**Comment by vpratfr** [comment]
See the [Installation Wiki](https://github.com/rappasoft/laravel-5-boilerplate/wiki/1.-Installation) - command #8 (gulp)

**Comment by rappasoft** [comment]
Handled with elixir: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/gulpfile.js

**Comment by nasirkhan** [comment]
somehow i missed to followup. 
I checked the gulpfile it combines the `app.scss` with some other files. But i wanted to know how u combine the font awesome and bootstrap here?

**Comment by mmakhno** [comment]
Nasirkhan, At **frontend/app.scss:**
```
@import "../../../../node_modules/bootstrap-sass/assets/stylesheets/bootstrap";
@import '../../../../node_modules/font-awesome/scss/font-awesome';
```
