### ISSUE TITLE
Language management

### ISSUE THREAD

**Issue by vpratfr** [rappasoft/laravel-5-boilerplate#348]
Once that guy supports PHP 5.5.x (currently requiring PHP 7) I think that would be a great tool to include by default: https://github.com/themsaid/laravel-langman

**Comment by blomdahldaniel** [comment]
Hm.. This seems quite nice but also redundant. My gut tells me this should just be a suggested package and maybe not a default feature..?

**Comment by rappasoft** [comment]
Just to be clear this package doesn't help with lang it just lets you easily change existing ones?

**Comment by vpratfr** [comment]
That package synchronizes the language files so that no message can be forgotten in any language.

For example :  you are developing a feature and you add a message in the english language. The other  language files are now missing that new message. And translators will have to look for it manually to paste it in their language file.

With that package you can add that message to all language files (sync) with one command line.

So not redundant. Very useful when developing in multiple languages, which is what the boilerplate does.

However, before getting it in, I would wait a little bit that some important missing features are implemented (see their repo, I opened a few).

**Comment by blomdahldaniel** [comment]
I will close this issue now since lack of activity. We will take a look at language management for version 3. Do you know if he support php 5.5 yet btw?
