### ISSUE TITLE
The user's resend confirmation email link is not working

### ISSUE THREAD

**Issue by tianissimo** [rappasoft/laravel-5-boilerplate#349]
According to #343, The route is under 'admin' middleware so it doesn't work for new registered users.

**Comment by blomdahldaniel** [comment]
Hm.. Can you make a PR that solves this?

**Comment by rappasoft** [comment]
This was fixed.

**Comment by tianissimo** [comment]
@rappasoft No, I don't think it was fixed. I can still reproduce the issue. Here is the steps after installing the latest version of laravel-5-boilerplate:

1. Register a new user and don't confirm the email yet.
2. Try to login with the newly registered user.
3. On the login page, the error message ` Your account is not confirmed. Please click the confirmation link in your e-mail, or click here to resend the confirmation e-mail.` will be shown
4. Click "click here" from the error message above.
5. You will never get the confirmation email from this resend link.

Again, the route name `admin.account.confirm.resend` used in the translation key `exceptions.frontend.auth.confirmation.resend` works for admin only, not for normal users.
