### ISSUE TITLE
Query Optimization

### ISSUE THREAD

**Issue by ravitej177** [rappasoft/laravel-5-boilerplate#350]
![screenshot from 2016-04-05 12 17 06](https://cloud.githubusercontent.com/assets/12657841/14273449/745728b0-fb28-11e5-8a1c-fcde3322e102.png)

When user login, There are multiple queries running in the db for checking permission groups, roles, individual permissions. what if there is large number of users, Will it drain the performance? is there any optimization to make it simple by joining all the queries.

**Comment by rappasoft** [comment]
I'm open to suggestions.

**Comment by blomdahldaniel** [comment]
I will close this as of now since lack of activity. Feel free to comment or reopen if anyone have thoughts about this.

**Comment by hopewise** [comment]
Any updates on performance for roles?

**Comment by jarod51** [comment]
Shouldn't we introduce the use of Laravel policies ?
