### ISSUE TITLE
Bosnadev/Repositories

### ISSUE THREAD

**Issue by mmakhno** [rappasoft/laravel-5-boilerplate#351]
Hi!
I've found interesting package: Bosnadev/Repositories (https://github.com/Bosnadev/Repositories)
I think it's good aproach to organize repositories.

Also this package has some articles from author (https://bosnadev.com/2015/03/07/using-repository-pattern-in-laravel-5/ or https://bosnadev.com/2015/03/26/using-repository-pattern-in-laravel-5-eloquent-relations-and-eager-loading/).

What do you think about it?

**Comment by rappasoft** [comment]
I will take a look soon.

**Comment by Mythos** [comment]
Sorry for necroing but this one seems also nice:
https://github.com/andersao/l5-repository
I prefer this one as it already comes with caching, generic repository features and is more actively developed.

**Comment by rappasoft** [comment]
I'll look, but they both would require a lot of work, I have a simple version of these already, as I extract out my datalayer, these might be overkill but i'll look into it.
