### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by arrakeen** [rappasoft/laravel-5-boilerplate#355]
I think we could improve how the password reset works.

Forcing the user to enter the email address twice isn't the best option.
Can't we go straight to the new password request after the user clicked on the email link?

**Comment by rappasoft** [comment]
You don't want the extra little bit of security?

**Comment by Arrakeen** [comment]
Does it really matter when we already ask for the old password?

**Comment by blomdahldaniel** [comment]
I think I agree with @arrakeen on this one. Guess the litle piece of security is not good enough vs what it would give in case of UX.

**Comment by rappasoft** [comment]
Ok will note for 3.0

**Comment by rappasoft** [comment]
I attempted to do this but couldn't figure out a good way to since the Laravel password reset class requires the email to figure out which user to update the password for. If anyone has a better way feel free, but i'd prefer to use the laravel methods.

**Comment by blomdahldaniel** [comment]
If a login fails you could store the email in a session and if the user enters the reset-password page the session-variable fills the input. Doesn't have to be fancier then that..?

**Comment by rappasoft** [comment]
I just need to make sure it's secure, do you see any issues with that?

**Comment by arrakeen** [comment]
What I've always done:

1) The user goes to the password reset request form and enters the email address
2) If the email address exists in the database, we create a hashed token and update the user with it
3) An email is sent to the user with a link that includes that token and the related email address
4) The user clicks the link that contains the 2 parameters (email/token) and gets to the reset form
5) If the email address exists in the database and the token is the exact same (case sensitive would be great), then we allow the user to change the password
6) The user has to enter the new password (twice) and then submit the form
7) Job done

**Comment by DennisRas** [comment]
What @arrakeen wrote is basically how most websites do this - including the Auth library in Laravel.

**Comment by rappasoft** [comment]
Ok, i'll work on it.

**Comment by rappasoft** [comment]
This is what I came up with but I don't love it: https://github.com/rappasoft/laravel-5-boilerplate/commit/9e425320debc96f958826aa8dbedcdf956d3c5c8

**Comment by rappasoft** [comment]
Merged it in, if anyone can do it better feel free to send a PR.
