### ISSUE TITLE
Loss of status column in CreateUsersTable migration

### ISSUE THREAD

**Issue by lspedalieri** [rappasoft/laravel-5-boilerplate#357]
I noticed the loss of the status column in the user table. The column is still needed in the backend.

**Comment by rappasoft** [comment]
I just did a fresh install and I have the status column in my users table.

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/blob/master/database/migrations/2015_12_29_015055_setup_access_tables.php#L16

**Comment by lspedalieri** [comment]
I see. Then something else gone wrong in the access table migration and i didn't notice.
Thank you.

**Comment by blomdahldaniel** [comment]
Hope you found a solution @lspedalieri I will close this issue as of now.
