### ISSUE TITLE
RuntimeException: No supported encrypter found. The cipher and / or key length are invalid.

### ISSUE THREAD

**Issue by nasirkhan** [rappasoft/laravel-5-boilerplate#359]
I started to use Gitlab CI for my Laravel projects, and configured a project (https://gitlab.com/nasirkhan/laravel-5-starter). There is not much test cased but the project setup is ok. 
I used the same configuration for an another project but the build is failing and shows the following  error. The build url is https://gitlab.com/nasirkhan/laravel-5-boilerplate/builds/1105655. 

`RuntimeException: No supported encrypter found. The cipher and / or key length are invalid.`

**Comment by poseso** [comment]
php artisan key:generate

**Comment by blomdahldaniel** [comment]
And the `.env` in general could be missing. Git is told to ignore the `.env` file because of its sensitive data.

**Comment by nasirkhan** [comment]
@poseso I ran the command `php artisan key:generate` 
@blomdahldaniel yes, it is ignored. but i have a `.env.gitlab` file and created the `.env` by using the command `cp .env.gitlab .env`

I would like to request you to check the build log where you will find the command i used or check the `gitlab-ci.yml` file https://gitlab.com/nasirkhan/laravel-5-boilerplate/blob/master/.gitlab-ci.yml

**Comment by poseso** [comment]
Did you check on config/app.php line 116?
'cipher' => 'AES-256-CBC',   <- it needs a 32 characters strings,  SomeRandomString its only 16 characters.. and also check permissions?

**Comment by nasirkhan** [comment]
on my `config/app.php` line 92 written as `'cipher' => MCRYPT_RIJNDAEL_128,`


--
*Nasir Khan Saikat*
www.nasirkhn.com

**Comment by poseso** [comment]
ah you are using v5.1

**Comment by poseso** [comment]
'key' => env('APP_KEY', 'SomeRandomString'),    <- php artisan key:generate    and set manually the key in there in your config/app.php try it

**Comment by nasirkhan** [comment]
`php-mcrypt` was disabled. changed `'cipher' => MCRYPT_RIJNDAEL_128,` to `'cipher' => 'AES-256-CBC'`, and it solved the issue. 

do you have any idea why the default cipher was changed?

**Comment by rappasoft** [comment]
If its different than that means that was the default at the time this project was created.
