### ISSUE TITLE
Update local from your repo

### ISSUE THREAD

**Issue by blomdahldaniel** [rappasoft/laravel-5-boilerplate#36]
Hi @rappasoft 

This question might be a bit silly.. But I cant get my head around this.

I have cloned your repo, then I deleted the .git folder (to get only my own history).
Now, one of my projects is a bit behind your repo (ex. the ModelFactory). How do I update and pull/merge the updates from your repo to my local repo?

In my head, something like `composer update`or `npm install` should do the trick but it clearly doesnt..

How should I work/think/act properly?

**Comment by rappasoft** [comment]
It may be a little tricky if you have downloaded an earlier version. You may just have to check the commit history and download the necessary files. In the event of a new project however you shouldn't need to.

**Comment by blomdahldaniel** [comment]
Hm.. In a new project I clone the current repo and therefore it is up to date or what do you mean with "new project?"

**Comment by rappasoft** [comment]
Any new clone should be fully up to date with the latest on here.

**Comment by blomdahldaniel** [comment]
Yes of course. But I wondered if there was a simple way to update and merge down your updates but i guess that has to be done the long way then. Thanks for answering. :smile:

**Comment by rappasoft** [comment]
Not that I know of since it's not as easy to update as a dependency. I've been doing it the hard way on my own projects as well, but if you find an easier way i'd love to hear.

**Comment by blomdahldaniel** [comment]
:+1:
