### ISSUE TITLE
Lets chat!

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-5-boilerplate#361]
Sorry I've been MIA lately, but I assure you I look every day.

We have all made a great product together, and I would like to continue to do so.

I have many components of other projects I was going to port over and sell on CodeCanyon, but I think i'm just going to add them here for everyone to use.

If any of you have taken a look at the code of spark, I really like the idea of the installer.

Basically you download an installer, which is just php files, and it then downloads the spark files and hooks them up in your laravel application for you.

I like this approach because it lets you keep the core files separate from the rest of the application, while letting you both change them, or update them through artisan, something you have all been wanting.

I haven't delve too deep into how he does it, but it is not simple. I'm hoping it will be a possibility in the future, where this repository is the installer files, and much like laravel, we will have a separate repository for the core files.

Here is what I currently have on my list:

- Timezones
- Ability to change the way a date is shown for different locales (or have it be an option on the usr dashboard)
- Change the event listeners to an event subscriber.
- I like the idea of items being locked if someone else is currently editing them.
- Datatables, or something similar as an example on the access tables.
- Maybe some sort of command line installer.
- Cleanup of the assets, what gets imported where, etc.
- Better use of SOLID principals
- Better use of repository/contract pattern
- Query optimization
- Full Documentation
- Decision on how to handle permissions, database or file based.
- TESTS!
- Internal API, api routes, api tokens, etc.
- All admin LTE features.
- Ability to specify the admin backend name, currently 'admin'. 
- Add history section, as well as classes to keep track of everything through model events.

It's a long road map but I think we can do it and have the best starter project for all of us to use and benefit from.

Did I miss anything?

**Comment by digitalit** [comment]
I use https://github.com/gaaarfild/laravel-conf for settings that needs to be changed by user.

It seems to work pretty good and it might be an alternative to database stored permissions?

**Comment by daniel-farina** [comment]
I'm not sure what OctoberCMS is using but its amazing. 
You should check it out. The installed is the cleanest I have seen.

**Comment by rappasoft** [comment]
What does everyone think about the current permissions section? Obviously users/roles are database driven, but I don't know if we need CRUD operations for permissions/groups/dependencies. Maybe just seed them?

**Comment by rappasoft** [comment]
As you can see I made a new branch for the future version, so you can play around and keep track of my progress: https://github.com/rappasoft/laravel-5-boilerplate/tree/3.0-dev

**Comment by digitalit** [comment]
I haven't  done any "upgrades" yet but i am about to now. What is the best approach? 

Move "my stuff" into an fresh install of this branch or move bits and pieces of this branch into my project?

**Comment by digitalit** [comment]
Can one base project on 3.0 or when if not?

**Comment by digitalit** [comment]
This looks good: https://github.com/Snowfire/Beautymail

**Comment by blomdahldaniel** [comment]
@rappasoft you just keep on delivering dude! This is so awesome! I have also been MIA but I hope that I can contribute with some of the stuff for 3.0.

Trying to figure out a way to do the Spark approach regarding installation and updates would be soooo awesome!! Really nice to have something to take inspiration of and learn from.

The list of things is so awesome! Would bee so cool!

I would like to add a point about UX. I think that the "dashboard" and "adminpanel" are a bit confusing right now. I would like to see something like *My profile* instead. 

Tests is a great idéa. So nice to feel secure about all the Auth-CRUD.

### Way to work with 3.0
Should we maybe create another repo for just 3.0 dev-purpose? That way we could more easily have a lot of issues and PRs going on. It could be nice to use an open PR-approach, that way people can fill in and review the stuff that is added into it? Or am I just off, should we stick it here just as easily? Was just a thought to not mess too much with the issue-list of this version..?

**Comment by num3thod** [comment]
Just an idea, but something like this would be useful to many projects imho https://www.npmjs.com/package/laravel-elixir-uncss
