### ISSUE TITLE
How to integrate AdminLTE fully?

### ISSUE THREAD

**Issue by robertholmes** [rappasoft/laravel-5-boilerplate#363]
First, thank you so much for this! I see that ADMINLTE is stripped down. I've downloaded the files...but where do they go in the project?

**Comment by blomdahldaniel** [comment]
What do you mean with stripped down? Do you mean all the plugins?

As of now, all the less-files have been converted to sass and is located in `resources/assets/sass/backend/AdminLTE/`. If you would like to add the plugins you can put them where you would like and just combine it all through elixir (gulpfile.js).

I hope you found a solution to this.

**Comment by blomdahldaniel** [comment]
Hopefully version 3.0 will include more of the examples from the AdminLTE theme.
