### ISSUE TITLE
Sort permissions

### ISSUE THREAD

**Issue by digitalit** [rappasoft/laravel-5-boilerplate#364]
Hi,
I really need to sort my permissions list it is frustrating to have to eye ball trough the huge list.

Please tell me how i can hard code an sorting for this list.

In the future im really hoping for an filtering/search and sort function for the access part of the BP.

Thanx guys.

**Comment by blomdahldaniel** [comment]
What do you mean by sort?
Right now they are sorted by alphabetical order after the permission *display_name*.

If you want to just tuck on a `->sortBy()` you can do that inside the view:
`resources/views/backend/access/roles/permissions/index.blade.php` Line: 151
```php
@foreach ($permissions->sortBy(...) as $permission)
```

Or if you want to do an `orderBy` that changes how permissions are sorted anywhere, you can do that from the database you can do that in the file:
`Repositories/Backend/Access/Permission/EloquentPermissionRepository.php` Line: 64 
Methods:
 `getPermissionsPaginated`
`getAllPermissions`

```php
public function getPermissionsPaginated($per_page, $order_by = 'display_name', $sort = 'asc') {}

public function getAllPermissions($order_by = 'display_name', $sort = 'asc', $withRoles = true)
```

**Comment by digitalit** [comment]
I dont med an static sort, i mean an actual sortin/filtering and search function like this:

![skarmavbild 2016-04-29 kl 13 56 07](https://cloud.githubusercontent.com/assets/6569136/14915337/67c4dc76-0e12-11e6-8ad8-d351bf26bee6.png)

When i work with permissions for an new function i dont want to see all the other permissions. Further more it is really annoying that the tab All permissions wont stay selected, nore the page making the workflow for adding new permissions a bit of a pain.

When im adding a new permissions for an new function i whant to show only the permissions for an suitable existing function so i easily can cut an paste. To do this i have this code

```
 return Permission::with('roles')->orderBy($order_by, $sort)->paginate($per_page);
        // return Permission::with('roles')->orderBy($order_by, $sort)->whereIn('group_id', [11, 13])->paginate($per_page);
```
 in 
Repositories/Backend/Access/Permission/EloquentPermissionRepository.php Line: 64 

 to temporarily achieve this.

**Comment by blomdahldaniel** [comment]
Okey, well thats a whole different story then. 

I though DataTables had a plugin for session/cache based searching/filter?

I dont think that we will change anything of this in v.2 but we will definitely try to find a better way of managing the auth-stuff.
