### ISSUE TITLE
Uploading Image

### ISSUE THREAD

**Issue by Ruwan-Ranganath** [rappasoft/laravel-5-boilerplate#367]
Hi, 
In the Boilerplate is there any per-defined method to upload image for users in the profile ?

**Comment by Punksolid** [comment]
I didn't find anything. Maybe it would be useful to integrate         "codesleeve/laravel-stapler": "^1.0"

**Comment by digitalit** [comment]
intervention/image is the only package one needs.

**Comment by blomdahldaniel** [comment]
Nope the boilerplate does not have any suported function for image handling. `intervention/image` has been great for me before. So, I would say, pull down a package, should be easy. :)
