### ISSUE TITLE
Confirmation email template editing and configuring

### ISSUE THREAD

**Issue by Ruwan-Ranganath** [rappasoft/laravel-5-boilerplate#369]
I've added google smtp configurations to the .env file following these  

```
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=myemail@gmail.com
MAIL_PASSWORD=mypassword
MAIL_ENCRYPTION= ? 

```
Still I'm not receiving any confirm email , running boilerplate on my localhost  . changed google security level to low . 

am I missing something? 

also where I can edit the email template ?

Thank you :+1:

**Comment by Punksolid** [comment]
You tried restarting the server? The env variables are loaded when you start the server.

**Comment by Ruwan-Ranganath** [comment]
I'm running Apchae server on Ubuntu, tried restarting it , still no working.

**Comment by blomdahldaniel** [comment]
These things can be tricky. Did you find a solution to this @Ruwan-Ranganath ? 
I suggest you seek help in the Laravel / laracasts forum for these non-repo questions. I think that they can give you better help. :)
