### ISSUE TITLE
Testing Issues

### ISSUE THREAD

**Issue by ven7ura** [rappasoft/laravel-5-boilerplate#37]
I was writing some tests, and I encountered an error.

This issue can be replicated by simply doing two tests with the call or visit methods.

    public function testFirstVisit()
    {
        $this->visit('/')
            ->see('Home');
    }

    public function testSecondVisit()
    {
        $this->visit('/')
            ->see('Home');
    }

This throws an error...

It seems that PHPUnit does not like the require_once in the routes.php file. If we move the required files in the routes file the issue is resolved.

**Comment by rappasoft** [comment]
Do you think there is an alternative solution? I hate all the routes in one file, and with a verbose ACL, it gets really confusing to look at really fast.

**Comment by blomdahldaniel** [comment]
@rappasoft :+1:  but is there any other call that PHPUnit accepts? Have @ven7ura searched what PHPUnit says about it?

**Comment by ven7ura** [comment]
Second test throws a 404 HttpNotFoundException...

It seems that changing from `require_once()` to `require()` fixes the issue...

**Comment by rappasoft** [comment]
Ok I will fix soon.

**Comment by rappasoft** [comment]
Changed to require() in upcoming commit.
