### ISSUE TITLE
Folders lang.

### ISSUE THREAD

**Issue by jefferson-andrade** [rappasoft/laravel-5-boilerplate#371]
What these folders lang inside the backend folder? I didn't understand very well.

Thanks!

**Comment by rappasoft** [comment]
Those are bigger chunks of text that are specific to the backend.

**Comment by jefferson-andrade** [comment]
Excuse my ignorance and my english of google translate lol

But these translations could not be within:

resources / lang / en /
resources / lang / en /

...

perhaps in a file backend.php

**Comment by rappasoft** [comment]
You can refactor how you want. They have more markup and links etc and shouldn't be in the strings language files.

**Comment by jefferson-andrade** [comment]
understood, thanks
