### ISSUE TITLE
Any way to get the refresh token for use in Google APIs ?

### ISSUE THREAD

**Issue by vladvisinescu** [rappasoft/laravel-5-boilerplate#373]
I want the user to be able to view some of his Google Analytics data and for that i also need the refresh token from the initial auth stored in the database.

is there any straightforward way to do this ?
i guess there\`s something to add to EloquentUserRepository.php  in the `findOrCreateSocial` method...

Thanks !

**Comment by vladvisinescu** [comment]
i guess there`s something to add to EloquentUserRepository.php  in the `findOrCreateSocial` method...

**Comment by rappasoft** [comment]
Does this help? https://github.com/rappasoft/laravel-5-boilerplate/blob/master/resources/views/backend/layouts/master.blade.php#L7

**Comment by vladvisinescu** [comment]
no, i need the refresh_token which comes in the response from google when using socialite.

**Comment by SumonMSelim** [comment]
can't you just get it from current/logged in users object; like this way? `auth()->user()->refresh_token`

**Comment by Francismori7** [comment]
You need to add the proper scopes and then the socialite implementation will add the refresh token to the token returned.

**Comment by rappasoft** [comment]
You can append more google scopes here: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/config/services.php#L86

**Comment by rappasoft** [comment]
If you know what the scope is I can add it as an option.

**Comment by Francismori7** [comment]
http://stackoverflow.com/a/36065985

Not a scope but rather an access type parameter

**Comment by rappasoft** [comment]
Is that with($parameters) native to Socialite or no? If so I can add it in.

**Comment by Francismori7** [comment]
Yes, it is now. See AbstracrProvider.php in Two.

**Comment by rappasoft** [comment]
Do you think this 'access_type' => 'offline' should be appended by default to google? Or should I leave it as an empty array and let the person add it.

**Comment by rappasoft** [comment]
Wait I already have this built in, there's a with array for each provider in config.
