### ISSUE TITLE
How to change the default language yo another one

### ISSUE THREAD

**Issue by dukenst2006** [rappasoft/laravel-5-boilerplate#374]
Hello, thank you for this awesome boilerplate. I want to change the default language English to French, how can i do it please ?

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/blob/master/.env.example#L4

Change that to **fr** and it will use the language files from the **fr** folder here: https://github.com/rappasoft/laravel-5-boilerplate/tree/master/resources/lang

**Comment by blomdahldaniel** [comment]
And if you want to remove the language picker you can disable it like this inside [config/locale.php#L11](https://github.com/rappasoft/laravel-5-boilerplate/blob/master/config/locale.php#L11)

```php
'status' => false,
```

Then with the info given above, your application will be in Fr and only Fr, no one get the opportunity to change it.

**Comment by dukenst2006** [comment]
That's great, thanks @rappasoft  and @blomdahldaniel
