### ISSUE TITLE
Force logout if user not active

### ISSUE THREAD

**Issue by digitalit** [rappasoft/laravel-5-boilerplate#375]
Is it possible when a logged in user visit the website, check if it's not a active user then logout the logged in user?

**Comment by digitalit** [comment]
OK i solved this like this:

i created an middleware in \App\Http\Middleware called CheckUserStatus

```
public function handle($request, Closure $next) {
        $user = $request->user();
        if ($user) {
            if (!$user = auth()->user()->status) {
                auth()->logout();
            }
        }
        return $next($request);
    }
```

and added \App\Http\Middleware\CheckUserStatus::class, in App\Http\Kernel

```
   protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \App\Http\Middleware\LocaleMiddleware::class,
            \App\Http\Middleware\CheckUserStatus::class,
        ],
```

So now if i change to status 0 on any user they get logged out upon next page request.

Please tell me if this is an okay or if i should do this another way?

**Comment by blomdahldaniel** [comment]
I think that your solution is ok. But for the best security and/or UX you shuld find some way to logout the user from the frontend, more like banks do.. This could be done either trhough plain front end js or storing timestamps and then perform cron jobs or something every minute on the server and then send a push-message to the correct user that make the frontend visit /logut or something.

I would again recommend you to go to the specific Laravel forums or laracasts forums for questions like this. You would get better answers and this repo can stay clean to repo specific stuff. :)

**Comment by digitalit** [comment]
I know this is probably easy to get an general answer to on Laracast but since i want to preserve the BP standard i thought i ask here.
