### ISSUE TITLE
Create user without password

### ISSUE THREAD

**Issue by pl38** [rappasoft/laravel-5-boilerplate#377]
Brilliant setup for Laravel really helps you get up and running quickly - thank you.

Has anyone set this up to create a user without a password, send the email to the registered address, with token and then have them create there own password - a bit like password reset?

**Comment by arrakeen** [comment]
I think jwt-auth fits your needs: https://github.com/tymondesigns/jwt-auth

**Comment by daniel-farina** [comment]
@pl38 

I think you need this to import multiple users and send them and email to reset their password correct? 

One simple way on your importer would be to add the following after the user is created with your custom script: 

```
$token = str_random(64);
 DB::table(config('auth.passwords.users.table'))->insert([
                        'email' => $user->email,
                        'token' => $token
                    ]);
//then notify user about the new password reset, you could always customize this email.
$user->notify(new UserNeedsPasswordReset($token));

```

You will need:
use App\Models\Access\User\User;
use Illuminate\Support\Facades\DB;
use App\Notifications\Frontend\Auth\UserNeedsPasswordReset;


Good luck!
