### ISSUE TITLE
User Create always uses the Member Role

### ISSUE THREAD

**Issue by Teranode** [rappasoft/laravel-5-boilerplate#38]
So when using the register form, I have the Default Role set as Validating via access.php
however when a user registers they end up in the Member Role by default regardless of what I set the Default User Role as during registration :(

**Comment by Teranode** [comment]
This is in events of: https://github.com/rappasoft/laravel-5-boilerplate/issues/25

the problem still persists for some reason and I don't know why

**Comment by rappasoft** [comment]
I will take a look.

**Comment by Teranode** [comment]
any luck?

**Comment by rappasoft** [comment]
Sorry will debug as soon as I can, maybe add a captcha in the meantime?

**Comment by Teranode** [comment]
I did add a captcha :/ - but they still get by.

**Comment by Teranode** [comment]
:/

**Comment by Teranode** [comment]
so im guessing nothing found?

**Comment by Teranode** [comment]
sigh never mind i ll just find some other way.

**Comment by rappasoft** [comment]
Sorry I keep meaning to do this but can never get to it. When it's fixed you can always merge it. It shouldn't be more than replacing a function if that.

**Comment by rappasoft** [comment]
I finally got a chance to look at this. I made a Validating role, and I changed default_role to validating, registered 10 times, each time it was correct. Is there something more you have added that could be messing with the logic?

**Comment by Teranode** [comment]
It's rather complicated, as it's usually spam users who get through. When a normal user registers they are put into the Validation Role, which is what I want, and it does happen, however, when a Spam user registers, for Whatever reason, they get put into the Member's Role >_>. I have no idea why, but it just happens.

I did some mail tests, and I don't know if it's useful or not, but mail's that can't be verified (spam emails or email's that aren't real) are not given the validation email, therefore skipping that entire process, so I don't know if that affects the roles or not.
