### ISSUE TITLE
incompatible with laravel 5.2 because of usage of env() inside seeders (and maybe elsewhere)

### ISSUE THREAD

**Issue by vesper8** [rappasoft/laravel-5-boilerplate#380]
As of Laravel 5.2 you can no longer access env() outside of the /config/ files.

```
Caching And Env

If you are using the config:cache command during deployment, you must make sure that you are only calling the env function from within your configuration files, and not from anywhere else in your application.

If you are calling env from within your application, it is strongly recommended you add proper configuration values to your configuration files and call env from that location instead, allowing you to convert your env calls to config calls.
```

That is, you can, but if you use php artisan config:cache, which is run by default, then all of your env() will return NADA. When using cache:config the env() variables are not accessible!!!

This results in 

```
        if (env('DB_CONNECTION') == 'mysql') {
            DB::table(config('access.users_table'))->truncate();
        } elseif (env('DB_CONNECTION') == 'sqlite') {
            DB::statement('DELETE FROM ' . config('access.users_table'));
        } else {
            //For PostgreSQL or anything else
            DB::statement('TRUNCATE TABLE ' . config('access.users_table') . ' CASCADE');
        }
```

Always going into the last else.. which throws errors while seeding.

You must create your own file in the /config/ folder and anywhere else in the code you must replace env('something') by config('yourfile.something')

**Comment by rappasoft** [comment]
You have the docs for where it says this? Not that I don't believe you just want to read more about it.

**Comment by pe3udent** [comment]
@rappasoft [https://laravel.com/docs/5.2/upgrade](https://laravel.com/docs/5.2/upgrade)

**Comment by rappasoft** [comment]
This should do it: https://github.com/rappasoft/laravel-5-boilerplate/commit/267a73b46c9f5e1568abb9ec8b819676d36489f6
