### ISSUE TITLE
Adding new fields to users

### ISSUE THREAD

**Issue by Ruwan-Ranganath** [rappasoft/laravel-5-boilerplate#381]
Need to add new fields to users table , ex : summery , image , age , gender 
I've added column to the table , but still have no luck finding model to add $fillable .
in the fresh laravel installation user.php is on app folder directly so I can add custom fields inside adding $fillable ,

**Comment by blomdahldaniel** [comment]
Hi! 

This is set inside the User.php file located in `app/Models/Access/User/User.php`
Look att the [file at line 25 and line 32](https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Models/Access/User/User.php#L25)

Everything is by default fillable except id and then `password` and `remember_token` are hidden (Line 32)

So, everything should work properly if you just add new columns to the DB.

**Comment by Ruwan-Ranganath** [comment]
Hello @blomdahldaniel , 
Thats weird , I just add simple "summery"  field to the database and and from  the `App\Service\Access\Trait\RegistersUsers.php`

add `dd ($request);` to check output. 

`    public function register(RegisterRequest $request)
    {
        if (config('access.users.confirm_email')) {
            $user = $this->user->create($request->all());
            event(new UserRegistered($user));
            dd ($request);
          //  return redirect()->route('frontend.index')->withFlashSuccess(trans('exceptions.frontend.auth.confirmation.created_confirm'));
        } else {
            auth()->login($this->user->create($request->all()));
            event(new UserRegistered(access()->user()));
            return redirect($this->redirectPath());
        }
    }`

dd output content field shows summery is submitted as below , 
`content: "_token=pbCCRPs4s6KOv68AFckVmB5xgWCf9RKMEONcA1Yz&name=newusers&password=newnewnew&password_confirmation=newnewnew&email=new%40new.com&summery=new+new+new+new"`

but in the database column it's empty .

**Comment by Ruwan-Ranganath** [comment]
Here is the solution I've found , 
goto `app\repositories\frontend\access\user\EloquentUserRepository.php`

you will find 

        public function create(array $data, $provider = false)
    {
        if ($provider) {
            $user = User::create([
                'summery' => $data['summery'], // add new field here
                'name' => $data['name'],
                'email' => $data['email'],
                'password' => null,
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed' => 1,
                'status' => 1,
            ]);
        } else {
            $user = User::create([
                'summery' => $data['summery'], // add new field here
                'name' => $data['name'],
                'email' => $data['email'],
                'password' => bcrypt($data['password']),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed' => config('access.users.confirm_email') ? 0 : 1,
                'status' => 1,
            ]);
        }

      
    }

check how i added new field 'summery' to the function.after you add new field there oost request will send new field data to the database.

**Comment by blomdahldaniel** [comment]
aah! Great! Ofc, i forgot that you had been appending the original form. Glad you found it! :)

**Comment by arikazukitomaharjan** [comment]
how to change table users to custom table in laravel boilerplate?can you answer me please?

**Comment by blomdahldaniel** [comment]
in [config/access.php](https://github.com/rappasoft/laravel-5-boilerplate/blob/master/config/access.php) you can set a custom name for the users table. Is that what you mean?
