### ISSUE TITLE
Symfony \ Component \ HttpKernel \ Exception \ MethodNotAllowedHttpException

### ISSUE THREAD

**Issue by poseso** [rappasoft/laravel-5-boilerplate#384]
When I go to /admin/access/users  and try to delete a user I get this error:

 Symfony \ Component \ HttpKernel \ Exception \ MethodNotAllowedHttpException
No message

C:\wamp64\www\poseso\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php

         * Throw a method not allowed HTTP exception.
         *
         * @param  array  $others
         * @return void
         *
         * @throws \Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
         */
        protected function methodNotAllowed(array $others)
        {
            throw new MethodNotAllowedHttpException($others);
        }
     
        /**
         * Determine if a route in the array matches the request.
         *
         * @param  array  $routes
         * @param  \Illuminate\http\Request  $request
         * @param  bool  $includingMethod
         * @return \Illuminate\Routing\Route|null
         */

Arguments

    ""

Environment & details:
GET Data empty
POST Data empty
Files empty
Cookies
_ga 	

"GA1.2.272491734.1458736571"

XSRF-TOKEN 	

"eyJpdiI6IlVNOTd0SUtONGdPb1hIK0ZuSURQUXc9PSIsInZhbHVlIjoiTWI1c0czaE56MXBGenFlQVhxSFNnVXVyQXUxdjcxMWdrdjlmaDFYU1U2ajkxek84d0xrdTFJN244WXJ0RnZEbjg0a2JFT1VyNXRnNFloUGZaT0NjWUE9PSIsIm1hYyI6ImJmM2M5ZTY0YzRjYTRlMmVkZDdmZjJjZmEyMDdjZjFhNzRlMmUwMDc4NWVjYTBlZmNhNmE2ZWIzYmViYzE4NzIifQ=="

lvapp_session 	

"eyJpdiI6IlBWZlVWQ2lhcFFVMkYrZzVnRkxuM2c9PSIsInZhbHVlIjoiNFVTM05sWjNNQTY1czZEek1CNTlmNmlFc1UwUHBzb3FHelBSM3JxU2JzMmV4cDJYMWJtM0pNbnFDcGNWcEpCQk9teWJEbm1JYW5GbFJNcUVRWEVUb1E9PSIsIm1hYyI6Ijc2YzM1MWQxODI2NzFhZWQ5N2I2YWI2MzAxOTQ5MzJlNGE1ZDRmZDA2OTU2ZDViYzdmOTNmYTJlZGNkNmYyZDcifQ=="

Session empty
Server/Request Data
REDIRECT_STATUS 	

"200"

it only happens with the delete button, on users / roles /permissions

**Comment by poseso** [comment]
Stack frames (24):
23 Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException 
…\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php219
22 Illuminate\Routing\RouteCollection methodNotAllowed
…\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php206
21 Illuminate\Routing\RouteCollection getRouteForMethods
…\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php158
20 Illuminate\Routing\RouteCollection match
…\vendor\laravel\framework\src\Illuminate\Routing\Router.php823
19 Illuminate\Routing\Router findRoute
…\vendor\laravel\framework\src\Illuminate\Routing\Router.php691
18 Illuminate\Routing\Router dispatchToRoute
…\vendor\laravel\framework\src\Illuminate\Routing\Router.php675
17 Illuminate\Routing\Router dispatch
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php246
16 Illuminate\Foundation\Http\Kernel Illuminate\Foundation\Http\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php52
15 call_user_func
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php52
14 Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\barryvdh\laravel-debugbar\src\Middleware\Debugbar.php49
13 Barryvdh\Debugbar\Middleware\Debugbar handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php136
12 call_user_func_array
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php136
11 Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php32
10 call_user_func
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php32
9 Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php44
8 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php136
7 call_user_func_array
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php136
6 Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php32
5 call_user_func
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php32
4 Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php103
3 call_user_func
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php103
2 Illuminate\Pipeline\Pipeline then
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php132
1 Illuminate\Foundation\Http\Kernel sendRequestThroughRouter
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php99
0 Illuminate\Foundation\Http\Kernel handle
…\public\index.php54

**Comment by poseso** [comment]
solved

**Comment by vangelis183** [comment]
How did u solve it?
