### ISSUE TITLE
how to remove index.php in url?

### ISSUE THREAD

**Issue by jiji262** [rappasoft/laravel-5-boilerplate#386]
like this url:
```
http://localhost/laravel-5-boilerplate/public/index.php/macros
```
it has "index.php" in it. 
With the .htaccess file has set and rewrite mod open, still no work.

**Comment by Ruwan-Ranganath** [comment]
How about running through the server using 
`php artisan serve`
?

**Comment by tonetlds** [comment]
@jiji262 

Try some `RewriteRule` in your .htaccess, like this:
```
<IfModule mod_rewrite.c>
    RewriteEngine On
 
    RewriteRule ^(.*)$ public/$1 [L]
</IfModule>
```

**Comment by rappasoft** [comment]
A default laravel installation comes with this by default: https://github.com/laravel/laravel/blob/master/public/.htaccess
