### ISSUE TITLE
Spark

### ISSUE THREAD

**Issue by ekandreas** [rappasoft/laravel-5-boilerplate#387]
Is it possible to combine Spark with the boilerplate or doesnt the ACL match? Or other challenges?

**Comment by rappasoft** [comment]
Spark itself is completely different from everything. It is meant to be used as a SaaS boilerplate itself, so it would be unfeasible to combine the two.

**Comment by ekandreas** [comment]
Not suprising :-)
Spark has no admin-panel as well and Rappasoft is so much more of an application boilerplate.
Thanks for the answer!
