### ISSUE TITLE
Easiest way to drop backend/frontend styling?

### ISSUE THREAD

**Issue by dylanharbour** [rappasoft/laravel-5-boilerplate#389]
I totally understand the need for some projects to have separate backend and frontend pages/assets, however I'd like to use the boilerplate for some projects that do not require separate frontend/backend pages and assets.

Specifically, these are for Back Office style apps that only have a "backend". Apart from just ignoring the entire front end structure, is there an easier way to just remove the separation of frontend and backend and only have one set of assets/routes/pages/controllers?

**Comment by blomdahldaniel** [comment]
Hm.. I don't think there would be any quick and easy solution for that. You would have to ignore it or restructure the entire project. One possible feature for the future would be an option in the installer @rappasoft  where the user can chose whether to use separated frontend vs backend or just have it smashed together. However the usecase for the smashed-together might be so small so it would not be worth doing. The whole project builds on a frontend / backend system...

**Comment by dylanharbour** [comment]
Thanks @blomdahldanie. I'm finding it to be more of a pain than its worth. Would be nice to have for the installer but I understand the limited use. 

Closing this issue, I was just wondering if there was something that I was missing which would have made it much easier!
