### ISSUE TITLE
Translation on Javascript files? is it possible?

### ISSUE THREAD

**Issue by poseso** [rappasoft/laravel-5-boilerplate#391]
is it possible to use {{ trans('menus.backend.access.permissions.management') }}   inside of a .js file? or a way to translate it? i want to translate this:

        buttonLabels: {
            next: 'Siguiente',
            back: 'Atrás',
            finish: 'Finalizar'
        },

but   next: '{{ trans('menus.backend.access.permissions.management') }} ',   doesnt seem to work

**Comment by blomdahldaniel** [comment]
No unfortunately, that is not possible. One way could be to pass the translated strings as javascript variables through the `\JavaScript` facade.

**Comment by poseso** [comment]
Do you have any example i can take a look at?

**Comment by blomdahldaniel** [comment]
Take a look at Laracasts repo (Jeffrey Way) [laracasts/PHP-Vars-To-Js-Transformer](https://github.com/laracasts/PHP-Vars-To-Js-Transformer).


### Example:
From your controller you may pass:
```php

{
  // Inside controller method
  $variable = 'Hello World";
  \Javascript::put([ 'myVariable' => $variable])

  return view('example-view');
}
```

And then you may access this data from javascript by simply using the variable name (in this case it would be `myVariable`

#### JavaScript example:
```javascript
console.log( myVariable ) // Hello World
```
