### ISSUE TITLE
where is frontend and backend path

### ISSUE THREAD

**Issue by shinnlu** [rappasoft/laravel-5-boilerplate#396]
i am newbie to laravel and just installed lavarel-t-boilerplate, but i don't know where is the route path to frontend and backend, please tell me that.
i have tried every one path in route.php but not working.

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Http/Routes/Frontend/Frontend.php#L6
https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Http/Routes/Backend/Dashboard.php#L3

**Comment by shinnlu** [comment]
thanks, @rappasoft , it's working after reload the Homestead.
