### ISSUE TITLE
resendConfirmationEmail not return real error

### ISSUE THREAD

**Issue by shinnlu** [rappasoft/laravel-5-boilerplate#397]
when i use resendConfirmationEmail to test email configuration, there is only one response:'A new confirmation e-mail has been sent to the address on file.', but i didn't found any email.
i found the code like this will not return real error
`
    public function resendConfirmationEmail($user_id, FrontendUserRepositoryContract $user, ResendConfirmationEmailRequest $request)
    {
        $user->sendConfirmationEmail($user_id);
        return redirect()->back()->withFlashSuccess(trans('alerts.backend.users.confirmation_email'));
    }

`

**Comment by blomdahldaniel** [comment]
Hm.. I am not sure what you mean is wrong?
Are you sure your mail-credentials where set correctly?

**Comment by shinnlu** [comment]
i mean the code not return real error message, it return success whatever it success or fail.

**Comment by rappasoft** [comment]
Fixed in the upcoming release.
