### ISSUE TITLE
Current Status

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-5-boilerplate#399]
I've obviously have had trouble finding time to work on this project, which sucks because I really enjoy this project. 

My plan is to scrap v3 for now, and take all the work i've done and implement it in v2.

I'll probably make a legacy branch like I did for 5.1, because I plan on removing the CRUD screens for permission management, since there is no real world use for it, and instead just use a seed file for managing that.

I recently used the access part for a different project and it works well without it, theres never a need to update permission names on the go since they are hard coded into the backed code. Users/Roles management will remain the same.

I also had a lot of bug fixes in v3 I found, which i'll implement.

I believe I will need this boilerplate for a new project of my own soon, so I will have time to work on it in preparation for that.

Stay tuned and thanks for the ongoing support!

**Comment by poseso** [comment]
Thanks for this great project! I look forward to see those bug fixes and changes.. :)

**Comment by rappasoft** [comment]
Development branch is stable with the removal of permissions/dependencies views and functionality. So many classes and files removed, yet the same result and less to manage.

**Comment by rappasoft** [comment]
Also added a session timeout middleware that when enabled and given a value will auto log the user out after x seconds in inactivity.

**Comment by rappasoft** [comment]
Gonna literally go through every single line of code and clean it up as perfectly as I can, and throw in a few more surprise features before I release it and make it the new master. Stay tuned.

**Comment by rappasoft** [comment]
![screencapture-l5boilerplate-dev-admin-access-users-1467434156446](https://cloud.githubusercontent.com/assets/6026504/16538252/fc520b14-3fec-11e6-9694-6ccd0d32414b.png)

Datatables are here.

**Comment by shinnlu** [comment]
seems permission are hide somewhere

**Comment by rappasoft** [comment]
Permission management is gone. Only in seeders now.

Theres no reason to make permissions on the fly because they need to be hard coded at runtime to do anything. So now you just keep track easily in the seeder.

App still lets you attach them to roles and such.

**Comment by rappasoft** [comment]
I've made a modular history class that lets you log anything you want with a simple API:

![screencapture-l5boilerplate-dev-admin-access-users-1467736961733](https://cloud.githubusercontent.com/assets/6026504/16592303/0fd3e77a-42ae-11e6-80fb-c84cf23b9756.png)

All default functionality will come out of the box as an example.

**Comment by rappasoft** [comment]
Currently controlled with an event subscriber class per model to keep it neat, but you'll be able to call the global history() helper anywhere to log whatever you want.

**Comment by digitalit** [comment]
When to you think the dev version is ok to upgrade to? 
All my created permissions in my db wont be affected by the removal of the "on the fly part" regarding permissions they will work as they do now right?

**Comment by rappasoft** [comment]
They won't but I wasn't planning on people to upgrade to this version, it's a massive overhaul, but if you want to spend the time it shouldn't effect anything, there might be one or two database changes but the migrations shouldn't break what's there.

The permission stuff as of now is pretty solid, i'm just adding new features.

**Comment by digitalit** [comment]
ok, so you recommend waiting with updating the BP?

**Comment by rappasoft** [comment]
It would be wise, it's going to take you a long time if you want to go that route. It shouldn't be much longer before I release it as is because i'm running out of time to work on it before my new projects start again.

**Comment by digitalit** [comment]
ok, thank you so much. Still haven't found any project even close to yours :)

**Comment by rappasoft** [comment]
Thats good! I use this for the starting point of all of my projects. I'm adding features like history that I know I implement on all of my projects.

**Comment by arrakeen** [comment]
Any chance to add a "log-in as" button in the back-end so admins can use users accounts without knowing their credentials?

**Comment by rappasoft** [comment]
Like in spark? So you can see it as the user sees?

**Comment by arrakeen** [comment]
Yep exactly!

**Comment by arrakeen** [comment]
Did that on another project, I used the sessions to achieve it.

**Comment by rappasoft** [comment]
Example?

**Comment by arrakeen** [comment]
I don't have the code close but I did something like:

By pushing a button, the admin throws the following methods:

`$request->session()->put('admin_userid', $user->id); // current user id
Auth::loginUsingId($newuser->id); //targeted user id`

And then we can display a floating button anywhere on the UI (frontend/backend) if the session exists:

`if (session()->has('admin_userid')) { **You are logged in as $user->id, get back to your admin account:** } // that gets the admin back to his account `

And if the admin wants to go back to his own account:
`Auth::loginUsingId($request->session()->get('admin_userid'));`

And then we destroy the saved session:

`$request->session()->forget('admin_userid')`

This could be useful for testing purpose or debugging in some cases.

**Comment by rappasoft** [comment]
![screencapture-l5boilerplate-dev-1467752392879](https://cloud.githubusercontent.com/assets/6026504/16599765/e91df8a4-42d1-11e6-9e5e-5cdee3c045fd.png)

**Comment by rappasoft** [comment]
@arrakeen can you see if this looks pretty solid: https://github.com/rappasoft/laravel-5-boilerplate/commit/d6dc33f0ab994752a4f7028d935e37c7f223bf61

**Comment by arrakeen** [comment]
@rappasoft Yep! Users should probably create and attach a role to this functionality to make it even more solid.

**Comment by rappasoft** [comment]
It is, you need the manage-roles permission to hit the loginAs route.

**Comment by rappasoft** [comment]
If anyone has a chance can they download and install the development branch and let me know what you think, play around, find bugs, etc.

Thanks!

**Comment by ninjaparade** [comment]
@rappasoft that's awesome!

While you're in there, something I've added a few times and think it would be a good to have for `frontend\auth\events` is a `UserConfirmedAccount` event/event handler.

I also was wondering about the login/logout events, do you tend to add more data to those events other than just the user object being passed? as of https://github.com/laravel/framework/pull/13704 the built in Session in Laravel dispatches these events already and now they can be queued.

Just curious your thoughts?

**Comment by rappasoft** [comment]
Sure here: https://github.com/rappasoft/laravel-5-boilerplate/commit/8b6e761fe5da8a8f4e61487c66bb24fbfbccf1b1

**Comment by ninjaparade** [comment]
@rappasoft ya me either. You could just bind the `\App\Listeners\Frontend\Auth\UserLoggedInListener` and `\App\Listeners\Frontend\Auth\UserLoggedOutListener` to the Session events.

`Illuminate\Auth\Events\Login` and `Illuminate\Auth\Events\Logout` and keep deleting code from your repo 💃

**Comment by rappasoft** [comment]
Here's the current change/feature list:

- Removed fluff code in backend/includes/header, see adminlte documentation for markup.
- Added member since timestamp to backend user popup.
- Added user roles list to backend user popup.
- Removed roles.web_developer translation line as it is no longer needed.
- Removed the button in the lower left of backend user popup and replaced with home button.
- Moved home translation from navs.frontend.home to navs.general.home.
- Deleted navs.backend.button translation as no longer needed.
- Replaced all instances of trans(‘nav.frontend.home’) to trans(‘nav.general.home’)
- Replaced all html links with link helper methods in backend/includes/header.php
- Used correct blade syntax where necessary in backend/includes/header.php
- Corrected blade syntax in change, email, reset, login, register.blade.php
- Added guest() method to access class
- Added logout() method to access class
- Corrected blade syntax in frontend nav and converted html links to link helper methods.
- Corrected blade syntax in profile/edit.blade.php, user/dashboard.blade.php, macros.blade.php, ga.blade.php, lang.blade.php
- Converted html links to link helper methods in user/dashboard.blade.php
- Corrected blade syntax in messages.blade.php and used session() helper instead of facade.
- Added margin/padding helpers.
- Fixed blade syntax and added link helpers on access header buttons and group create/edit.
- Fixed forgot password email translation
- Removed permission/dependency/groups management in its entirety
- Added session timeout middleware preset to 10 minutes.
- Many small cleanups
- Converted all uses of {!! !!} to {{ }} where applicable for security reasons.
- Replaced html label/checkbox/submit items with form facade versions.
- Removed any inline styles for external versions.
- Turned on debugbar query tracer so you can attempt to tell where each query originates.
- Check for mail failures when sending confirmation email from backend and display to user.
- Added datatables jquery plugin and replaced default index for users/roles with searchable/filterable datatables.
- Added suggested sort number when creating a new role.
- Modular history class that lets you log any activity to one table and show globally, by type, or by entity. Supports multiple links via array. Trans links stored in database and converted when displayed using history.php lang files.
- Added “Login As” feature for admins to login as whatever user they please for whatever the reason may be.
- Fixed social users with no email by making one with the name and provider.
- Added user confirmed event.
- Remove delete user/deactivate button for self.
- Remove system property from permissions as its no longer needed.
- Changed all guarded properties to fillable as they have been studied to be better for use.

**Comment by rappasoft** [comment]
I think i've changed enough thus far to govern a 3.0 tag at this point anyway. I'm going to go through all the functionality, make new screenshots, update wiki, hopefully tomorrow.

**Comment by pe3udent** [comment]
@rappasoft awesome project! thanks for it.

I 've found a bug: datatable's search starts every time on key press. It may be better to add a timeout?

**Comment by pe3udent** [comment]
Sorry, my fault [https://datatables.net/reference/option/searchDelay](https://datatables.net/reference/option/searchDelay)

**Comment by blomdahldaniel** [comment]
@rappasoft you'r the man!

**Comment by rappasoft** [comment]
<img width="940" alt="screen shot 2016-07-06 at 12 04 06 pm" src="https://cloud.githubusercontent.com/assets/6026504/16625303/cbe280ac-4371-11e6-92ac-a3895aac21fc.png">

Soon..

**Comment by rappasoft** [comment]
Released! Thanks for the help guys. Screenshots and wiki updated. Just have to write the docs on the new history facade.

Find and submit bugs as normal now.

**Comment by dylanharbour** [comment]
Well done! Keen to play with it! 

Thanks for all the hard work!

**Comment by rappasoft** [comment]
Here are the history docs: https://github.com/rappasoft/laravel-5-boilerplate/wiki/14.-History-Management

**Comment by minaung7** [comment]
Hi,Excuse me sir,May i know something.I'm using laravel boilerplate.Laravel boilerplate had contained the language setting for backend so i can change the language easily but i don't know how to change the language for my frontend web page.so please sir,Could you explain me how to do it cause i'm a new laravel beginner?Respect to Senior elder brother.So please.......
