### ISSUE TITLE
Permitted to enter admin section from Default User

### ISSUE THREAD

**Issue by gaurav112** [rappasoft/laravel-5-boilerplate#40]
I was testing the Access functionality for the Default User and found out that i was able to access the admin section even though I was logged in through the Default User generated from the DB Seed

I eventually found the problem, So thought should share:

RouteNeedsRoleOrPermission.php

From
```
if ($assets['needsAll'])
			if (! access()->hasRoles($assets['roles'], true) || ! access()->canMultiple($assets['permissions'], true))
				return $this->getRedirectMethodAndGo($request, $params);
		else
			if (! access()->hasRoles($assets['roles'], false) && ! access()->canMultiple($assets['permissions'], false))
				return $this->getRedirectMethodAndGo($request, $params);
```

TO

```
if ($assets['needsAll']) {
            if (!access()->hasRoles($assets['roles'], true) || !access()->canMultiple($assets['permissions'], true)){
                return $this->getRedirectMethodAndGo($request, $params);
            }
        }else {
            if (!access()->hasRoles($assets['roles'], false) && !access()->canMultiple($assets['permissions'], false)){
                return $this->getRedirectMethodAndGo($request, $params);
            }
        }
```

I had issues with the conditions bracket.

**Comment by rappasoft** [comment]
Thanks much I'll change this. Also, would you be willing to share a test or two? That's what this project lacks the most. It would be greatly appreciated.

**Comment by gaurav112** [comment]
I don't actually do any unit testing. But I am currently using your boilerplate in one of my project. And as I keep getting issues, will keep posting.
Appreciate your work though.

**Comment by rappasoft** [comment]
Appreciate it.
