### ISSUE TITLE
Graph Database (neo4j)

### ISSUE THREAD

**Issue by airbase9018** [rappasoft/laravel-5-boilerplate#400]
Hi Guys

Just want to check if we can use neo4j for our database instead of using mysql? I will be trying to test neo4j (using a package, NeoEloquent) and laravel (base code).

Hope we can also easily integrate neo4j with this boilerplate.

:)

**Comment by rappasoft** [comment]
Never heard of or used it, but looking at NeoEloquent that's probably the way you want to go.
