### ISSUE TITLE
Suggestion add-ons

### ISSUE THREAD

**Issue by digitalit** [rappasoft/laravel-5-boilerplate#402]
I know that this project is focused on the basic stuff only but wouldn't it be great to have some add-ons that go beyond the basic BP since there is an specific structure to follow?

**Comment by rappasoft** [comment]
If I knew how to build it more like a Wordpress type CMS, I'd wish to have a setup where we can make other plugins and themes and just drop them into a folder. But I don't have experience with that.

That being said we do have the suggested plugins page of the wiki.
