### ISSUE TITLE
I want to add Chinese language pack, how should I add?

### ISSUE THREAD

**Issue by eleven0220** [rappasoft/laravel-5-boilerplate#403]
I want to add Chinese language pack, how should I add?

**Comment by rappasoft** [comment]
Wait until the next release which is the next few days, because many things have changed.

**Comment by rappasoft** [comment]
You can follow these instructions: https://github.com/rappasoft/laravel-5-boilerplate/wiki/9.-Localization

**Comment by krishnaguragain** [comment]
I am using this http://iridadesign.com/starter-public-edition-4/www/
for some small projects and it is rich in seo because of its seo friendly url.

**Comment by topegret** [comment]
@eleven0220 do you have Chinese lanaguage pack for this project yet? thanks!
