### ISSUE TITLE
Login route does not work

### ISSUE THREAD

**Issue by Shuyinsama** [rappasoft/laravel-5-boilerplate#404]
I'm sorry if this is not application specific. I'm not sure where to ask/search anymore.

After a couple of weeks developing locally I wanted to put this project on a development server.
I have just set up a new VPS with Ubuntu/LAMP etc.

So far it looks like most things work except for the page after you enter login credentials and hit submit.
The return page gives me a 500 error page. Now I am sure this has something to do with either wrong .htaccess setup or anything but I am kind of lost here.

I hope this info is enough but thanks in advance anyway.

**Comment by blomdahldaniel** [comment]
Do you have a .env file and done `php aritsan key:generate` on the serverside?
Installed the composer dependencies?

**Comment by Shuyinsama** [comment]
I have and I did yes.
Basically when I click on login it goes to the Login page.
I enter my email and password and click submit, The url stays the same but the page gives me a 500 error page (from chrome itself)

**Comment by poseso** [comment]
did you checked the files/folders permissions ?  might be a permission problem

**Comment by Shuyinsama** [comment]
@poseso yes thank you I did set the permissions at one point but apparently not all files were owned by the same group so it had some permission errors. thanks I'll close this now
