### ISSUE TITLE
New Controller

### ISSUE THREAD

**Issue by wasiqaftab** [rappasoft/laravel-5-boilerplate#407]
Hello 

i try to add controller using php strome but its not working . taking backend route path wrongly . but when i use artisan command it will work. any idea why its doing like that.

`[ReflectionException]                                                              
  Class App\Http\Controllers\Backend\Backend\Packages\TestController does not exist`

@rappasoft can you please guide

**Comment by poseso** [comment]
Backend\Backend ?shouldn't that be App\Http\Controllers\Backend\Packages\TestController ?

**Comment by wasiqaftab** [comment]
@poseso yes this is what i thought but some how i dont have any idea why its take backend 2 time

**Comment by poseso** [comment]
How did you tried to add the controller ?

**Comment by rappasoft** [comment]
I think you're missing the App in the namespace.

**Comment by wasiqaftab** [comment]
Ahh my bad yes i do it works now .. 
Cheers :)
