### ISSUE TITLE
3.1 Update - Please read

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-5-boilerplate#409]
As of 3.1, I have implemented route model bindings for any backend routes where applicable. 

https://github.com/rappasoft/laravel-5-boilerplate/commit/fca8c940636c24af460b8e98eab2b357e025d1a3

https://github.com/rappasoft/laravel-5-boilerplate/wiki/6.-Changelog

I advise you to read up on the docs so you understand how the flow of information now works.

https://laravel.com/docs/5.2/routing#route-model-binding

Basically, the slug in the route i.e. user/{user} combined with the injected model in the controller method, will match the model and find the resource by the URI segment and return it.

So this means in your repositories or whatnot, you no longer have to do User::find($id), because it's done  beforehand so it's available immediately in your controller method.

Look at the backend User/Role controllers for examples.

Also had to convert all routes to not be plural, because using route resource uses the singular version as the slug and I didn't want to do it the sloppy way. 

Since it's such a big change in the API i've dubbed this 3.1

**Comment by shinnlu** [comment]
i just update to 3.1, as we talked before in [Current Status](https://github.com/rappasoft/laravel-5-boilerplate/issues/399) the permissions is gone, but i can't find the seeder you said.
how to list user's permissions like previous version?
how to add permission to user, i can't find document about writing those related function.

**Comment by rappasoft** [comment]
There are no more user specific permissions.

I went along with the norm of every other CMS (wordpress, magento, joomla, etc)

You create permissions and attach them to roles, then attach roles to users.

**Comment by shinnlu** [comment]
permission list is required to review current setting.
after removed , i can only guess what permission has created.
where i can find the create permissions and attach roles code document?

**Comment by rappasoft** [comment]
I don't understand?

**Comment by shinnlu** [comment]
Sorry for my english.
I can double check permissions settings in group list in previous version, and check how many permission i created in permissions list too.

**Comment by poseso** [comment]
How do you manage permissions for example if you have a module  and want to give the user permissions just to   Create and View but not Delete or Edit, how is it managed crud permissions?

**Comment by rappasoft** [comment]
I removed that functionality in v3 for a simpler user has roles method.

**Comment by poseso** [comment]
in v3 there is no way to manage crud separetely?

**Comment by rappasoft** [comment]
Think about it, there's no reason to be editing permissions on the go, the application needs them all to run. And its a bad idea in case someone accidentally gets access they delete permissions and now all of a sudden your app is screwed.

So as you build your app you append to your PermissionSeeder and reseed as you deploy.

**Comment by poseso** [comment]
You are right, makes perfect sense.
