### ISSUE TITLE
Issue with Facebook Login

### ISSUE THREAD

**Issue by jmenendezlih** [rappasoft/laravel-5-boilerplate#41]
I was create a app and adding ids to .env.
When I try to log in with facebook, I cant an show me a error.
![screen shot 2015-07-10 at 3 55 24 pm](https://cloud.githubusercontent.com/assets/12663325/8627935/94dcdac0-271c-11e5-80e8-983064c22736.png)

**Comment by rappasoft** [comment]
Ok I will look into this. Socialite is the biggest issue with this project.

**Comment by jmenendezlih** [comment]
I resolve make  a composer update, repository in the proyect is fixed when update. Thanks @rappasoft  for your work.
