### ISSUE TITLE
500 error because of localization

### ISSUE THREAD

**Issue by sagark1510** [rappasoft/laravel-5-boilerplate#412]
Hi,

I have installed fresh laravel-5-boilerplate release 3.1.1 and followed installation guide. After installation and all steps executed successfully I got 500 error while running application on browser and it specifically stops executing after Language drop down where trans function is used in foreach loop. 

If I set config->locale->status = false homepage starts working but all other pages give maximum function nesting level error. 

Can anybody suggest what might be the possible solution and moreover am I missing any configuration in .env file or something?

Please find below images for the reference. 

![status false](https://cloud.githubusercontent.com/assets/2134076/16763167/54c68dfa-4845-11e6-8d5c-88acb0fa2dca.png)

Status false homescreen looks good.

![status true](https://cloud.githubusercontent.com/assets/2134076/16763169/54cbfcea-4845-11e6-8720-34794da6b24e.png)

Status true homescreen breaks from langauge dropdown.

![status false login](https://cloud.githubusercontent.com/assets/2134076/16763168/54cbc90a-4845-11e6-8a05-814ee4450f13.png)

Status false login page exception.

**Comment by rappasoft** [comment]
do a ```php artisan clear-compiled```

Try one of these other issues that were solved with the same problem:

https://github.com/rappasoft/laravel-5-boilerplate/issues?utf8=%E2%9C%93&q=Maximum%20function
