### ISSUE TITLE
No access for admin from routes

### ISSUE THREAD

**Issue by harlet** [rappasoft/laravel-5-boilerplate#413]
Hi,

I have in the middlewareGroups :
 `'client' => [
            'web',
            'auth',
            'access.routeNeedsRole:Client',
  ],`

Administrator Role has no access there... how can i make him have access?

**Comment by rappasoft** [comment]
This is missing from that method. Edit your UserAccess.php file and change hasRole to:

```
public function hasRole($nameOrId)
    {
    foreach ($this->roles as $role) {
        //See if role has all permissions
        if ($role->all) {
            return true;
        }
        
        //First check to see if it's an ID
        if (is_numeric($nameOrId)) {
            if ($role->id == $nameOrId) {
                return true;
            }
        }

        //Otherwise check by name
        if ($role->name == $nameOrId) {
            return true;
        }
    }

    return false;
}
```

**Comment by rappasoft** [comment]
Fixed this and added more functionality: https://github.com/rappasoft/laravel-5-boilerplate/commit/ce916c760a26fca1838da68f92b1e35c273b065c
