### ISSUE TITLE
[Enhancement] New frontend using AdminLTE

### ISSUE THREAD

**Issue by danswiser** [rappasoft/laravel-5-boilerplate#419]
@rappasoft and other contributors,

Does anyone have any objections to also using AdminLTE as the frontend UI? When I see the [top-nav layout from AdminLTE](https://almsaeedstudio.com/themes/AdminLTE/pages/layout/top-nav.html), it looks like a much cleaner and uniform UI given that we're already using AdminLTE for the backend.

I know a lot of people may just completely replace the frontend UI, however I like the idea and might end up using it myself.

I'm still a novice but I'm interested in other people's opinions and will submit a pull request when I finish.

**Comment by rappasoft** [comment]
My reasoning behind not doing this, and leaving it as bare-bones as possible, is I know 9.9/10 people are going to swap all of that frontend stuff out for a custom made website.

The frontend of these apps are most likely the selling point, customer facing, so it's going to be "salesy" and not admin looking.

So the less people have to delete the easier it will be.

That's my reasoning, though that does look nice, I think it would be more work for people.

**Comment by codydh** [comment]
I'll throw a vote in the opposite side. While many sites will replace the default, some will not (especially for basic tools/internal use), so I think having a consistent interface for front and backend would be very welcomed!

**Comment by jeremymolina** [comment]
I really like AdminLTE but it is a very difficult theme to set-up and remove, so for beginners remove it will be a paint.
