### ISSUE TITLE
Stripe

### ISSUE THREAD

**Issue by LunarDevelopment** [rappasoft/laravel-5-boilerplate#422]
Hey, This is an old Q&A and I've noticed that the billing Service is no longer in the project, is there a way to use stripe in the boilerplate that I'm missing or do I need to integrate cashier from scratch?

**Comment by rappasoft** [comment]
You can use cashier if you want, those stripe classes were pre-cashier, which is why they were eventually removed. They may still work but I think stripe came out with an updated API recently so I can't be sure.

**Comment by LunarDevelopment** [comment]
Thanks for the clarification, I'll implement cashier then.

I didn't want to write code someone had already done better, hohoho.
