### ISSUE TITLE
Socialite Redirect

### ISSUE THREAD

**Issue by LunarDevelopment** [rappasoft/laravel-5-boilerplate#423]
Hello! 

Amazing project, I'm enjoying it a lot. 

I'm having trouble with twitter log ins however, I click log in with twitter then I get redirected to my TWITTER_REDIRECT from .env however I think I'm wrong in having it set as: 
``` 
TWITTER_REDIRECT=http://127.0.0.1:8000/
``` 
I can't find the route in the app which it should be to make use of the ?oauth= token etc that is appended after the twitter log in.

**Comment by LunarDevelopment** [comment]
Anyone else moronic enough to have this same issue, my redirect URL needed to be like so: 
```
TWITTER_REDIRECT=http://127.0.0.1:8000/login/twitter
```
Where /twitter is whatever provider you're configuring. It just took the patience to read what the code was doing in App\Services\Access\Traits UseSocialite.php

**Comment by rappasoft** [comment]
This should be in the wiki docs as well. 

Anthony Rappa
