### ISSUE TITLE
Session time out and "remember me"?

### ISSUE THREAD

**Issue by clin407** [rappasoft/laravel-5-boilerplate#424]
I'm looking at the session timeout and noticed it doesn't seem to respect the remember me checkbox when logging in.  Is it possible to make it so when remember me is checked that it would ignore the session timeout?

**Comment by rappasoft** [comment]
I feel like it wouldn't respect the remember me if it's on because the whole point of it was for security. The remember me would still work for frontend users because by default it's only added to the admin middleware, which is not where you want people accidentally wandering in.
