### ISSUE TITLE
Cannot find permission controller in latest version

### ISSUE THREAD

**Issue by naysumyat** [rappasoft/laravel-5-boilerplate#425]
Hi,
I have been using roles and permissions controller in older versions of laravel-5-boilerplate. I cannot find it anymore in latest version.is it removed for some reason ?

**Comment by rappasoft** [comment]
That's because it doesn't exist as managing permission via UI has been removed.

**Comment by error500** [comment]
Permissions should be added with artisan tinker ?

` php artisan tinker
Psy Shell v0.7.2 (PHP 5.6.15 ÔÇö cli) by Justin Hileman
> $permission = new App\Models\Access\Permission\Permission
=> App\Models\Access\Permission\Permission
> $permission->name="foo"
=>foo
> $permission->display_name="bar"
=>bar
> $permission->save()
`
