### ISSUE TITLE
Permision on user

### ISSUE THREAD

**Issue by ahtun** [rappasoft/laravel-5-boilerplate#427]
Hi all,
How I can add permissions to user, not to group ? And check access on permission.
Please help me.

**Comment by rappasoft** [comment]
That functionality has been removed in the new version in replacement for a simpler access. You can make a role specific for a user with one permission if you need, and assign multiple roles to the user.

**Comment by ahtun** [comment]
Maybe I can restore that functionality for me. In which version I Can find that code ?

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/releases/tag/2.3.12

**Comment by thaonguyen90** [comment]
I see there are 3 default permissions, but no additional permissions functionality

**Comment by rappasoft** [comment]
The 3 default permissions are attached to the default roles. https://github.com/rappasoft/laravel-5-boilerplate/blob/master/database/seeds/Access/PermissionRoleSeeder.php

Administrator has all by default and you don't have to specify.

**Comment by thaonguyen90** [comment]
So now I only assign roles to the user as a permissions. :)  :)

**Comment by rappasoft** [comment]
Roles are just groups of permissions, so a role with 1 permissions is essentially the same thing.

**Comment by thaonguyen90** [comment]
so a role with 1 permissions is essentially the same thing.

===> Why, when I add the required 1 selected file permissions. example Permissions management modules, I add roles Blog (view blog).
