### ISSUE TITLE
 throw new NotFoundHttpException;

### ISSUE THREAD

**Issue by mikimaine** [rappasoft/laravel-5-boilerplate#429]
In the users page it sometimes throw 
` throw new NotFoundHttpException; `

and it will show no users? please help! the previous version doesn't do this things!

**Comment by mikimaine** [comment]
![capture](https://cloud.githubusercontent.com/assets/10907808/17049523/7737cf4e-4ff6-11e6-8727-54b8a28c46b9.PNG)

**Comment by mikimaine** [comment]
![asd](https://cloud.githubusercontent.com/assets/10907808/17052458/3579999c-5006-11e6-950f-6689c5b69dd0.PNG)

**Comment by rappasoft** [comment]
Closing because duplicate of: https://github.com/rappasoft/laravel-5-boilerplate/issues/441
