### ISSUE TITLE
Laravel Boilerplate Installer v1

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-5-boilerplate#431]
Hey guys,

I've created a [command line installer](https://github.com/rappasoft/laravel-boilerplate-installer) to run all of the stuff for you instead of having to do it manually. I have it working on Laravel Homestead but haven't tested on MAMP/XAAMP so don't be surprised if it doesn't work in its first release.

I just installed a fresh version using the installer and it took about 3 minutes (npm install takes forever).

It takes you through the following steps:

- Download
- Composer Install
- Copy the .env file
- Generate the Key
- NPM Install
- Running Gulp
- Set the Namespace
- Connect to the Database
- Set the Administrator Account
- Seed the Database

It gives you a global ```boilerplate new``` command so you can install where ever. 

Hope this speeds up your development even more!

**Comment by blomdahldaniel** [comment]
This is awesome!
