### ISSUE TITLE
Error when logging out while logged in as somebody else

### ISSUE THREAD

**Issue by vernard** [rappasoft/laravel-5-boilerplate#434]
Try it.

1. Log in as administrator.
2. Log in as the backend user.
3. Log out. (Not Re-Login as X. Just Log out like a normal user would.)
4. Surprise!

I've tried to fix it myself but I can't come up with an appropriate fix (or a fix you think that is acceptable). It might come out as obstrusive on the feature so I'll just report it to you.

Just blocking the error message by changing the first line from file `resources\views\includes\partials\logged-in-as.blade.php`
````
@if (session()->has("admin_user_id") && session()->has("temp_user_id"))
````
to this line
````
@if (access()->user() && session()->has("admin_user_id") && session()->has("temp_user_id"))
````

won't work. Since when I log in, there are still leftovers from the temp session data.

I think the login as feature should make use of the events (log in and log out events) instead of being tightly coupled with `UserRepositoryContract`. What do you think?

**Comment by rappasoft** [comment]
I'll take as look as soon as I can, it will probably stay where it is now only because I don't have much time, but I'm sure it could be better since it was a last minute feature.

**Comment by rappasoft** [comment]
Dirty fix until I have time to refactor and rethink it: https://github.com/rappasoft/laravel-5-boilerplate/commit/2acb3f6b2b62ac1e528fb19167aef8e3f3247f01
