### ISSUE TITLE
Implicit route binding for User

### ISSUE THREAD

**Issue by vernard** [rappasoft/laravel-5-boilerplate#438]
Hi.

As implemented in 3.1 #409

Routes for `user/{user}` will work if you used ID. If you wanted to use another column, let's say `username`. 

According to [laravel docs](https://laravel.com/docs/5.2/routing#route-model-binding),
you will have to override the method `getRouteKeyName` and return `username` in this case.

But in this boilerplate, that won't work because of this line from the `App\Providers\RouteServiceProvider`.
````
/**
 * This allows us to use the Route Model Binding with SoftDeletes on
 * On a model by model basis
 */
$router->bind('user', function($value) {
    return User::withTrashed()->where('id', $value)->first();
});
````

I don't understand while this line exists. Adding a condition to your model to display soft deletes is case to case basis and should not happen by default.

What are your thoughts?

**Comment by rappasoft** [comment]
It's there because some of the functionality in the admin section will fail since it will try to find a user that is already deleted. I don't know any other way around it.

**Comment by vernard** [comment]
Then I believe this binding needs to be explicit on that controller.

Which functionality exactly?

**Comment by rappasoft** [comment]
Where it needs to grab a deleted user to restore or destroy.

**Comment by vernard** [comment]
I tested it on my PR and it is still working. Deleted users cannot be edited, so that's fine.

**Comment by rappasoft** [comment]
No but in order to be restored or destroyed they still need to be "found", hence the "withTrashed"

**Comment by vernard** [comment]
Did you test it?

**Comment by rappasoft** [comment]
I did I was getting an error, I found that snippet of code on the laravel forums.

**Comment by rappasoft** [comment]
Here it is on SO: http://stackoverflow.com/questions/19445615/route-model-binding-and-soft-deletes-laravel-4

**Comment by vernard** [comment]
Sorry I was not versed with Laravel 4 so I didn't know this. Maybe it is different in the current Laravel version. 

Can you tell me how to replicate the exact issue in the master branch? I can delete/deactivate/reactivate a user without any issues.

**Comment by rappasoft** [comment]
It's not a specific L4 thing thats just the article I found. I'll try to get the exact error.

**Comment by rappasoft** [comment]
Replicate:

- Comment out that block.
- Delete user.
- Go to deleted users and hit restore.
- Get 404 error.

The route model binding can not find the user because that block tells it to search in the soft deleted users as well.

**Comment by vernard** [comment]
Updated my PR. I binded `deletedUser` when referencing a deleted user.

**Comment by rappasoft** [comment]
Had to tweak it but it's merged.
