### ISSUE TITLE
Gulp Configuration

### ISSUE THREAD

**Issue by jmenendezlih** [rappasoft/laravel-5-boilerplate#44]
In a GulpFile the destination of compile file is frontend.css, etc...
but when i compile or activate gulp watch the compiled is in app.css and link on my master.blades is to frontend.css.

Whats is wrong here?

**Comment by rappasoft** [comment]
I had issues with that at one point, changing the package.json to elixir 1.0 fixed it. I have it working on 2.0 now but I didn't change anything. I couldn't figure out if they changed the API or not.

**Comment by jmenendezlih** [comment]
ok thanks
