### ISSUE TITLE
There is a error message: Datatables warning, Users management dont load

### ISSUE THREAD

**Issue by cahucadi** [rappasoft/laravel-5-boilerplate#441]
![image](https://cloud.githubusercontent.com/assets/5466872/17255579/74f8bed0-557f-11e6-803c-9a0c67d95351.png)

There is a error message: Datatables warning . Table id=user-table - Ajax error

**Comment by ivan-grozni** [comment]
Having the same issue here.

They mention here that it may be an extra <th> https://github.com/yajra/laravel-datatables/issues/171 
 
or here that it might be a typo http://stackoverflow.com/questions/37980368/error-datatable-with-laravel-and-mysql-datatables-warning-table-id-example-a 

But still no luck

**Comment by rappasoft** [comment]
Cant' replicate

**Comment by ivan-grozni** [comment]
I'm thinking it might be a database error - it returns 401 Unauthorized for me. Also, any time I click anything on the Access Management tab, I am forced to log in again. Any thoughts on what mysql config could be wrong?

**Comment by ivan-grozni** [comment]
This actually might be the same as:

https://github.com/rappasoft/laravel-5-boilerplate/issues/429

**Comment by rappasoft** [comment]
I just installed a fresh install using the command line installer. I have no issues. I'm running on Homestead. What is everyones current environments?

**Comment by ivan-grozni** [comment]
Running Win10 with MySQL via Xampp. I did verify it is working in Firefox, but chrome is the only problematic browser

**Comment by rappasoft** [comment]
I don't know why that's happening for you guys. I tried homestead/MAMP, in every browser. With no issues. If you find the reason feel free to fix.

**Comment by poseso** [comment]
I'm using OSX 10.11.3 with Chrome 51.0.2704.106 (64-bit) and MAMP Pro 3.4, and I'm not having this issues

**Comment by cahucadi** [comment]
Hi,

If a remove 

                    {data: 'confirmed', name: 'confirmed'},
                    {data: 'roles', name: 'roles'},


from 

  $(function() {
            $('#users-table').DataTable({

It loads, but if I use any of those, the error message show up

**Comment by luismareze** [comment]
I am getting the the same error in here

**Comment by cahucadi** [comment]
Hi. I might sound crazy guys... but if you use only 5 fields in the datatable (no matter which ones), it works... I'm still trying to understand why and trying to fix it.

**Comment by mikimaine** [comment]
hey, this error is showing  because the server is  return 404 for the datatables GET request. 

![hxr](https://cloud.githubusercontent.com/assets/10907808/17582797/1e7a2882-5fb6-11e6-9750-65345f7cdf6d.PNG)

**Comment by jjasiunas** [comment]
I was consistently receiving a 401 Unauthorized response in Chrome and Firefox when running the app locally via php artisan serve. After changing the AJAX requests for the get, deactivated, and deleted options, I no longer receive a 401 error. I do, however, occasionally encounter a token mismatch error that causes the popup.

/app/Http/Routes/Backend/Access.php
```php
/**
 * For DataTables
 */
// Route::get('user/get', 'UserController@get')->name('admin.access.user.get');
Route::post('user/get', 'UserController@get')->name('admin.access.user.get');

/**
 * User Status'
 */
// Route::get('user/deactivated', 'UserController@deactivated')->name('admin.access.user.deactivated');
// Route::get('user/deleted', 'UserController@deleted')->name('admin.access.user.deleted');
Route::post('user/deactivated', 'UserController@deactivated')->name('admin.access.user.deactivated');
Route::post('user/deleted', 'UserController@deleted')->name('admin.access.user.deleted');
```

app/resources/views/backend/access/deactivated.blade.php
app/resources/views/backend/access/deleted.blade.php
app/resources/views/backend/access/index.blade.php

```javascript
ajax: {
    url: '{{ route("admin.access.user.get") }}',
    // type: 'get',
    type: 'post',
    data: {status: 0, trashed: false}
},
```

**Comment by jsiebach** [comment]
Ajax error means you have an error in your server, not the front end.  Please post what your laravel error log says to help troubleshoot

**Comment by mikimaine** [comment]
there is no laravel error log ..... even when i have enable debug mode

**Comment by cutemonster** [comment]
you can copy and paste your GET url on your browser to see if the data correctly generated.  I meant the url in datatable javascript in your view file.

**Comment by stephenahiggins** [comment]
Has anyone found a solution to this? 

I have it working locally fine (Mac OS, AMPPS, Mysql), however on a remote IIS server (Mysql, Windows, IIS) I get the error.

**Comment by stephenahiggins** [comment]
So, after much trial and error I found the reason for my problem. 

It seems that IIS  limits the length of a URL string causing a 404. 

The workaround I found was to add the following to the web.config file of the IIS server: 
`<system.webServer>
  <security>
    <requestFiltering>
      <requestLimits maxQueryString="xxxx"/>
    </requestFiltering>
  </security>
</system.webServer>`

I wonder if the issue is something to do with Windows itself. I don't use Apache on Windows, so I can't say, but perhaps it is a filesystem setting?

**Comment by rappasoft** [comment]
Good find @stephenahiggins, I wonder if that's why everyone is having this problem.

**Comment by bab55z** [comment]
no solution yet ?

**Comment by rappasoft** [comment]
I've yet to be able to replicate the problem so I can't help.

**Comment by Deadalusmask** [comment]
change the method to post  in ajax and routes solved the problem.

**Comment by bab55z** [comment]
@rappasoft i installed it using
-Windows 10
-fresh WampServer 3.0.4 64 bit with default configs
-always using `php artisan serve` to serve app
maybe it can help reproduce it

**Comment by bab55z** [comment]
i checked the request sent to the server and i noticed the probleme is somming fromm the last parameter in the get request. when i remove that parameter i get a successfull result.

**sample request**
`http://localhost:8000/admin/access/user/get?draw=1&columns[0][data]=id&columns[0][name]=id&columns[0][searchable]=true&columns[0][orderable]=true&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=name&columns[1][name]=name&columns[1][searchable]=true&columns[1][orderable]=true&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=email&columns[2][name]=email&columns[2][searchable]=true&columns[2][orderable]=true&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=confirmed&columns[3][name]=confirmed&columns[3][searchable]=true&columns[3][orderable]=true&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=roles&columns[4][name]=roles&columns[4][searchable]=true&columns[4][orderable]=true&columns[4][search][value]=&columns[4][search][regex]=false&columns[5][data]=created_at&columns[5][name]=created_at&columns[5][searchable]=true&columns[5][orderable]=true&columns[5][search][value]=&columns[5][search][regex]=false&columns[6][data]=updated_at&columns[6][name]=updated_at&columns[6][searchable]=true&columns[6][orderable]=true&columns[6][search][value]=&columns[6][search][regex]=false&columns[7][data]=actions&columns[7][name]=actions&columns[7][searchable]=true&columns[7][orderable]=true&columns[7][search][value]=&columns[7][search][regex]=false&order[0][column]=0&order[0][dir]=asc&start=0&length=10&search[value]=&search[regex]=false&status=1&trashed=false&_=1476546066323`

**problematic parameter**
notice the last one  `...trashed=false`**&_=1476546066323**

**Comment by albertonieto** [comment]
I am running XAMPP (Apache 2.4.23, MariaDB 10.1.16, PHP 7.0.9) on a W8.1 with Google Chrome and I get the error sometimes. Some other times I just refresh the page and the data is there with no errors.

I hope that will help!

**Comment by rappasoft** [comment]
@Deadalusmask I believe has the correct answer.

See the patch in v4 here: https://github.com/rappasoft/laravel-5-boilerplate/commit/a654fba4ac830a293758002f99ac7fa15f8657e2

The code won't match up to what everyone has now but you'll get the idea.

I think this will be the final fix. Also, table loading is much faster because of it.

**Comment by bab55z** [comment]
@rappasoft i just tried this but i get "invalid JSON" now and no way to fix that.

**Comment by rappasoft** [comment]
It works fine for me both ways, are all of you that are getting errors not using Homestead?

**Comment by poseso** [comment]
it also works for me both ways i am not using homestead

**Comment by bab55z** [comment]
i am not using Homestead. I already have many projects running fine with my Wampserver 64bit stack including laravel based.

**Comment by blomdahldaniel** [comment]
Mamp on macOS works fine as well.

**Comment by rappasoft** [comment]
I think there is some sort of weird specific common denominator on the machines that its happening on but I have no idea what because I cant replicate.

**Comment by bab55z** [comment]
in the ajax query can someone tell where is the last query parameter from. the **_** parameter i mentioned it in one of my previous comments.

**Comment by vjaykoogu** [comment]
hey even i face this.. But on my MACbook this works fine... i think this is browser issue.. Try on IE

**Comment by luismareze** [comment]
is not a browser issue.
I am running in chrome and am getting too.

**Comment by stephenahiggins** [comment]
Can you paste your Apache config file?

**Comment by luismareze** [comment]
[httpd.txt](https://github.com/rappasoft/laravel-5-boilerplate/files/536886/httpd.txt)

**Comment by bab55z** [comment]
I changed the ajax call method to **post** but i get `invalid json` on **Chrome** and **Opera** but this fix works fine with **Firefox** . I used to use Opera and Chrome for dev but i'll switch this time to Firefox with the **Get to Post fix** until a final patch is pulled out.

And i thinks the problem could also be related to the browser engine as Chrome and Opera use the same **Chromium** engine.

My dev environnement is as this
-Windows 10
-fresh WampServer 3.0.4 64 bit with default configs

apache 2.4.18
PHP 5.6.19
MySQL 5.7.11
-always using php artisan serve to serve app

hope it helps.

**Comment by blomdahldaniel** [comment]
Wow! I just got the same problem!
When looking at exceptions in debuggbar I could follow the issue to  actually be a typo (that i had just made) in one of the locale-files. So it seems like the DataTables-error is blamed for mistakes elsewhere in the program..? Could that be the case here?

**Comment by rappasoft** [comment]
It could be possible, maybe we can search the error on google in conjunction with Laravel to see if we can find anything we didn't think of.

**Comment by rappasoft** [comment]
Can someone with these issues install a fresh release of 4.0.2 and tell me if you still have said issues, or if the other work we've done to the data tables fixed it randomly.

**Comment by defser** [comment]
4.0.2 fixes this issue!

**Comment by rappasoft** [comment]
Horray!

**Comment by poseso** [comment]
I don't know if it's just me, but this is what I did, I go to Access Management then on the search I type "user" without the quotes then hit backspace till everything is deleted and error appears

Request URL:http://localhost/BP5/public/admin/access/user/get
Request Method:POST
Status Code:500 Internal Server Error
Remote Address:[::1]:80


Same dialog as:

![74f8bed0-557f-11e6-803c-9a0c67d95351](https://cloud.githubusercontent.com/assets/4913152/19809631/1730fbe4-9cf8-11e6-96f0-fca42f95f3e8.png)

**Comment by blomdahldaniel** [comment]
Wow that sounds strange! I cannot replicate that. Browser thing again? Sounds quite weird?

**Comment by minedun6** [comment]
I suggest u use homestead as this was a reported bug wheb serving with
aerisan. If the error still persists then the problem is on your side.

Le ven. 28 oct. 2016 22:29, Daniel Blomdahl <notifications@github.com> a
écrit :

**Comment by poseso** [comment]
That was at work with Windows 10 + Wamp 3.0.4  now i'm gonna try to replicate in my home with OSX Sierra + MAMP Pro 3.5.2, keep you updated of any findings be back later

**Comment by poseso** [comment]
Hi guys, just to confirm that everything is working flawless i think theres something wrong with my pc at work, so please dismiss 💃

**Comment by alenija** [comment]
I have the same problem, while executes the query executes a logout, and i have bad response

**Comment by mukesh-chauhan** [comment]
i have same problem,when fatch the record in data table.
