### ISSUE TITLE
Cannot permantely delete user

### ISSUE THREAD

**Issue by poseso** [rappasoft/laravel-5-boilerplate#443]
I delete the user, then go to deleted users, then try to delete the deleted user and get this message:

![screen shot 2016-07-30 at 2 17 47 pm](https://cloud.githubusercontent.com/assets/4913152/17272289/aed15b3a-5660-11e6-8113-17456e30116b.png)

Any ideas of what might be wrong?

**Comment by poseso** [comment]
had to change app/Http/Routes/Backend/Access.php

removed Route::get('delete', 'UserController@delete')->name('admin.access.user.delete-permanently');  from * Specific User and put it on * Deleted User

now its working again

```
            Route::group(['prefix' => 'user/{deletedUser}'], function() {
                Route::get('delete', 'UserController@delete')->name('admin.access.user.delete-permanently');
                Route::get('restore', 'UserController@restore')->name('admin.access.user.restore');
            });
```

**Comment by rappasoft** [comment]
That's where it is: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Http/Routes/Backend/Access.php#L47

**Comment by rappasoft** [comment]
Don't know why yours wasn't.

**Comment by poseso** [comment]
weird, it wasn't in mine, well but at least it's now working correctly  hehe

**Comment by AlehDev** [comment]
Replase:

``
public function delete(User $user)
{
    //Failsafe
    if (is_null($user->deleted_at))
{
        throw new GeneralException("This user must be deleted first before it can be destroyed permanently.");
}
``
..
on:
``
public function delete(User $user)
{
    //Failsafe
    if ($user->trashed())
{
        throw new GeneralException("This user must be deleted first before it can be destroyed permanently.");
}
``
...
