### ISSUE TITLE
Question: Laravel 5.3

### ISSUE THREAD

**Issue by digitalit** [rappasoft/laravel-5-boilerplate#446]
How will Laravel 5.3 affect this project?

**Comment by tpharaoh** [comment]
Also, curious since 5.3 is using vue.js more will this boilerplate and others start to use it more

**Comment by rappasoft** [comment]
I have no idea. I'd have to start over and I don't think I have the time right now.

**Comment by brentkozjak** [comment]
Laravel 5.3 is simply suggesting Vue.js.  There's no reason that it would have to be included in this boilerplate.  Having said that, it looks like there's a fair amount of changes - https://laravel.com/docs/master/upgrade#upgrade-5.3.0

**Comment by rappasoft** [comment]
I would like to start fresh with it since I've been doing that. However I first have to learn all of the new stuff and see where I can incorporate it. Seems like there's changes to auth.

**Comment by digitalit** [comment]
Well, im Rappasold so i guess im going to stick with 5.2 until you make an 5.3 version of the BP :)

**Comment by tpharaoh** [comment]
5.3 should be backwards compatible.

Maybe you don't need changes?

**Comment by ninjaparade** [comment]
@tpharaoh that's not true, there is an upgrade process that's a couple hours that involves changing files, adding files, deleting files and pasting content into existing files etc.

also its a major version update, think OSX versions, Laravel (the framework) doesn't follow semver

**Comment by rappasoft** [comment]
I've decided to once again start from scratch from 5.3, but first I have to learn 5.3 as much as I know 5.2 to get all of the benefits out of the new features. Bare with me it will probably take a while.

I also want to get all the issues handled before hand.
