### ISSUE TITLE
sending email

### ISSUE THREAD

**Issue by jffsn** [rappasoft/laravel-5-boilerplate#448]
Hello my friends,

I'm with a problem in sending e-mail, I have two applications on my machine with the same e-mail configuration, one sends the email and the other does not send, but there is no error it just does not send.

Someone is with this problem?

Thank you

**Comment by rappasoft** [comment]
Wouldn't really be able to help without a log file. But i'm willing to bet its not the boilerplate itself and its an email configuration.

**Comment by jffsn** [comment]
Sorry, it was a configuration error lol

I'm really sorry

**Comment by rappasoft** [comment]
No problem.
