### ISSUE TITLE
get the right records based off roles?

### ISSUE THREAD

**Issue by clin407** [rappasoft/laravel-5-boilerplate#449]
Not sure if this is something this boilerplate has already but I wanted to see if there's a way to make it so certain roles has access to manage other people's records while others don't.

In my example, there's a manager and user role and a list of posts. For the manager, they should be able to manage everyone's post while the user can only manage their own. Previously, I just implemented a code similar to the below to get what I wanted. the canModify/canView methods basically compared to see if they had the correct roles and returned true if they did. Otherwise it would compare the user id on the post with the user's ID.

```
public function authorize()
    {
        switch ($this->method()) {
            case 'POST':
            {
                return true;
            }
            case 'GET':
            {
                if($this->route()->parameter('post'))
                {

                    if($this->is("*/edit") || $this->is("*/delete"))
                    {
                        return \Auth::user()->canModify($this->route()->parameter('post')->user_id);
                    }
                    return \Auth::user()->canView($this->route()->parameter('post')->user_id);
                }
                return true;
            }
            case 'PUT':
            case 'PATCH':
            case 'DELETE':
            {
                return \Auth::user()->canModify($this->route()->parameter('post')->user_id);
            }
            default:break;
        }
    }
```

does the boilerplate have something similar?

**Comment by rappasoft** [comment]
In the request authorize method I would do something like:

access()->hasRole("role") || access()->id() == Request::segment(2)

So either the user has the correct role or the currently logged in user is trying to edit their own stuff.

It would have to be a little more secure but you get the idea.

**Comment by clin407** [comment]
Yea, I haven't worked on it much but in my case, the ID in the segment wouldn't belong to the user ID (access()->id() should return user id right)? 

The logic for me would be more like

if role is either X,Y,Z OR if access()->id() == user_id in the current record.

**Comment by rappasoft** [comment]
Yeah that's how i would do it just make sure if the person changes the URL they don't get any unintended access.
