### ISSUE TITLE
Create new Role and Permission

### ISSUE THREAD

**Issue by nasirkhan** [rappasoft/laravel-5-boilerplate#45]
I want to create new Roles and Permissions. can you please extend a doc explaining this area?

**Comment by mrgwilliam** [comment]
From what I have seen in the system, you can add roles and permissions using the backend user management system. Under Roles and Permissions buttons. If you would like to preload them with your application, you will need to modify the Database Seeds with respect to RoleTableSeeder.php or UserTableSeeder.php

**Comment by rappasoft** [comment]
Yes exactly.
