### ISSUE TITLE
Call to a member function attachRole() on null  

### ISSUE THREAD

**Issue by thomasvanderbeek** [rappasoft/laravel-5-boilerplate#450]
When using a fresh install and following the instructions I get an error on the `php artisan db:seed` command:

Seeded: UserTableSeeder
Seeded: RoleTableSeeder
                                                           
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Call to a member function attachRole() on null

**Comment by thomasvanderbeek** [comment]
This happens when you remove the default "Backend user" and "Default user" in the UserTableSeeeder.php $users array.

To resolve this, add those users again:
`
            [
                'name' => 'Backend User',
                'email' => 'executive@executive.com',
                'password' => bcrypt('1234'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Default User',
                'email' => 'user@user.com',
                'password' => bcrypt('1234'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
`
And run `php artisan db:seed`.

**Comment by rappasoft** [comment]
Yeah it needs them to complete the seed. If you dont need them I suggest deleting after you install from the admin backend.

**Comment by connor11528** [comment]
I am getting this same error. I have a fresh install and deployed the application to heroku. I would like to populate my production database so ran:

```
$ heroku run php /app/artisan db:seed 
Running php /app/artisan db:seed on ⬢ laravel5boilerplate... up, run.4843 (Free)
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Seeding: AccessTableSeeder
Seeding: UserTableSeeder
yes
Seeding: RoleTableSeeder
Seeding: UserRoleSeeder

                                                           
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Call to a member function attachRole() on null 
```

What is the command to add those users or how do I fix this? Thank you
