### ISSUE TITLE
Lazy loading on History renderType

### ISSUE THREAD

**Issue by HilmanAnshori** [rappasoft/laravel-5-boilerplate#451]
Hello,

There's queries number problem on History repository when accessing renderType with string parameter.
In EloquentHistoryRepository line 63 : 

```php
$history = History::whereHas('type', function ($query) use ($type) {
   $query->where('name', ucfirst($type));
})->latest()->get();
```
and this is queries count
![screenshot_9](https://cloud.githubusercontent.com/assets/3981733/17665174/5acbd5ea-6323-11e6-808d-4161e7cd7b69.jpg)

changed it to : 
```php
$history = History::with('user')->whereHas('type', function ($query) use ($type) {
   $query->where('name', ucfirst($type));
})->latest()->get();
```

result : 
![screenshot_10](https://cloud.githubusercontent.com/assets/3981733/17665200/9813a02c-6323-11e6-8a08-9fc91d723698.jpg)

Thanks

**Comment by rappasoft** [comment]
Can you make a PR?

**Comment by chemitaxis** [comment]
Thanks

**Comment by rappasoft** [comment]
Fixed on development thank you.
