### ISSUE TITLE
Avoid N+1 Query

### ISSUE THREAD

**Issue by lsc20051426** [rappasoft/laravel-5-boilerplate#454]
Hi, I like this repo very much.
But seems N+1 query problem is not solved:
https://laravel.com/docs/5.2/eloquent-relationships#eager-loading

you should be able to see the sql querys in debugtoolbar. 
when you have a lot of user and roles, the sql query grows a lot. 

#451 is one of the example.

**Comment by rappasoft** [comment]
Fixed on development thank you.
