### ISSUE TITLE
how to pass model to sidebar?

### ISSUE THREAD

**Issue by cutemonster** [rappasoft/laravel-5-boilerplate#456]
I have a product model which has a few products that I want to include in the side bar.
Could you tell me how to pass the product model to sidebar.blade?

thanks

**Comment by brentkozjak** [comment]
This is a general Laravel question and not really related to this boilerplate, but to answer your question there are several ways to do it.  For example you could create a view composer.  See here - https://laravel.com/docs/5.2/views#passing-data-to-views

**Comment by cutemonster** [comment]
Hi brentkozjak,
  I also thought about the view composer.  What other methods can be done?
thanks

**Comment by rappasoft** [comment]
You can register a view composer that binds data to sidebar.blade.php.

**Comment by cutemonster** [comment]
thanks all.  Will use view composer.
