### ISSUE TITLE
datatables Excel button export feature not showing

### ISSUE THREAD

**Issue by cutemonster** [rappasoft/laravel-5-boilerplate#457]
I followed instruction on yajra datatables demo by putting

    dom: 'Bfrtip',
    buttons: [  'copy', 'csv', 'excel', 'pdf', 'print'   ]

but buttons still not showing.  Anybody having the same issue?

**Comment by rappasoft** [comment]
Are there any console errors? I know there are files associated with those working.

**Comment by cutemonster** [comment]
no message in console.
What I did is added the following code.
![excel](https://cloud.githubusercontent.com/assets/212361/17879148/3c3e534c-68a4-11e6-80b6-09fc7359566a.PNG)

**Comment by poseso** [comment]
did you added:

https://cdn.datatables.net/buttons/1.1.0/js/dataTables.buttons.min.js"
https://cdn.datatables.net/buttons/1.1.0/js/buttons.print.min.js

**Comment by cutemonster** [comment]
got it.  thanks for the tips.
I used the builder to include all extensions.
So I include the following and everything work!
You can custom build your own extensions here: https://datatables.net/download/

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/jszip-2.5.0/pdfmake-0.1.18/dt-1.10.12/af-2.1.2/b-1.2.2/b-colvis-1.2.2/b-flash-1.2.2/b-html5-1.2.2/b-print-1.2.2/cr-1.3.2/fc-3.2.2/fh-3.1.2/kt-2.1.3/r-2.1.0/rr-1.1.2/sc-1.4.2/se-1.2.0/datatables.min.css"/>
 
<script type="text/javascript" src="https://cdn.datatables.net/v/bs/jszip-2.5.0/pdfmake-0.1.18/dt-1.10.12/af-2.1.2/b-1.2.2/b-colvis-1.2.2/b-flash-1.2.2/b-html5-1.2.2/b-print-1.2.2/cr-1.3.2/fc-3.2.2/fh-3.1.2/kt-2.1.3/r-2.1.0/rr-1.1.2/sc-1.4.2/se-1.2.0/datatables.min.js"></script>

**Comment by vishalchandGIT** [comment]
How to include this in react import ??????

https://cdn.datatables.net/buttons/1.1.0/js/dataTables.buttons.min.js"
https://cdn.datatables.net/buttons/1.1.0/js/buttons.print.min.js
