### ISSUE TITLE
Access::hasRole() shows user has role, even though role doesn't exist

### ISSUE THREAD

**Issue by mruzekw** [rappasoft/laravel-5-boilerplate#458]
I'm working with `Access::hasRole()` and `$user->hasRole()` and both return true when given a role that doesn't exist.

```
Access::hasRole('a');
// true

$user->hasRole('b')
// true
```

Neither `a` nor `b` exist.

I must be missing something. Please help.

**Comment by rappasoft** [comment]
If it's the administrator role it will, because it checks to see if the all flag is true before checking the existence of the role itself.

https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Models/Access/User/Traits/UserAccess.php#L21

**Comment by rappasoft** [comment]
Or rather, if one of the role has the 'all' flag set.

**Comment by mruzekw** [comment]
I just noticed this. I will test as another user then. Thank you!
