### ISSUE TITLE
Issue with User EloquentUserRepository and UserContract

### ISSUE THREAD

**Issue by kierandes** [rappasoft/laravel-5-boilerplate#46]
Hello,

I really like the new changes to the boilerplate, very slick. However I'm having an issue with the EloquentUserRepository. I have not changed either the EloquentUserRepository nor the UserContract. The bug is as follows:

FatalErrorException in EloquentUserRepository.php line 13: Declaration of App\Repositories\Backend\User\EloquentUserRepository::create() must be compatible with App\Repositories\Backend\User\UserContract::create($input)

Any help would be greatly appreciated

**Comment by rappasoft** [comment]
Something is definitely wrong. It means the method stub here: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Repositories/Backend/User/UserContract.php does not match the implementation here: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Repositories/Backend/User/EloquentUserRepository.php

Which it does, it should be 

```public function create($input, $roles, $permissions);```

I just downloaded a fresh copy and it works. There must be a different issue.
