### ISSUE TITLE
DataTable Query

### ISSUE THREAD

**Issue by nimeshc64** [rappasoft/laravel-5-boilerplate#461]
i want to filter data using date range, i have vreate date column how to filter using date range in "BETWEEN" keyWord

my code
 ```
return Datatables::of($details)
            ->filter(function ($query) use ($request) {
                if ($request->has('fromDate') and $request->has('toDate'))
                {
                    $query->where('create_date', 'BETWEEN', "%{$request->get('fromDate')}%",'AND',"%{$request->get('toDate')}%");
                }
            })
            ->make(true);
```

**Comment by error500** [comment]
it's a Laravel syntax

The whereBetween method verifies that a column's value is between two values:

 $users = DB::table('users')
                     ->whereBetween('votes', [1, 100])->get();

It should work with models too
