### ISSUE TITLE
upgrade to 5.3.* ?

### ISSUE THREAD

**Issue by SaqibZafar** [rappasoft/laravel-5-boilerplate#462]
any plans for 5.3?

**Comment by digitalit** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/issues/446

**Comment by SaqibZafar** [comment]
thanks @digitalit

**Comment by rappasoft** [comment]
I will, but I will have to start over as too much has changed as usual. I'm mid way through readying the docs and then i'm going to go through the API before I start, so I can incorporate as much as I can from the new stuff.

And as much as it pains me, and without destroying my access class, i'm going to look into this gate/policy thing laravel has going on to try to see if I can use any of that as well.

**Comment by IvanBernatovic** [comment]
@rappasoft No pressure, but do you have some kind of ETA (at least is it weeks or months far)? I'll soon start new project for client so I'm curious how it's going? :)

**Comment by rappasoft** [comment]
Couldn't really say, it's literally this current version just in a new 5.3 application. And removing some stuff that I think is useful.

I'm hoping for less than a month, it has to do with how much free time I have.

**Comment by RUIFERNANDE5** [comment]
@rappasoft any updates on it mate?

**Comment by saji89** [comment]
Laravel Boiler plate v 4.0 for Laravel 5.3 has been released. #485
