### ISSUE TITLE
renderEntity doesn't check for type

### ISSUE THREAD

**Issue by jsiebach** [rappasoft/laravel-5-boilerplate#464]
The current `renderEntity` function in `EloquentHistoryRepository.php` doesn't distinguish which type of entity you are trying to render history for.  If you have an entity called `Foo` and you try to render the history of Foo ID 3, it will also render the history of User ID 3 in the table.

I wrote this function to correct this:

```
public function renderEntityOfType($entity_id, $type) {

		$history = History::with('user', 'type')
			->where('entity_id', $entity_id)
			->whereHas('type', function($query) use ($type) {
				$query->whereName($type);
			})->latest()->get();

		if (! $history->count())
			return trans("history.backend.none_for_entity", ['entity' => $history->type->name]);

		return $this->buildList($history);
	}
```

I could write a pull request if you want.  Maybe would check for numeric or string on the `type` field? I chose to use string only to avoid the extra DB hit.  

Another option would be to eliminate `history_types` all together and make history a polymorphic many-to-many relation.  Then we could have a `HasHistory` trait and that would handle the history relationship.  `log` could be a function in that trait.  We could even do a custom scope and write a custom blade component so rendering it would just be `@history($user)`, and any class with the `HasHistory` trait could be there instead as well

Thanks for this great boilerplate!

**Comment by cutemonster** [comment]
thanks jsiebach, I'm working on the history on entity.  This is useful!

    ->whereHas('type', function($query) use ($type) {
    $query->whereName($type);

I don't understand the "use" keyword,  could you explain or point me to the document?
I'm not sure how to search for it.

thanks!

**Comment by jsiebach** [comment]
`use` allows an anonymous function to use a variable that isn't within its scope.  Since we added `use ($type)` we have access to the `$type` variable inside the function. docs: http://php.net/manual/en/functions.anonymous.php

**Comment by cutemonster** [comment]
perfect, thanks.  I understand now.

**Comment by blomdahldaniel** [comment]
This is good feedback, pinging @rappasoft to take a look at the `EloquentHistoryRepository.php@ renderEntityOfType`

**Comment by rappasoft** [comment]
This is a little old and i've been a little sidetracked. Can someone explain why you can't use renderType or a different method? Is this new functionality or fixing something that is broken?

**Comment by rappasoft** [comment]
I altered the renderEntity function to take type:

```
public function renderEntity($entity_id, $type) {
		$history = History::with('user', 'type')->where('entity_id', $entity_id);

		if (is_numeric($type)) {
			$history = $history->where('type_id', $type);
		} else {
			$type = strtolower($type);

			$history = $history->whereHas('type', function ($query) use ($type) {
				$query->where('name', ucfirst($type));
			});
		}

		$history = $history->latest()->get();

		if (! $history->count())
			return trans("history.backend.none_for_entity", ['entity' => $history->type->name]);

		return $this->buildList($history);
	}
```
