### ISSUE TITLE
PSR2 Standards

### ISSUE THREAD

**Issue by Sekonda** [rappasoft/laravel-5-boilerplate#465]
Hey,

I just cloned down the repo and I'm looking to build an app with it. When I run PHP CodeSniffer for PSR2 I get a ton of issues (most can be fixed automatically).

Would you like me to make a pull request for this?

**Comment by rappasoft** [comment]
If you wish, but i'm currently working on 5.3 and it will probably get overwritten. I will try to do it automatically with PHPStorm before I finish if I remember. Maybe theres a plugin?

**Comment by Sekonda** [comment]
You can do it by running
`composer require squizlabs/php_codesniffer`

You can check the standards by running 

`./vendor/bin/phpcs app/ --standard=PSR2`

and you can fix (most of it) by running

`./vendor/bin/phpcbf app/ --standard=PSR2`

**Comment by rappasoft** [comment]
Ok I will look.
