### ISSUE TITLE
Connect with Facebook after regular login

### ISSUE THREAD

**Issue by vladvisinescu** [rappasoft/laravel-5-boilerplate#466]
I`m not familiar with how Socialite works, first of all.

What I would like to do is give the user the ability to connect his Facebook Account AFTER he has already registered as a regular user through the regular register form.

Is there any way to make this happen?

thanks,
Vlad

**Comment by rappasoft** [comment]
That is not what socialite is, socialite is the ability to log in with the social account. You would have to implement that from scratch.

**Comment by sitesense** [comment]
Expanding on this a little... if the email address of the 'regular' user is the same as that used for the social account, then the accounts are connected by default.
