### ISSUE TITLE
Salesforce and Socialite

### ISSUE THREAD

**Issue by LunarDevelopment** [rappasoft/laravel-5-boilerplate#467]
Hello! 

I'd like to allow users to log in with [Salesforce Socialite Provider](http://socialiteproviders.github.io/providers/salesforce/) Could you offer some guidance on what I'd need to do? 

I've tried following only thier instructions on integration but to no avail, I think its because files like \Services\Access\Traits\UseSocialite.php are (to me) quite complex chains of functions to follow through the providers and services / controllers and blade files to figure out what I need to add.

**Comment by rappasoft** [comment]
http://socialiteproviders.github.io/providers/salesforce/
