### ISSUE TITLE
how to add more fiield to user create 

### ISSUE THREAD

**Issue by nimeshc64** [rappasoft/laravel-5-boilerplate#468]
i want to add db user table to add username field and save, how to do this

**Comment by rappasoft** [comment]
Add your username column and than change this function to return username: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Services/Access/Traits/AuthenticatesUsers.php#L99

**Comment by rappasoft** [comment]
You need to add the input to the view, then make sure its being passed to this function:

https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Repositories/Frontend/Access/User/EloquentUserRepository.php#L87

**Comment by brentkozjak** [comment]
I'm doing the same thing.  Something to keep in mind if you also want to support Socialite user registrations, you'll need to perform some logic here - https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Repositories/Frontend/Access/User/EloquentUserRepository.php#L127 to set the username automatically or perhaps allow the user to specify their own username post-registration.

**Comment by rappasoft** [comment]
Yes the reason I use email by default is that's how laravel has it out of the box.
