### ISSUE TITLE
How to get the current loggedin user role name.

### ISSUE THREAD

**Issue by vivekpandey0460** [rappasoft/laravel-5-boilerplate#47]

**Comment by gaurav112** [comment]
Users can have multiple roles. 
So you can get all the role  of the current user by 
```
auth()->user()->roles
```
You can the use a for each to find your specific role.

If you are trying to find if the current user has a specific role then use:

```
auth()->user()->hasRole($yourRole)
```
Hope this helps.

**Comment by rappasoft** [comment]
Yes the above is true, if you want more of a string to output I would do: 

```implode(", ", access()->user()->roles->lists('name')->toArray()```

For the current logged in user
