### ISSUE TITLE
Actions buttons

### ISSUE THREAD

**Issue by dennisvanvalderen** [rappasoft/laravel-5-boilerplate#471]
Hello.

In the user management page the data is retrieved by making a get call to the admin.access.user.get with the get parameters that are filled in with the JS. When I fill this in I get back exactly what I expected.

But I do not understand how the action buttons are being made into the $user->action_buttons.
The controller goes like this:
public function get(ManageUserRequest $request) {
        return Datatables::of($this->users->getForDataTable($request->get('status'), 
// alot of code.
                return $user->action_buttons;

And when I look into the UserAttribute.php I can see there is:
public function getActionButtonsAttribute()
and it returns all the action buttons.

But how is it that the $user knows that action_buttons is going to be the getActionButtonsAttribute?
Where can I find that? 

I'm very sorry if this is a stupid question but I'm trying to really understand what is going on in the theme.

**Comment by rappasoft** [comment]
That's default Laravel functionality.

https://laravel.com/docs/5.3/eloquent-mutators#defining-an-accessor
