### ISSUE TITLE
Question about Query Builder

### ISSUE THREAD

**Issue by digitalit** [rappasoft/laravel-5-boilerplate#473]
I use Query Builder for all my sql and i read that in 5.3 even the QB will return a Collection.

What will i gain QB wise by upgrading to 5.3?

**Comment by rappasoft** [comment]
It just makes it the norm, you will have to append all QB calls with toArray() if you don't want to break anything, or modify the code to use the collection instead of the array.

**Comment by digitalit** [comment]
So this code would work in 5.2?

`    /**
     * @param  $id
     * @throws GeneralException
     * @return mixed
     */
    public function getTicket($id)
    {
        $query = DB::table('tickets');

        $query->select('tickets.*');

        $query->where('tickets.id', $id);

        $ticket = $query->first();

        if (!is_null($ticket)) {

            return $ticket;

        }

        throw new GeneralException(trans('exception.backend.tickets.not_found'));
    }`

**Comment by rappasoft** [comment]
The difference as I understand was that the get method on the query builder in 5.2 returned an array and in 5.3 returns a collection.

**Comment by digitalit** [comment]
Ok
