### ISSUE TITLE
If there any way to use a variable inside of the @permission?

### ISSUE THREAD

**Issue by lewp** [rappasoft/laravel-5-boilerplate#474]
I would like to set a variable in the controller then pass it to the view and use it inside of the @permission.  Is this possible?  I can get the variable to display on the page using {{$permission}} but if I do @permission($permission) or @permission({{$permission}}) it doesn't work.

**Comment by rappasoft** [comment]
The first one should work fine.

Try

`access()->has($permission)`

**Comment by lewp** [comment]
That didn't seem to work either.  It's possible that I am using your early version of this same boilerplate as I noticed I have to do @permission and @endpermission instead of @endauth.  Was the variable functionality not supported them?

**Comment by rappasoft** [comment]
Yes that is a really old version. I don't remember if that's supported.

**Comment by lewp** [comment]
Thanks, I figured out a way of doing it in the controller using Access::can that seems to work.  I have the previous version but don't think it's really feasible to update everything.  Thanks for your help.
