### ISSUE TITLE
Question: how to run in c9.io?

### ISSUE THREAD

**Issue by DanJFletcher** [rappasoft/laravel-5-boilerplate#476]
I'm trying to run the boilerplate project on cloud 9. I set the `APP_URL` in the `.env` to `https://laravel-boilerplate-danjfletcher.c9users.io`.

When I visit this URL: `https://laravel-boilerplate-danjfletcher.c9users.io/public/` I get mixed content errors, but when I click on any link that doesn't route to the home page everything seems to be working fine, and my URL looks like this: `http://laravel-boilerplate-danjfletcher.c9users.io/public/macros`. If I click a link bring me to the home page my URL then looks like this: `https://laravel-boilerplate-danjfletcher.c9users.io:80/public/` with the port number in the URL.

Cloud 9 won't serve on port 80.

So I don't know if this is a noob question or not, but how do I either get rid of the `:80` when clicking on links, or how do I change the port that shows up there?

The odd thing, is that the Macros link seems to be generated using the exact same method as the Index link, but Macros works?

Maybe my problem is generating the `https` URLs to begin with? This boiler plate seems like it's going to save me a TON of work, but I'm so lost as to how to even get started. I'm pretty new to Laravel in general so there are a lot things going on that I'm not use to seeing.

**Comment by blomdahldaniel** [comment]
It sounds like this has more to do with Cloud 9. Or maybe with laravels core functionality. I suggest that you seek help in either the laravel- or cloud 9 forums. 
The issues for this repo needs to relate to the boilerplate in particular. 

I hope you'll find a solution. Feel free to post your solution here.

**Comment by DanJFletcher** [comment]
Thanks, I'll be sure to post the solution here if I find it.
