### ISSUE TITLE
password

### ISSUE THREAD

**Issue by anandat** [rappasoft/laravel-5-boilerplate#477]
what is the password for admin n user those are alread register..!!
n cant register withnew user
some thig like this.....Expected response code 250 but got code "530"
all set in my .env n mail.php plz rply asap possible thnku so much

**Comment by poseso** [comment]
You can find it in https://github.com/rappasoft/laravel-5-boilerplate/blob/master/database/seeds/Access/UserTableSeeder.php#L31
