### ISSUE TITLE
login with username

### ISSUE THREAD

**Issue by nimeshc64** [rappasoft/laravel-5-boilerplate#479]
i added user table to username column, then i want to login with user name, is it possible??

**Comment by crazyjoery** [comment]
it should be possible, my guess would be to adjust the traits used by the boilerplate to use the username instead of the email adress.

**Comment by rappasoft** [comment]
You have to change this to the correct column: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Services/Access/Traits/AuthenticatesUsers.php#L99

**Comment by blomdahldaniel** [comment]
I will close this issue as of now, feel free to comment or reopen if necessary. :)

**Comment by radifans** [comment]
@rappasoft I can't find the following file on current build, which file I need to change in current build?

**Comment by patricksebastien** [comment]
File config/access.php MODIFIED
// Login username to be used by the controller.
-        'username' => 'email',
+        'username' => 'username',

resources/lang/en/validation.php MODIFIED
         'frontend' => [
+            'username' => 'Username',
             'first_name' => 'First Name',

File resources/views/frontend/auth/login.blade.php MODIFIED
                         <div class="row">
                             <div class="col">
                                 <div class="form-group">
-                                    {{ html()->label(__('validation.attributes.frontend.email'))->for('email') }}
+                                    {{ html()->label(__('validation.attributes.frontend.username'))->for('email') }}
 
-                                    {{ html()->email('email')
+                                    {{ html()->text('username')
                                         ->class('form-control')
-                                        ->placeholder(__('validation.attributes.frontend.email'))
+                                        ->placeholder(__('validation.attributes.frontend.username'))
                                         ->attribute('maxlength', 191)
                                         ->required() }}
                                 </div>
