### ISSUE TITLE
Your Account is Banned message when creating accounts via seeding

### ISSUE THREAD

**Issue by kobescoresagain** [rappasoft/laravel-5-boilerplate#48]
I am getting this message automatically when I create accounts via seeding,  I looked around in the database and I don't see a 'status' field that is set to 2.  How can I either fix the problem in the seeding itself or easily unban these accounts without going through the password reset steps.

**Comment by rappasoft** [comment]
Are you specifically setting the status column in the seed to 2?

**Comment by kobescoresagain** [comment]
No, actually I don't set the status column at all. Thanks in advance for the help.  Do I need to go ahead and set status? Here is what I am doing in the seeder:

<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon as Carbon;

class UserTableSeeder extends Seeder {

	public function run() {


		//Add the master administrator, user id of 1
		    DB::statement('TRUNCATE TABLE ' . config('auth.table') . ' CASCADE;');


		$users = [
			[
				'name' => 'test',
				'username' => 'Admin',
				'email' => 'test@mailinator.com',
				'password' => bcrypt('fakepass'),
				'confirmation_code' => md5(uniqid(mt_rand(), true)),
				'confirmed' => true,
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now()
			],
			[
				'name' => 'Default User',
				'username' => 'Tester',
				'email' => 'test2@mailinator.com',
				'password' => bcrypt('fakepass2'),
				'confirmation_code' => md5(uniqid(mt_rand(), true)),
				'confirmed' => true,
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now()
			],
		];

		DB::table(config('auth.table'))->insert($users);

	}
}

**Comment by rappasoft** [comment]
The 4th migration setup_access_tables, installs the status column, did you run all of the migrations?

**Comment by kobescoresagain** [comment]
I do indeed have that in my migrations.  I did have to modify things as I am using postgres.  Here is what I have in that file:

<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\Schema;

class SetupAccessTables extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::table(config('auth.table'), function ($table) {
			$table->boolean('status')->after('password')->default(true);
		});

		Schema::create(config('access.roles_table'), function ($table) {
			$table->increments('id')->unsigned();
			$table->string('name')->unique();
			$table->timestamps();
		});

		Schema::create(config('access.assigned_roles_table'), function ($table) {
			$table->increments('id')->unsigned();
			$table->integer('user_id')->unsigned();
			$table->integer('role_id')->unsigned();
			$table->foreign('user_id')
				->references('id')
				->on(config('auth.table'))
				->onUpdate('cascade')
				->onDelete('cascade');
			$table->foreign('role_id')->references('id')->on(config('access.roles_table'));
		});

		Schema::create(config('access.permissions_table'), function ($table) {
			$table->increments('id')->unsigned();
			$table->string('name')->unique();
			$table->string('display_name');
			$table->boolean('system')->default(false);
			$table->timestamps();
		});

		Schema::create(config('access.permission_role_table'), function ($table) {
			$table->increments('id')->unsigned();
			$table->integer('permission_id')->unsigned();
			$table->integer('role_id')->unsigned();
			$table->foreign('permission_id')
				->references('id')
				->on(config('access.permissions_table'));
			$table->foreign('role_id')
				->references('id')
				->on(config('access.roles_table'));
		});

		Schema::create(config('access.permission_user_table'), function ($table) {
			$table->increments('id')->unsigned();
			$table->integer('permission_id')->unsigned();
			$table->integer('user_id')->unsigned();
			$table->foreign('permission_id')
				->references('id')
				->on(config('access.permissions_table'));
			$table->foreign('user_id')
				->references('id')
				->on(config('auth.table'));
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::table(config('auth.table'), function(Blueprint $table)
		{
			$table->dropColumn('status');
		});

		Schema::table(config('access.assigned_roles_table'), function (Blueprint $table) {
			$table->dropForeign(config('access.assigned_roles_table').'_user_id_foreign');
			$table->dropForeign(config('access.assigned_roles_table').'_role_id_foreign');
		});

		Schema::table(config('access.permission_role_table'), function (Blueprint $table) {
			$table->dropForeign(config('access.permission_role_table').'_permission_id_foreign');
			$table->dropForeign(config('access.permission_role_table').'_role_id_foreign');
		});

		Schema::table(config('access.permission_user_table'), function (Blueprint $table) {
			$table->dropForeign(config('access.permission_user_table').'_permission_id_foreign');
			$table->dropForeign(config('access.permission_user_table').'_user_id_foreign');
		});

		Schema::drop(config('access.assigned_roles_table'));
		Schema::drop(config('access.permission_role_table'));
		Schema::drop(config('access.permission_user_table'));
		Schema::drop(config('access.roles_table'));
		Schema::drop(config('access.permissions_table'));
	}
}

**Comment by kobescoresagain** [comment]
I did find status in the tables, it is set to TRUE for both users.

**Comment by rappasoft** [comment]
There should be no reason that message is being thrown while seeding.

**Comment by azulkipli** [comment]
I got this issue too when using PostgreSQL, related to 
https://github.com/rappasoft/laravel-5-boilerplate/issues/51

I do comment these statement, because on postgresql these not supported
```
DB::statement('SET FOREIGN_KEY_CHECKS=0;');
...
DB::statement('SET FOREIGN_KEY_CHECKS=1;');
``
and

```DB:table('table')->truncate()``` in each seed classes

I try this
http://espadav8.co.uk/2015/03/04/laravel-database-seeding-with-postgresql/
but still not solve banned issue

**Comment by azulkipli** [comment]
to solved this banned issue on PostgreSQL I change status type to integer instead of boolean

**Comment by kobescoresagain** [comment]
Thanks Azulkipli,  I made that change it and worked.

**Comment by rappasoft** [comment]
I have fixed all of this with this commit: https://github.com/rappasoft/laravel-5-boilerplate/commit/57a36034305e7998c8e3459a666d4a8a89fc0164
