### ISSUE TITLE
Adding more socialite providers

### ISSUE THREAD

**Issue by crazyjoery** [rappasoft/laravel-5-boilerplate#480]
i'm trying to add the battlenet socialite provider to the application that has been build on your boilerplate. The only issue i run into is that whenever it gets the response from Blizz's battlenet api it only returns a battlenet email but no name. 

After some digging i've been using [Socialite-BattleNet](https://github.com/teamreflex/Socialite-BattleNet) from team reflex. But they suggest the following:
```
// redirect route
Session::put('bnet.region', 'eu');
return Socialite::with('battlenet')->redirect();

// callback route
$user = Socialite::driver('battlenet')->user();
$accountId = $user->getId(); // bnet accountId
$battletag = $user->getNickname(); // bnet battletag
```

What would be the easiest/best way to implement this in the boilerplate socialite setup?

**Comment by rappasoft** [comment]
Make sure it doesn't require you to add additional scopes.

**Comment by crazyjoery** [comment]
looked over that allready and there are no extra scopes i need to be added as far as i can tell will go over it again.

**Comment by crazyjoery** [comment]
overlooked a simple line of code. my bad for opening a ticket.
