### ISSUE TITLE
IDE Helper shows some errors

### ISSUE THREAD

**Issue by digitalit** [rappasoft/laravel-5-boilerplate#481]
Hi,

This code in UserController
        <pre>
         return view('backend.access.edit')
            ->withUser($user)
</pre>
works but the IDE Helper gives error:
 "Method 'withUser' not found in \Illuminate\Contracts\View\Factory\Illuminate\View\View

The correct way seems to be
  <pre>
        return view('backend.access.edit')
            ->with('user', $user)
</pre>

Also Flash messages
<pre>
return redirect()->back()->withFlashSuccess(trans('alerts.backend.users.deleted'));
</pre>
works but the IDE Helper gives error:
 "Method 'withFlashSuccess' not found in \Illuminate\Http\RedirectResponse

The correct way seems to be
  <pre>
       return redirect()->back()->with('flash_success', trans('alerts.backend.users.deleted'));
</pre>

**Comment by rappasoft** [comment]
They're both correct. I prefer the way it is. 

Anthony Rappa
President
631-334-6650

**Comment by digitalit** [comment]
Any particular reason? Just curious :)

**Comment by rappasoft** [comment]
It's valid Laravel syntax. I think it looks cleaner and less redundant. I tend to use most Laravel functionality no matter how small to both help people learn and help me remember. 

Plus you'd be surprised how much time you save coding. 

Anthony Rappa
President
631-334-6650

**Comment by digitalit** [comment]
Ok.
