### ISSUE TITLE
Package Warning: Guzzle

### ISSUE THREAD

**Issue by vnchopra** [rappasoft/laravel-5-boilerplate#482]
Im sure people know about his warning but i d like to let you know as well. Got this warning:

"Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead."

**Comment by rappasoft** [comment]
We are not pulling in guzzle in our composer.json file. It must be from one of the packages' dependencies.

**Comment by conspacer** [comment]
@vnchopra it is required by the package "satooshi/php-coveralls"
https://packagist.org/packages/satooshi/php-coveralls
