### ISSUE TITLE
Laravel Flash Messages

### ISSUE THREAD

**Issue by poseso** [rappasoft/laravel-5-boilerplate#487]
I still does not understand how is this working? where is it coming from?

I found  includes\partials\messages.blade.php which contains the messages, i do

@include('includes.partials.messages')

and

return redirect()->route('admin.test')->withFlashSuccess(trans('test.general.messages.save'));

and the flash message appears, but, is this a package? I want to understand where is it coming from or how its been done?

**Comment by rappasoft** [comment]
The messages blade file checks for all types of session messages and displays the correct alert box depending on the session key. This file is loaded in ```master.blade.php```.

The ```withFlashSuccess($message)``` is a Laravel feature where you can use dynamic method names.

It converts to this at runtime:

`->with('flash_success', $message)`

And in messages.blade.php is caught and displayed here: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/resources/views/includes/partials/messages.blade.php#L7

The $errors->any() in the first if is also a laravel feature, as laravel will pass an array called $errors to any view to which an error is thrown, so it's just checking for that.

All in all this file could probably be a little cleaner, as it is from V1, but for now it does the job.
