### ISSUE TITLE
question on entity_id in history table

### ISSUE THREAD

**Issue by cutemonster** [rappasoft/laravel-5-boilerplate#489]
What is **entity_id** used for in history table?
I have a **product** with **type_id** 1.  
I want to have history of each product,  Can I use this **entity_id** to store my **product_id**?

thanks!

**Comment by pebbo** [comment]
I think your assumption is correct :)

**Comment by pebbo** [comment]
if you want to track changes within your products, have to look at https://github.com/VentureCraft/revisionable

**Comment by cutemonster** [comment]
thanks, will check that out.
