### ISSUE TITLE
How to get data using related table?

### ISSUE THREAD

**Issue by xnhinzkyx** [rappasoft/laravel-5-boilerplate#49]
Hello,

I just want to ask if how to get data from related tables? Like here in "EloquentUserRepository.php" with this example line:

public function getUsersPaginated($per_page, $status = 1, $order_by = 'id', $sort = 'asc') {
		return User::where('status', $status)->orderBy($order_by, $sort)->paginate($per_page);
	}

I want have a query from two table joined or something? or get user based from specified role from table roles, anyone?

Thank you. This is a great package.

**Comment by rappasoft** [comment]
If you have a specific role you can grab the users with the relationship, as specified here:

https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Role.php

```
$role = Role::find(1)->users
```

**Comment by xnhinzkyx** [comment]
Thanks for this but I'm new to laravel can you show me how to display it using this function?

public function getUsersPaginated($per_page, $status = 1, $order_by = 'id', $sort = 'asc') {
return User::where('status', $status)->orderBy($order_by, $sort)->paginate($per_page);
}

Thanks.

**Comment by rappasoft** [comment]
I'm confused, exactly what are you trying to display with a function?

**Comment by xnhinzkyx** [comment]
I'm trying to display users with a role moderator for example using that function getUsersPaginated().

Like return User::where('status', $status)->orderBy($order_by, $sort)->paginate($per_page)->role('moderator');

**Comment by rappasoft** [comment]
Try something like:

```
User::whereHas('role', function($q) {
    $q->where('name', '=', 'moderator');
})->where('status', $status)->orderBy($order_by, $sort)->paginate($per_page)->role('moderator');
```

That may work, untested.

**Comment by xnhinzkyx** [comment]
Thanks but it gives me an error:

BadMethodCallException in Builder.php line 2003:
Call to undefined method Illuminate\Database\Query\Builder::role()

Do i need to add something?

**Comment by rappasoft** [comment]
It might be ```roles``` instead. Or it might not work at all because it's a pivot table.

**Comment by xnhinzkyx** [comment]
Yeah it doesn't work for me but still thank you for your support.
