### ISSUE TITLE
Application loggout of the seesion while submitting the forms.

### ISSUE THREAD

**Issue by vjaykoogu** [rappasoft/laravel-5-boilerplate#490]
- It's acting weired, sometimes it takes in the form fields and sometimes it loggs out of the session to login screen.

* i'm using latest master branch.

**Comment by blomdahldaniel** [comment]
What form are you using when you get this error?

**Comment by vjaykoogu** [comment]
i've created new forms eg: a) will add product details and b) will create new categories.   Again those forms will on ROLE base  only admin can add new categories and products.

**Comment by vjaykoogu** [comment]
- StoreProductRequest.php
~~~~~~~~~~~~~
/**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return access()->allow('view-backend');
    }
~~~~~~~~~~~~~~~~~~~~~~

**Comment by wizston** [comment]
This is most likely a browser issue (Most especially Chrome), change your browser or if you must use chrome try it in incognito mode.

**Comment by vjaykoogu** [comment]
Thanks alot @wizston this help, but any idea why this is happening ?

**Comment by blomdahldaniel** [comment]
Wow that is really weird!! Must be based on some deprecated stuff...?

**Comment by vjaykoogu** [comment]
have not idea on that @blomdahldaniel but yes need to check.

**Comment by activemonkeys** [comment]
Had a similar issue. Changed session driver from file to database (have a look at the documentation as you need to add a migration as well). Since then it works fine.

**Comment by vjaykoogu** [comment]
Guys @activemonkeys @blomdahldaniel @wizston  can i keep this issue as open until we solve this issue OR  Add as Note: in Readme file so this might help other developers who might face this issue in future.

**Comment by rappasoft** [comment]
Are there any flash messages when you get logged out?

**Comment by vjaykoogu** [comment]
no i don't get any messages

**Comment by vjaykoogu** [comment]
This is browser issue  better we close this.
