### ISSUE TITLE
New Feature Request- Import/Export Excel

### ISSUE THREAD

**Issue by PSNAppz** [rappasoft/laravel-5-boilerplate#491]
The Maatwebsite provides import/export excel formats. I recommend you add this feature to this boilerplate.

**Comment by LunarDevelopment** [comment]
This functionality is easily added to controllers with a library like
phpleagues CSV reader writers.

The question to answer before including that into a boilerplate is : what
standard model do people want to import CSV s into across many projects?

**Comment by blomdahldaniel** [comment]
Yes, the Maatwebsite provides a great package. But just like @LunarDevelopment says, it is easy to implement by your self. There might be a clear implementation to export lists of users but that is in no way something that is a requirement. Therefore I dont think that it suites to be default in the boilerplate. And another thing is that I think DataTables has a plugin for this as well. 

I will close this issue for now, feel free to reply with your thoughts.
