### ISSUE TITLE
Multiple Roles in middleware(Access.RouteNeedsRole) doesn't work in Legacy_5.1

### ISSUE THREAD

**Issue by shubhampatel812** [rappasoft/laravel-5-boilerplate#492]
Middleware Access.RouteNeedsRole(Legacy_5.1) is not as per the Access.RouteNeedsRole(Master).
So I am having a problem in Multiple Role Authentication in Middleware RouteNeedsRole.

**Comment by rappasoft** [comment]
That's why its legacy 5.1, it doesn't keep updated with any of the new stuff.
