### ISSUE TITLE
Attribute roles/permission with grants option

### ISSUE THREAD

**Issue by error500** [rappasoft/laravel-5-boilerplate#494]
Hi !
this is a functionnal question : 
Is there a way to create a role that gives Access management without the possibility to give Admin role. In other words, it should be nice to **list the roles** that a user can gives in **Access permission group**. Or something like a **grant** option

your opinion ?

**Comment by minedun6** [comment]
If I did get your question, you want to grant a user specific role with its related permissions ?
I hope I did it right ?
If that's the case then you need to access a user then grant him the specific role. Of course you can create specific role with a set of specific permissions.
Check out AsgardCMS, they have a dedicated ACL packages built-in so maybe you can check their implementations on how they did that and get an idea.
I really hope it helped out.
