### ISSUE TITLE
I cloned this package 5 months before and added my own CMS on it, How can I make use of the new updates added to the package since then ?

### ISSUE THREAD

**Issue by Hazemwd** [rappasoft/laravel-5-boilerplate#495]
I know this is not related to a bug in the package, but I think here is the best place to ask such a question.

I cloned this package 5 months before and added my own CMS on it, How can I make use of the new updates added to the package since then ?

Thanks.

**Comment by rappasoft** [comment]
There's really no way without following the commit history and updating manually.

**Comment by Hazemwd** [comment]
So, if I wanna use the RTL support you added, what is the best way to achieve this ?
and Thanks for your efforts and this gr8 package.

**Comment by rappasoft** [comment]
Yeah you would have to import the needed classes and update the gulp file and recompile.

**Comment by blomdahldaniel** [comment]
I hope you have got an idea of how to solve this now @Hazemwd 
I will close this for now.
