### ISSUE TITLE
how to config socialite?

### ISSUE THREAD

**Issue by tinh1115** [rappasoft/laravel-5-boilerplate#5]
Hi man,

I had problem with http://mysite.com/auth/login/SERVICE, it redirect to "request permission" and redirect to http://mysite.com/auth/login/SERVICE and redirect to permission again and again.

How to fix it?

**Comment by tinh1115** [comment]
I checked and understood the config is right. But I saw this message as exception: "Client error response [url] https://accounts.google.com/o/oauth2/token [status code] 401 [reason phrase] Unauthorized". 

I developed in localhost btw.

**Comment by rappasoft** [comment]
Sometimes localhost is glitchy, but it seems like the tokens set in your .env file aren't right.

**Comment by tinh1115** [comment]
I checked in method "protected function getTokenFields($code)" the clientid & clientSecret is the same. I think this is why the error happened. 

But i checked back the .env config, the GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET is different

**Comment by tinh1115** [comment]
Fixed the problem with same id & secret, because in the services config you put id and secret is GOOGLE_CLIENT_ID for both.

**Comment by tinh1115** [comment]
I still got this message after posting:
"Client error response [url] https://accounts.google.com/o/oauth2/token [status code] 401 [reason phrase] Unauthorized"

**Comment by tinh1115** [comment]
Fixed.

**Comment by rappasoft** [comment]
How did you fix it?

**Comment by tinh1115** [comment]
I re-configed file services.php, put the right value for secret key of all service. Currently client id and secret key are the same as the latest version.

Second re-generated secret key and applied to .env

That's all. it's working good on my local now.

Btw your works are cool. Thank you for sharing ^^

**Comment by rappasoft** [comment]
Thanks! I'll push a fix.
