### ISSUE TITLE
Macro's broken when updating app:name

### ISSUE THREAD

**Issue by dodwmd** [rappasoft/laravel-5-boilerplate#50]
I updated app:name to something other than 'App'. I edited config/access.php and gave the new model location for Role and Permission and everything seems to work ok except the Macro's page.

When loading the Macro's page the following error occurs:

```
FatalErrorException in ClassLoader.php line 347:
Maximum function nesting level of '100' reached, aborting!
```

**Comment by dodwmd** [comment]
More testing shows that 'Auth::guest()' in the template is causing the problem to logged in users.

**Comment by rappasoft** [comment]
The auth::guest where?
