### ISSUE TITLE
Change name App cause break project

### ISSUE THREAD

**Issue by abkrim** [rappasoft/laravel-5-boilerplate#500]
Version: Laravel 5.* Boilerplate, Currently 5.3 (git clone today)

When change name of App, break project.

```
php artisan app:name NewName
composer dumpautolad
gulp
```

![l53boilerplate_app_home_error_change_appname](https://cloud.githubusercontent.com/assets/1238625/19314463/7afb713c-909a-11e6-90fa-3203d88dd2d6.jpg)

**Comment by rappasoft** [comment]
I believe all these issues have been dealt with on the development branch at this point.
