### ISSUE TITLE
Problems getting the history log to work on my models

### ISSUE THREAD

**Issue by minedun6** [rappasoft/laravel-5-boilerplate#507]
hi, so just like the title says, i'm having issues making the history log work on my other models.
I followed the steps which are to make an event called ClientCreated and populated it with a public property of $client. Next I added a clienteventlistener that I registred in the eventserviceprovider, and i added the on created and on updated methods(manually). and i called the event()->fire(new ClientCreated($client)) in my clientrepository but still it didn't work.
Did I skip something ?

**Comment by minedun6** [comment]
solved this with adding an entry in the historytypetableseeder.

**Comment by rappasoft** [comment]
You need to make sure the type exists of course.

**Comment by poseso** [comment]
I still havent be able to use the history type on any of my models jeje I'd like to learn how to use it correctly

**Comment by minedun6** [comment]
Actually I never I could make it work as well at first. Turns out to be rather easy task, u need to add to the historytypetableseeder all ur models like 'Company' or 'Client' and then u do the same steps I did when I was describing my problem. If u still can't ask me again.

**Comment by poseso** [comment]
but isnt the same if i add it manually to the db? to the history type table ?

**Comment by minedun6** [comment]
not like you will only add to the db the type that you want to be logged. For example, there is no need to log adding countries or some sort of statuses entities right ? only for important entities such as users, invoices... but ultimately it's up to you if you want to log them or not.

**Comment by poseso** [comment]
I can't get it to work, maybe some day when i see a real example with all the steps, maybe then i'll try it again heh

**Comment by rappasoft** [comment]
There's real examples in the boilerplate. The history types are the entities, i.e. User. History items are associated with a type. That way you can pull by type, etc. Look at the db structure, and look at the methods, it's really quite easy.

**Comment by rappasoft** [comment]
See how to use with entity here: https://github.com/rappasoft/laravel-5-boilerplate/blob/development/resources/views/backend/access/show/tabs/history.blade.php
