### ISSUE TITLE
Add check if db driver is MySQL on DatabaseSeeder

### ISSUE THREAD

**Issue by azulkipli** [rappasoft/laravel-5-boilerplate#51]
I use PostgreSQL so these statement not supported,

```
DB::statement('SET FOREIGN_KEY_CHECKS=0;');

...

DB::statement('SET FOREIGN_KEY_CHECKS=1;');
```

Maybe need to check database driver type eg: 

```
if(env('DB_DRIVER')=='mysql'){
    DB::statement('SET FOREIGN_KEY_CHECKS=0;');
}
```

**Comment by azulkipli** [comment]
if using postgres use this to TRUNCATE for each table

```
DB::statement("TRUNCATE TABLE users CASCADE");

```

**Comment by rappasoft** [comment]
I have fixed all of this with this commit: https://github.com/rappasoft/laravel-5-boilerplate/commit/57a36034305e7998c8e3459a666d4a8a89fc0164
