### ISSUE TITLE
User dataTables search function error 500

### ISSUE THREAD

**Issue by insic** [rappasoft/laravel-5-boilerplate#515]
When try to use the search box under User management a pop apears with the following message.

DataTables warning: table id=users-table - Ajax error. 

Checking ajax response I got error 500 and the following error message.

`mb_strtolower() expects parameter 1 to be string, array given`

I use the latest boilerplate version.

**Comment by blomdahldaniel** [comment]
Yes, that is true! I will try to take look at it!

**Comment by nasirkhan** [comment]
It was ok in the development branch, @rappasoft might have changed something before release.

**Comment by rappasoft** [comment]
Seems like a problem with the plugin: https://github.com/yajra/laravel-datatables/issues/248

But no one seems to have a fix, i'll have to trial and error it.

**Comment by gotrecillo** [comment]
If we make the roles not searchable it will work.

But we wont search on the roles.

```Javascript

{data: 'roles', name: 'roles', searchable: false},

**Comment by rappasoft** [comment]
Yes I just found that out too and it works that way, I was actually coming to post I don't want to do that because people will wonder why certain things aren't being searched when they can see them there.

Trying to think of a different way.

**Comment by gotrecillo** [comment]
https://datatables.yajrabox.com/eloquent/joins

What do you think about this ?

**Comment by rappasoft** [comment]
I'm trying to figure it out with no luck, If you can figure it out feel free to make a PR.

**Comment by gotrecillo** [comment]
I got it.

Gonna clean it up and make a PR

**Comment by rappasoft** [comment]
Cool thanks!

**Comment by rappasoft** [comment]
We're working on this here: https://github.com/rappasoft/laravel-5-boilerplate/pull/517

If anyone can help up with the remaining bugs.

**Comment by rappasoft** [comment]
Sorry this auto-closed but I want to keep it open until the bugs are fixed. I merged the search fix because it does work, but there's these issues left:

- Sorting roles column on users table duplicates rows
- Sorting permissions column on roles table duplicates rows
- Sorting or searching number of users column still errors, so I turned it off.

**Comment by gotrecillo** [comment]
https://datatables.yajrabox.com/relation/morph-to-many

I think that makes imposible to sort by a column created from a relationship.

**Comment by rappasoft** [comment]
Alright guess it is what it is!
