### ISSUE TITLE
How can we emebed a modal within the datatables

### ISSUE THREAD

**Issue by minedun6** [rappasoft/laravel-5-boilerplate#518]
Can you help me out on how to emebed a modal within the datatables' each row and populate the modal accordingly. The idea is I added a `data-id` to the edit button and did embed a modal to show on it but what I'm trying to acheive is that I need to call the controller and fetch the related data of a user then in the ajax response load a view so that it can be shown dynamically into the modal content.

**Comment by rappasoft** [comment]
Not sure exactly what you're asking.

**Comment by minedun6** [comment]
here i prepared some screenshots so it can be clear.
[http://postimg.org/gallery/ej500l9y/](VisionERP)

**Comment by rappasoft** [comment]
Seems like you just need to do an ajax request to some method that gets the users data and displays it in the form.

**Comment by minedun6** [comment]
already done that but I can't pass the the variable since the edit button is within the attribute trait.
All i'm asking is if there is a tutorial or if u can be nice enough as to show me around/help me.

**Comment by rappasoft** [comment]
You have the ID of the user in the attribute trait, add it as a data attribute to the button, get that when the button is clicked and fire an ajax request to a route to get the whole user object as json then parse it.

**Comment by minedun6** [comment]
already did but maybe I'm too dump to get it to work. will try again later when i get home.
In the meantime, 

how can i pass the "?" as a javascript variable ? 
`url: {{ route('admin.category.edit', ?) }}`

And last but not least, doesn't this package require a file manager maybe ?

**Comment by blomdahldaniel** [comment]
the `{{  route('admin.category.edit', ?) }}` will yield an url like `admin/category/edit` or whatever you set it to. Then in your javascript you can append this with a javascript variable, lets call it `userID`

then your javascript would be:
```javascript 
let userID = // fetch data-id for ex: $(this).data('id')
// then later on when you give ajax url:
url: '{{ route("admin.access.user.get") }}' + '/' + userID,
```

To make it easier to understand, this would be the equal. But then you'll have a hardcoded url which might not be so good for bigger stuff.
```javascript 
let userID = // fetch data-id for ex: $(this).data('id')
// then later on when you give ajax url:
url: '/your/url/here/' + userID,
```

That way you can get the id be set by javascript.


On the other hand, in bigger applications you will want to avoid to have a lot of javascript within the blade file, probably you will want to extract the javascript to a `.js` file. Then you'll have to use hardcoded urls or a system to handle your resources.
