### ISSUE TITLE
When user confirmed email it is not authenticated user & redirected to dashboard

### ISSUE THREAD

**Issue by azulkipli** [rappasoft/laravel-5-boilerplate#52]
In AuthController when user confirmed email it is not authenticated user & redirected to dashboard

I see your code in 
https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Http/Controllers/Frontend/Auth/AuthController.php#L120

Try to redirect user to frontend dashboard but it not logged in.

in https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Repositories/Frontend/User/EloquentUserRepository.php#L187

no login attempt made.

How to fix this by redirect user instead to login page..?

**Comment by rappasoft** [comment]
I'm sorry I don't know if I fully understand what is not happening right?

**Comment by num3thod** [comment]
@azulkipli If I understand correctly, you will want to change the following redirect in the AuthController:
```
public function confirmAccount($token) {
		//Don't know why the exception handler is not catching this
		try {
			$this->auth->confirmAccount($token);
			return redirect()->route('auth/login')->withFlashSuccess("Your account has been successfully confirmed!");
		} catch (GeneralException $e) {
			return redirect()->route('auth/login')->withInput()->withFlashDanger($e->getMessage());
		}
	}
```
