### ISSUE TITLE
ramsey/uuid question

### ISSUE THREAD

**Issue by poseso** [rappasoft/laravel-5-boilerplate#521]
I saw in the packages when doing composer install that

  - Installing ramsey/uuid (3.5.1)

is this being used anywhere in the bp ? i have used it before but dont seem to find anything in the bp where it is used? just wondering

**Comment by Uebix** [comment]
Hello @poseso , the package ramsey/uuid is required by laravel/framework and not by the bp.

**Comment by poseso** [comment]
Ah ok thanks for your quick response, will close now
