### ISSUE TITLE
Carbon Localization 

### ISSUE THREAD

**Issue by activemonkeys** [rappasoft/laravel-5-boilerplate#526]
Hi - not sure whether this is a bug or I'm overlooking something. I have read the earlier closed threads for this excellent boilerplate on the localization of dates. However, I was still unable to localize the Carbon dates in the 5.3 version by just changing the language environmental variables in the .env file.

As a "dirty fix" I added "setLocale(LC_TIME, env('APP_LOCALE'));" in the \App\Http\Middleware\LocaleMiddleware handle function. This seems to work fine for the moment. However I believe this is not the right way to do it. 

Just interested whether others are experiencing a similar behavior with the localization of Carbon dates. 

Thanks,
Walt

**Comment by rappasoft** [comment]
The Carbon locale gets set both in LocaleMiddleware and AppServiceProvider, is it not working for you?

**Comment by activemonkeys** [comment]
That's right - as a test, please add the following line to a random blade template

{{\Carbon\Carbon::now()->formatLocalized('%A %d %B %Y')}}

In my case, when I change the language with the language selector, the date/time remains English (as specified in the .env file) 

Just wondering whether this is standard behavior or is related to my development setup (Laragon) or a bug? 

Thanks,
Walt

**Comment by blomdahldaniel** [comment]
I tried this out and the only language that does not take affect is Arabic and Thai. And to get that to work one could research the carbon locale for support there. 

So, I pasted in:
`{{\Carbon\Carbon::now()->formatLocalized('%A %d %B %Y')}}`
In the index page, changed the language from the language dropdown and it worked.

Does none of the languages work for you?

**Comment by activemonkeys** [comment]
Hej Daniel - Tack så mycket for checking. Just tried it again on a vanilla boiler-plate installation. Same problem. The date remains in its original language where the other (translated) parts of the website normally change when I choose another language. Tested all languages, none of them changes the carbon date. 

Only when I hardcode the language in the blade file, it works (example with french date): 

                    <?php setLocale(LC_TIME, 'fr'); ?>
                    {{\Carbon\Carbon::now()->formatLocalized('%A %d %B %Y')}}

Perhaps it has to do with my development environment (Laragon) or the session-driver (currently set to "file").  Will have another look... 

Walt

**Comment by activemonkeys** [comment]
Did some testing by changing the session-driver from "file" to "cookie", "database", "apc", "memcached", "redis" and "array". The problem remains the same. All texts are normally translated when changing the language with the language selector. It's just the carbon date that keeps its original language.  

For the moment I have created a work-around by adding the following line to my blade files

<?php setLocale(LC_TIME, (Session::get('locale'))); ?>

This seems to work fine.

**Comment by rappasoft** [comment]
If I switch it changes:

<img width="737" alt="screen shot 2016-11-03 at 16 40 54" src="https://cloud.githubusercontent.com/assets/6026504/19984350/5a284e34-a1e4-11e6-8aa4-46f3af33a8ec.png">

**Comment by activemonkeys** [comment]
Thanks Anthony - it's good to read that it works for both you and Daniel. I guess it must be something in my server setup (laragon) then. As mentioned I tested on a plain vanilla version of your nice boiler-plate with a laragon setup just out-of-the-box. With the work-around as mentioned above, it also works at my end so I'll close this topic. Thanks again for your effort. Much appreciated!

**Comment by rappasoft** [comment]
If you figure it out let everyone know in case someone else has the same issue, or there could be something wrong and Dan and I are the exceptions.

As long as you have it solved someway currently.
