### ISSUE TITLE
Currently Sign In User ID? 

### ISSUE THREAD

**Issue by Saad-Malik** [rappasoft/laravel-5-boilerplate#529]
How to get the current id of the user that is signed in ? I tried auth::id() but its not working?

**Comment by base-zero** [comment]
@Saad-Malik To access the currently authenticated user you will need to use the following code.

```php
Auth::user()->id
```
Or if you don't want to use the facade you can use the Laravel helper function

```php
auth()->user()->id
```

**Comment by minedun6** [comment]
the helper functio access ()->id () works just fine as well.

**Comment by Saad-Malik** [comment]
Thanks
