### ISSUE TITLE
Problem with Gulp

### ISSUE THREAD

**Issue by TwiSka** [rappasoft/laravel-5-boilerplate#53]
Gulp don't generate a new css with clean install. 

I use less, and the css don't change..

Why,

Thanks !

**Comment by blomdahldaniel** [comment]
Hi!
I think i have found the problem and a solution, change this code in the **gulpfile.js:**
#### from:
```
.less([ // Process front-end stylesheets
            'frontend/main.less'
        ], 'resources/assets/css/frontend/main.less')
```

#### to:
```
.less([ // Process front-end stylesheets
            'frontend/main.less'
        ], 'resources/assets/css/frontend/main.css')
```
So only change the file extension in the output format. Must have been too quick with the copy paste there @rappasoft 

So, change from **.less** to **.css** in the output parameter.

Then you should get the right css?

**Comment by blomdahldaniel** [comment]
I have now posted a pull request with a fix of the issue.
But you can of course change the **gulpfile.js** file on your own and then you should be back up and running. Hope this is the fix for you.

**Comment by rappasoft** [comment]
Merged. Thanks as always.
