### ISSUE TITLE
really struggling to add new routes with admin middleware

### ISSUE THREAD

**Issue by vesper8** [rappasoft/laravel-5-boilerplate#530]
I don't know if I'm just brainfarting here but I am really struggling and have been for over 2 hours so I figured I'd ask for help at this point.

Using the very latest 4.x branch. I am trying to add new routes that exist in one of my modules. The namespace is not Backend. I am wrapping the routes with this

Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {
    // my routes in here
});

I am pretty sure in the previous boilerplate that was all that was needed to secure custom routes with your admin middleware.

My logged in user has admin rights so he should be able to view everything.

Yet for some reason two things are happening that I don't understand. First, my routes don't have access to the authenticated user at all! Second.. I am super confused when you say "these routes require view-backend". You are essentially saying "these routes require a user with a role containing the permission "view-backend". Right? There is actually no place or no way to "assigns routes to permissions" ?

Can you please help out and let me know what I'm doing wrong here?

**Comment by rappasoft** [comment]
Sure there is.

Did you look to see what the admin middleware does? https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Http/Kernel.php#L40

It's wrapping 3 other middlewares.

If you want to wrap some routes that are protected from a permission you would use routeNeedsPermission middleware.

Plus, you shouldn't have to place prefix admin/middleware admin anywhere else as here: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/routes/web.php#L28 it is taken care globally for you. 

You can then dive down further within there to narrow your permissions, such as in the user management: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/routes/Backend/Access.php#L16

**Comment by vesper8** [comment]
Hi @rappasoft and thanks for replying. Sorry I couldn't answer back faster before you closed the issue.

I already knew about everything you said.. yet I am still having a problem. It seems to be because I am using routes and views loaded from a module's service provider. Let me try and explain and maybe you can shed some light on why I'm having these problems.

I did modify my folder structure and namespaces (within my modules) to include a Backend/Frontend structure by the way.

So, the following code works if I add it within the normal /routes/web.php

```
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
	/**
	 * These routes need view-backend permission
	 * (good if you want to allow more than one group in the backend,
	 * then limit the backend features by different roles or permissions)
	 *
	 * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
	 */
	require (__DIR__ . '/Backend/Dashboard.php');
	require (__DIR__ . '/Backend/Search.php');
	require (__DIR__ . '/Backend/Access.php');
	require (__DIR__ . '/Backend/LogViewer.php');
});

Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'middleware' => 'admin'], function () {
    Route::get('something', ['as'=> 'something.index', 'uses' => '\ModuleName\Http\Controllers\Backend\ModuleController@index']);
});
```

Notice I took out the as="admin." part from the Route::group but that doesn't matter, the above code works and the middleware gets applied and I am able to load my route and the associated views.

Now here's the weird part that's throwing me off.

In my app.php I include my module's service provider.

And inside my service provider I load my routes and views as explained in the 5.3 Laravel docs

```
    public function boot()
    {
        if (! $this->app->routesAreCached()) {
            require $this->modulePath . "/routes/api.php";
            require $this->modulePath . "/routes/console.php";
            require $this->modulePath . "/routes/web.php";
        }

        $this->loadViewsFrom($this->modulePath . "/resources/views", "{$this->moduleName}");
    }

```

All of this works fine in that my routes and their views work. The problem is when I try to add that same Route::group within my module's web.php. Then the middleware appears to get called but it doesn't have access to the authenticated User and so the middleware just throws me back to the dashboard

```
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'middleware' => 'admin'], function () {
    Route::get('something', ['as'=> 'something.index', 'uses' => '\ModuleName\Http\Controllers\Backend\ModuleController@index']);
});
```

Same exact code block as above. But when it's in the /routes/web.php it works, when it's in my module's /modules/mymodule/routes/web.php then it fails. The middleware gets called but fails as I noted above

I'm really puzzled why that is... any thoughts?

Many thanks

**Comment by vesper8** [comment]
Hrmm.. looks like I found my problem. I added the web middleware explicitly on top of the admin middleware and now I have access to the authenticated user and it works.

I guess this was being done automatically on any routes in the /app/ folder through the RouteServiceProvider

Does this sound correct to you? Anyway now it works.. wish I hadn't lost 2 hours over it... hope it helps someone else that's using a module approach

```
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'middleware' => ['web','admin']], function () {
    // routes
});
```

**Comment by rappasoft** [comment]
You shouldn't have to specify the web middleware since it is included in the admin middleware group, but maybe something you moved around messed with that?

**Comment by vesper8** [comment]
pretty sure I didn't move anything around that could affect this. Also your admin middleware loads the auth middleware.. not the web ? The web middleware is added via the RouteServiceProvider.

Pretty sure my problem is related to how I am loading routes via a custom package service provider. Anyway I think I'll do some more tests and reply back with any findings

**Comment by rappasoft** [comment]
Right sorry stumbling words.

What I meant was admin middleware should be all you need to secure routes behind a permission.

I'm currently in the middle of writing tests for everything. The frontend tests are done and you can pull from that branch if you want to test, going to start backend today.

**Comment by rappasoft** [comment]
Gonna close but reply back when you have anything.
