### ISSUE TITLE
Repository return boolean

### ISSUE THREAD

**Issue by minedun6** [rappasoft/laravel-5-boilerplate#533]
Hi, I don't know if the package is tightly coupled with vuejs or no but it seems that the repositories all return a boolean value instead of either the created/updated/deleted object so that maybe it can be picked up in the vuejs to be dealt with. I know that I can change the behaviour but maybe put this on your todo list for the upcoming versions so that it can useful. 
Last note is the fact that each time I add routes/packages I need to run 
`php artisan config:cache or php artisan route:cache` so maybe include these as well.

**Comment by rappasoft** [comment]
I'm not sure as I have not used Vue with it yet, you might need to give code examples.

**Comment by minedun6** [comment]
Will be sure ^^

Le jeu. 3 nov. 2016 15:28, Anthony Rappa <notifications@github.com> a
écrit :

**Comment by rappasoft** [comment]
Not sure what to do with this as I don't fully understand the question.
