### ISSUE TITLE
Security Fix: All users must read

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-5-boilerplate#534]
One of the users brought this to my attention.

Apparently Datatables doesn't escape html before outputting, which is resulting in an opening for XSS attacks, please apply this fix to any version of the BP you have that uses the Datatables jQuery plugin:

https://github.com/rappasoft/laravel-5-boilerplate/commit/4cdfcbf15feadbf2c63d4a61c531a5cd41086702

Also anyone with a BP version that has the History functionality will need to do this release:

https://github.com/rappasoft/laravel-5-boilerplate/commit/3b6956289cd50fe90619a29a95abce8f7eddba61

We might be able to find a work around later but for now this fixes.

**Comment by blomdahldaniel** [comment]
#### Note about the history change:
Worth noting is that all history that is already stored will have a `<strong>` wrapper in the database which causes the `<string>username</string>` block to be printed in raw text. So the history table will have to be emptied/refactored and then all new history will have the right syntax.

**Comment by rappasoft** [comment]
Correct unfortunately, it's just safer this way until there is a better solution.
