### ISSUE TITLE
[Help] Does the boilerplate provide some thing for making api calls ? 

### ISSUE THREAD

**Issue by Saad-Malik** [rappasoft/laravel-5-boilerplate#535]
Hi 

I want to make the api calls for login and sign up etc. Can you tell me if boiler plate provides something that i can start from? 

More over can you give suggestions on what is the best way to develops api in laravel ?

**Comment by rappasoft** [comment]
API calls to what?

**Comment by Saad-Malik** [comment]
For login and sign up etc


-------- Original message --------

**Comment by rappasoft** [comment]
Why would you need to do that?

**Comment by blomdahldaniel** [comment]
Are you thinking about making your own OAuth 2 application?
Or do you want to do the login through javascript entirely? Because in that case you have all you need with the current routes/api.
