### ISSUE TITLE
Sorry to ask this question here ....

### ISSUE THREAD

**Issue by vjaykoogu** [rappasoft/laravel-5-boilerplate#537]
I really like the design approach infact I'll use this for all my projects.. what this design pattern called as ?

**Comment by rappasoft** [comment]
Which one..?

**Comment by vjaykoogu** [comment]
This laravel  boilerplate

**Comment by vjaykoogu** [comment]
Keeping requests separate everything in repository etc

**Comment by rappasoft** [comment]
That's just my style. The requests is a Laravel feature that I prefer over keeping validation in the controllers. The repositories is called the Repository Pattern or the Repository/Interface pattern.

**Comment by vjaykoogu** [comment]
Why added  many controllers ex : user module

**Comment by vjaykoogu** [comment]
I mean there should be a reason right for adding separate controllers  ?

**Comment by rappasoft** [comment]
Yes if you listen to Laravel Podcase, the creator suggests if you have a controller with any more than the default CRUD methods, you should break them out to a different controller. Many small controllers are cleaner than one big one.

**Comment by vjaykoogu** [comment]
While creating the controllers from commandline u give complete path or just copy paste files ?

**Comment by rappasoft** [comment]
You'll get the same things regardless but I prefer to copy and paste because it's faster for me.

**Comment by vjaykoogu** [comment]
But one thing I'm facing difficulties understanding is middleware permission..  ex: I create new menu called categories. So permission is "View-backed "  ?

**Comment by rappasoft** [comment]
You would create a new permission called manage-categories and add it to whatever roles you wanted.

**Comment by rappasoft** [comment]
That's done in the seeder.

**Comment by vjaykoogu** [comment]
Ohhhh so you mean to say if I have 10 menus then I have to create 10 different permissions roles ?

**Comment by rappasoft** [comment]
Only if you want to give access to some people and not others. If everyone who enters the backend can do all the things, then you only need 1 permission.

**Comment by pebbo** [comment]
One question regarding the repositories: I understand that as kind of abstraction so that the underlaying source of data can be changed easily. Is that correct? Furthermore: Has anyone needed that pretty often in his career as a developer? Just asking out of curiosity.

**Comment by rappasoft** [comment]
I do it regardless of project size as it just promotes clean code. I have used the repository/interface model multiple times when using multiple APIs on the same project, to just be able to switch between them with 1 line of code.
