### ISSUE TITLE
Remember me not working

### ISSUE THREAD

**Issue by poseso** [rappasoft/laravel-5-boilerplate#538]
When you log in, it's supposed to log you out if you close the browser and open it again, but instead is keeping you logged in even if you don't check the remember me, is it just me?

The normal behavior should be if i log in do whatever and close the browser, i should be automatically logged out unless i have ticked the remember me button.

BP 4.0.8

**Comment by blomdahldaniel** [comment]
Yes, I can confirm this behaviour in:
- Chrome Canary
- Chrome
- Safari
- Mozilla

So there is definitely some bug involved here.

**Comment by poseso** [comment]
I think the problem relies on the SESSION_DRIVER, i changed on config/session.php 

    'driver' => env('SESSION_DRIVER', 'cookie'),  <- Default file

    'lifetime' => 120,

    'expire_on_close' => true,  <- this was on false


same on .env from file to cookie

now it's working good, maybe is a bug with the file session driver? but at least for now this has solved my problem

**Comment by poseso** [comment]
I see that is also working with database

php artisan session:table

php artisan migrate

and change cookie with database  its also working

**Comment by rappasoft** [comment]
I see, expire_on_close false is Laravel default. I wonder why.

Also, I think file driver would be better than cookie don't you?

**Comment by poseso** [comment]
i actually see that is working with file also, the only problem was expire_on_close set to false, being in true is working as expected, i also think file driver is better than cookie

**Comment by rappasoft** [comment]
Fixed
