### ISSUE TITLE
Package name changed, intentional?

### ISSUE THREAD

**Issue by mruzekw** [rappasoft/laravel-5-boilerplate#539]
I was looking at release 4.0.0 and I noticed in the `composer.json` that the package name changed. Was this intentional?

https://github.com/rappasoft/laravel-5-boilerplate/blob/2f3e2734efe3f81bd8084e7bc47ff68aeb166892/composer.json#L2-L3

**Comment by rappasoft** [comment]
Damnit no I probably started with a fresh composer file and forgot to change it X_X Thanks!
