### ISSUE TITLE
Cannot assign role and permission to user

### ISSUE THREAD

**Issue by insic** [rappasoft/laravel-5-boilerplate#541]
I am sorry if I miss something. But I see this working before but now after updating to the latest version I cannot assign role and permission to user during add new user and edit existing user.

**Comment by rappasoft** [comment]
This is why i'm writing tests. I found the problem and here's the fix. https://github.com/rappasoft/laravel-5-boilerplate/commit/5fa5a2fc6675947482146d46d5414c921774f4a8
