### ISSUE TITLE
confirmation code in User Registration

### ISSUE THREAD

**Issue by Saad-Malik** [rappasoft/laravel-5-boilerplate#544]
Can you tell me whats this confirmation code in user registration ? What can be the possible work around for creating a user using restful api

**Comment by rappasoft** [comment]
I don't understand what you mean. The confirmation code is the code that is sent to the user as a link in their email to confirm their account when they click it.

**Comment by Saad-Malik** [comment]
I want to create this confirmation code when a post request is made to create user through an ios app? Can you point me where is this confirmation code being generated in laravel ? Or which class is handling this ?

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Nov 16, 2016 at 8:13 PM +0500, "Anthony Rappa" <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't understand what you mean. The confirmation code is the code that is sent to the user as a link in their email to confirm their account when they click it.

-

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Repositories/Frontend/Access/User/UserRepository.php#L78

**Comment by Saad-Malik** [comment]
Thank you. :) thats what i was looking for.

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Nov 16, 2016 at 8:23 PM +0500, "Anthony Rappa" <notifications@github.com<mailto:notifications@github.com>> wrote:


https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Repositories/Frontend/Access/User/UserRepository.php#L78

-

**Comment by rappasoft** [comment]
Ok cool!
