### ISSUE TITLE
DataTables warning: table id=users-table - Invalid JSON response

### ISSUE THREAD

**Issue by poseso** [rappasoft/laravel-5-boilerplate#545]
I'm trying to change the adminLTE template with mine, however when i set:
@extends ('backend.layouts.app2') for my testing purposes i get invalid json response, how ever if i use the original backend.layouts.app it works well, the dialog that appears is:

DataTables warning: table id=users-table - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

is there anything i should know? or the way is working?

This happens on resources/views/backend/access/index.blade.php when i change the layout with mine

BP 4.0.10

**Comment by deditaryadi** [comment]
maybe you will need to include this script:
```

$.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
```

as defined in /resources/assets/js/plugins.js

and include this
```

        <script>
            window.Laravel = <?php echo json_encode([
                'csrfToken' => csrf_token(),
            ]); ?>
        </script>

```
in your app.blade.php

**Comment by poseso** [comment]
wow, it actually worked with the $.ajaxSetup i didn't figured out that was in the plugins.js since i just added to my app.blade:

        <script>
            window.Laravel = <?php echo json_encode([
                'csrfToken' => csrf_token(),
            ]); ?>
        </script>


with the ajaxSetup headers my problem is solved, thanks for the heads up
