### ISSUE TITLE
 Route [account.confirm.resend] not defined

### ISSUE THREAD

**Issue by digitalit** [rappasoft/laravel-5-boilerplate#547]
When i try to add my stuff in the new BP i get:

ErrorException in UrlGenerator.php line 314: Route [account.confirm.resend] not defined.

Why is that?

**Comment by nickfan** [comment]
i found that's a lang file issue,
resources/lang/nl/exceptions.php at line 54:

change 

```
route('account.confirm.resend', ':user_id')
```

into

```
route('frontend.auth.account.confirm.resend', ':user_id')
```

**Comment by blomdahldaniel** [comment]
@nickfan good call there. I dont know if that was the problem for @digitalit though?
I commited a fix for this in the development branch. Rappa will include that in the next version release.

@digitalit I cannot replicate this error.
Can you describe what actions that lead to this error?

I have tried:
- From frontend
  - Try to login before I have confirmed the new account
  - Click resend the email
  - Does that successfully
- From backend
  - Resend confirmation email from backend as admin successfully

**Comment by nickfan** [comment]
i got the same issue when i add some composer package to the application,and after review the error log, i found that must be the 'nl' lang file havn't update the route name after rewrite the route code.

**Comment by rappasoft** [comment]
Fixed.
