### ISSUE TITLE
bug with postgresql databases

### ISSUE THREAD

**Issue by gotrecillo** [rappasoft/laravel-5-boilerplate#548]
When seeding the boilerplate using postgresql there is an error because we are truncating history_types and there is a foreign key referencing history.

**Comment by rappasoft** [comment]
That's why there is a key check before and after for mysql, I don't use postgres so I don't know what the procedure is.

**Comment by gotrecillo** [comment]
it would be similar to roles seeder 

``` PHP
if (DB::connection()->getDriverName() == 'mysql') {
            DB::table('history_types')->truncate();
        } elseif (DB::connection()->getDriverName() == 'sqlite') {
            DB::statement('DELETE FROM history_types');
        } else {
            //For PostgreSQL or anything else
            DB::statement('TRUNCATE TABLE history_types CASCADE');
        }
}
```

**Comment by rappasoft** [comment]
Added to dev branch for next release thanks.
