### ISSUE TITLE
Master app yield question

### ISSUE THREAD

**Issue by digitalit** [rappasoft/laravel-5-boilerplate#550]
Why is it named 

before-styles-end and after-styles-end 

in stead of

before-styles and after-styles

is there an point with -end?

**Comment by minedun6** [comment]
Why are u then named peter and carlsson ?

Le ven. 11 nov. 2016 13:45, Peter Carlsson <notifications@github.com> a
écrit :

**Comment by digitalit** [comment]
Care to elaborate that?

**Comment by minedun6** [comment]
Its just a naming convention my friend i hope u didnt get offended

Le ven. 11 nov. 2016 13:50, Peter Carlsson <notifications@github.com> a
écrit :

**Comment by minedun6** [comment]
U can change it conveniently if u want ^^

Le ven. 11 nov. 2016 13:53, yassine ben slimane <yuginim@gmail.com> a
écrit :

**Comment by digitalit** [comment]
No problem, just that i'm rather new to blade so i was wondering if there were any reason for using -end in the yield.

In my world there often is an -start followed by and -end and i just felt that the -end was unnecessary.

**Comment by rappasoft** [comment]
Because if you look in the mater blade file: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/resources/views/backend/layouts/app.blade.php#L72

One gets placed before the master scripts end, and one gets placed after the master scripts end.

**Comment by digitalit** [comment]
Yes i get that, but why the -end, why dont:

` 
@yield('before-scripts')
 {{ Html::script(elixir('js/backend.js')) }}
@yield('after-scripts')`

**Comment by rappasoft** [comment]
I have no idea in my head it makes sense, this is the first time its come up in 3 years.

**Comment by digitalit** [comment]
Sorry for bringing it up, i was just confused :)

To make it more sense in that case it would be @yield('before-scripts-start') in the before yield :)

**Comment by poseso** [comment]
it has more sense before-scripts-end since you can have scripts above it and then you are telling  to put others before ends

**Comment by digitalit** [comment]
Ok

**Comment by blomdahldaniel** [comment]
I kind of agree that the `-end` postfix is redundant just like @rappasoft implied.
And I am not sure whether it should be changed. I will close this issue for now. feel free to make a PR or just change it in your own projects.
