### ISSUE TITLE
Carbon Set Locale in AppServiceProvider case error for some locale

### ISSUE THREAD

**Issue by nickfan** [rappasoft/laravel-5-boilerplate#551]
Current Code:

```
Carbon::setLocale(config('app.locale'));
```

that's wrong for locales settings , for example:

zh-CN as laravel locale code

zh as Carbon code 

zh_CN as php setLocale code

Fixed by:

```
Carbon::setLocale(config('locale.languages')[config('app.locale')][0]);
```

for version: dev-master

**Comment by rappasoft** [comment]
Fixed from PR
