### ISSUE TITLE
Decoding Html in Blade views using link_to_route function

### ISSUE THREAD

**Issue by benjacksondev** [rappasoft/laravel-5-boilerplate#553]
I am using the latest stable build of 5.2.. Currently 5.2.39.
When i use:
`{!! link_to_route('frontend.about-us', '<span class="caret"></span>'.trans('navs.frontend.about-us')) !!}`

The span tags are printed as plain text rather than as HTML.

**Comment by rappasoft** [comment]
Because you're using the blade syntax that does that. Use {{ }}

**Comment by benjacksondev** [comment]
So when I use:
`{{ link_to_route('frontend.about-us', '<span class="caret"></span>'.trans('navs.frontend.about-us')) }}`

I get the same output as:
`{!! link_to_route('frontend.about-us', '<span class="caret"></span>'.trans('navs.frontend.about-us')) !!}`

Ideally the output should be '(icon)About us' but the output is actually:
`<a href="http://final.dev/about-us">&lt;span class="caret"&gt;&lt;/span&gt;about us</a>`

**Comment by rappasoft** [comment]
You should not be getting the same thing, I was backwards {!! !!} is for unescaped data, so it should be printing your span tags.

https://laravel.com/docs/5.3/blade#displaying-data

**Comment by benjacksondev** [comment]
By default, Blade {{ }} statements are automatically sent through PHP's htmlentities function to prevent XSS attacks. If you do not want your data to be escaped, you may use the following syntax:
Hello, {!! $name !!}.

This is exactly what I want, hence starting off with the {!! $name !!} syntax. I do not want the data to be escaped, however neither syntax when wrapped in the link_to_route function is working.

**Comment by rappasoft** [comment]
Oh I didn't even realize, You cant put html in that function, that I know of. You have to just use route() inside an HTML A tag.

`<a href='{{ route(.frontend.about-us') }}'><span class="caret"</span> {{ trans('navs.frontend.about-us') }}</a>`

**Comment by benjacksondev** [comment]
No worries, Thanks man.
