### ISSUE TITLE
format date in resources\views\backend\access\index.php

### ISSUE THREAD

**Issue by poseso** [rappasoft/laravel-5-boilerplate#554]
I'm trying to change the date format but don't know how to here:

                {data: 'created_at', name: '{{config('access.users_table')}}.created_at'},
                {data: 'updated_at', name: '{{config('access.users_table')}}.updated_at'},

i would like to ->format('d-m-Y')

any guidance on where to look or how can this be accomplished?

Thanks

BP 4.0.10

**Comment by poseso** [comment]
should i add:

            ->editColumn('created_at', function ($user) {
                return $user->created_at ? with(new Carbon($user->created_at))->format('m/d/Y') : '';
            })
            ->editColumn('updated_at', function ($user) {
                return $user->updated_at ? with(new Carbon($user->updated_at))->format('Y/m/d') : '';
            })

on the UserTableController?

**Comment by rappasoft** [comment]
Yes that would probably work.

**Comment by poseso** [comment]
yeah it worked, thx
