### ISSUE TITLE
Repositories use of Eloquent

### ISSUE THREAD

**Issue by andrew-za** [rappasoft/laravel-5-boilerplate#556]
Any reason why the repositories save() / update() do not use Eloquent objects?

Instead call update method statically 
`parent::update()`

Should be:
`$user->update()`

**Comment by rappasoft** [comment]
The methods have the same name which is why you're calling the parent method. But they do expect Model instances: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Repositories/BaseRepository.php#L18

**Comment by andrew-za** [comment]
I just see that less code could be used:
Instead of:
`$user = $this->createUserStub($data);

DB::transaction(function() use ($user, $data, $roles) {
			if (parent::save($user)) {`

Rather something like this:
`$user = $this->createUserStub($data);

        if ($user->save()) {
            $user->roles->sync($input['roles']);
        }`

**Comment by rappasoft** [comment]
Transactions make sure all of the function in the closure has no issues before commiting, so I wouldn't get rid othat.

**Comment by minedun6** [comment]
for banking systems, transactions make sure that either everything is executed together or nothing is exectued. Let's say you're making a transfer of money which is saved and when you are about to get your receipient (this is a trash example, you can have email or other related logic related to that created transfer), there is a huge blackout or system went down with no reason, so the transfer is made but whatever comes next wasn't triggered, so big issues comes up that needs to be rolled back, transaction makes sure that whatever logic inside of it gets all executed or everything is rolled back which can be convenient in these kinds of systems and most of all, it's good practise.

```
DB::transaction(function() use (... $variables) {
    // logic to run
)};
```

**Comment by rappasoft** [comment]
Simplified in upcoming.
