### ISSUE TITLE
Enhancement: Cartalyst Sentinel

### ISSUE THREAD

**Issue by SuperlativeEntity** [rappasoft/laravel-5-boilerplate#56]
Now that Cartalyst Sentinel is open source, would you consider it?

**Comment by rappasoft** [comment]
What would make it so much better than what is already there?

**Comment by Teranode** [comment]
i honestly prefer the one rappasoft has implemented, you can basically configure it yourself. While with Sentinel being open source, support will be eventually limited later on, plus it's a burn as you would just be using a package dependency.

**Comment by SuperlativeEntity** [comment]
Each to their own.
