### ISSUE TITLE
How to manage groups and permissions in latest Laravel 5.3 Boilerplate

### ISSUE THREAD

**Issue by maheshvnit** [rappasoft/laravel-5-boilerplate#560]
![laravel-boilerplate - permission management - old](https://cloud.githubusercontent.com/assets/1824319/20460640/9fda3eaa-af0f-11e6-9079-71fb7bb25c38.png)
# How to manage groups and permissions in latest Laravel 5.3 Boilerplate?
- like in old version there was custom permissions, groups, group permisssions

**Comment by maheshvnit** [comment]
Old version have much feature as per access management, but latest these look removed.
If still there please tell us how to use it, to create groups and group permissions like old one.

**Comment by rappasoft** [comment]
We removed that for a simpler approach of just permissions and roles.

**Comment by rappasoft** [comment]
There's no UI to manage permissions because there's no reason they should change on the fly, instead you manage it in the seeder and reseed that one when you add or remove.

**Comment by maheshvnit** [comment]
Ok thanks, Any way thats was good to have group and permissions.

**Comment by maheshvnit** [comment]
Now we can not manage module level access, I was trying to use it specially because it had group permission and we can manage groups as module.

**Comment by minedun6** [comment]
Then you can have a look at 5.2 and get the code. He just wanted a more
easy to go boilerplate.

Le lun. 21 nov. 2016 09:48, Mahesh Prasad <notifications@github.com> a
écrit :

**Comment by rappasoft** [comment]
The only thing that changed was the removal of the UI, the rest of the functionality is still there. Groups were just a convenience factor, they weren't necessarily needed.
