### ISSUE TITLE
In the resource controller is how to achieve the instantiation model

### ISSUE THREAD

**Issue by dragon-D** [rappasoft/laravel-5-boilerplate#561]
I see you in the controller directly into the current id has been a good example of the model
```php
  public function edit(Role $role)
    {
        return view('backend.access.roles.edit')
            ->withRole($role)
            ->withRolePermissions($role->permissions->pluck('id')->all())
            ->withPermissions($this->permissions->getAll());
    }
```
here $role is http://127.0.0.1/admin/access/role/3/edit to return the role model object of id 3
Will here is how to achieve

**Comment by blomdahldaniel** [comment]
Hm.. I dont quite understand your question. Do you mean the route model binding in Laravel? Take a look at the Laravel Dokumentation, they explain how it works:
[Route Model Binding](https://laravel.com/docs/5.3/routing#route-model-binding)

Hope this helps.

**Comment by dragon-D** [comment]
I specified a route in the resource
```php
Route::resource('test', 'TestController');
```
and then visit the controller
Http://127.0.0.1/test/1/edit On the controller edit method
```php
    public function edit($id)
    {
        Model::find($id);
    }
```
Here I have to find (1) in order to get id 1 result set。
but I see you
```php
    public function edit(Role $role)
    {
        //$role A result set of 1 has been obtained
        return view('backend.access.roles.edit')
            ->withRole($role)
            ->withRolePermissions($role->permissions->pluck('id')->all())
            ->withPermissions($this->permissions->getAll());
    }
```
$role do not need to find($id) will be able to directly id = 1 object
Will here is how to achieve

**Comment by blomdahldaniel** [comment]
Okey, then I understand. It is done through Route Model Binding just like i wrote before. The Laravel dokumentation is great at explaining how it works.
[https://laravel.com/docs/5.3/routing#route-model-binding](https://laravel.com/docs/5.3/routing#route-model-binding)

So what happens is that when: 
```php
public function edit(Role $role)
```
Laravel understands that the Role model should be used and then expects the ID to be the route parameter to look for and then retrieve the user.

**Comment by dragon-D** [comment]
Very grateful, after reading the document to understand

**Comment by blomdahldaniel** [comment]
Glad it helped. The Laravel documentation is awesome. :)
