### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-5-boilerplate#562]
I've made a slack channel for this project. Please give me your email addresses so I can invite you.

**Edit:** Get your invite here: https://laravel-5-boilerplate.herokuapp.com

**Comment by poseso** [comment]
carlosmsanchez@gmail.com

**Comment by digitalit** [comment]
peter@digitalit.se

**Comment by minedun6** [comment]
yuginim@gmail.com

Le lun. 21 nov. 2016 17:37, Peter Carlsson <notifications@github.com> a
écrit :

**Comment by JuanVillagran** [comment]
jmvillagranfiallos@gmail.com

**Comment by hamzstramgram** [comment]
maxime.shz@gmail.com

**Comment by safoorsafdar** [comment]
safoor.safdar@gmail.com

**Comment by minedun6** [comment]
yuginim@gmail.com

Le mar. 22 nov. 2016 09:57, Safoor Safdar <notifications@github.com> a
écrit :

**Comment by marktopper** [comment]
marktopperdk@gmail.com

**Comment by rappasoft** [comment]
Everyone here so far should have an invite.

**Comment by wimnok** [comment]
wim@ekomurz.nl

**Comment by trixanapp** [comment]
trixanapp@gmail.com

**Comment by mikimaine** [comment]
mikias.amdu@gmail.com
