### ISSUE TITLE
Wiki: Link broken

### ISSUE THREAD

**Issue by DeDu** [rappasoft/laravel-5-boilerplate#563]
The link "View Suggested Packages" on the page "[Installation](https://github.com/rappasoft/laravel-5-boilerplate/wiki/1.-Installation)" seems to be broken . It points to https://github.com/rappasoft/laravel-5-boilerplate/wiki/8.-Suggested-Packages-&-Tutorials which doesn't seem to exist anymore.

**Comment by poseso** [comment]
its actually 7 now not 8


https://github.com/rappasoft/laravel-5-boilerplate/wiki/7.-Suggested-Packages-&-Tutorials

**Comment by blomdahldaniel** [comment]
Thanks guys, it is fixed now. 👍
