### ISSUE TITLE
Routing via Role 

### ISSUE THREAD

**Issue by stephenahiggins** [rappasoft/laravel-5-boilerplate#57]
Hi, 

Firstly, just to say that this piece of software has been invaluable to me over the past month. It has definitely saved me lots of time! 

Just a question about routing via permission. I can't seem to get it to work. 
I have three different roles: 'Administrators', 'Power Users' and 'Users'.
I would like to restrict access to certain routes for each of these roles?

Appologies, if it has been covered elsewhere.

**Comment by rappasoft** [comment]
Try this: https://github.com/rappasoft/laravel-5-boilerplate#route_middleware

**Comment by stephenahiggins** [comment]
Gha! Just seen it re-reading the Readme. Sorry!!
