### ISSUE TITLE
How can i create from logged user 

### ISSUE THREAD

**Issue by pc-mon** [rappasoft/laravel-5-boilerplate#572]
Hello
I get problem when I use Auth::user()->id or Auth::user()->post()->create([]) 
how can i get ID of logged user 
thank you

**Comment by poseso** [comment]
did you tried access()->id ?

**Comment by rappasoft** [comment]
id() is a method, there is also a $logged_in_user variable in the global scope you can use anywhere thats registered in the GlobalComposer.

**Comment by poseso** [comment]
remember that he may also be restricting sections by access so it should look for the acces()->id in that case? maybe im wrong but in my case it works or maybe the way i am managing it

**Comment by rappasoft** [comment]
No, $logged_in_user just calls access()->user(), access->id() calls auth()->id(). They both get the logged in user. If the rest of the code is correct he should be able to do $logged_in_user->post()->create([])

**Comment by rappasoft** [comment]
Or access()->user()->post()->create([])

**Comment by poseso** [comment]
exactly i always use with access()->

**Comment by pc-mon** [comment]
first thank you so much for huge of replying and it's worked well 
ok then which Model i have to write the relationship between post and user ?

**Comment by pc-mon** [comment]
It's worked well , thank you so much :)

**Comment by hexpit** [comment]
where $logged_in_user is set? I am unable to find its defenition.

**Comment by bryanrscott** [comment]
\app\Providers\ComposerServiceProvider
