### ISSUE TITLE
Best Then this code DB::table('users')->all()

### ISSUE THREAD

**Issue by pc-mon** [rappasoft/laravel-5-boilerplate#573]
Hello
thank you for great work 
It's question about code , to make it better 
this is my code Best Then this code DB::table('users')->all()
there any better then this code with model 
thank you in advance

**Comment by blomdahldaniel** [comment]
Hm.. I dont quite understand your question. But the same query csn be done through `User: :all()` if that is what you're looking for? 
Go read the dokumentation of Laravel Eloquent to learn more about it. 
https://laravel.com/docs/5.3/eloquent

**Comment by pc-mon** [comment]
yes it's worked well , thank you so much
