### ISSUE TITLE
Get Users in admin/access/user/get page

### ISSUE THREAD

**Issue by pc-mon** [rappasoft/laravel-5-boilerplate#575]
Dear
Hope you doing well 
I have problem with AJAX and one page , and i get error message : 
DataTables warning: table id=users-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7
As I followed the URL (http://datatables.net/tn/7) I get this page not found 
and this path : http://localhost:8000/admin/access/user/get is Page Not Found 
and thank you in advance

**Comment by vangelis183** [comment]
Hi,
did you changed the layout? Maybe you are calling DataTables twice.
About the path: http://localhost:8000/admin/access/user/get This should be called as POST Request and not GET

**Comment by pc-mon** [comment]
It's working well with artisan serve ,but not working with apache2 
I'm talking about this problem of user only

**Comment by blomdahldaniel** [comment]
Can you see the correct url when you do a `artisan route:list` on your apache2 machine?

I have hade a similar issue I think. And honestly I dont know what fixed it. DataTables is quite sensitive and when some tiny error exists on the backend, it lands as a DataTable error alert.

My way of solving this was actually to reset to most recent commit that worked and then, step by step, commit by commit, add on the new stuff.

If you find another solution, please explain how you solved it. Otherwice I'm afraid that you might just have to roll things back.. 😔

**Comment by pc-mon** [comment]
Error : /admin/access/user/get - No such file or directory
Route : POST      | admin/access/user/get                           | admin.access.user.get                    | App\Http\Controllers\Backend\Access\User\UserTableController
JS : 


    <script>
        $(function() {
            $('#users-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: 'http://localhost:8000/admin/access/user/get',
                    type: 'post',
                    data: {status: 1, trashed: false}
                },
                columns: [
                    {data: 'id', name: 'users.id'},
                    {data: 'name', name: 'users.name', render: $.fn.dataTable.render.text()},
                    {data: 'email', name: 'users.email', render: $.fn.dataTable.render.text()},
                    {data: 'confirmed', name: 'users.confirmed'},
                    {data: 'roles', name: 'roles.name', sortable: false},
                    {data: 'created_at', name: 'users.created_at'},
                    {data: 'updated_at', name: 'users.updated_at'},
                    {data: 'actions', name: 'actions', searchable: false, sortable: false}
                ],
                order: [[0, "asc"]],
                searchDelay: 500
            });
        });
    </script>

**Comment by pc-mon** [comment]
I think the problem in route , but I still have this problem

**Comment by blomdahldaniel** [comment]
Yes, that is likely. Anything in routes and sometimes also controllers seem to cause that error instead of throwing exceptions.

This is one of the reasons DataTables should be removed in my opinion.. #555

**Comment by vangelis183** [comment]
@pc-mon `Error : /admin/access/user/get - No such file or directory `
this states a get request for a post route.

If its working on `artisan serve` and not with apache maybe you should try using another localsystem like: laragon.org

**Comment by pc-mon** [comment]
in mac working as php artisan serve but not working with XAMPP
in ubuntu not working at all

**Comment by pc-mon** [comment]
Hello
when I change in route to be get instead of post , it's working but without result 
I hope I can find solution for this issue 
thank you in advance

**Comment by pc-mon** [comment]
ErrorException: Call to undefined method Yajra\Datatables\Engines\BaseEngine::withtrashed() in /var/www/mhj/mhj-hr-system/vendor/yajra/laravel-datatables-oracle/src/Engines/BaseEngine.php:407

**Comment by error500** [comment]
Having the same.
`App\Http\Controllers\Backend\Access\User\UserTableController
\\line 45 : this causes the problem
->withTrashed()`

**Comment by pc-mon** [comment]
fixed : "yajra/laravel-datatables-oracle": "^6.20"

**Comment by pc-mon** [comment]
Thank you so much

**Comment by pc-mon** [comment]
please change it in line 17 
https://github.com/rappasoft/laravel-5-boilerplate/blob/master/composer.json
thank you in advance

**Comment by error500** [comment]
@pc-mon : did you change to 6.2 and made composer update ? i tryed but get plenty of dependency errors !

**Comment by pc-mon** [comment]
Actually , Yes I did 
then in terminal I've received one message talking about clean the files and i select yes , after that i get in php , next i installed php7.0-gd , finial it's worked well

**Comment by error500** [comment]
shame on me "plenty of errors" was so ugly... but easy"

```
apt-get install php7.0-gd
composer update
```
