### ISSUE TITLE
PDOException: could not find driver

### ISSUE THREAD

**Issue by gridworkz** [rappasoft/laravel-5-boilerplate#581]
Hi:

I just did a fresh boilerplate download / install on a new Ubuntu 16.04. npm: 3.10.9 node: v6.9.2.

I did `phpenmod pdo_mysql` (then restarted apache2) but I can't seem to get rid of the `PDOException:  could not find driver` error after running `gulp` (then) `phpunit`. 

I'm running  - 

**PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )**
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies

php -i|grep PDO
PDO
PDO support => enabled
PDO drivers => mysql
PDO Driver for MySQL => enabled

Have you seen this before? 

Cheers,
Dave

**Comment by gridworkz** [comment]
Ah, forgot to install sqlite => `sudo apt-get install php7.0-sqlite`

Onward and sideways! Dave

**Comment by blomdahldaniel** [comment]
Aha! I have not seen that error before. Glad that you solved it and provided the solution. :)
Will close it for now.
