### ISSUE TITLE
Gulp watch issues with css compile.

### ISSUE THREAD

**Issue by jonathan-bird** [rappasoft/laravel-5-boilerplate#583]
In the latest version of the boilerplate for Laravel 5.3, I get the error with css files occassionally with gulp watch command run. Sometimes it works, others it doesn't. Unchanged gulpfile.js

```Error: ENOENT: no such file or directory, stat '/home/vagrant/Projects/others/someproject/public/build/css/frontend-f957367b10.css'```

The file isn't actually in there. Then I try gulp itself, and it works.

I'm running it within a vagrant homestead VM.

**Comment by num3thod** [comment]
Getting the same issue with regular old MAMP stack. Haven't really dug into it though.

**Comment by blomdahldaniel** [comment]
Hm.. Yeah, I have the same issue actually. Haven't bothered to dig deeper. But this is something we should look into.

**Comment by jonnywilliamson** [comment]
This is a huge issue for me at the moment.

I'd been following this conversation ( https://github.com/laravel/elixir/issues/626 ) on laravel-elixir prior to using this repository and I didn't realise how much it would bite me until this week.

It appears that calling `.webpack` in the gulpfile multiple times causes `gulp watch` but NOT `gulp` serious problems. It seems to get caught in a loop and then after a while just dies or thrown an error.

The way the current `gulpfile.js` is laid out, and my lack of knowledge in this area, means it might not be easy to NOT call `.webpack` multiple times.


At the moment I've had some limited success deleting the build folder first before running gulp watch like this

`rm -Rf public/build && gulp watch`

Maybe helps someone here.

**Comment by jonathan-bird** [comment]
Same here.

I'm fixing this at work atm and I've getting deeper into it. Seems to be referenced here: https://github.com/JeffreyWay/laravel-elixir-webpack-official/pull/15

**Comment by insic** [comment]
deleting `public/build/rev-manifest.json` will temporarily fix the issue and lets you run `gulp watch` again.

**Comment by blomdahldaniel** [comment]
Yes, this fixes it for me also! But why is it just a temporarily fix?

**Comment by eleftrik** [comment]
Same problem here. I run 

`rm -rf public/build; gulp watch`

but I get

```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: ENOENT: no such file or directory, stat '/Users/............/public/build/js/frontend-cbf5f8a76a.js'
    at Error (native)
```

Any idea? Thanks
