### ISSUE TITLE
Saving related models

### ISSUE THREAD

**Issue by minedun6** [rappasoft/laravel-5-boilerplate#584]
I'm trying to save a model with it's related relations :

`public function create($input)
    {
        $box = $this->createBoxStub($input);

        DB::transaction(function() use ($box, $input) {
            if (parent::save($box)) {

                $location = $this->location->find($input['location']);
                $worker = $this->worker->find($input['default_worker']);

                -> $box->location()->sync($location);
                -> $box->defaultWorker()->sync($worker);

                //event(new BoxCreated($box));
                return true;
            }

            throw new GeneralException(trans('exceptions.backend.access.users.create_error'));
        });

    }`

and this is the createboxstub

    `protected function createBoxStub($input)
    {
        $box = self::MODEL;
        $box = new $box;
        $box->code = 'BOX' . $input['code'];

        return $box;
    }`

but problem is that it outputs 'Call to undefined method Illuminate\Database\Query\Builder::sync/save/attach()'

I don't know why but it won't allow me to save the related model to the box model. Is there any way of going about this ?

**Comment by blomdahldaniel** [comment]
Is this specific to this project or boilerplate?

**Comment by minedun6** [comment]
no i just want to store the related model into the db but doesn't seem like the model is being persisted since it's inside a DB::transaction so it won't execute until everything is ok.
I'm just trying to make use of good practise and transactions are the best way to go about it, but for now i'm just making do with simply assigning the id frim input manually and not using eloquent related handling.

**Comment by blomdahldaniel** [comment]
Then I have to suggest that you adress this issue in the laravel or laracasts forum. It is nice that this community can help each other but we need to keep the issue-list clean and keep it related more strictly to the boilerplate. It is a lot of work for us to manage anyway.

So I suggest the laravel or laracasts forum or maybe try to ask for help in our slack channel.

**Comment by minedun6** [comment]
well it would seem this is related to this boilerplate my friend ^^.
Here's what I'm trying to acheive, you already have how to create a user, what I want to do is to hook in into the process of creating the user and then create a related worker on it. How can I go about this.

**Comment by minedun6** [comment]
so anything might worth the try ?
problem is that since most of the create/update methods on the repository returns a bool no way of chaining the methods.
