### ISSUE TITLE
Can someone help me to integrate Vuetify with the boilerplate?

### ISSUE THREAD

**Issue by ramesh-tr** [rappasoft/laravel-5-boilerplate#586]
Can someone help me to integrate https://github.com/vuetifyjs/vuetify with this boilerplate? 

It would be great if someone can provide me some guidelines to integrate.

**Comment by blomdahldaniel** [comment]
hm.. This is not a small question, and also not related to this boilerplate. Its rather a question of understanding javascript and VueJS.

First, you need to follow the instructions for how to use it in an [Existing project](https://vuetifyjs.com/quick-start). Use yarn/npm to install and then require it in

```javascript
import Vue from 'vue'
import Vuetify from 'vuetify'
 
Vue.use(Vuetify)

// Vue, main instance
//.....
  mounted () {
    this.$vuetify.init()
  }
//.....
```
I would suggest using webpack just like we do in this boilerplate.

If you need more help than this I think you should try to google a bit more, read the docs thoroughly for Vuetify and VueJS. Google for projects that does what you need, integrate vuejs and laravel.

As a help on the way, here's a laravel project that has VueJS 2.0 and vue-router wrapped up around a laravel structure. https://github.com/fagray/vuejs2-laravel53-starter

Good luck!

**Comment by ramesh-tr** [comment]
Thanks, @blomdahldaniel. 

I asked this question only because this boilerplate already includes Vue 2.0, and wanted to know the possibility of integrating different libraries without a lot of code refactoring/rewriting before starting my project.

**Comment by blomdahldaniel** [comment]
This boilerplate uses vue 2.0 but only with tiny examples, just like Laravel 5.3 does out of the box. You dont break anything if you would remove that (except of some tests for that maybe).
