### ISSUE TITLE
Backend > Log Dashboard : variable reports doesn't exist

### ISSUE THREAD

**Issue by error500** [rappasoft/laravel-5-boilerplate#589]
While accessing /admin/log-viewerss

`Undefined variable: reports (View: /var/www/laravel-5-boilerplate/resources/views/vendor/log-viewer/dashboard.blade.php)`

On  Merge branch 'release/4.1.4', Apache 2.4, php7, debian jessie

**Comment by error500** [comment]
@rappasoft  @blomdahldaniel  don't you have this issue ? is it my install ?

**Comment by poseso** [comment]
@error500 I also have this error

**Comment by poseso** [comment]
I fixed by doing   php artisan log-viewer:publish --force

then i had to redo my old changes

**Comment by poseso** [comment]
btw this happened to me only when I did a composer update since they updated chart js to v2.3.0, so they changed the script in the dashboard.blade.php to:

    <script>
        $(function() {
            new Chart($('canvas#stats-doughnut-chart'), {
                type: 'doughnut',
                data: {!! $chartData !!},
                options: {
                    legend: {
                        position: 'bottom'
                    }
                }
            });
        });
    </script>

and the old one is:

    <script>
        $(function() {
            var data = {!! $reports !!};
            new Chart($('#stats-doughnut-chart')[0].getContext('2d'))
                .Doughnut(data, {
                    animationEasing : "easeOutQuart"
                });
        });
    </script>

**Comment by rappasoft** [comment]
Fixed in upcoming release thanks.
