### ISSUE TITLE
How to make a POST request in frontend without authenication ? 

### ISSUE THREAD

**Issue by phihung93ap** [rappasoft/laravel-5-boilerplate#591]
I have  a form (and ajax POST) to collect customer feedback. It always redirect to login routes before controller can receive request. I don't know why. 
This is my controller 

```
namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class FeedbackController extends Controller
{
	public function test(Request $request)
	{      //some process here
		return response()->json("");
	}
}
```
My Route in Frontend.php

`Route::post('/feedback', 'FeedbackController@test');`

**Comment by blomdahldaniel** [comment]
And the route is placed outside of the route group with auth middleware?

**Comment by rappasoft** [comment]
Anywhere around here: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/routes/Frontend/Frontend.php#L9

**Comment by phosphore** [comment]
@rappasoft I created a Route Group in Frontend.php#L9 (outside the group with ['middleware' => 'auth']), but I still get redirected to the login page.
@phihung93ap how did you manage to solve this?

**Comment by pebbo** [comment]
show your code please. should be easy.

**Comment by phosphore** [comment]
@pebbo There's nothing strange or wrong in my code.
I had to add to the class `VerifyCsrfToken` in `app/Http/Middleware/VerifyCsrfToken.php` the URI of the route exclude it from CSRF verification.
```
    protected $except = [
        'myrouteuri/*',
    ];
```

**Comment by nittonfemton** [comment]
I have the same issue.

The POST route is sent to authentication screen.

`<?php

/**
 * Frontend Controllers
 * All route names are prefixed with 'frontend.'.
 */
Route::get('/', 'FrontendController@index')->name('index');
Route::get('macros', 'FrontendController@macros')->name('macros');
Route::get('jobs', 'FrontendController@jobs')->name('jobs');
Route::get('jobs/edit/{id}', 'FrontendController@displayjob')->name('displayjob');
Route::get('hits', 'FrontendController@hits')->name('hits');
Route::get('hits/load/{id}', 'FrontendController@loadhit')->name('loadhit');
Route::post('/hits/assignment/{id}', 'FrontendController@assignment')->name('assignment');
`

[Frontend.php.zip](https://github.com/rappasoft/laravel-5-boilerplate/files/975918/Frontend.php.zip)

**Comment by matthewmnewman** [comment]
Just to make you aware I experienced the same issue with Ajax but all you need to do is ensure that you add the X-XSRF-TOKEN to the header to your request. 
```
$.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
});
```
