### ISSUE TITLE
Add support for Full AdminLTE css

### ISSUE THREAD

**Issue by minedun6** [rappasoft/laravel-5-boilerplate#592]
Is it possible to have all the adminlte css features like the widgets they have or the other plugins already included ?
Would help a lot as the boilerplate would be complete.

**Comment by blomdahldaniel** [comment]
Hm.. What do you mean? Do you mean all the examples should be inside this boilerplate? (like inside the [demo](https://almsaeedstudio.com/themes/AdminLTE/index2.html) of AdminLTE?) 

I dont think that would be a good idéa. I (in my opinion) would not like to spend my first hour removing stuff from the boilerplate when creating a new project. The documentation and examples are good enough in the docs so it is easy to add them in. All the css and js is supported from in the demo. (Except some graphs and charts where you need to pull in external js, but the docs gives instructions for that.)

So, I think it is better if we keep it minimalistic and dont force too much onto the new project. Rather keeping it clean.
