### ISSUE TITLE
version 4.1.5, dropdown menu question

### ISSUE THREAD

**Issue by cutemonster** [rappasoft/laravel-5-boilerplate#593]
My dropdown menu for language and default user no longer working.
Could you tell me which js file to toggle it? 
![image](https://cloud.githubusercontent.com/assets/212361/21542376/22fba6ae-cd72-11e6-8d4e-69e6b525b7ae.png)

thanks!
Ken

**Comment by blomdahldaniel** [comment]
Do you have any errors if you open up browser console? (Mac: `cmd+alt+J` for Chrome)

**Comment by cutemonster** [comment]
No error on browser console.  I wonder what I did to overwrite it somewhere as if event is not fired.

**Comment by blomdahldaniel** [comment]
It is a bootstrap functionality there. Sure you have jQuery and the bootstrap js included in your project?

**Comment by cutemonster** [comment]
Thanks, I will try again and let me close this thread.

**Comment by blomdahldaniel** [comment]
I hope you'll find a solution
