### ISSUE TITLE
Russian language pack

### ISSUE THREAD

**Issue by schel4ok** [rappasoft/laravel-5-boilerplate#595]
Hi

I just download last version for L5.3 and started to preparing russian translation.
I did copy of **lang/en** folder, renamed it with **lang/ru**
Everything seems to be ok, except one thing.
In the menulist instead **Russian** I see **menus.language-picker.langs.ru**, though in config I added 

```
	'languages' => [
                ...
		'ru' 	=> ['ru', 'ru_RU', false],
                ...
	],
```

I think that it cannot understand ru_RU locale code, but it should be correct.
here is my [screenshot](https://yadi.sk/i/74k31yIf376uhG)

**Comment by trixanapp** [comment]
Add to 

'language-picker' => [
        'language' => 'Language',
        /**
         * Add the new language to this array.
         * The key should have the same language code as the folder name.
         * The string should be: 'Language-name-in-your-own-language (Language-name-in-English)'.
         * Be sure to add the new language in alphabetical order.
         */
        'langs' => [
            'ar' => 'Arabic',
            'da' => 'Danish',
            'de' => 'German',
            'en' => 'English',
            'es' => 'Spanish',
            'fr' => 'French',
            'it' => 'Italian',
			'nl' => 'Dutch',
            'pt-BR' => 'Brazilian Portuguese',
            'sv' => 'Swedish',
            'th' => 'Thai',
            'ru' => 'Russian',
        ],
    ],

in resources/lang/en/menus.php
and all languages files
example
'ru' => 'Русский',

P.S.
И посоветую хороший пакет в помощь к переводу:
Laravel 5.2 Translation Manager
 https://github.com/vsch/laravel-translation-manager
Хотел тож перевести, но... как то не нет времени...

**Comment by schel4ok** [comment]
yes. thanks
I just didn't know that I need to add 'ru' => 'Русский', in menus.php for other languages.
