### ISSUE TITLE
search

### ISSUE THREAD

**Issue by schel4ok** [rappasoft/laravel-5-boilerplate#596]
It is more enhancement request rather than issue.
Every site should have search functional and contact form. So maybe you add some in this boilerplate?

Seacrh using vuejs
https://github.com/RachidLaasri/laravel-scout-and-vuejs

Modal contact form using vuejs
http://taha-sh.com/blog/how-to-create-a-reusable-modal-box-in-laravel-vuejs

**Comment by rappasoft** [comment]
The search is only a stub as everyone implements search differently and we don't feel like dealing with PR's and issues with something that is really opinionated.

**Comment by blomdahldaniel** [comment]
Totally agree! 
This is a boilerplate, not a framework or cms. 

The boilerplate is supposed to be easy to dig into and dont force a lot of things that might be unnecessary for some people. Only bare minimum should be included, the rest is up to the Developer. :)
