### ISSUE TITLE
NPM install errors inside homestead

### ISSUE THREAD

**Issue by Mythos** [rappasoft/laravel-5-boilerplate#597]
I've installed homestead for my project and when I'm inside homestead and run ```npm install``` I'll get several errors.

I'm using laravel-5-boilerplate v4.1.5 and homestead v4.0.3.

Here's the npm-debug log:
[npm-debug.txt](https://github.com/rappasoft/laravel-5-boilerplate/files/691612/npm-debug.txt)

Somehow I've managed to install it before on my windows machine, but when I've run ```gulp``` I got the error, that ```node-sass``` was not found. So I tried to reinstall it.

**Comment by blomdahldaniel** [comment]
What version of node / npm do you have? 
Make sure everything is up ti date and match laravel requirements.

**Comment by Mythos** [comment]
Ah sorry, I had the node version in mind with knowing I'll need it before I started writing this issue. :P
This homestead version comes with following:

* Linux "project" 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* PHP 7.1.0-2+deb.sury.org~xenial+1 (cli) ( NTS )
* NodeJS v6.9.1

Also running it as "vagrant" (default user) or with sudo doesn't work.

**Comment by rappasoft** [comment]
Closed due to inactivity.
