### ISSUE TITLE
Error when same email for different providers

### ISSUE THREAD

**Issue by tinh1115** [rappasoft/laravel-5-boilerplate#6]
For i.e: if user using same email for facebook & google, then it will be error.

I think provider info should be in different table. one user can has many different provider based on same email. 

And then each row in provider info table will be mapped with a user_id in users table

**Comment by tinh1115** [comment]
I think this is a major change for this project. So I closed it issue. I fixed this problem by remove provider, provider_id from use table user_providers with provider, provider_id, user_id and some others. 

and also make a change at "findByUserNameOrCreate" method. This work for my project as it shoud support login via servial social media site.

**Comment by rappasoft** [comment]
This has been fixed with the last new release.

**Comment by tinh1115** [comment]
cool ^^
