### ISSUE TITLE
log-viewer error with route:cache

### ISSUE THREAD

**Issue by vesper8** [rappasoft/laravel-5-boilerplate#602]
Not sure if this is on my side but I've been dealing with this error for a long time and trying to fix it now.

Whenever I run php artisan route:cache I get this error, have tried googling it or figuring out what's causing it but can't

```
[LogicException]
  Unable to prepare route [admin/log-viewer/{date}/all] for serialization. Uses Closu
  re.
```

I'm aware that you can't use closures when you want to cache routes, but I can't figure out where this closure is! Is it part of the vendor package itself?

**Comment by digitalit** [comment]
Same here.

**Comment by prspace** [comment]
Route::group([
        'prefix' => '{date}',
    ], function () {
        Route::get('/', [
            'as'   => 'log-viewer::logs.show',
            'uses' => '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@show',
        ]);

        //TODO: Figure out why the default link isn't working
        Route::get('/all', function ($date) {
            return redirect()->route('admin.log-viewer::logs.show', [$date]);
        });

        Route::get('download', [
            'as'   => 'log-viewer::logs.download',
            'uses' => '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@download',
        ]);

        Route::get('{level}', [
            'as'   => 'log-viewer::logs.filter',
            'uses' => '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@showByLevel',
        ]);
    });

After

> //TODO: Figure out why the default link isn't working

 this line it's uses closer. Comment this line or move it to a controller to run `route:cache`

**Comment by rappasoft** [comment]
Fixed in upcoming release, see dev log.
