### ISSUE TITLE
Fresh Install - Failed Unit Tests

### ISSUE THREAD

**Issue by CoryDean** [rappasoft/laravel-5-boilerplate#604]
Boilerplate Version 5.3

There were 2 failures:

**1) UserRouteTest::testResendUserConfirmationEmail
A request to [http://l5boilerplate.dev/admin/access/user/3/account/confirm/resend] failed. Received status code [500].**

Caused by
Swift_TransportException: Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required
" in C:\xampp\htdocs\RealTSuite\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php:383

**2) LoggedOutFormTest::testLoginForm
Did not land on expected page [http://l5boilerplate.dev/admin/dashboard].**

Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'http://l5boilerplate.dev/admin/dashboard'
+'http://l5boilerplate.dev/login'

FAILURES!
Tests: 128, Assertions: 635, Failures: 2.

Process finished with exit code 1 at 11:01:23.
Execution time: 179,099 ms.

**Comment by rappasoft** [comment]
You need to be able to send mail, so install mailtrap.io which is what it was tested on.

**Comment by rappasoft** [comment]
<img width="588" alt="screen shot 2017-01-16 at 21 17 58" src="https://cloud.githubusercontent.com/assets/6026504/22005453/4708e1d8-dc31-11e6-9cc8-e244f258e6fa.png">

**Comment by CoryDean** [comment]
Okay. I've got the mailing test to pass, however, I am still getting the error:

LoggedOutFormTest::testLoginForm
Did not land on expected page [http://l5boilerplate.dev/admin/dashboard].

Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'http://l5boilerplate.dev/admin/dashboard'
+'http://l5boilerplate.dev/login'

**Comment by rappasoft** [comment]
Must be something with your setup, i'm on homestead. Haven't tested on MAMP/XAAMP.

**Comment by CoryDean** [comment]
I've figured this out. I made all Unit Tests specific to my environment.
