### ISSUE TITLE
Routes are not working

### ISSUE THREAD

**Issue by wasiqaftab** [rappasoft/laravel-5-boilerplate#606]
i am using latest repo i got this error on server. but it works fine on homestead

<code>
UnexpectedValueException in Route.php line 646:
Invalid route action: [App\Http\Controllers\Backend\Takeaway\addOnCategory\AddOnCategoryTableController]
</code>

**and here is the code in controller**
`
namespace App\Http\Controllers\Backend\Takeaway\AddOnCategory;

use App\Http\Controllers\Controller;
use App\Repositories\Backend\Takeaway\AddOnCategory\AddOnCategoryRepository;
use Yajra\Datatables\Facades\Datatables;

use App\Http\Requests\Request;

/**
 * Class UserTableController
 */
class AddOnCategoryTableController extends Controller
{
	/**
	 * @var UserRepository
	 */
	protected $addOnCategory;

	/**
	 * @param UserRepository $users
	 */
	public function __construct(AddOnCategoryRepository $addOnCategory)
	{
		$this->addOnCategory = $addOnCategory;
	}

	/**
	 * @param ManageUserRequest $request
	 * @return mixed
	 */
	public function __invoke() {

		return Datatables::of($this->addOnCategory->getForDataTable())
			->addColumn('actions', function($addOnCategory) {
				return $addOnCategory->action_buttons;
			})
			->make(true);
	}
}

`
**and here is the code in route**

<code>
Route::group([
    'prefix'     => 'takeaway',
    'as'		 => 'takeaway.',
    'namespace'  => 'Takeaway\addOnCategory',
], function() {

    /**
     * Settings Specific Functionality
     */

    /**
     * User CRUD
     */

    Route::resource('/addOnCategory', 'AddOnCategoryController');
    Route::get('addOnCat/get', 'AddOnCategoryTableController')->name('addOnCategory.get');
});
</code>

**Comment by poseso** [comment]
i think it should be:

Route::get('addOnCat/get', 'AddOnCategoryTableController')->name('addOnCategory.get');
Route::resource('/addOnCategory', 'AddOnCategoryController');

**Comment by wasiqaftab** [comment]
@poseso didnt work like that

**Comment by gbaudoin** [comment]
AddOnCategoryTableController is the name of the controller, you have to specify a method like AddOnCategoryTableController@get.

See https://laravel.com/docs/5.3/controllers#resource-controllers

Please do not open issues on github for your code, come discuss it it the Slack chatroom ( http://laravel-boilerplate.com/ )
