### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-5-boilerplate#609]
I know Laravel 5.4 released today, but don't expect an update right away as I first have to wait for Laravel Collective to update their repositories to 5.4.

Also, since they changed almost everything about Vue and Webpack/Gulp/Mix whatnot, I'll probably refactor that whole thing.

Or I might just start from a fresh 5.4 installation if it becomes a problem. 

Patience is appreciated.

**Comment by poseso** [comment]
👍

**Comment by derekphilipau** [comment]
And I just got comfortable with 5.3 :(  Awesome job on boilerplate, take your time!

**Comment by LunarDevelopment** [comment]
It's an issue in the industry when even the frameworks you adopt have
themselves shiney syndrome.

**Comment by jonnywilliamson** [comment]
Thank you @rappasoft .

**Comment by JPurinsh** [comment]
Hey, i was wondering, whats the progress here? :)

**Comment by rappasoft** [comment]
Waiting for laravel collective to update before I start.

**Comment by glaubersp** [comment]
They've created branch 7.0 for Laravel 5.4 support, @rappasoft .

**Comment by rappasoft** [comment]
I've migrated most of the files over minus the tests (Dusk?) and the assets because i'm having a hard time figuring our laravel mix as it doesn't work the same as elixir and they find it necessary to change this in every version. So i'm trying to find more documentation since the laravel docs lack in this section.

**Comment by derekphilipau** [comment]
@rappasoft, you could check out Spark 4 and see how they got mix working.  personally, I'm trying my best to ignore 5.4 while I learn Vue 2.

**Comment by digitalit** [comment]
Also focusing on learning Vue 2 and the procedure to upgrade to 5.4 was not at all difficult BoilerPlate-wise but some of my packages i needed messed things up so im sticking to 5.3 for now.

All though i have some recommendations regarding Vue 2 and that is to start working with Axios in stead of vue-resource since 5.4 has gone over from soon to be deprecated vue-resource to Axios. 

Correct me if im wrong but here is what i did:

In bootstrap.js change 

```
window.Vue = require('vue');
require('vue-resource');

Vue.http.interceptors.push((request, next) => {
    request.headers.set('X-CSRF-TOKEN', Laravel.csrfToken);
    next();
});
```

to

```
window.axios = require('axios');

window.axios.defaults.headers.common = {
    'X-Requested-With': 'XMLHttpRequest'
};
```

and in package.json change 

```
"vue-resource": "^1.0.3"
```
to 

```
"axios": "^0.15.3"
```

This way you dont have to change any Vue-code when moving to 5.4 later.

**Comment by V0rtexIMS** [comment]
Hey guys! I was also wondering what is the progress with the update? No pressure though :)

**Comment by digitalit** [comment]
God im eager to move to 5.4 :) I have been trying Vue in 5.4 and man do i like the new laravel-mix, it's lightning fast and the watch works great.

Keep up the god work @rappasoft :)

**Comment by rappasoft** [comment]
Anyone know if this RTL CSS thing will still work with laravel mix since its built on webpack?

**Comment by rappasoft** [comment]
Dev branch is now up to speed with what i've been working on: https://github.com/rappasoft/laravel-5-boilerplate/commit/e538a893513d79b7e4e148841a6b3474994549b0

Major Outstanding:

- Tests
- RTL CSS Support
- Backend Datatables currently not working
- JSON Lang Files (Maybe)

Minor/Upgrades:

- Magic Facades
- Simplify Repositories
- Give History Class Fluent API


Other small things.

Please feel free to make PR's to help as I am low on time hence why it's taking so long.

Big shout out to @jonphipps for the help thus far.

**Comment by activemonkeys** [comment]
Thanks Anthony. Great job! (as always). Just installed the new version and all went smoothly. Will do some further testing. 

As for the documentation, please add "npm run dev" in order to create the necessary css and js files.

**Comment by rappasoft** [comment]
Yes the documentation I will duplicate and update what's changed so older versions are available.

I'll do the documentation before I merge master, but there's still much to do as anticipated.

**Comment by rappasoft** [comment]
See these 2 commits for my RTL solution:

https://github.com/rappasoft/laravel-5-boilerplate/commit/34eaa2b93298f7c873c55ebcb26fc5e347180698
https://github.com/rappasoft/laravel-5-boilerplate/commit/412b6e1d253898d13f7849faed0342f08dc89222

**Comment by rappasoft** [comment]
Current dev branch looking almost done. Will probably release in the next few days, still have to do the new docs.

**Comment by arikazukito** [comment]
select2, datapicker and ck editor are not integrated in laravel 5.4, 
i have installed saperately too but i think due to mistake in order it is not being running.
