### ISSUE TITLE
Enhancement: How would I let users log in using either their username or email from a single input field?

### ISSUE THREAD

**Issue by mbsvpn** [rappasoft/laravel-5-boilerplate#61]
How would I let users log in using either their username or email from a single input field?

**Comment by rappasoft** [comment]
You will have to alter App\Repositories\Frontend\Auth\EloquentAuthenticationController@login to not use laravel Guard's default login functionality, which uses e-mail, but instead make you own that checks for either username or email address.

I can make this in a later release.
