### ISSUE TITLE
excel

### ISSUE THREAD

**Issue by schel4ok** [rappasoft/laravel-5-boilerplate#615]
I am a little bit confused. I see config file excel, but  I don't see maatwebsite/excel in composer.
So what excel config is doing?

**Comment by rappasoft** [comment]
I believe the datatables plugin has it has an option to export as CSV or something of the like.

**Comment by schel4ok** [comment]
ok. I see it in yajra/laravel-datatables-oracle dependencies

**Comment by howdu** [comment]
After updating I was getting a similar error about missing excel class. I had to manually run: composer require phpoffice/phpexcel

  Class 'PHPExcel_Shared_Font' not found
