### ISSUE TITLE
Frontend/Backend [Question]

### ISSUE THREAD

**Issue by digitalit** [rappasoft/laravel-5-boilerplate#616]
I see many projects that divides frontend and backend. As i learn more and more Vue i realize i want to use it for frontend client side. 

I find my selfe replacing Blades with pure Vue more and more.

Is there any chance you would make an Boilerplate that separates Frontend Vue and Backend Laravel cause this would be so great?

Thank you for making my Laravel life easier :)

**Comment by rappasoft** [comment]
Shouldn't Vue be components in your blade files?

I think what you want would be inconvenient for 90% of the community as people use Vue as components of views and not the views themselves.

At least that's how I see it, then again I don't use it.

**Comment by digitalit** [comment]
Well you can use Vue as isolated components in blade, this is how i use Vue right now. 

The frontend and backend use of Vue and Laravel im talking about is to use Vue for all clientside browser stuff and Laravel to feed it.

With this setup the blades is never used at all, everything you see in browser is pure Vue and content is handled by connecting via API to Laravel.

This is not an proposal to change to the fantastic Laravel-BP but maybe in the future another great Rappa project.

When you take your skills and dive into the Vue lake i think we will see an Laravel-Vue Boilerplate that is off the hook :)

**Comment by Jovian** [comment]
@digitalit , and what about SEO? It will be a problem, no?

**Comment by digitalit** [comment]
I think you can use Vue as an MPA and with vue-router mapping "real urls" for Google to index.

Im still enjoying the hybride way with Laravel handling the routes in the menu and when i click on customers i load an Vue SPA called customers.js in customers/index.blade.php that contains all customer stuff like orders, projects and so on.

This way i only load the required js for each part of my page.

I also use Vuex to store values in separate modules for each sub function, this way i can easily use values across my different Vue components.

**Comment by rappasoft** [comment]
I wish I could help more but honestly I haven't had time to dive into Vue. I have a bunch of videos lined up for when i get a chance. Trying to release the next version of the BP.

**Comment by digitalit** [comment]
Im not sure i will ever use pure Vue, as long as i can use it on parts of the BP I'm totally satisfied.

**Comment by rappasoft** [comment]
Will revisit in the future when I know how to code Vue lol.
