### ISSUE TITLE
Save in History

### ISSUE THREAD

**Issue by pc-mon** [rappasoft/laravel-5-boilerplate#618]
Hello
Thank you for this an amazing Admin Dashboard 
I just have issue how to save all my logs in history table as users table 
thank you in advance

**Comment by rappasoft** [comment]
I don't think I understand the question.

**Comment by pc-mon** [comment]
ok,Login or register ..etc for user actions will save it all in History table in database, I'm looking to use it in another applications not only user changes or login

**Comment by rappasoft** [comment]
http://laravel-boilerplate.com/documentation.html#history-management

**Comment by pc-mon** [comment]
Yes, It's really what I'm looking for!
thank you so much
