### ISSUE TITLE
BP 5.4 Failing on composer install

### ISSUE THREAD

**Issue by poseso** [rappasoft/laravel-5-boilerplate#622]
I downloaded the project and hit composer install and get this error:

Generating autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize

  [Symfony\Component\Debug\Exception\FatalErrorException]
  syntax error, unexpected 'namespace' (T_NAMESPACE)

Script php artisan optimize handling the post-install-cmd event returned with error code 255

I tried:

composer update --no-scripts
then
composer dump-autoload -o
then
composer update 

and getting the same error, any ideas of what could be wrong ?

**Comment by rappasoft** [comment]
It has something to do with the new routes, for some reason only works on PHP >= 7 right now, looking in to it.

**Comment by Jovian** [comment]
Trying to install via `composer update` and getting the same error, using php 7.1.

**Comment by rappasoft** [comment]
It should work with 5.6 though, laravel 5.4 only requires 5.6 so I don't know if they just didn't test it with 5.6.

**Comment by Jovian** [comment]
I've tested with PHP 5.6.28 and bare Laverel works fine, while this Boilerplate throws error as shown in the first message of this topic.
With PHP 7.10 i have no issues now.

**Comment by amamarul** [comment]
Hello,
the problem is in Route::namespace(...
I change (   // Route::namespace('Access')->prefix('access')->as('access.')->group(function () {   )
 for   (  Route::group(['namespace' => 'Access', 'prefix' => 'access' , 'as' => 'access.' ], function () {  )
there are some groupes like this

**Comment by poseso** [comment]
I also made a few changes and is working all good now at the moment, i have tested everything and got no errors so far, I tried with PHP 5.6.25 and PHP 7.0.10 and is working on both,

on routes\backend\Access.php i changed line 6 with:

Route::name('access.')->prefix('access')->namespace('Access')->group(function () {

and line 13 with:

Route::group(['namespace' => 'User'], function() {

and line 64 with:

Route::group(['namespace' => 'Role'], function() {

Then routes\backend\Search.php Line 4 with:

Route::name('search.')->prefix('search')->namespace('Search')->group(function () {

Then routes\frontend\Access.php Line 7 with:

Route::name('auth.')->namespace('Auth')->group(function () {

And routes\frontend\Frontend.php line 15 with:

Route::name('user.')->namespace('User')->group(function () {

and last routes\web.php line 17 with:

Route::name('frontend.')->namespace('Frontend')->group(function () {

**Comment by poseso** [comment]
@rappasoft can you please confirm? I think Route::namespace doesnt exist but with the lines I changed it works perfectly on php 5.6.* and 7.*

**Comment by anthony-caretraxx** [comment]
Yeah i'm looking theres no docs for the new routes so I'm just guessing syntax.

**Comment by rappasoft** [comment]
Here I wrote some tests: 58e5f6f#diff-2206cb09f6b693b1e15bfc9ae5d341d0

**Comment by rappasoft** [comment]
This should fix it: https://github.com/rappasoft/laravel-5-boilerplate/commit/456bfe8076d26c7e4ed73a1fb7bd74828b246869
