### ISSUE TITLE
Compiled assets are huge. Laravel 5.4 [Question]

### ISSUE THREAD

**Issue by Jovian** [rappasoft/laravel-5-boilerplate#627]
http://i.imgur.com/RDnsr1M.png

I think it's too much for frontend.js on a freshly installed Boilerplate.
Yes, it's compiled with `-dev`, but anyway too much.

I wonder if anyone of you separates bootstrap (vendor) javascript and/or uses CDN?
As I understand right. if we use separate JS plugins files as they are spread across many websites, there is a chance, that user will have them already cached.

Just wondering, how you -- prof. developers -- managing assets. What's your preferred way?

**Comment by rappasoft** [comment]
When you take into consideration the amount of functionality in those files I don't think its too much. This is all web packs fault, but that's the way laravel is by default so that's how I did it.

**Comment by Jovian** [comment]
@rappasoft, what do you think about this:

[Vendor Extraction](https://laravel.com/docs/5.4/mix)

> One potential downside to bundling all application-specific JavaScript with your vendor libraries is that it makes long-term caching more difficult. For example, a single update to your application code will force the browser to re-download all of your vendor libraries even if they haven't changed.

If you intend to make frequent updates to your application's JavaScript, you should consider extracting all of your vendor libraries into their file. This way, a change to your application code will not affect the caching of your large vendor.js file. Mix's extract method makes this a breeze:

**Comment by howdu** [comment]
Plus we'll have http2 soon enough where concatenating is less beneficial
