### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by poseso** [rappasoft/laravel-5-boilerplate#632]
@rappasoft Where are you reading about Route::as   and Route::namespace ?  where are you getting this?

Because they dont work for me, just curious about where are you reading about this?

btw the master is 5.4?

**Comment by amamarul** [comment]
Hi,
I already fixed that and I made a pull request
Is very simple to fix, look at this
https://github.com/amamarul/laravel-5-boilerplate/commit/e286cb82c667a915da1d9d039728df0c75fbba0b
Good luck
Maru

**Comment by rappasoft** [comment]
https://laravel-news.com/route-improvements

Yes master is 5.4

**Comment by poseso** [comment]
I don't see any Route::namespace or Route::as in there....

**Comment by rappasoft** [comment]
I assumed the syntax and it works for me on PHP 7.1

**Comment by rappasoft** [comment]
Restored routes to old syntax until laravel properly documents them.
