### ISSUE TITLE
Trigger Email Verification on Change Email

### ISSUE THREAD

**Issue by gcshri** [rappasoft/laravel-5-boilerplate#636]
Looking at app/Repositories/Frontend/Access/User/UserRepository.php, I can see this is where the user email is updated, in the updateProfile function.

~~~~
if ($user->canChangeEmail()) {
            //Address is not current address
            if ($user->email != $input['email']) {
                //Emails have to be unique
                if ($this->findByEmail($input['email'])) {
                    throw new GeneralException(trans('exceptions.frontend.auth.email_taken'));
                }

                $user->email = $input['email'];
            }
        }
~~~~

My question - the new email that the user enters, is unverified. 

Can someone give me some pointers on how I could reset the confirmed field for the user and send them a new verification message? 

Looking for a good way to do this, as I am on day two of testing the boilerplate.

**Comment by rappasoft** [comment]
You can store the new email in a temporary database column, or a session some how and fire the UserNeedsConfirmation notification (you will need to modify some stuff) and when its confirmed replace the current email address with the temporary one. Or something like that.

**Comment by gcshri** [comment]
Thanks, that is what I was sort of thinking about. Will work on it and update appropriately.

**Comment by rappasoft** [comment]
Here I took a simpler approach and did it for everyone: https://github.com/rappasoft/laravel-5-boilerplate/commit/94c77e600f8616216811775607b1141e1a7c6815

Tested and works.
