### ISSUE TITLE
where is the function :onlyTrashed()   ????

### ISSUE THREAD

**Issue by cnsecer** [rappasoft/laravel-5-boilerplate#640]
### code 
[https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Repositories/Backend/Access/User/UserRepository.php#L104](https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Repositories/Backend/Access/User/UserRepository.php#L104)

**Comment by cnsecer** [comment]
@rappasoft

**Comment by rappasoft** [comment]
This is default Laravel functionality that queries the deleted at column.

**Comment by cnsecer** [comment]
thank you
