### ISSUE TITLE
Gulpfile missing?

### ISSUE THREAD

**Issue by blissio** [rappasoft/laravel-5-boilerplate#646]
Installing the latest issue from the installation instructions shows no gulpfile.js - resulting on gulp returning errors:

`Local gulp not found in ~/sites/demo`

Gulp is successfully installed, but there seems to be no gulpfile.js in the repo.

**Comment by mikimaine** [comment]
The latest version of Boilerplate uses webpack .

**Comment by blissio** [comment]
Thanks Miki, that explains it 👍

**Comment by jatiyanon** [comment]
could you please explain step by step installation (difference from the website Quick Start) for newbies like me.

**Comment by mikimaine** [comment]
Create a separate thread with descriptive title and i will explain you there so that other's will also find it easily.
