### ISSUE TITLE
gulpfile.js  Local gulp not found in

### ISSUE THREAD

**Issue by phuongphally** [rappasoft/laravel-5-boilerplate#649]
I can not found this file .
[09:36:40] Local gulp not found in c:\xampp\htdocs\po
[09:36:40] Try running: npm install gulp

**Comment by amamarul** [comment]
Hello,
Laravel 5.4 now uses Laravel Mix, you must run `npm run`
_see that:_ https://laravel.com/docs/5.4/mix
_Other similar issues_
https://github.com/rappasoft/laravel-5-boilerplate/issues/646
https://github.com/rappasoft/laravel-5-boilerplate/issues/633

**Comment by phuongphally** [comment]
@amamarul 
Hello , 
Thank for your reply fast.

Thanks.

**Comment by amamarul** [comment]
You're welcome.
I know exactly what you feel when you are working and you need help at that moment.
I just saw your question and knew the answer, so I answered
Regards, 
Maru
