### ISSUE TITLE
HELP:: adding Profile model

### ISSUE THREAD

**Issue by barantr90** [rappasoft/laravel-5-boilerplate#651]
Hello to every one.
I want to add a Profile table for my project but when I try to access profile information I cant...
Here is my codes. How to connect relationship with user and profile models?
Thank you.

App\Models\Access\Profile\Traits\Relationship\ProfileRelationship.php
`public function user()
    {
        return $this->belongsTo(config('auth.providers.users.model'), config('access.profile_user_table'), 'profile_id', 'user_id');
    }`

App\Models\Access\User\Traits\Relationship\UserRelationship.php
`public function profile()
    {
        return $this->hasOne(config('access.profile'), config('access.profile_user_table'), 'user_id', 'profile_id');
    }`

btw It will be really good, if you add a "adding new model, model relationships" etc. on documentation.

**Comment by cutemonster** [comment]
what error did you get?

**Comment by barantr90** [comment]
I didnt get any error. 
I cant doing relationships. Actually I just want to learn how can I add a model and do hasOne, belongsTo rekationships.

**Comment by cutemonster** [comment]
Assume you have profile table set up.
you can check with code like this

````
  $user = User::find(1);
  $profile = $user->profile();
  dd($profile);
````

**Comment by amamarul** [comment]
it is a relationship, to get them is without "()", if you put the "()" you will get the QueryBuilder
```
  $user = User::find(1);
  $profile = $user->profile;
  dd($profile);
```
You use the "()" you can update data. For example:
```
$user->profile()->phone = '451';
$user->save();
```
