### ISSUE TITLE
A missing package in composer.json?

### ISSUE THREAD

**Issue by Sarahphp1** [rappasoft/laravel-5-boilerplate#658]
Hi there! 
I noticed this line in laravel-5-boilerplate/config/datatables.php:
`
        /**
         * Default fractal serializer.
         */
        'serializer' => League\Fractal\Serializer\DataArraySerializer::class,
`
But, I don't see the package called 'League\Fractal' in composer.json. My IDE is complaining, so I am wondering if it's an important library.
The yajra/laravel-datatables suggested it but did not require it here:
[https://github.com/yajra/laravel-datatables/blob/7.0/composer.json](url)

Excellent laravel boilerplate by the way. Thanks for all your hard work.

**Comment by rappasoft** [comment]
Its not required unless you want to use that functionality, so I didn't force it.

**Comment by Sarahphp1** [comment]
ok, great.
Thanks
