### ISSUE TITLE
Backend footer jumps to middle of page on refresh

### ISSUE THREAD

**Issue by newpain01** [rappasoft/laravel-5-boilerplate#660]
Hi,

I am trying to figure out why the footer on the backend jumps up to the middle of the page on refresh, it's pretty annoying and looks bad. If anyone has a possible solution, please let me know. Here is a screenshot that I took in the middle of refresh:

![l5boilerplate](https://cloud.githubusercontent.com/assets/22168845/24109847/d9d798e8-0dcc-11e7-8c46-26a32dba3a53.png)

**Comment by poseso** [comment]
Maybe a div not closed

**Comment by newpain01** [comment]
@poseso thank, I will go through the code to see if there is some div. The thing is that, the same problem happens to the original laravel-5-boilerplate

**Comment by poseso** [comment]
ah! ok now I understand what you meant, in that case you could use something like http://git.blivesta.com/animsition/fade/  for the page transitions, it's really nice

**Comment by newpain01** [comment]
yea, it's just a flash, anytime you refresh the page the footer just jumps up in a second and goes back.
This fade plugin will cover that, yea.
Thanks

**Comment by rappasoft** [comment]
If you find a solution (though I don't think its a big deal) and it's not a lot of added baggage you can make a PR for it if you want.
