### ISSUE TITLE
Phpunit test can fail

### ISSUE THREAD

**Issue by rikaix** [rappasoft/laravel-5-boilerplate#661]
#laravel-5-boilerplate 5.4
most warning than issue

## Phpunit tests fails if :

You don't have activated sqlite plugin (PHP PDO), in my case i had choosen  Mysql in .env and database config,

The phpunit Tests run with sqlite in :memory: by default

if you have changed your password in /database/seeds/Access/UserTableSeeder.php and seed

because the password is hardcoded in /tests/Frontend/Forms/LoggedOutFormTest.php
near L 125
HERE (LoggedOutFormTest.php ), you need to write the same password you choose before

to go "all green".

**Comment by rappasoft** [comment]
The tests should not be effecting your live database that's why the in memory sqlite was chosen.
