### ISSUE TITLE
npm run hot - Errors with saying it needs to change "[chunkhash]" to just "[hash]"

### ISSUE THREAD

**Issue by Shuyinsama** [rappasoft/laravel-5-boilerplate#665]
# What version?
Laravel 5.4 Boilerplate

# Explanation
I was trying to use the `npm run hot` script to start up a development server and do some local developing. But whenever I browse to the url `http://localhost:8080` it errors on me.

# What did I try
I looked around if packages needed to be updated but I'm guessing this goes way deeper then I expected. I tried to change the part where it says `[chunkhash]` to `[hash]` and then it does run but the server then errors with `Cannot GET /` so it was not that simple.

# Error

```log
 ERROR  Failed to compile with 2 errors                                                                                                  3:30:44 PM

 error  in [name].[chunkhash].js

Cannot use [chunkhash] for chunk in '[name].[chunkhash].js' (use [hash] instead)

 error  in [name].[chunkhash].js

Cannot use [chunkhash] for chunk in '[name].[chunkhash].js' (use [hash] instead)
```

**Comment by rappasoft** [comment]
Working for me, I don't use that command but if you figure it out let us know.
