### ISSUE TITLE
Webpack relative url path

### ISSUE THREAD

**Issue by alexandre-pereira** [rappasoft/laravel-5-boilerplate#667]
Relative path doesn't work for bootstrap glyphicon font during compilation via npm run if you use a subfolder.
Tested on WAMP 64bits, PHP 7.0 on Windows 10

# What version?
5.4, latest

**Comment by motia** [comment]
Look at the `app.scss` files, and replace 

`@import "../../../bootstrap-sass/assets/stylesheets/bootstrap"`
by
`@import "~bootstrap-sass/assets/stylesheets/bootstrap"`
The same goes for font-awesome or any node module dependecy.

**Comment by rappasoft** [comment]
I'll change that in the next release, works both ways for me but that's more elegant.
