### ISSUE TITLE
[Question] Bootstrap 4

### ISSUE THREAD

**Issue by digitalit** [rappasoft/laravel-5-boilerplate#668]
Hi @rappasoft ,

Do you have any plant on upgrading the BP with Bootstrap 4?

Have anyone of you BP:ers tried Bootstrap 4 in the BP?

**Comment by poseso** [comment]
The template I use with the bp is based on BS4

**Comment by digitalit** [comment]
Are you referring to the template you use for front or the admin template?

I think the admin template is Admin-LTE and uses Botstrap 3?

**Comment by poseso** [comment]
i mean for the backend i dont use Admin LTE

**Comment by digitalit** [comment]
God you make me curious @poseso :)

I don't like the Admin-LTE and would like to get rid of all that bloated stuff and use something cleaner, what template do you use?

**Comment by poseso** [comment]
I use Remark

**Comment by digitalit** [comment]
Looks great any tip on as how to implement it in the BP?

**Comment by digitalit** [comment]
Im using Porto as front end template but would like to have BP4 template for front end as well, any tip?

I have account on themeforest so will buy Remark and maybe som other template you can recommend that has BP4 @poseso .

**Comment by poseso** [comment]
you can implement it using webpack

**Comment by digitalit** [comment]
Sweet, this is my webpack.mix
```
mix.sass('resources/assets/sass/frontend/app.scss', 'public/css/frontend/dist/frontend.css');
mix.sass('resources/assets/sass/backend/app.scss', 'public/css/backend/dist/backend.css');

mix.combine([
    'public/css/frontend/dist/frontend.*.css',
    'resources/assets/css/plugin/bootstrap-select/bootstrap-select.min.css'
], 'public/css/frontend/frontend.css');

mix.combine([
    'public/css/backend/dist/backend.*.css',
    'resources/assets/css/plugin/bootstrap-select/bootstrap-select.min.css'
], 'public/css/backend/backend.css');

mix.js('resources/assets/js/backend/customers/customers.js', 'public/js/backend/customers/customers.js');

mix.js('resources/assets/js/backend/medias/medias.js', 'public/js/backend/medias/medias.js');

mix.js([
        'resources/assets/js/frontend/app.js',
        'resources/assets/js/plugin/sweetalert/sweetalert.min.js',
        'resources/assets/js/plugins.js'
    ], 'public/js/frontend/frontend.js');
mix.js([
        'resources/assets/js/backend/app.js',
        'resources/assets/js/plugin/bootstrap-select/bootstrap-select.min.js',
        'resources/assets/js/plugin/sweetalert/sweetalert.min.js',
        'resources/assets/js/plugins.js'
    ], 'public/js/backend/backend.js');
mix.version();
```

customers and media are Vue components only loaden on specific admin pages but backend app.js contains Admin-LTE codes.

i dont know if sweetalert is part of Admin-LTE as well?

Anyway, can you please guide me as how to swap Admin-LTE for Remark?

**Comment by digitalit** [comment]
@poseso i can pay you for your time guiding me :)

**Comment by poseso** [comment]
Heheh you don't have to, talk to me in the slack channel ill help you

**Comment by digitalit** [comment]
Fantastic!

**Comment by rappasoft** [comment]
I'll upgrade when it's released.
