### ISSUE TITLE
"NetworkError: 404 Not Found -... public/fonts/fontawesome-webfont.woff2?v=4.3.0"

### ISSUE THREAD

**Issue by lthanhdungn** [rappasoft/laravel-5-boilerplate#67]
Dear Rappasoft,
I had a problem when I full compiled following your Installation guide, and in admin page, there are some errors in fontawesomefont url.

If I add the fontawesomefont css link in admin page, it's ok, but I think it's not good solution.

![l5b](https://cloud.githubusercontent.com/assets/2120864/9544593/45613084-4dac-11e5-83ac-f7b7bf3d9b10.jpg)

**Comment by rappasoft** [comment]
I just commited a change for the fonts the other day, see if changing to this helps: https://github.com/rappasoft/laravel-5-boilerplate/commit/b77cf9db9e1416fc87d743937c0b962be0a2e62c

**Comment by lthanhdungn** [comment]
Thanks for your support.
