### ISSUE TITLE
I got this error message when installing 

### ISSUE THREAD

**Issue by jonny77** [rappasoft/laravel-5-boilerplate#671]
"The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths." 

After I copy .env.example to .env ,and   ran :  php artisan key:generate , also got the message as well . 
My php version is 7.1.3
My os is MacOs ..

**Comment by donmarkus** [comment]
Same issue

**Comment by mohamed-zezo** [comment]
+1 Same issue

**Comment by lednhatkhanh** [comment]
Same

**Comment by lednhatkhanh** [comment]
Hello, just add this 
```
APP_KEY=base64:iemTvjr5Mpfq8O+WUJvZ51MxfWmTGnMy5KgZRovRoD4=
```
To your `.env` file and run `php artisan key:generate` again.

**Comment by rappasoft** [comment]
Seems like a cache issue? https://github.com/laravel/framework/issues/9080

**Comment by jonny77** [comment]
i resolve in this way : Copy any APP_KEY code from other project to .env file,and then run 
php artisan key:generate again , that is ok !!!

**Comment by illuminate3** [comment]
I just reported this too. Do like jonny77 said ...

**Comment by illuminate3** [comment]
The clear cache method didn't work for me because artisan is blocked by the error.

**Comment by rappasoft** [comment]
I see the error, and this thread from laravel: https://github.com/laravel/framework/issues/9080

But none of what they say is working.

If you copy one from another project and run it again it works.

**Comment by rappasoft** [comment]
I'll try to figure it out today.

**Comment by wasiqaftab** [comment]
@rappasoft any update on that issue. i am having same issue like @illuminate3 have

**Comment by rappasoft** [comment]
Set it to what was said above and run key:generate again and it will work:

base64:iemTvjr5Mpfq8O+WUJvZ51MxfWmTGnMy5KgZRovRoD4=

**Comment by rappasoft** [comment]
The only solution i can come up with is to include that as a default, but that's a security issue.

**Comment by jonny77** [comment]
@rappasoft , I do not think it is a security issue because you will run  key:generate after that to confirm whether it works :-D

**Comment by rappasoft** [comment]
Yeah I just included a default in the .env.example that's the only thing that works and all the laravel forums are no help.

**Comment by kylesean** [comment]
+1 Same issue, so strange! All the artisan commands are blocked by the error.
