### ISSUE TITLE
Permanently deleting user needs updates to history log

### ISSUE THREAD

**Issue by cheshirec7** [rappasoft/laravel-5-boilerplate#674]
Create a new user, delete, then delete permanently. In the Dashboard Recent History it will say "Admin Istrator permanently deleted user {user}" (instead of the actual user name).

To fix, at line 91 in \app\Listeners\Backend\Access\User\UserEventListener.php add:

->withAssets([
            'user_string' => $event->user->name
          ])

**Comment by poseso** [comment]
user_string or user_link ?

**Comment by cheshirec7** [comment]
user_string. There is nothing to link to.

**Comment by cheshirec7** [comment]
Actually I think more should be done with this. All the previous log links are broken for the permanently deleted user, so update the history table.

Add to EloquentHistoryRepository.php:

```
public function updateLogAssets()
  {
    return History::where('type_id', $this->type->id)
      ->where('user_id', access()->id())
      ->where('entity_id', $this->entity_id)
      ->update(['assets' => $this->assets]);
  }
```

Update UserEventListener.php to be:
```
 public function onPermanentlyDeleted($event)
  {
    history()->withType($this->history_slug)
      ->withEntity($event->user->id)
      ->withText('trans("history.backend.users.permanently_deleted") <strong>{user}</strong>')
      ->withIcon('trash')
      ->withClass('bg-maroon')
      ->withAssets([
        'user_string' => $event->user->name
      ])
      ->log();

    history()->withType($this->history_slug)
      ->withEntity($event->user->id)
      ->withAssets([
        'user_string' => $event->user->name
      ])
      ->updateLogAssets();
  }
```

**Comment by rappasoft** [comment]
Fixed.
