### ISSUE TITLE
Password reset improvement

### ISSUE THREAD

**Issue by cheshirec7** [rappasoft/laravel-5-boilerplate#675]
These are two somewhat unusual cases but the second has happened to one of my users and puts them in a spot where they don't know what to do next.

First in app.php change the expire time to 1 min:
```
'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 1,
        ],
    ],
```

Now send yourself two password reset emails. Click on the first one and you will get "An unknown error occurred", but fortunately it shows the "Reset Password" form so you can send another password reset email.

Now click on the second password reset email you received. *After* submitting the form it will tell you "This password reset token is invalid" (it timed out) and does not let you send another password reset email.

To fix these problems I propose adding a few lines to the following function in ResetPasswordController.php:

```
 public function showResetForm($token = null)
  {

    if (!$token)
      return redirect()->route('frontend.auth.password.reset');

    $email = null;
    try {
      $email = $this->user->getEmailForPasswordToken($token);
    } catch (\Exception $e) {
    }

    if (!$email)
      return redirect()->route('frontend.auth.password.reset')->withFlashWarning('There was a problem resetting your password (invalid token). Please try again.'); 
    
    $user = $this->user->findByEmail($email);

    $exists = app()->make('auth.password.broker')->tokenExists($user, $token);
    if (!$exists)
      return redirect()->route('frontend.auth.password.reset')->withFlashWarning('There was a problem resetting your password (token expired). Please try again.');

    return view('frontend.auth.passwords.reset')
      ->withToken($token)
      ->withEmail($email);
  }
```
The user gets much better messages of what's going on.

BTW this Laravel 5 Boilerplate is a fantastic piece of work and I really want to help make it better! :)

**Comment by rappasoft** [comment]
Is 1 minute generally what you set yours to expire? Seems way too fast.

**Comment by cheshirec7** [comment]
I suggested one minute just for ease of testing. Actually I'm using 1440 minutes (1 day) just to avoid this problem. The mail server I use sometimes takes forever to send password reset emails so some people don't wait, then try again the next day.

**Comment by rappasoft** [comment]
Closing this since you made a PR and i'm waiting for people to weigh in.
