### ISSUE TITLE
Undefined variable: reports (View: D:\Xampp\htdocs\laravel-5-boilerplate\resources\views\vendor\log-viewer\dashboard.blade.php)

### ISSUE THREAD

**Issue by texnika01** [rappasoft/laravel-5-boilerplate#676]
ErrorException in 77e19f6f45dff1fedc8a88659efb464fe43ddd4a.php line 55:
Undefined variable: reports (View: D:\Xampp\htdocs\laravel-5-boilerplate\resources\views\vendor\log-viewer\dashboard.blade.php)

**Comment by rappasoft** [comment]
In the current version of that file there is no variable called reports, I think you need to update log-viewer and copy over the new files.
