### ISSUE TITLE
DebugBar

### ISSUE THREAD

**Issue by LunarDevelopment** [rappasoft/laravel-5-boilerplate#677]
Hello! 

I've noticed that my config/app.php doesn't have the `Barryvdh\Debugbar\ServiceProvider::class` provider or `'Debugbar' => Barryvdh\Debugbar\Facade::class,` alias for debug bar. 

What is the correct syntax for using the debug bar in the boilerplate? 

`app('debugbar')->info($request->email);` works without the registered alias/ provider but `DebugBar::info($request->email);` doesn't.

**Comment by jonnywilliamson** [comment]
That's because it's been registered in the `AppServiceProvider.php` file so that it only loads on NON production servers:

https://github.com/rappasoft/laravel-5-boilerplate/blob/c5f7d95f11c584a9ed2446fa28174fb068257e62/app/Providers/AppServiceProvider.php#L73

**Comment by rappasoft** [comment]
Yes see above.
