### ISSUE TITLE
Laravel 5.1.11

### ISSUE THREAD

**Issue by Teranode** [rappasoft/laravel-5-boilerplate#68]
: | - they decided to put Authorizable in there. so now it has permission based things. You should check it out. (It's optional to install though)

http://laravel.com/docs/5.1/authorization

**Comment by rappasoft** [comment]
Damnit. No roles though?

**Comment by rappasoft** [comment]
I feel like this boilerplate is going to be a thing of the past soon because they're launching a SaaS template soon I hear.

**Comment by Teranode** [comment]
In my head im going "FML" because its probably true, so many things to change >_<
Well I think they did it so you could extend it and create your own set of functions.

I don't think they'll implement roles, i dont know :/ - i mean i looked in the trait and its only
 function can(){}

so it's a possibility they will add more, but this is just their basic implementation, probably to hel people implement their own auth system.

**Comment by Teranode** [comment]
where did u hear this saas rumor?

**Comment by rappasoft** [comment]
On the forums from Laracon I believe.

**Comment by rappasoft** [comment]
It's called Spark: https://www.youtube.com/watch?v=uOU_N8PNOD8

**Comment by Teranode** [comment]
<_< this looks so tedious for people who already use their own bootstrap service. Not saying it's a problem for them, it's just that they'd be creating a layer over an already implemented layer that people have.

**Comment by rappasoft** [comment]
I agree. I believe this will kill mine. Unless I scrap this one and build a new one off of 5.1.11 or Spark. It is becoming tedious to manage the auth library.

**Comment by Teranode** [comment]
>_> well im ready for it because well, bootstrap 4 is witching to Sass and i use LESS 500% of the time, and know nothing on sass, so im just going to be learning new things..... again...

I think the Laravel Spark Beta will be in September somewhere, is my estimation, ill keep an eye out and send you a heads up. For now though i'm going to stick with what i currently have until i know everything about spark.

**Comment by rappasoft** [comment]
It definitely looks like a big help. If anything i'll start over with 5.11 sans the access library. And make a spark boilerplate with all of the other stuff. I don't really want to manage two, but I don't know what else to do.

**Comment by Teranode** [comment]
What you could do, is manage both, and when spark eventually comes out of it's beta phase. You could just create a final version for the custom boilerplate you have.

And then start fully supporting spark, i mean spark will probably have "ALOT" more helpful pointers for users so i'm pretty sure people should be willing to understand the switch in support. But that's entirely up to you.

**Comment by rappasoft** [comment]
I could, but so far i've yet to use this boilerplate to make a SaaS app with subscriptions. I use it for the users/roles/permissions. 

Maybe I can just make it better than what it is now. The laravel Gate class apparently needs some work according to this post: https://www.reddit.com/r/laravel/comments/3j0s8q/authorization_in_laravel/culvlo1

And also, people are saying the permissions aren't stored in the database?

**Comment by Teranode** [comment]
permissions isnt stored in the database :|

They are stored and accessed from code. So you would have to create them in code.

**Comment by rappasoft** [comment]
That leaves out the ability for a UI doesn't it? And the ability to associate the permissions with roles if someone wanted to build in roles.

**Comment by Teranode** [comment]
Well, its the precise reason it's basic <_<, you shouldn't start until there is some definite answers given about the current implementations.

**Comment by rappasoft** [comment]
Maybe i'll work on the auth library and make it better. Than when spark is released combine them.

**Comment by Teranode** [comment]
the one thing i liked fro mthe presentation was the Teams function, i've been looking for something like it, and would want to expand on it.

**Comment by rappasoft** [comment]
The thing i'm always afraid of with those projects is:

A: is it just a composer package where if I wanted to change a function in a vendor file I have to do a bunch of shit.
B: if not, it's a bunch more files in my app directory that will get outdated with time.
C: I didn't write any of the code so I have to take the time to learn exactly what's going on first and risk creating bugs or breaking functionality when adding on to it.

**Comment by Teranode** [comment]
yea i know how u feel, my vendor is like 17MB : |

And its just filled with packages some of which i fear will not get support in the future possibly, then ill end up having to update it myself. ( which i dont mind, but its a lot of packages )

**Comment by Teranode** [comment]
so spark will probably get a beta in september and either be released sometime later this year or early 2016.

**Comment by rappasoft** [comment]
I don't think Spark comes with anything but the new Gate class. So I think I will continue to develop my access library because at least I will still use it. And I honestly don't feel like changing workflows. The only thing I may change is swapping out the request classes for a Policy class.

**Comment by Teranode** [comment]
thats fine :) - my core uses your core so i'm fine with whatever.

**Comment by rappasoft** [comment]
I just have the "Taylor created it so it must be better than mine" issue going on.

**Comment by Teranode** [comment]
I can see that happening. However you should consider it a foundation/core rather than something better than your creations. In essence its not better than yours rather, it makes what you create better.

**Comment by rappasoft** [comment]
Yes except in this case its a replacement for what I create, so do I abandon a library i've built and know every line of for one thats a couple dozen files in a vendor folder that I have no idea what anyone does? Or do I just make this one better and ignore the new laravel files.

**Comment by Teranode** [comment]
hmmm, that is rather a hard decision. I'd usually go with the latter and mix a bit of both. But i'm still not sure what spark will hold.

**Comment by blomdahldaniel** [comment]
Ooh... Feel with you @rappasoft this is a tough question.. I guess we all have to wait just a little while longer to see what Spark will hold. And I guess that Spark will be free....?

**Comment by rappasoft** [comment]
Yeah it seems like its going to be an artisan command or something of the sort to install. 

Anthony Rappa

**Comment by rappasoft** [comment]
I ended up adding the files, then removing them.
Just kept the policies folder.

I don't know if theres anything in that class I don't already have. It would take alot to either switch over or combine them.

**Comment by blomdahldaniel** [comment]
Good decision at this stage i would say, your stuff is great in the context of this repo. The spark things will be nice aswell and i think, as you say, that a switch or combining might come in the future. Meanwhile, we keep on building our things. :)
