### ISSUE TITLE
phpunit fatal error during fresh install

### ISSUE THREAD

**Issue by cutemonster** [rappasoft/laravel-5-boilerplate#684]
Hi,
at the last step when I run phpunit i get the following error.

`PHP Fatal error:  Uncaught Error: Call to undefined method PHPUnit_Util_Configuration::getTestdoxGroupConfiguration() in C:\WEB\boiler\vendor\phpunit\phpunit\src\TextUI\TestRunner.php:1066`

Do you have any idea?

thanks

**Comment by matthiku** [comment]
Same here. The full call stack is:
```
1. {main}() C:\xampp\php\phpunit:0
2. PHPUnit_TextUI_Command::main() C:\xampp\php\phpunit:46
3. PHPUnit_TextUI_Command->run() C:\xampp\php\pear\PHPUnit\TextUI\Command.php:129
4. PHPUnit_TextUI_TestRunner->doRun() C:\xampp\php\pear\PHPUnit\TextUI\Command.php:176
    0.4299    2629744   5. PHPUnit_TextUI_TestRunner->handleConfiguration() C:\laragon\www\LaraBoil\vendor\phpunit\phpunit\src\TextUI\TestRunner.php:163
```

**Comment by rappasoft** [comment]
Look here: https://github.com/sebastianbergmann/phpunit/issues/2432
