### ISSUE TITLE
Socialite Issues

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-5-boilerplate#7]
Just be advised there are issues with socialite currently in this project. Due to the lack of documentation I implemented it wrong. I'm trying to find time to redo it. Everything else works.

**Comment by rappasoft** [comment]
Fixed. Can now log in with any or all providers using same email address. And then the user can do a forgot password and add a password and log in natively as well.

**Comment by Krubb** [comment]
Splendid Sir!
