### ISSUE TITLE
Quick question regarding email verification/socialite

### ISSUE THREAD

**Issue by num3thod** [rappasoft/laravel-5-boilerplate#70]
Hi @rappasoft , first off, great work here. Loving this boilerplate.

Currently, when a user signs in through socialite, a confirmation email is sent. I tried to disable this in the user repository, but to no avail. How would you approach this?

Thanks.

**Comment by rappasoft** [comment]
It's sending the confirmation email regardless?  I don't really remember but i'm not sure if that part of the code gets hit using socialite. I'll have to look.

**Comment by num3thod** [comment]
Just to confirm, it indeed sends a confirmation email regardless. Also, in this case, the provider is Google. Thanks BTW.

**Comment by rappasoft** [comment]
Stupid question, but did you try to set the confirm_email config in the access.php config file to false, and/or comment out line 54/55 in Frontend/EloquentUserRepository.php as well as the sendConfirmationEmail function in that file as well?

**Comment by num3thod** [comment]
Yes. That indeed prevents email confirmations. The issue is that users who sign up using email _should_ be sent a verification email, while users who sign up using sociale should _not_ have to (defeats the purpose/convenience of social login).

**Comment by rappasoft** [comment]
Ah I see, I guess I didn't think about that. I'll have to look into changing it.

**Comment by num3thod** [comment]
I'm thinking something like this:
```
public function create($data, $provider = false) {
    $user = User::create([
        'name' => $data['name'],
        'email' => $data['email'],
        'password' => $provider ? null : $data['password'],
        'confirmation_code' => md5(uniqid(mt_rand(), true)),
        'confirmed' => config('access.users.confirm_email') ? 0 : 1,
    ]);
    $user->attachRole($this->role->getDefaultUserRole());

    if (config('access.users.confirm_email') and $provider = null)
        $this->sendConfirmationEmail($user);

    if ($provider = null) {
        $user->confirmed = 1;
        $user->save();
    }

    return $user;
}
```

Though this doesn't change the "confirmed" status to "1" for some reason.

**Comment by rappasoft** [comment]
Yes make a pull request.

**Comment by blomdahldaniel** [comment]
This is sweet @num3thod  :smiley: 
:+1:

**Comment by num3thod** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)
