### ISSUE TITLE
Executive Role can't create resources

### ISSUE THREAD

**Issue by minedun6** [rappasoft/laravel-5-boilerplate#707]
Even after granting Executive role the permissions to create resources, I still get "You do not have access to do that."
I did some debugging, and I did a dd() on the authorize method, it returns true, but for an unknown reason, this error still comes out. 

this is a portion of my code: 

    <?php

     namespace App\Http\Requests\Backend\Reception;
 
     use App\Http\Requests\Request;

     class StoreReceptionRequest extends Request
    {
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return access()->allow('create-reception');
    }

**Comment by rappasoft** [comment]
Is this something custom you're making or are you having trouble with the default install?

**Comment by minedun6** [comment]
I'm sorry for the trouble caused here but fixed it and it works all along.
