### ISSUE TITLE
Macro Examples: not working

### ISSUE THREAD

**Issue by fishmad** [rappasoft/laravel-5-boilerplate#71]
I've just installed this for the first time, I assume if I select Australia from country list (Macro Examples) than I should be presented with a list of pre-populated Australian states. This is not the case - what ever country I select the states always remain as USA states

Running Xampp on Windows with latest commit

**Comment by rappasoft** [comment]
The macros only present the select boxes. They provide you with selectCountry and selectState form helpers. If you want more you can append to the [https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Services/Macros.php](macros file).
