### ISSUE TITLE
Update laravel 5 boilerplate ?

### ISSUE THREAD

**Issue by t-prod** [rappasoft/laravel-5-boilerplate#710]
Hi,

I see a lot of commits and improvements ans want to thank you for that.
I have laravel boilerplate for laravel 5.4. I would like to update it easily. How can I do ?

**Comment by t-prod** [comment]
Any ideas ?
I'm developing a saas app to host multi sites.
I could do it manually but I think we could do better no ?

**Comment by rappasoft** [comment]
Manual is the only way, this is a starter project not a plugin. You are intended to take it and build on it.

**Comment by t-prod** [comment]
Thanks for your confirmation. Regards
