### ISSUE TITLE
login with username instead of email

### ISSUE THREAD

**Issue by radifans** [rappasoft/laravel-5-boilerplate#720]
I want user to be logged in with username instead of email, I'm already followed the instruction on #479 but it seems it's already deprecated, what file should I change for the current build?

**Comment by rappasoft** [comment]
It's in \Illuminate\Foundation\Auth\AuthenticateUsers line 143

**Comment by putheakhem** [comment]
@rappasoft is there any instruction on how to do it on the current version?
