### ISSUE TITLE
Issue with last merge

### ISSUE THREAD

**Issue by JuanMarceloVillagranFiallos** [rappasoft/laravel-5-boilerplate#723]
I forked the previous repo and it was all good, a couple of minutes ago i merged upstream/master and it destroyed my app, anything i can do mate?

![image](https://cloud.githubusercontent.com/assets/28311675/25852862/6653af66-3490-11e7-8c95-79183e96c709.png)

**Comment by rappasoft** [comment]
You shouldn't merge the releases like that it's not built to handle it. It's not a package where you can just update. Just like the laravel/laravel master if they change something you have to manually add it in. A lot of stuff was done in that release, I would try to back it out.

**Comment by rappasoft** [comment]
If you copy the lang files over it should fix those issues but theres no telling what else it broke.

**Comment by JuanMarceloVillagranFiallos** [comment]
I see, thank you for replying and I will revert back to the previous merge and start to add things manually,  by the way I love the boilerplate, thank you very much for your effort. You can close this now 😃

**Comment by rappasoft** [comment]
Sorry wish I had an easier way. Glad you like it!
