### ISSUE TITLE
Permissions management

### ISSUE THREAD

**Issue by SafaaFX** [rappasoft/laravel-5-boilerplate#728]
Hello,
I just installed the last version of the boilerplate for laravel 5.4 and I didn't find the permissions management!
Is it no more included? 
Thank you 
Safaa

**Comment by yugan24** [comment]
[https://github.com/rappasoft/laravel-5-boilerplate/issues/475](url)

**Comment by SafaaFX** [comment]
hey @yugan24  the page is not accessible :/

**Comment by poseso** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/issues/475

**Comment by SafaaFX** [comment]
@poseso thank you
