### ISSUE TITLE
Keep redirecting to login page

### ISSUE THREAD

**Issue by mariaczi** [rappasoft/laravel-5-boilerplate#73]
Hi,

What can be the reason? I have form with some AJAX validation.
If I touch anyhow this field with AJAX validation, after refresh it will always redirect me to login page.

**Comment by rappasoft** [comment]
Can you give an example?

**Comment by sisodiakaran** [comment]
Same issue. Ajax redirect me to login page. my routes are:

```
Route::group(['namespace' => 'Payment', 'prefix' => 'secure', 'middleware' => 'web'], function () {
    Route::post('address/save.json', 'AddressController@save');
    Route::post('address/select.json', 'AddressController@set');
});
```

@mariaczi any clue? how you resolved this issue?

**Comment by varmad** [comment]
Any post request is keep moving to login page, is there any configuration?
