### ISSUE TITLE
Custom CSS per Page

### ISSUE THREAD

**Issue by Arwany** [rappasoft/laravel-5-boilerplate#731]
# What version?: 4.4.0

How does this per-page css file work please?

There is this file under: `resources/assets/sass/frontend/pages/_dashboard.scss` I tried to look where it is being used but could not find it, how do you make a per-page scss file and import it please? I suspect this has to do with the route-name.

Thank you for your reply. I appreciate any response.

**Comment by bryanrscott** [comment]
This is not quite what you ask so, I keep my per page css with the page blade using the 
```
@section('after-styles')
@endsection
```

**Comment by Arwany** [comment]
I think I already got what I want, which is:

`@import 'pages/dashboard'`
which is just organizing the css.

@bryanrscott I am already doing what you said, many thans :-)

**Comment by rappasoft** [comment]
There is no built in 'per-page' as it's 1 generated css file. But you can of course modify the webpack mix file to generate multiple css versioned files on a per page basis instead of all in one.
