### ISSUE TITLE
5.4 - Socialite error after first_name, last_name update.  Undefined property: Laravel\Socialite\Two\User::$first_name

### ISSUE THREAD

**Issue by daniel-farina** [rappasoft/laravel-5-boilerplate#732]
I think there is a bug on sociallite after the first_name last_name update. 

I get the following while trying to registering with  Facebook: 

**Undefined property: Laravel\Socialite\Two\User::$first_name**

Using Laravel 5.4 Boilerplate

I'll try to figure it out and keep you posted.

**Comment by daniel-farina** [comment]
I can confirm there is a bug after adding first and last name. 
I made a pull request: #733 Temporarily fixing this issue. 

My first pull request on git ^^; big day for me.

**Comment by rappasoft** [comment]
Fixed: https://github.com/rappasoft/laravel-5-boilerplate/commit/3373e07aee0fc0c2ff59f348a4109ff89532ec58
