### ISSUE TITLE
font-awesome relative path

### ISSUE THREAD

**Issue by starlino** [rappasoft/laravel-5-boilerplate#738]
I need to run this project from a path:

domain.com/project/

Problem is that  frontend.css is absolutely referenced from  /fonts/ , and thus requires project to be run from domain.com/ root

See for example /public/css/frontend.css

@font-face{font-family:FontAwesome;src:url(/fonts/vendor/font-awesome/fontawesome-webfont.eot?674f50d287a8c48dc19ba404d20fe713)

I think a more flexible solution is to refer to the fonts folder relative to the CSS file:

Like So:
../fonts/vendor/font-awesome/fontawesome-webfont.eot?674f50d287a8c48dc19ba404d20fe713)

What is the best way / place to fix this ?

Thanks,

**Comment by krzykz** [comment]
Declare 

`$fa-font-path:        "../fonts" !default;`

Before importing fontawesome :)

**Comment by starlino** [comment]
In what file  do I need to place this line ? Thanks.

**Comment by krzykz** [comment]
Hi! It should go above the import of fontawesome since it's going to be used inside the file :)

Like this:
`
$fa-font-path: "../your/font/path";
@import "~font-awesome/scss/font-awesome";
`

Don't forget to do it in the backend as well!
