### ISSUE TITLE
Sesion expires gives error instead of redirect

### ISSUE THREAD

**Issue by everton15m** [rappasoft/laravel-5-boilerplate#742]
After installing the laravel boilerplateI have noticed that when the user session expires and you try to navigate at a route that requires the user logged in I receive error like:

ErrorException in 4092af348301ebdcc63bf4a3a7a7710086bcb670.php line 81:
Trying to get property of non-object (View: /home/vagrant/Code/caritsan/resources/views/backend/includes/header.blade.php) (View: /home/vagrant/Code/caritsan/resources/views/backend/includes/header.blade.php) (View: /home/vagrant/Code/caritsan/resources/views/backend/includes/header.blade.php)

instead of redirecting to the login page.
Do you have any ideeas?

**Comment by rappasoft** [comment]
It sounds like a token mismatch and should be getting caught here: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Exceptions/Handler.php#L52

**Comment by everton15m** [comment]
public function render($request, Exception $exception)
    {

        if ($exception instanceof TokenMismatchException) {
            return redirect()->route('frontend.auth.login');
        }


        if ($exception instanceof \Illuminate\Validation\ValidationException) {
            return $this->handleValidationException($request, $exception);
        }

        if ($exception instanceof GeneralException) {

            return redirect()->back()->withInput()->withFlashDanger($exception->getMessage());
        }


        return parent::render($request, $exception);
    }


Did not help, Every time a user session is expired and he refreshes the page is see in the logs an error like this : ErrorException: Trying to get property of non-object in /var/www/html/caritsan/storage/framework/views/a8c31c2bb75ffbbdf157821d66e8d0da14bd2336.php:81

 ErrorException: Trying to get property of non-object in /var/www/html/caritsan/storage/framework/views/a8c31c2bb75ffbbdf157821d66e8d0da14bd2336.php:81

where the line that crashes is 
                 <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="<?php echo e(access()->user()->picture); ?>" class="user-image" alt="User Avatar"/>
                        <span class="hidden-xs"><?php echo e(access()->user()->name); ?></span>
                    </a>
