### ISSUE TITLE
composer error on Generating optimized autoload files

### ISSUE THREAD

**Issue by pmirandaarias** [rappasoft/laravel-5-boilerplate#749]
In the end of `composer install`, I got this error:

phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.1)
phpunit/phpunit suggests installing ext-xdebug (*)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize

  [RuntimeException]
  The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct
   key lengths.

Script php artisan optimize handling the post-install-cmd event returned with error code 1

Why is that?

**Comment by pmirandaarias** [comment]
Hm, I had to rename .env.example to .env before the `composer install`, now it works, I just was following the install steps in order.

**Comment by rappasoft** [comment]
Composer should have done that for you. It might not have had permission to rename the file.

**Comment by noxify** [comment]
Correct me if I'm wrong, but the `.env` file will be generated only with

```
composer create-project rappasoft/laravel-5-boilerplate my-awesome-project
```

**Comment by monocidar** [comment]
you also can try php artisan key:generate for the [RuntimeException] about supported ciphers are AES-128-CBC and AES-256-CBC.

**Comment by rappasoft** [comment]
This line should be doing it: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/composer.json#L54

**Comment by rappasoft** [comment]
If it doesn't just copy the .env manually and rerun composer.
