### ISSUE TITLE
how is mail being sent from mailable in  laravel boilerplate 5.4??

### ISSUE THREAD

**Issue by arikazukitomaharjan** [rappasoft/laravel-5-boilerplate#754]
# Before you create an issue make sure that:
- Your issue is **strictly related to the boilerplate** itself. Questions about Laravel in general belongs to the [laracasts](https://laracasts.com/discuss/) or [laravel](http://laravel.io/forum) forums.
- You have read the [wiki](https://github.com/rappasoft/laravel-5-boilerplate/wiki) thoroughly.
- You have searched for a similar issues among all the former issues (even closed ones).
- You have tried to replicate the issue with a clean install of the project.

# Be explicit
Try to be as explicit as you can when you ask anything.

# What version?
Please when it's necessary, provide the version of your copy of the boilerplate. You can find the version number in the original README.md.

**Comment by rappasoft** [comment]
What do you mean how? Thats what the laravel mailable class does: https://laravel.com/docs/5.4/mail#writing-mailables
