### ISSUE TITLE
How to modify the css file and merge

### ISSUE THREAD

**Issue by dk4210** [rappasoft/laravel-5-boilerplate#755]
First of all thank you for this project. It works great! 
I'm trying to understand how to modify the css file and to compile it.
When I go to laravel\public\css\frontend.css  the code looks minimized. Do I just manually format it to edit it?
How to I compile it with the webpack.mix.js file?

Thanks,
Dan

**Comment by mikimaine** [comment]
It uses Laravel webpack plugin called 'Laravel-mix' to manage assets. You need to have node and webpack to edit CSS file. you can find the raw CSS at 'resources/sass' and js at 'resources/js'
You end files there and run the command 'npm run dev' for development and 'npm run prod' for production.

**Comment by dk4210** [comment]
I found it right before you posted 
https://laravel.com/docs/5.4/mix

Thanks for the help.
