### ISSUE TITLE
Load DB user at every request

### ISSUE THREAD

**Issue by mtx-z** [rappasoft/laravel-5-boilerplate#757]
Hey there !

I'm optimizing my application, and i see that, when a user is logged, it's object is loaded from DB at every request.
This seems to happend on the  `\Illuminate\Session\Middleware\StartSession` middleware but i cant find the code (auth() is empty before, and populated after execution). 

My aim is to cache this request to prevent a DB load at every request. 

Is it rappasoft related ? Or Laravel related ?

(I deleted the rappasoft readme before GITing, so i cannot find the version used from here. But it was at the time of Laravel 5.1).

Thanks a lot

**Comment by rappasoft** [comment]
I load the user on every request for security in case it was modified by something on the request before. If you want to cache it you can cache on successful login and fetch the cache on page load in stead of from the DB.
