### ISSUE TITLE
laravel 5.4 boilerplate with multi auth?

### ISSUE THREAD

**Issue by yelnyaface** [rappasoft/laravel-5-boilerplate#761]
I tried modifying the code so I can have multi auth for 2x tables 'user' and 'admin',
but failed,

does anyone know how to create modify the boilerplate code, so mutli auth can work?

**Comment by rappasoft** [comment]
BP uses stock laravel auth, just add a new guard.

**Comment by yelnyaface** [comment]
hi, thanks for the reply, can you explain a little bit more bout how to do that?

I need 2x tables 'admin' 'user', both with funcitonalities like confirm email, etc

also I need the backend admin panel to have the same dashboard pages for admin

**Comment by rappasoft** [comment]
This project isn't built for that exactly, but there's plenty of material to be found: https://stackoverflow.com/questions/41843804/how-to-create-multi-auth-in-laravel-5-4
