### ISSUE TITLE
Where is 'withFlashDanger()' and 'withUser()' is defined? 

### ISSUE THREAD

**Issue by yelnyaface** [rappasoft/laravel-5-boilerplate#769]
hi, does anyone know where 'withFlashDanger()' and 'withUser()' is defined?

**Comment by rappasoft** [comment]
http://laravel-boilerplate.com/5.4/documentation.html

**Comment by pairote** [comment]
Hi @yelnyaface ,

Actually, the calling of method `withFlashDanager` and other methods with a name that starts with `with` in `Illuminate\Http\RedirectResponse` are just dynamic class method invocations. Take a look at the code [here](https://github.com/laravel/framework/blob/master/src/Illuminate/Http/RedirectResponse.php#L231).
