### ISSUE TITLE
How can I have REST-api for project developed using this boilerplate

### ISSUE THREAD

**Issue by cliffon** [rappasoft/laravel-5-boilerplate#778]
First of all this is really a great boilerplate ,a great way to start , 
 what i need is a way to have this application also on apps , so is there a way to make rest api on top of this boilerplate. thank you

**Comment by rappasoft** [comment]
It's just a normal Laravel application so yes you can make your API.

**Comment by cliffon** [comment]
so if i use dingo/api with jwt authentication will it in any way affect original functionality

**Comment by rappasoft** [comment]
It depends how and where you put it I guess but generally speaking it shouldn't. BP uses laravel default authentication, so if it would effect that, then it would effect this.

**Comment by rappasoft** [comment]
http://esbenp.github.io/2016/04/11/modern-rest-api-laravel-part-1/
https://www.programmableweb.com/news/how-to-build-restful-apis-using-php-and-laravel/how-to/2014/08/13
https://code.tutsplus.com/courses/build-a-rest-api-with-laravel
https://learninglaravel.net/laravel-5-rest-api-basic-authentication-tutorial
https://github.com/Tony133/LaravelApiRest
https://www.udemy.com/restful-api-with-laravel-php-homestead-passport-hateoas/

**Comment by rappasoft** [comment]
Also: https://www.udemy.com/restful-api-with-laravel-php-homestead-passport-hateoas/?utm_content=_._pd_1109150_._&utm_source=facebook&utm_medium=udemyads&utm_campaign=NEW-FB-DRT-Visitor-2Day-EN-ENG_._ci_._sl_ENG_._vi_._sd_._la_EN_.&k_clickid=c1551e2a-0d18-493c-bd5a-e2ff2a7fae2e_95677778&utm_term=_._ag_Development-_._ci_._._pi_1688250301215027_._gi_all_._ai_18--65_._an_Development-BjNvlL_._lo_%5BAustralia,%20Canada,%20United%20States,%20United%20Kingdom%5D_._
