### ISSUE TITLE
php artisan db:seed error

### ISSUE THREAD

**Issue by odyright** [rappasoft/laravel-5-boilerplate#78]
[Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i
  n your SQL syntax; check the manual that corresponds to your MySQL server v
  ersion for the right syntax to use near 'CASCADE' at line 1 (SQL: TRUNCATE
  TABLE users CASCADE)

**Comment by Soufraz** [comment]
What are you trying to do?
Can you post your code? Is better to help.  :)

**Comment by odyright** [comment]
OK but which code precisly are you asking for?

**Comment by Soufraz** [comment]
Ow sorry. The title of issue. "php artisan db:seed"   :D 
What is your mysql version? You only get the project and ran the seed?
`composer install` and `php artisan migrate` thrown some error?

**Comment by odyright** [comment]
yes ...same thing

**Comment by rappasoft** [comment]
You're only going to get that message if using PostgreSQL, if you want MySQL make sure all your settings are correct.

I don't normally use PostgreSQL, so I haven't had the opportunity to check those conditionals in the seeders, there very well may be something wrong with the syntax.

Anyone with PostgreSQL care to try a fresh install?

**Comment by odyright** [comment]
I use MySQL

**Comment by rappasoft** [comment]
Something is not right. Is your default in database.php set to mysql? And not getting overridden by an environment variable or something?

**Comment by odyright** [comment]
.env and databse.php have the same!

**Comment by rappasoft** [comment]
That's weird, just get rid of the database checks at the stop of the seeder files and keep the mysql versions. See if that works.

**Comment by odyright** [comment]
nothing, may be i missed something! or i don't know to handle it!

**Comment by rappasoft** [comment]
Was that a fresh install? If not try a fresh install.

**Comment by odyright** [comment]
yes it is.... may be must i upgrade MySQL vers. ?

**Comment by rappasoft** [comment]
I believe you need 5.6 or greater.

**Comment by odyright** [comment]
i think also that the mistake is where the "TRUNCATE TABLE Syntax" is located....  UserTableSeeder.php

**Comment by odyright** [comment]
OK, thank you very much. You'r a good guy!
i like your work.

**Comment by rappasoft** [comment]
Haha no problem. I will double check and make sure everything's working properly

**Comment by odyright** [comment]
ok it will be reassuring

**Comment by mikimaine** [comment]
im having the same problem .... after a fresh install . my MySQL version 5.7.10.
before this when i work on Ubuntu i have never face this problem??
i have check my env and databse.php file and all is set to mysql . when i create account manually it works . only when i create seed this happens .. 
this is the error 
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i
  n your SQL syntax; check the manual that corresponds to your MySQL server v
  ersion for the right syntax to use near 'CASCADE' at line 1 (SQL: TRUNCATE
  TABLE users CASCADE)

**Comment by kendugu** [comment]
I had this same issue and solved it by including DB_CONNECTION in my .env file. For some reason the config wasn't defaulting to MySQL even though DB_CONNECTION was missing.

**Comment by mikimaine** [comment]
yap that also worked for me.... 
i just added DB_CONNECTION to the .env file.

**Comment by jeanarmel** [comment]
Worked for me as well

**Comment by maobunthon** [comment]
It work just add DB_CONNECTION=mysql in my .env file
Thank you very much :)
