### ISSUE TITLE
Class 'Doctrine\DBAL\Driver\PDOSqlite\Driver' not found in TestCase

### ISSUE THREAD

**Issue by vutrungduc7593** [rappasoft/laravel-5-boilerplate#785]
I got this error message when try to write a api test

```cmd
1) Tests\Api\Access\AccessTest::it_return_all_users
Error: Class 'Doctrine\DBAL\Driver\PDOSqlite\Driver' not found

C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Database\SQLiteConnection.php:49
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Database\Connection.php:854
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Database\Schema\Grammars\SQLiteGrammar.php:221
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Database\Schema\Blueprint.php:107
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Database\Schema\Blueprint.php:82
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php:239
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php:148
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:221
C:\Users\Admin\web-projects\foodlog-backend\database\migrations\2015_12_29_015055_setup_access_tables.php:100
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php:353
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php:359
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php:328
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php:251
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php:301
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php:279
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\ResetCommand.php:68
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:29
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:87
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:31
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Container\Container.php:539
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Console\Command.php:182
C:\Users\Admin\web-projects\foodlog-backend\vendor\symfony\console\Command\Command.php:264
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Console\Command.php:167
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Console\Command.php:197
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\RefreshCommand.php:104
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\RefreshCommand.php:55
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:29
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:87
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:31
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Container\Container.php:539
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Console\Command.php:182
C:\Users\Admin\web-projects\foodlog-backend\vendor\symfony\console\Command\Command.php:264
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Console\Command.php:167
C:\Users\Admin\web-projects\foodlog-backend\vendor\symfony\console\Application.php:869
C:\Users\Admin\web-projects\foodlog-backend\vendor\symfony\console\Application.php:223
C:\Users\Admin\web-projects\foodlog-backend\vendor\symfony\console\Application.php:130
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Console\Application.php:141
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php:220
C:\Users\Admin\web-projects\foodlog-backend\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:221
C:\Users\Admin\web-projects\foodlog-backend\tests\TestCase.php:76
```

This is my code
```php
<?php

namespace Tests\Api\Access;

use TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class AccessTest extends TestCase
{
    use DatabaseMigrations;

    /**
    * @test
    *
    * Test: GET /api/users.
    */
    public function it_return_all_users()
    {
        $users = [
            factory(\App\Models\User::class)->create(),
            factory(\App\Models\User::class)->create()
        ];

        $response = $this->get('/api/users', $this->headers($users[0]));

        $response
            ->assertStatus(200);
    }
}
```

**Comment by bloggervista** [comment]
have you installed composer package correctly?

**Comment by rappasoft** [comment]
Can you die and dump at the beginning of the function to ensure it's being hit and not coming from a migration or set up method?

**Comment by vutrungduc7593** [comment]
@rappasoft It's not being hit, but when i remove trait DatabaseMigrations, it's being hit

**Comment by rappasoft** [comment]
Then it would be safe to say theres something wrong in a migration.

**Comment by bloggervista** [comment]
I guess it may be due to removing columns .
You need this package I guess
composer require doctrine/dbal

**Comment by rappasoft** [comment]
Yes that was removed natively in Laravel 5.2

**Comment by vutrungduc7593** [comment]
Thanks @bloggervista , i installed doctrine/dbal and it's working now

**Comment by bloggervista** [comment]
@rappasoft should we add this package or leave as it is ?

**Comment by rappasoft** [comment]
We don't need it for anything so it would just be added dependencies for no reason.

**Comment by igorsantos07** [comment]
Unfortunately, not everyone will read that doc section, as Laravel is overall very straight-forward to develop and autocompletion in IDEs work very well. I'm opening a request for that error to be clearer about the missing dep.

**Comment by ahmad-sa3d** [comment]
Thanks, this fixes the issue for me, error message is not helpful

**Comment by saviobosco** [comment]
This error occurs when adding ,removing or modifying columns in migration file after the table has been created. It does not work well in laravel using "sqlite" as the DB_CONNECTION.

**Comment by daydevelops** [comment]
> This error occurs when adding ,removing or modifying columns in migration file after the table has been created. It does not work well in laravel using "sqlite" as the DB_CONNECTION.

This was my case as well. I added a new migration for a column on an existing table. Everything worked fine on my MySQL db, but when I ran my tests using a sqlite db, everything crashed and burned.

Using Laravel 5.7

**Comment by vurcease** [comment]
Adding to the pile to support the solution: composer require doctrine/dbal corrected the error for me. Using Laravel 5.5.

**Comment by Antarian** [comment]
Should be added back as dependency or cleared from code of Laravel project generator.
Laravel 7 code templates generated by creating project are suggesting SQLite in memory for tests. Which eventually fail because of this.
My test failed on removing column.

Is wasting everyone time Laravel intention?

**Comment by cristianecheverri** [comment]
> 
> 
> I guess it may be due to removing columns .
> You need this package I guess
> composer require doctrine/dbal

Thank you, it works!

**Comment by ibiams** [comment]
> Should be added back as dependency or cleared from code of Laravel project generator.
> Laravel 7 code templates generated by creating project are suggesting SQLite in memory for tests. Which eventually fail because of this.
> My test failed on removing column.
> 
> Is wasting everyone time Laravel intention?

doctrine/dbal version 3 doesn't have class 'Doctrine\DBAL\Driver\PDOSqlite\Driver'.
Try installing version 2:

composer require doctrine/dbal:2.12.1

Documentation says it is stable: https://www.doctrine-project.org/projects/dbal/2.12.html

**Comment by anayarojo** [comment]
> > Should be added back as dependency or cleared from code of Laravel project generator.
> > Laravel 7 code templates generated by creating project are suggesting SQLite in memory for tests. Which eventually fail because of this.
> > My test failed on removing column.
> > Is wasting everyone time Laravel intention?
> 
> doctrine/dbal version 3 doesn't have 'Doctrine\DBAL\Driver\PDOSqlite\Driver' class.
> Try installing version 2:
> 
> **composer require doctrine/dbal:2.12.1**
> 
> Documentation says it is stable: https://www.doctrine-project.org/projects/dbal/2.12.html

Thanks.

For me, it worked removing doctrine/dbal version 3

```sh
composer remove doctrine/dbal
```

And then installing doctrine/dbal version :2.13
```
composer require doctrine/dbal:2.13
```
