### ISSUE TITLE
Considering update to Laravel 5.5

### ISSUE THREAD

**Issue by mikimaine** [rappasoft/laravel-5-boilerplate#788]
Since Laravel 5.5 will be released this month should we consider updating this based on the dev branch of Laravel 5.5?

**Comment by rappasoft** [comment]
You can do it manually but I will put out a new release once upgraded.

**Comment by bloggervista** [comment]
@rappasoft how about bootstrap 4 also as laravel 5 has frontend preset.

**Comment by egodsk** [comment]
@bloggervista Laravel Boilerplate uses AdminLTE as the main layout provider, and that admin layout is built on top of Bootstrap 3. So my best bet is there will not be a update to Bootstrap 4, before AdminLTE comes with a new version, that uses Bootstrap 4.

**Comment by rappasoft** [comment]
Yeah for things like that I have to wait for the other people who's projects we use, like laravel collective for the  html/form helpers, I cant update to 5.5 without them first. If we can find a free/open source admin theme that runs on BS 4 I'd give it a look.

**Comment by bloggervista** [comment]
@rappasoft  I think there are plenty of admin themes for bootstrap 4 and they look modern as well . One example is http://coreui.io. 
And there are problems with some package like they use guzzle/guzzle deprecated library.
And regarding laravel collective i guess using normal html is better as using them seems no advantages, isn't it? It is just a opinion bro.

**Comment by rappasoft** [comment]
The laravel form methods have a lot of helpful features, one of my favorites is Form::model where you pass it the object and it pre-fills the inputs for you, great for edit screens.

**Comment by mikimaine** [comment]
@rappasoft but that can easily be replaced with Vuejs two-way data binding, I think now is the time to move away from Forms, What do you think?

**Comment by bloggervista** [comment]
@rappasoft  Yes i guess it is time to move away from Form due to technologies like react, vue. Form::model  usually cause more implicit problem and is slow.
Laravel even removed it due to slowness of that form and they also have limitation in customization. (as I think)
So i guess we need to move away from Forms :)

**Comment by jonathan-bird** [comment]
Release for 5.5 is out :D 

Sounds good re: removing Form & vue & react future. 

Working with this boilerplate on a few of my large projects I've found that I use BS4 for my front-end, and BS3 for the boilerplate panel, so it's easy to do that way. From memory, there's some bootstrap.scss which includes bootstrap 3 (lol) which is included in both front-end and back-end, so just delete that and import 3 & 4 separately.

**Comment by noxify** [comment]
Maybe an alternative admin theme with BS4:

https://github.com/modularcode/modular-admin-html/

**Comment by bloggervista** [comment]
http://coreui.io has support for VUE, REACT And Angular so it can also be alternative :)

**Comment by jonathan-bird** [comment]
Do you have a rough ETA on 5.5 release @rappasoft? - no rush at all, but I'm close to starting a project, so wanting to know whether to hold off on your release or just DL 5.4 boilerplate & manually upgrade

**Comment by derekphilipau** [comment]
would like to see BS4 default for this boilerplate.  switched to BS4 a while ago, was actually considering using coreui for my frontend.  since 5.5 is an LTS release I plan on finally releasing my app w/  BS4 & 5.5 and not worry too much about upgrades afterwards.  maybe next version of boilerplate can be LTS as well?

**Comment by bloggervista** [comment]
i guess if there will be LTS version of boilerplate the progress of this boiler plate is slow and i guess it is not necessary for such thing like boilerplate to provide LTS as for deploying you must edit many files and be familiar with it. For me boiler plate is used as education for writing codes :)

**Comment by derekphilipau** [comment]
@bloggervista I understand your point.  While boilerplate is a great way to learn, I also trust boilerplate to take care of all the common things like access control so I can focus on unique aspects of my app.  I'm a single developer with very limited time.  Currently, every time a new version of Laravel, Vue or boilerplate is released it costs me valuable time to upgrade my application.  Having a stable boilerplate branch for 5.5 would be valuable to me.

**Comment by vesper8** [comment]
CoreUI with BS4 and Vue support looks really fantastic!!!

It would be great if you supported it.. heck you could even replace AdminLTE completely with it!

**Comment by rappasoft** [comment]
It would take me months to create a new version with a new template and all the things listed above. As time is not something I have a lot of right now I don't know what i'm going to do. I haven't started anything with 5.5 yet and I honestly don't know enough about Vue to build it in.

**Comment by bloggervista** [comment]
@rappasoft  how about pull request?

**Comment by rappasoft** [comment]
I don't think a PR would work since the entire thing would have to be done from the ground up. I like the coreui look and all, but I know nothing about Vue, plus a ton of translations would have to be removed and different ones added.

**Comment by bloggervista** [comment]
@rappasoft  in core ui i believe you can choose other like html5 ajax version.

**Comment by Shuyinsama** [comment]
In terms of flexibility I think the Ajax version would work best. But in terms of keeping this maintainable and having some sort of control on quality i'd say look at the Vue.js/React versions of coreui.

@rappasoft do you have any internal documentation on what to port over during a update of laravel version? I am willing to help porting over the current 5.4 boilerplate to the new 5.5 when it releases and maybe get rid of some old Bootstrap and other elements here and there.

**Comment by nasirkhan** [comment]
Core UI is a very good option and i believe AdminLTE should be replaced with this. 

I agree with @Shuyinsama , do you have any check list, if not can you please prepare one? I would love to get involved with this. At the same time Can we set a tentative release date for 5.5 version release with and without CoreUI. I think a big number of people (including me) are waiting for this release.

**Comment by rappasoft** [comment]
Swapping out the admin theme would be a full from scratch rebuild, if you guys are willing to wait a couple months then i'll build it.

CoreUI
Vue
Gates/Policies/Bouncer instead of my access library (it's time to retire it)

**Comment by jonathan-bird** [comment]
Sounds pretty good to me.

On 29 Aug. 2017 12:32 pm, "Anthony Rappa" <notifications@github.com> wrote:

Swapping out the admin theme would be a full from scratch rebuild, if you
guys are willing to wait a couple months then i'll build it.

CoreUI
Vue
Gates/Policies/Bouncer instead of my access library (it's time to retire it)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/rappasoft/laravel-5-boilerplate/issues/788#issuecomment-325537091>,
or mute the thread

**Comment by nasirkhan** [comment]
@rappasoft 
Waiting few months and get a completely new release is not a good idea. Rather we can release sever versions in those few months. At the very first release upgrade the Laravel, then admin theme. 

Earlier we discussed several times if it is a good idea integrate the Vue/React/Angular or be just a Laravel only boilerplate. If we now agree to have those frontend layer then we may start that in another branch. what is your plan?

**Comment by Shuyinsama** [comment]
@nasirkhan I get that, but you also have to consider that @rappasoft has other priorities too, and does this on the side. If he says it means it will be a complete from scratch build. We should respect his timeframe.

This is why I mentioned a earlier internal doc for upgrading. Maybe we can help and add pull requests for it and all that.. Lighten the workload a bit.

**Comment by rappasoft** [comment]
Yes what @Shuyinsama said, I devote as much time to this as I can. Theres probably over a thousand hours of development into it already over the years. I want to keep it up to date but Laravel grows like a weed. I have Laravel fatigue trying to just keep up with whats new and changed on a daily basis.

I will get a 5.5 release out, it will be much different, I will probably remove certain features and swap others out with better external packages, to both save time now, in the future, and make it easier to manage.

I will use Bouncer for roles/abilities, remove my access class.
I will probably find an external history package.
I will try to keep all of the extra auth stuff.
I will remove the current socialite code and see if theres been a better way to do it, that code is circa Socialite 1.0
I will use CoreUI, and try to implement their Vue components
I will use BS4, if it plays nice in alpha.

**Comment by Shuyinsama** [comment]
@rappasoft Many thanks for the boilerplate and your time put into it.
As mentioned earlier I am willing to help if needed.

Currently Bootstrap 4 is in beta on their main site: https://getbootstrap.com/ so at least that's something

Bouncer is great I did a project with it a couple weeks back and it works perfectly

**Comment by rappasoft** [comment]
Thanks @Shuyinsama, the main problem is I have to learn all of this new stuff before I can build it. Especially Vue, I know its the fun cool thing everyone wants, so that one will take me the longest.

**Comment by Shuyinsama** [comment]
It’s not something I really need persé.

**Comment by Shuyinsama** [comment]
Sorry about that I was posting from a Iphone app and the return button posted immediately.

Anyway, I don’t know much of Vue or if it’s preffered. I think in some sense the perfect way would make it library agnostic, so as to not be stuck to a certain development path again.

But that would take more time and CoreUI has multiple versions so that might be interchanagable fast (switch to a react version for example)

Altough I am starting to doubt if you need to bring in a whole backend UI.

Looking at that now it allows you to do basic CRUD for Users and Roles and view Logs.

It’s definitely nice for sure but could something like this be developed as a laravel package? So it’s pluggable?

**Comment by mikimaine** [comment]
I believe we have to migrate to modern FE framework like Vue. 

Now that we know CoureUI has Vue version we should go for that.

@rappasoft  I am willing to help on the rewrite to the application with Vue.

**Comment by rappasoft** [comment]
I started a new project, but most of the packages used haven't been updated to allow 5.5 yet even. Also Bouncer is not 5.5 yet.

**Comment by Shuyinsama** [comment]
@rappasoft Literally 6 hours after your comment here Bounce was supposedly updated: https://github.com/JosephSilber/bouncer/issues/203

**Comment by rappasoft** [comment]
I think i'll wait the couple days for a stable release. Trying to figure out where I want to start.

**Comment by vesper8** [comment]
You should consider maybe using Spatie's Laravel-Permission instead of Bouncer

Here's a detailed review of the two.. they are both great and it's hard to say which is better.. but I tend to think Spatie's packages get more love and better documentation.

Read the review at least and then you can decide https://laravel-news.com/two-best-roles-permissions-packages

**Comment by rappasoft** [comment]
I have started. Should we use the current translation method with the keys, or switch to human readable with the json files?

**Comment by Shuyinsama** [comment]
Is there a huge benefit to the json version? I have no problems with the current way of translating and think it works fine. Consider the amount of work for it. Of course you would need to do the Default english translations and other users could pull request other translations

**Comment by rappasoft** [comment]
That's probably what's going to happen since I'm going to be changing a lot. The translations will prob live in a separate repository. 

The Laravel docs say json is better for large applications. 

Unless we can come up with a standard to naming the keys.

**Comment by derekphilipau** [comment]
In addition, for those of us using Vue/etc. heavily it may be tidier to have all translations stored in JSON.

**Comment by rappasoft** [comment]
Can you explain more?

**Comment by Shuyinsama** [comment]
My guess would be that Vue Components rely heavily on JSON formatting for translations,
Making it easier to use Vue instead of pure PHP/HTML/Blade type templating?

**Comment by derekphilipau** [comment]
This is only my first Laravel application with Vue.  I'm still struggling with the balance between Blade templates and Vue components, but the bigger my Vue components get the more responsibilities they have like permissions and translations.  I currently have duplications with the translations in your boilerplate and those needed by Vue (JSON).  I'm not exactly sure how to integrate the two, but moving everything to JSON might be a good start.

**Comment by rappasoft** [comment]
I'm probably going to stick to the way it is to make it easier for all the people that have current language packs to update.

**Comment by daniel-farina** [comment]
@rappasoft 
I've been extremely busy at work but I'll do my best to help soon. My friend and I are on the same boat as you when it comes to start using VUE.

I'm not sure how you were able to keep going at all the changes from Laravel for so long but your strategy of making Boilerplate as minimal as possible and using third party open source solutions is very smart in order to keep this project alive.

**Comment by rappasoft** [comment]
Just to re-iterate, I started from scratch with this, which means it's like learning it all over again. So please give me some time, If you need a 5.5 in the meantime just follow laravel upgrade guide with the current version.

**Comment by rappasoft** [comment]
Update: Almost done with the frontend.

**Comment by nasirkhan** [comment]
Awesome. Thanks for let us know the updates.

Are you going to push these changes to a new branch soon?

How can assist you here?

On Sep 12, 2017 9:26 AM, "Anthony Rappa" <notifications@github.com> wrote:

Update: Almost done with the frontend.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rappasoft/laravel-5-boilerplate/issues/788#issuecomment-328724044>,
or mute the thread

**Comment by rappasoft** [comment]
I can make a branch so everyone can see but i'm not up to the point of taking PR's yet. It's really nothing special currently, changed a few things since I started over, ported most classes over. New kickass base repository I found, spatie permissions, etc.

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/tree/feature/5.5

Frontend is done minus the language switcher which isn't working.

Please no PR's

**Comment by derekphilipau** [comment]
For those of you who were interested in CoreUI, today I did a quick integration of CoreUI Vue with Laravel 5.5.  (I plan on using CoreUI for my front-end with this boilerplate):  https://github.com/derekphilipau/laravel-5.5-coreui-vue-separated  
https://github.com/mrholek/CoreUI-Vue

**Comment by rappasoft** [comment]
@derekphilipau I'm trying to get BS4 to work on the frontend right now, all assets are there it's just not working, thoughts?

**Comment by rappasoft** [comment]
Maybe you can take a look: https://github.com/rappasoft/laravel-5-boilerplate/commit/ebc594b425ad47b6e75f32992bc33edaaae1f29f

**Comment by derekphilipau** [comment]
i just did a fresh install of that branch, changed the BS4 package from alpha to `"bootstrap": "^4.0.0-beta",`, ran ` npm run dev` and the generated frontend.css definitely includes Bootstrap v4.0.0-beta.  Do you mean the formatting of the blade files (like navbar)?  I can adapt the frontend templates to BS4 tomorrow.

**Comment by rappasoft** [comment]
I know it's included, yes the formatting, I just assumed the markup was the same. I guess not.

**Comment by derekphilipau** [comment]
hmm, i see what you mean. i just tried disabling a lot of extra stuff like debugbar and replaced the index with https://v4-alpha.getbootstrap.com/examples/starter-template/, still didn't work correctly, navbar especially.  i can look at it in about 8 hrs. if you want to work on other stuff

**Comment by rappasoft** [comment]
Yeah something isn't fully right. I got some stuff to work if you pull most recent.

**Comment by nasirkhan** [comment]
Tough it is not completed, but i checked the BS4 and it is working perfectly. You can check at https://github.com/nasirkhan/laravel-5-boilerplate

**Comment by rappasoft** [comment]
The current 5.5 branch is working for you and doesnt look like crap?

**Comment by nasirkhan** [comment]
sorry previous comment gone missing. 

* pulled the 5.5 branch. the index was broken. the reason is BS3 and BS4 markups and class names are very different. 
* copied the `nav` from an example and pasted here and then it worked perfectly. Did not updated the text though. 
* `card`s uses different classes than the one added in 5.5 branch
* `dropdown nav` was not working at the beginning as `jQuery` was missing.
* updated the `vue template` but need some other changes to make it look perfect.
* there is no icon set included by default but they have a list of preferred libraries.

**Comment by rappasoft** [comment]
BS4 no longer uses glyph?

**Comment by nasirkhan** [comment]
no it is not in the library. 
Details: https://getbootstrap.com/docs/4.0/extend/icons/

**Comment by bloggervista** [comment]
Bs4 uses favicons isnt it

**Comment by rappasoft** [comment]
No it ships with none and lets you choose.

**Comment by bloggervista** [comment]
Sorry i means fontawesome fa.

**Comment by rappasoft** [comment]
Index works BS4 now. Have to do the rest of the views.

**Comment by rappasoft** [comment]
So as far as the backend with CoreUI, would it be best to do an HTML frame and have the Vue components in there, I don't know if I want it to be SPA style because less people will be able to use it. I think the routing should be handled by Laravel and just inject the components it needs in.

**Comment by nasirkhan** [comment]
I also agree with you that the routes should be handled by Laravel and please do not make it a SPA

**Comment by derekphilipau** [comment]
I spent the morning trying to integrate https://github.com/ARCANEDEV/LogViewer (BS3.3.5, Jquery, etc.) with Laravel 5.5/BS4/CoreUI/Vue.  It's a lot of work for what I personally feel is little gain.  I'm fine with the old backend, it doesn't have to be pretty but simple, stable & functional.  Having said that, I still plan on using Laravel 5.5/BS4/CoreUI/Vue for the front-end.

**Comment by rappasoft** [comment]
Is CoreUI BS4 only? I don't want to have different versions of bootstrap for frontend and backend. I'm not going to use any plugin that doesn't support BS4, or if I do, it would use their vendor files and just call their routes.

What part of CoreUI are you using for your frontend @derekphilipau?

**Comment by derekphilipau** [comment]
My laravel/vue app has a complicated frontend that a "dashboard" is perfect for, so I'm trying CoreUI Vue.  Also I'm learning from their use of vue-router, bootstrap-vue, and vue-chartjs.  I think CoreUI was just started a year ago and was always BS4? Looks like AdminLTE is planning to go BS4 for next major release.  I agree it would be great to be as consistent as possible between front/backend by using BS4, but LogViewer might be a problem.  It would be pretty simple to update the LogViewer blade templates for BS4, but removing jquery more difficult (and not really necessary unless you want pure Vue). I can try to help with the LogViewer, first see if the dev is interested.

**Comment by rappasoft** [comment]
Well bootstrap requires jquery anyway so what would be the issue?

**Comment by bloggervista** [comment]
AdminLTE seems not to switch to bootstrap 4 until it releases full stable version. It might takes year for bootstrap 4 version whereas every other popular library uses bootstrap 4.

**Comment by derekphilipau** [comment]
Projects like https://bootstrap-vue.js.org/ and vue-chartjs are making it possible to go "pure" Vue, with absolutely no dependence on jquery.  But I think for backend it's not a huge issue to stay with jquery, boilerplate backend can always be updated later once Vue alternatives to jquery are more stable

**Comment by nasirkhan** [comment]
@rappasoft From my understanding updating the Laravel and use some related packages are the first priority and then everything else. Releasing fast and in phases could be a strategy. 
We can go full Vue but as it is a Laravel focused project and you are not that fluent in that we can try to do it later on. 

We may start with CoreUI Ajax or minimal Vue. Do doing so we will get a new look with BS4, jQuery, and the Laravel backend will be ready to use was a complete product.

After the release we can discuss and add more Vue. That part can be done via PR. what is your plan.

**Comment by rappasoft** [comment]
I'm doing my best to swap out all the custom stuff I had to manage to an external package that someone else manages, for example the history is being swapped for a package that tracks changes to models (not as robust but still useful)

I think the plan since I already have BS4 working on the frontend, is to use the static version os CoreUI for the backend using BS4, and rebuild what we have. Then from there after we launch we can start converting some components of the backend to the CoreUI Vue equivalent.

**Comment by nasirkhan** [comment]
I also mentioned the same. Vue should be added when we have a stable BS4 version. 

When you think you are ready please let us know, I would love to assist you here.

**Comment by derekphilipau** [comment]
I created an issue to see if https://github.com/ARCANEDEV/LogViewer has any plans for a BS4 version.  Anyway, I have already converted some of its blade files in order to assess difficulty. Mostly typical BS3->BS4 issues.  If there is any response or progress I will let you know.

**Comment by rappasoft** [comment]
I converted the frontend to BS4 after reading the docs, it is not perfect in all screen sizes if someone can fix and make a PR for all the frontend views please.

**Comment by derekphilipau** [comment]
Today I made a "themeable" version of LogViewer, now it can show either BS3 or BS4.  I hope someone here will take a look at it before I try a PR.  I'm not clear about how to develop/test a laravel package, please see README_TEST.md file for how I did things.  https://github.com/derekphilipau/LogViewer

**Comment by nasirkhan** [comment]
@rappasoft Any update regarding this new release?

**Comment by rappasoft** [comment]
Been giving it almost 5 hours a day for a few weeks now. It is just a side project. It's about 50% done. It's not going to have core ui vue version at launch.

**Comment by nasirkhan** [comment]
@rappasoft do not get me wrong. I am not pushing to release fast. I know it is your side project. You are maintaining this project for a long time and consistently updating. Only a very few starter project or cms could do that so far. Thanks for your great effort. 
Actually i wanted to start a new project on Laravel 5.5 based on this boilerplate. I know it has some important features and if i have an idea about the release dates then i can continue to explore the other parts of Laravel.

**Comment by rappasoft** [comment]
Probably at least a couple of weeks, not counting tests or documentation.

Here's the back so far:

<img width="1440" alt="screen shot 2017-09-17 at 16 00 23" src="https://user-images.githubusercontent.com/6026504/30524421-595bf816-9bc1-11e7-8ad3-18388c668855.png">

**Comment by rappasoft** [comment]
For those of you itching, the current branch is pretty far along minus the user/roles CRUD UI and some other stuff.

**Comment by rappasoft** [comment]
<img width="1440" alt="screen shot 2017-09-17 at 23 19 08" src="https://user-images.githubusercontent.com/6026504/30528193-a4950a74-9bfe-11e7-9d84-c2e016466917.png">

**Comment by derekphilipau** [comment]
I just put in a PR for LogViewer, [adding "themes"](https://github.com/ARCANEDEV/LogViewer/pull/170).  For now, you can easily update the current LogViewer to BS4 simply by replacing the views directory with the BS4 version in my repository:  https://github.com/derekphilipau/LogViewer/tree/master/resources/views/bootstrap-4

**Comment by rappasoft** [comment]
Awesome i'll definitely use that to save some time thanks! If you have time, can you download the current build and try to replicate the issue I posted here: https://github.com/spatie/laravel-activitylog/issues/268

Something else seems to be interacting with that extension and causing weird behavior. Let me know if anyone can replicate that behavior on their end or if its just me.

**Comment by rappasoft** [comment]
Also if anyone wants to make the language dropdown in the backend more compact since it goes off the screen that would be helpful.

And also the frontend views are bootstrap 4, but I haven't optimized them for mobile yet, if anyone has time and wants to contribute.

**Comment by bloggervista** [comment]
@derekphilipau  its working for me thanks

**Comment by derekphilipau** [comment]
i'll check out the activitylog problem.  this might be of help to one of you- i just spent two hours figuring out why npm wasn't installing anything, re-installed everything on my system, finally realized it's actually a problem with the css-beautify.js, just manually install ````npm install js-beautify@1.6.14```` and specify the right dependency in your package.json
````npm ERR! enoent ENOENT: no such file or directory, chmod '....../..../.../node_modules/js-beautify/js/bin/css-beautify.js'````

**Comment by rappasoft** [comment]
Haven't had that problem, is it CoreUI related?

**Comment by derekphilipau** [comment]
js-beautify is a dependency of vue, so during yesterday while the js-beautify npm was broken, all npm installs of anything requiring vue (including boilerplate) were failing.  resolved now: https://github.com/beautify-web/js-beautify/issues/1254

**Comment by nasirkhan** [comment]
Yesterday i faced the same issue with npm and not is has been resolved. 

@rappasoft i can look into the frontend to make it responsive. Regarding the long dropdown usually i use Select2 (http://select2.github.io/) if you think it is ok, i can integrate that too.

**Comment by minedun6** [comment]
@nasirkhan is it possible to integrate select2 plugin using vue ?
so far I haven't been able to use it with Vue. Maybe I didn't know how to but I'd like to see integrated for future use.

**Comment by derekphilipau** [comment]
@minedun6 @nasirkhan You can look at these vue components:  https://github.com/sagalbot/vue-select  https://github.com/monterail/vue-multiselect

However, if you look through the comments for this issue you will see that Vue will not be used, boilerplate only provides the framework on which you can build a Laravel application (with Vue if you choose).

**Comment by nasirkhan** [comment]
for the next release it will not be a Vue project. so Select2 should be ok. I think we should check the other possibilities of using Select2-Vue libraries after this release.

**Comment by bloggervista** [comment]
I guess there is no problem in submitting PR . You can check out 5.5 feature branch and pull request those branch. 
Yes next release won't be vue but later will be so we will think vue later. Lets release this coreui version as soon as possible.

And Arcanedev has already created branch for bootstrap 4 so it is expected to release soon . I guess we should work on backend other parts as soon as possible.

**Comment by rappasoft** [comment]
I'd rather try to fix it without an extra plugin first. 

Maybe by dropping the font size or padding.

**Comment by nasirkhan** [comment]
As it is just links we can add multiple columns in the drop down.

**Comment by rappasoft** [comment]
I created a channel in slack called bp_update where we can take this conversation because this page is getting long.

**Comment by bloggervista** [comment]
rappsoft can you give url to slack channel?

**Comment by rappasoft** [comment]
@bloggervista https://laravel-5-boilerplate.herokuapp.com/

**Comment by bloggervista** [comment]
@rappasoft  can we move away from that FORM laravel collective package. If you want I can PR it. Anyway amount of code is nearly same and this is package is not used by many people .

**Comment by rappasoft** [comment]
I use it a lot for the form model method, someone said you can do the same thing using Vue binding but I don't know how right now.

**Comment by lloricode** [comment]
hmmm may I ask something?

estimate time to wait for 5.5?

:+1:

**Comment by nasirkhan** [comment]
Very valid question. I was asking the same, that we are ok to wait and should have a tentative release date. But as @rappasoft works on this project in his free time and obviously he has other projects, he can not commit a specific date. 

All we can do is to request him 😄 and wait a while. At the same time we can assist him to complete the project. 

To know the latest updates you can join the slack channel at https://laravelboilerplate.slack.com/messages/C75A9UJBC/

**Comment by rappasoft** [comment]
Yes I have a todo list in the 5.5 slack channel if anyone wants to help.

**Comment by lloricode** [comment]
@rappasoft, yes I pull the branch `feature/5.5`, but it seams to be long journey :D

I thought `composer.json` is the only need to change for upgrading to a new latest laravel framework.

**Comment by rappasoft** [comment]
Haha not exactly.

**Comment by illuminate3** [comment]
What is the over goal for this project?
It would be nice to have a defined feature set that we all could help to submit PRs or even ideas.

**Comment by bloggervista** [comment]
@illuminate3  If you can help then you can check 5.5 development branch and send pull request.

Remove unused language lines when completed
Get images/logo.png to stop generating on npm dev
Get spatie/activitylog working correctly
Can't get pace-js to load in without causing errors (Commented out in js/backend/before.js)
Fix log viewer BS4 views
Add a nice page header section that the views can extend instead of throwing an H1 at the top which looks like shit.

Join at heroku
https://laravelboilerplate.slack.com/messages/C75A9UJBC/files/F75F8FM7X/ for more info

**Comment by Drivez** [comment]
@rappasoft  Have you checked out the [https://github.com/rinvex/fort](url) package for authentication?

**Comment by rappasoft** [comment]
Already have spatie baked in

**Comment by illuminate3** [comment]
@Drivez and @rappasoft 

Fort takes care of the authentication and has 2 factor ability. Spatie seems to more involved with authorization.

Any reason to go with Spatie over Bouncer or Shinobi from caffinated?

**Comment by rappasoft** [comment]
I like spatie packages because they always use the most up to date PHP versions and never go stale. I'm not trying to give everyone all the features, it should be easy enough to swap them out if someone wanted to.

**Comment by illuminate3** [comment]
Makes sense.

**Comment by vesper8** [comment]
I stopped using laravelcollective's form in favour of spatie's https://github.com/spatie/laravel-html

I think it's worth a look, I find it more useful and more updated

**Comment by illuminate3** [comment]
@vesper8

I haven't seen that yet. That does look more useful! Thanks

**Comment by Rootes** [comment]
@rappasoft Señor, is possible to do a "php artisan make:backend NameOfTheLink" That generate the files that we need for after work on them. that would be amazing for amateurs like me.. :)

**Comment by poseso** [comment]
De hecho hay un paquete de una colega que hace basicamente todo por ti aca el link :

https://github.com/amamarul/boiler-plate-commands

**Comment by rappasoft** [comment]
The 5.5 branch is in its final stages, I want to thank everyone for their help. It's been a massive upgrade.
