### ISSUE TITLE
Error in the documentation

### ISSUE THREAD

**Issue by pmirandaarias** [rappasoft/laravel-5-boilerplate#789]
In: http://laravel-boilerplate.com/5.4/documentation.html#session-timeout
it's mentioned this: `If the environment variables are not set, it will fallback to the defaults set in app\config\misc.php.` and that file doesn't exists.

**Comment by poseso** [comment]
misc.php is under l5.3 version and it contains this:

<?php

return [

	/**
	 * In seconds
	 * Default: 10 mins
	 */
	'session_timeout_status' => env('SESSION_TIMEOUT_STATUS', true),
	'session_timeout' => env('SESSION_TIMEOUT', 600)
];

**Comment by bloggervista** [comment]
I guess we need to update documentation then :)

**Comment by rappasoft** [comment]
Can you make a PR to the documentation?

**Comment by bloggervista** [comment]
currently i am having exams after finishing i will PR it if it is not fixed till that time. And it is not that much major issue :)

**Comment by bloggervista** [comment]
@rappasoft where are docs stored and where should we PR for updaing docs?

**Comment by Shuyinsama** [comment]
@bloggervista https://github.com/rappasoft/laravel-boilerplate-documentation

**Comment by bloggervista** [comment]
@Shuyinsama as this package is being upgraded to 5.5 I guess we will have completely rewritten docs. So We can close this issue.

**Comment by Shuyinsama** [comment]
I agree. After the upgrade to 5.5 is done we will focus on the docs and will take this with is.

Thanks!
