### ISSUE TITLE
FontAwesome Missing Replace with CDJNS links

### ISSUE THREAD

**Issue by 0E800** [rappasoft/laravel-5-boilerplate#790]
Font Awesome not working out of the box. There is no vendor/fonts dir.

File to edit:
`/public/css/backend.css`
`/public/css/frontend.css`

Replace all FontAwesome sources with below. 

https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.eot
https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.svg
https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.ttf
https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff
https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2

Glyphicons are also missing.

Replace with:
//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/fonts/glyphicons-halflings-regular.eot
//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/fonts/glyphicons-halflings-regular.svg
//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/fonts/glyphicons-halflings-regular.ttf
//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/fonts/glyphicons-halflings-regular.woff
//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/fonts/glyphicons-halflings-regular.woff2

**Comment by bloggervista** [comment]
I guess it is included isn't it 

In public/fonts/vendor/font-awesome

I guess laravel boiler plate is mainly for local development and referencing too many cdn links is not good isn't it?

**Comment by rappasoft** [comment]
Laravel mix should create the folders for you as it tries to import them.

**Comment by rappasoft** [comment]
Or make a PR with CDN links and i'll test.
