### ISSUE TITLE
Removing Duplication On View 

### ISSUE THREAD

**Issue by bloggervista** [rappasoft/laravel-5-boilerplate#793]
If we go to backend.access.edit and backend.access.create views we see many are duplicated and difference is very small. Is there any optimization can we do?

And is this package going to depend on laravel form builder in future also?

**Comment by rappasoft** [comment]
What do you mean?

**Comment by bloggervista** [comment]
@rappasoft  i mean if you see the form code is so much repeated. And form builder is not used anymore isnt't it?

**Comment by rappasoft** [comment]
The form builder is used on every form isn't it?

**Comment by bloggervista** [comment]
i mean other don't use it. And if you check edit part of boilerplate inside view and create part of boiler plate you will notice many code are same inside {!! Form:: !!}
