### ISSUE TITLE
Lose stylesheets or Page not lfull loaded 

### ISSUE THREAD

**Issue by phuongphally** [rappasoft/laravel-5-boilerplate#794]
Load CSS not working , 

I have to refresh many to get it work

The problem like this picture .

https://drive.google.com/file/d/0BxWTfF4b4CCWR3Z0R09BT0FYX0E/view

Can you tell me please , I really need your helps .

Thanks for your answers .

**Comment by bloggervista** [comment]
What you mean by load css. everything seems fine to me

**Comment by phuongphally** [comment]
I don't know too , You can see in picture I share to you .


Some time layout not load and some time  form css not good .


After refresh page is ok . But how the end user ? they need to refresh all time ? 

Thanks your reply .

**Comment by bloggervista** [comment]
may be your connection is slow. And can you show screenshot of how chrome debugging tools console look like when there is error

**Comment by bhill77** [comment]
@phuongphally cek your browser console. maybe there is an error on your js script

**Comment by rappasoft** [comment]
There is definitely nothing wrong with asset loading.
