### ISSUE TITLE
Where's Jquery loaded?

### ISSUE THREAD

**Issue by pmirandaarias** [rappasoft/laravel-5-boilerplate#797]
In `app,js` from backend, we have:

```
//Make sure jQuery has been loaded before app.js
if (typeof jQuery === 'undefined') {
    throw new Error('AdminLTE requires jQuery');
}
```

While in `webpack.mix.js`:

``.js([
        'resources/assets/js/backend/app.js',
        'resources/assets/js/plugin/sweetalert/sweetalert.min.js',
        'resources/assets/js/plugins.js'
    ], 'public/js/backend.js')``

So, if `app.js` is the first javascript file loaded, how can be jquery be enabled and working?

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/blob/master/resources/assets/js/bootstrap.js#L10
