### ISSUE TITLE
Laravel Passport Personal Access Tokens is not “personal” at all

### ISSUE THREAD

**Issue by oaigudmundsson** [rappasoft/laravel-5-boilerplate#799]
Hello!

I posted a topic about this on [stackoverflow](https://stackoverflow.com/questions/45415429/laravel-passport-personal-access-tokens-is-not-personal-at-all)  but couldn't get any answers. I wonder if this could relate to this boilerplate.

I am login as admin and from there i created my first Personal Access Tokens (PAT) for admin. Then i want to create a new PAT for user A. But instead i do see the admins PAT. If i go to user B, then i do see admins PAT as well. 

Any thought about this?

Cheers

**Comment by rappasoft** [comment]
This project has no functionality that uses passport, and I haven't used it, so I personally can't be of help. You should try the laracast forums.
