### ISSUE TITLE
trans_choice uses a non-working syntax

### ISSUE THREAD

**Issue by Shuyinsama** [rappasoft/laravel-5-boilerplate#802]
# What version?
Laravel 5.4 Boilerplate

# Issue
I was working on translating and moving the notifications dropdown from the backend to the frontend and noticed that the `trans_choice` was stuck on `you have 1 notification` while I had 3 notifications ready.

the translations file [strings.php#53](https://github.com/rappasoft/laravel-5-boilerplate/blob/master/resources/lang/en/strings.php#L53) uses the following line:
```php
{0} You don\'t have notifications|{1} You have 1 notification|[2,Inf] You have :number notifications
```

this didn't work for me cause it would always return the `You have 1 notification`.
So after searching the issues I found a old issue https://github.com/rappasoft/laravel-5-boilerplate/issues/272

Yet that solution didn't work either. So after checking laravel documentation I changed the line to the following in combination with the solution from that issue:
```php
{0} You don\'t have notifications|{1} You have 1 notification|[2,*] You have :number notifications
```
_notice I changed `Inf` to `*`_

I can put this in my pull request for the dutch translation and could change it everywhere if you want

**Comment by rappasoft** [comment]
Fixed
