### ISSUE TITLE
Registering users with different role from frontend while doing signup

### ISSUE THREAD

**Issue by arikazukito** [rappasoft/laravel-5-boilerplate#806]
I am user boilerplate of version 5.4.
I want to know how to give a roles in signup form in the beigining while doing signup.
The roles like the employee signup and employer signup at different signup form .

**Comment by Shuyinsama** [comment]
I don't fully understand your question.

Do you want to be able to apply a role to a user from the frontend registration form?
If so then that would be kind of dangerous don't you think?

The frontend registration is made for users to register by themselves. If you would allow people to choose their own roles in your systems then why make roles at all?

**Comment by arikazukito** [comment]
I want to make two registration form which will register emloyer and
employeee.
So how can i make it?

On 21 Aug 2017 16:14, "Patrick van Zadel" <notifications@github.com> wrote:

I don't fully understand your question.

Do you want to be able to apply a role to a user from the frontend
registration form?
If so then that would be kind of dangerous don't you think?

The frontend registration is made for users to register by themselves. If
you would allow people to choose their own roles in your systems then why
make roles at all?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rappasoft/laravel-5-boilerplate/issues/806#issuecomment-323708186>,
or mute the thread

**Comment by Shuyinsama** [comment]
Create a different function in a controller for each form.
1 Form uses `storeEmployee` function that creates a User model with the role `employee`
1 Form uses `storeEmployer` function that creates a User model with the role `employer`

Where would you put these?
Are these forms on the frontend?
Are these forms in the backend only visible to admins?
How would you verify that someone is a employer or employee.
You don't want someone being registered with the wrong role.

On a different note: This is more of a question for [laracasts](https://laracasts.com/discuss)

**Comment by arikazukito** [comment]
I want to put it in frontend with 2 register form.
1 for employee and other for employer.
one who register by clicking to employee register will get role of employee
and other registering by clicing in employer will get role employer

On Mon, Aug 28, 2017 at 3:04 PM, Patrick van Zadel <notifications@github.com

**Comment by Shuyinsama** [comment]
Then the option I mentioned above should do fine.

I would recommend some verfication and/or validation for these though. Otherwise you'd have employees registering as employers.
