### ISSUE TITLE
(question) How do you version-control your permissions?

### ISSUE THREAD

**Issue by eduardoarandah** [rappasoft/laravel-5-boilerplate#808]
Let's say you add a new module to your app. 
And remove another module. 

And in production there were roles a lot of roles added, with custom permissions. 

What are your best practices for keeping your permissions table up to date?

**Comment by rappasoft** [comment]
Permissions are static, I usually just add them to the seeder and re-seed that seeder when I need to, then any roles can just be recreated manually.

**Comment by wgqi1126** [comment]
@rappasoft 

In laravel doc, it said:
[https://laravel.com/docs/5.6/seeding](https://laravel.com/docs/5.6/seeding)
 > Laravel includes a simple method of seeding your database with test data using seed classes. 

so **How do you version-control your permissions** on **production** env.

**Comment by bambamboole** [comment]
@wgqi1126 its how he describes it...
Just Put them into a PermissionSeeder and run it on deployment

**Comment by wgqi1126** [comment]
@bambamboole 

Seeder is used for test data on deployment.

If I want change permission after launch on production env.

What is the best boilerplate?

😂

**Comment by rappasoft** [comment]
It's not against the law to rerun a seeder on production.

When I merge in new features that add permissions, i'll rerun permission seeder on production and then I have all the permissions I need for the application to run.

**Comment by wgqi1126** [comment]
You mean that you created a seeder that only for permission, but not [this seeder](https://github.com/rappasoft/laravel-5-boilerplate/blob/master/database/seeds/Auth/PermissionRoleTableSeeder.php).

😳

**Comment by bambamboole** [comment]
@wgqi1126 you can also seed database within a migration. that way you can take advantage of the normal laravel schema versioning.

**Comment by eduardoarandah** [comment]
I solved it like this:

1: create a config file with permissions 

2: create a command  “permissionsSync” that adds inexistent permissions

3: call that comand every time you git pull in production 

This way your permissions get  version controlled because config->permissions is version controlled
