### ISSUE TITLE
Problem with npm install

### ISSUE THREAD

**Issue by teramandiri** [rappasoft/laravel-5-boilerplate#81]
I'm using Windows 7 64bit, node v4.0.0, npm 2.14.3. I encounter errors when running npm install. I use Administrator for run prompt command.
![npm install error](https://cloud.githubusercontent.com/assets/14168640/9866551/d5e7ee24-5b8d-11e5-95e3-431c53c3be73.png)

**Comment by Soufraz** [comment]
I faced the same problem.. 
In my case, I update the npm and it works.

**Comment by rappasoft** [comment]
Yeah sometimes the initial install hangs up for some reason, just running an update seems to always fix the problem.

**Comment by raakesh** [comment]
I was also having same problem.
It somehow worked with the following steps.
-remove node_modules
-run npm install npm@latest -g
-and run npm install again
