### ISSUE TITLE
Documentation: Debugbar `explain` must be disabled when using non-mysql

### ISSUE THREAD

**Issue by chrismichaels84** [rappasoft/laravel-5-boilerplate#812]
This is really simple, and only half pertaining to the awesome laravel-5-boilerplate, but a line in the documentation would have saved me 6 hours of bug hunting.

When using postgres (or any non-mysql driver) you must disable the `explain` function for the laravel-debug bar. When this is enabled, it causes debugbar to crash and causes errors in some of the other queries that don't even get reported.

Related to https://github.com/barryvdh/laravel-debugbar/pull/352.

Everything else seems to work fine with postgres. Thank you.

**Comment by chrismichaels84** [comment]
As I continue working with postgres, I will collect any other oddities. I would be happy to open a PR against the documentation to cover steps needed to use postgres instead of the default mysql (if any others creep up).

**Comment by rappasoft** [comment]
Disabled by default with next version.
