### ISSUE TITLE
When open the boilerplater localhost/app-name/public

### ISSUE THREAD

**Issue by ojames314** [rappasoft/laravel-5-boilerplate#819]
found this bugs when run localhost/app-name/public
Warning: require_once(/Applications/XAMPP/xamppfiles/htdocs/smarthr1/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/smarthr1/bootstrap/autoload.php on line 17

Fatal error: require_once(): Failed opening required '/Applications/XAMPP/xamppfiles/htdocs/smarthr1/bootstrap/../vendor/autoload.php' (include_path='.:/Applications/XAMPP/xamppfiles/lib/php') in /Applications/XAMPP/xamppfiles/htdocs/smarthr1/bootstrap/autoload.php on line 17

**Comment by ojames314** [comment]
will be glad if help can render ASAP. thanks.

**Comment by Shuyinsama** [comment]
As mentioned in your other issue. I think this is because you are accessing it through the public folder in XAMPP.

Otherwise it seems the autoload is not created, try something like
`composer dump-autoload`
