### ISSUE TITLE
php artisan migrate:refresh error

### ISSUE THREAD

**Issue by hopewise** [rappasoft/laravel-5-boilerplate#82]
Hello,

First of all, I would like to thank you for this great work, but when I had integrated it into my project, I got this issue, can you please check it here:

http://stackoverflow.com/questions/32624683/where-is-the-migrations-source-files

**Comment by rappasoft** [comment]
There is no such file in this boilerplate. There is a CreatePasswordResetsTable file though. I don't know where that is in your project. All migration files are under database/migrations
