### ISSUE TITLE
FONT ICONS NOT SHOWING AFTER SEVERAL REFRESHING

### ISSUE THREAD

**Issue by ojames314** [rappasoft/laravel-5-boilerplate#820]
Hello,

Please do note that font icons not displaying after installing. please see attached file for more info
thanks

![font icons not showing](https://user-images.githubusercontent.com/21101042/30001338-00e5a808-9040-11e7-8084-c7a4e37e1cd2.png)

**Comment by Shuyinsama** [comment]
Please check your console output.

I have been using this project for months now and all of them (even a new project) display Font Icons.

Judging by your other "issue" it seems you are using windows and XAMP. It seems to me that directly accessing the "public" folder results and unknown relevant paths. Laravel should normally not be accessed through the public folder but should be pointed as the "root" folder of your virtual host. making it the default folder.

This is not an issue with the boilerplate. Try something like Laravel Homestead

**Comment by krishnaguragain** [comment]
@ojames314 Please use laragon to easily create the virtual host and please check console and sometimes adblocker block fonts.
