### ISSUE TITLE
Package guzzle/guzzle is abandoned ?

### ISSUE THREAD

**Issue by adnanmayo** [rappasoft/laravel-5-boilerplate#825]
Whenever i `composer update` or `composer install` i got this warning. 

`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`

how to fix this?

I am using laravel 5.4 boilerplate

**Comment by rappasoft** [comment]
That's because one of the other packages is trying to import it, nothing we can do until they update.
