### ISSUE TITLE
New Access Control

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-5-boilerplate#83]
Working on new access control library, much more configurable. Basing it loosely off of the Magento ACL system, but building it entirely from scratch.

Below is a preview of the new 'Permission Groups' section which allow you to organize your permissions into groups and subgroups that will be listed as a hierarchal tree view when adding them to roles, much like magento.

![1](https://cloud.githubusercontent.com/assets/6026504/9962790/9a4d54b6-5df5-11e5-95f5-ac5f340c2846.png)
![2](https://cloud.githubusercontent.com/assets/6026504/9962791/9a4e2ba2-5df5-11e5-95f8-8b7f579adcb4.png)

Feel free to checkout the feature branch as a new project to test, however it is no where near done. The only sections that are done are the permissions and groups.

Hope you like it and think this will be a really nice update for better access control on larger applications.

**Comment by blomdahldaniel** [comment]
oOo! this looks interesting man! :smile:

**Comment by strainovic** [comment]
Excellent work! Just keep going!

**Comment by rappasoft** [comment]
Glad you like. Will post a picture of the new role screen in a few.

**Comment by rappasoft** [comment]
Here's the new add role screen:

![role](https://cloud.githubusercontent.com/assets/6026504/9973237/40a20c02-5e3d-11e5-826d-2e589e09ef91.png)

**Comment by rappasoft** [comment]
Just pushed that to the feature if you want to play. Still have to integrate into the users areas.

**Comment by idevwebs** [comment]
You're doing some awesome stuff here! Nice work :)

**Comment by teramandiri** [comment]
Hey Rappa, first thanks for your awesome stuff. It's really helped me to learning ACL.
I tried the feature branch for the new project, but results like this.
![permission](https://cloud.githubusercontent.com/assets/14168640/9980332/67f88c5e-5fbe-11e5-9e51-5539f5a8c277.png)

And
![role](https://cloud.githubusercontent.com/assets/14168640/9980336/7eb50e40-5fbe-11e5-995a-d648f45ff1d5.png)

Is there something wrong?

**Comment by rappasoft** [comment]
Finished create/edit user.
Just have to test everything and update the docs.

<img width="1440" alt="2015-09-21 10 23 15 am" src="https://cloud.githubusercontent.com/assets/6026504/9994357/dd4eecd2-604a-11e5-8a5f-eda53167f700.png">

**Comment by rappasoft** [comment]
Anyone want to install this and play around, let me know if you find any bugs?

https://github.com/rappasoft/laravel-5-boilerplate/tree/feature/remake_access_library

**Comment by rappasoft** [comment]
Merged
