### ISSUE TITLE
error in plugins

### ISSUE THREAD

**Issue by arikazukito** [rappasoft/laravel-5-boilerplate#832]
Plugins like selects, ckeditor and datepicker is not working in laravel 5.4 boilerplate...
I have put their respective css file and js file seperately and compliled and i think their compilation order is not proper

**Comment by rappasoft** [comment]
I have used all of those plugins with the boilerplate, the boilerplate can not cause third party frontend stuff not to work, you must not be adding it right.

**Comment by arikazukito** [comment]
can you teach me how to put those plugin order, it always says select2
function is undefined

**Comment by poseso** [comment]
Just put it after all scripts load
