### ISSUE TITLE
production url

### ISSUE THREAD

**Issue by nimeshc64** [rappasoft/laravel-5-boilerplate#846]
*In Production i want to go web site without /public , how to do this, like php artisan serve ** 

# What version?
boilerplate. 5.2

**Comment by rappasoft** [comment]
Not sure what you're asking.

**Comment by brentkozjak** [comment]
It sounds like your root html path is configured incorrectly.  You'll need to configure your production webserver to serve the /public directory as opposed to the base Laravel directory.  It is also likely that you're inadvertently serving your entire Laravel directory to the world, including files such as .env which is, of course, a massive security vulnerability - so it is important to get this right.

**Comment by nasirkhan** [comment]
I assume you installed the project on a cPanel (or similar control panel) and uploaded files on `public_html` directory. Please your webmaster or hosting support to change the domina root to laravel public directory.
