### ISSUE TITLE
PDO Exception with Postgres

### ISSUE THREAD

**Issue by pvsridhar** [rappasoft/laravel-5-boilerplate#849]
I am installing this in my localhost with Postgres as backend. But it showing **[PDO Exception]** could not find driver. I am able to run this MySQL.

I am able to run other Postgres Laravel projects successfully.  

My DB Connection:
DB_CONNECTION=pgsql
DB_HOST=127.0.0.1
DB_PORT=5432
DB_DATABASE=mydbname
DB_USERNAME=postgres
DB_PASSWORD=mypwd

Also, updated default connection to pgsql in database.php and cleared cache.
# What version?
Laravel 5.4

Any help would be appreciated. 
Thanks in advance..

**Comment by baneetsharma** [comment]
I had a similar kind of issue, what I did was install sqlite and php-sqllite3

In ubuntu :  sudo apt-get install sqlite php-sqlite3

**Comment by pvsridhar** [comment]
Ok.. Thank you.. I will try this...

**Comment by pvsridhar** [comment]
It is working.. Thank you..
