### ISSUE TITLE
Version explanations for the repo

### ISSUE THREAD

**Issue by blomdahldaniel** [rappasoft/laravel-5-boilerplate#85]
Hi @rappasoft 

I just tuned in to your repo to make a pull request for the Swedish language pack i have been working on for some time. As I came to the repo I saw something about Log viewer. Or that might have been in some issiue or somethin, and I was like *"What tha heck, whats that!?"* I haven't checked it out yet but I  really want to try it out because it seems awesome.

I then started to dig down in the commit history. *"What else has he been up to that Rappa NewYorker..."* I saw the fluent routes with version [1.3.7-8](https://github.com/rappasoft/laravel-5-boilerplate/commit/541130544dfd2e4a3080e6f9b50baf8f578534d3) for me those two are pretty big, I have been longing for something like that but did not know what or why I felt that I wanted something different. (On the subject of those 2 updates, I really think they make it feel more, as you say, fluent, so nice!).

And since this repo is growing, you are putting in more and more great stuff in it, I really want to be able to have quick look in the readme (maybe at the bottom of the readme or someplace else) to se what has changed. So just a brief explanation or maybe some times a bullet list of the changes. That would really help and also lift up the experience of this project. The commits messages is often just not explanation enough of what the new update holds. 

Just some late night thoughts from Sweden.
This project is great!

**Comment by rappasoft** [comment]
Yeah the one thing I lack besides code blocks is actual documentation. This is my first open source project so pardon my lack of a log or wiki. I will start a changelog at the bottom of the readme beginning with the release of the new access library. I wish there was an easier way to roll out updates where a composer update would pull them in, but since its a whole project I don't know the easiest way. Ideas?

**Comment by blomdahldaniel** [comment]
A changelog would be a great start. And yes, the project is getting bigger, pretty soon a wiki would come in handy... But... The big but.. That could soon take a lot of time.. The danger of too much documentation is that one day you might end up hesitating before coding because you know you have to spend an aweful amount of time in the docs... Dont know if you will feel that way but I understand if you would.

But a change log would be really nice for now, a bit easier to handle. Now that I think of it, I guess the wiki would be most about the access library right? Cause the other stuff should be pretty straight forward. So maybe that would not be that bad?

Oh boy, what if I could run `composer update` to get your latest updates.. Man that would be so sweet. But it would be impossible not to break a lot for that specifik projekt...

Gah.. (I just spent 15 min on writing a suggested method until i finally was done and realized that that was not possible..) Darn.. This is hard.. I must say that a changelog with a explanation and a link to the commit would be great. Then it would be easier to check out the 5-10 files that has been changed and then take it step by step if one would like to upgrade a feature. But then it gets more important that every release is a bit more secure. And since you get a lot of help by people who is using it, testing it, that might not be the way to go here either..

We should get hold of a open source veteran here. I guess that in the beginning like this there aint no easy ways...?

**Comment by rappasoft** [comment]
Yeah I can't think of a way, unless I repo out every feature into the vendor folder and composer, but I don't want to do that. Nor do I want to make a shell script for every update that people have to run, that's the main thing I hate about Magento's security updates.

**Comment by blomdahldaniel** [comment]
Yeah this is tricky. 
One thing that would be nice is that you declare every important bug fix in the changelog, so that one can se what changes maybe have to be done. Like how some of the early fixes of socialite was added.

**Comment by rappasoft** [comment]
Added a change log starting with this last release.

**Comment by blomdahldaniel** [comment]
Great!
