### ISSUE TITLE
Some Packages that should be included in the composer.json

### ISSUE THREAD

**Issue by hasokeric** [rappasoft/laravel-5-boilerplate#86]
Thoughts?

Here are 10 that I use for a typical fresh build of Laravel 5.1.

laravelcollective/html
barryvdh/laravel-debugbar
patricktalmadge/bootstrapper
cviebrock/eloquent-sluggable
laracasts/generators
laracasts/flash
barryvdh/laravel-ide-helper
creativeorange/gravatar
intervention/image

**Comment by rappasoft** [comment]
The laravelcollective/html is technically "illuminate/html" : "5.*" Is there a difference?
I had laravel debugbar but it was causing issues, I can try again.
Laracast generators are already in there.
Laracast flash I made by own version of, you can session flash "flash_danger", "flash_warning", etc and get the appropriate colored alert box with the provided message.
The IDE helper is more of a personal thing.
Gravatar I may add.
The intervention library depends on what you're actually creating a project for.

**Comment by rappasoft** [comment]
I will copy these and go one by one to see which would fit best.

**Comment by blomdahldaniel** [comment]
Personally i pulled in debugger myself since I think that is a great tool.

slugable is a verry nice tool, i have required in that for my projects aswell but as of right now it would not mage sense to pull in packages into this repo that would not be used.
