### ISSUE TITLE
After logging in as Administrator the /macros page throws errors

### ISSUE THREAD

**Issue by hasokeric** [rappasoft/laravel-5-boilerplate#87]
When i login as Administrator and i go to the Home page it all works fine... I can Edit my Name and Change my Password.

Once i click on Macros i get -> http://screencast.com/t/mviOn0hI this is running on Vagrant most recent Homestead.

```
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Maximum function nesting level of '100' reached, aborting!' in /home/vagrant/carrierpulse/vendor/laravel/framework/src/Illuminate/Foundation/AliasLoader.php:63
```

**Comment by rappasoft** [comment]
Weird, do a composer update/dumpautoload -o and see if it fixes it.

**Comment by hasokeric** [comment]
thanks for the response it looks like a issue with xdebug i increased its nesting level to 150 and error is gone.

**Comment by mahanteshpolicepatil** [comment]
Hasokeric can you please tell me the path and name of the file and what change you did to increase nesting level to 150..??
