### ISSUE TITLE
Twitter login

### ISSUE THREAD

**Issue by idevwebs** [rappasoft/laravel-5-boilerplate#88]
Again, great work!

I just tried to login with twitter, and got these two errors:

http://testapp.dev/auth/login/twitter?oauth_token=TWITTERTOKEN&oauth_verifier=TWITTERV

 1/2 PDOException in Connection.php line 381: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null 

 2/2 QueryException in Connection.php line 636: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null (SQL: insert into `users` (`name`, `email`, `password`, `confirmation_code`, `confirmed`, `updated_at`, `created_at`) values (TWITTERNAME, , TWITTERVAL, CONFCODE, 0, 2015-09-20 16:25:42, 2015-09-20 16:25:42)) 

As twitter does not provide user email without requesting to be whitelisted, I would suggest adding a post auth twitter specific view requesting the new user to provide their email address.

**Comment by rappasoft** [comment]
Can you explain a little further? I'm not familiar with Twitter's API. Or make a pull request if you get it to work.
