### ISSUE TITLE
Resend confirmation email is easily abused

### ISSUE THREAD

**Issue by brentkozjak** [rappasoft/laravel-5-boilerplate#881]
Hi all,

This relates to boilerplate 5.4 (I'm not sure if it applies to the new 5.5 work).

I noticed that a user can easily invoke an email to resend a password confirmation email using a simple GET request to `http://laravel.dev/account/confirm/resend/<user id>`

For unconfirmed users, this would be fine... However, it will happily send a confirmation email to ANY user with that id, confirmed or not.  This makes it trivial for someone to spam any of your users with confirmation emails, including admins etc.  Example: If I paste this into my browser, my admin user receives an email:

`http://laravel.dev/account/confirm/resend/1`

I guess a fix for this would be to check if the user is already confirmed before resending a confirmation email.  To make it even more secure, we could look up the user by some sort of hash rather than user ID to make the URL less guessable.

**Comment by rappasoft** [comment]
Update the method for the time being:

`public function sendConfirmationEmail(User $user)
    {
    	if ($user->isConfirmed()) {
			return redirect()->route('frontend.auth.login')->withFlashSuccess(__('exceptions.frontend.auth.confirmation.already_confirmed'));
		}

        $user->notify(new UserNeedsConfirmation($user->confirmation_code));

        return redirect()->route('frontend.auth.login')->withFlashSuccess(__('exceptions.frontend.auth.confirmation.resent'));
    }`

**Comment by rappasoft** [comment]
Fixed on the new branch, feel free to copy to your existing project:

https://github.com/rappasoft/laravel-5-boilerplate/commit/28f0fc026ccd09012ac1b84810290036bec8eda4

**Comment by brentkozjak** [comment]
Thanks Anthony.  Good call using a UUID - I will implement that into my project.
