### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by unixtime** [rappasoft/laravel-5-boilerplate#89]
If a user register for a new account and does not validate email - He/She can still login by requesting new password, under forget password and login successfully after resting the password. Perhaps that is another way of validating email, but the [dashboard]-->[users] shows the user email is not verified. 

I am using PostgreSQL as a backend database. I don't know if that makes a different.

**Comment by rappasoft** [comment]
You were correct. Please add this function to your PasswordController to override the default laravel password reset function, to check for this issue beforehand: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app%2FHttp%2FControllers%2FFrontend%2FAuth%2FPasswordController.php#L53

Thanks for finding it.
