### ISSUE TITLE
Dont get socialite to work

### ISSUE THREAD

**Issue by Krubb** [rappasoft/laravel-5-boilerplate#9]
Hi again!

I created my google-app, got all my credentials that i entered to the suggested .env variables.
my GOOGLE_REDIREC=http://subdomain.mysite.com/auth/login/google

I have pushed my stuff up to the real server that was registered at google.

So i tried to create a new app and keys, i applied them on the .env on the server

 And the FIRST time when i click "Login with Google" i get this error:
`InvalidStateException in AbstractProvider.php line 161:`
And then i go back, refresh and click the same link i get this error:
`ClientException in RequestException.php line 89:
Client error response [url] https://www.googleapis.com/plus/v1/people/me?prettyPrint=false [status code] 403 [reason phrase] Forbidden`

Is there anything else I need to do? Cause i do not get any further after that error.
I pulled the repo  after your latest commit where you stated the Socialite to be fixed.
I have done your new migrations and all that jazz.

Hope we can figure this out as well!

**Comment by rappasoft** [comment]
is GOOGLE_REDIREC suppose to be GOOGLE_REDIRECT?

**Comment by Krubb** [comment]
Yes, sorry, it is spelled correctly in my .env

**Comment by rappasoft** [comment]
Socialite is a pain in the ass.

**Comment by Krubb** [comment]
Feel with you man! I hope you will hang in there! :)

**Comment by Krubb** [comment]
Exciting update of the repo, do you know if Socialite works now?

**Comment by rappasoft** [comment]
It's a pain in the butt, it seems it works for some people and not others, for instance they work for me, but not for you lol.

**Comment by Krubb** [comment]
xD :)
I havnt tried it in this new update yet. Will give it a new shot and let you know.
Funny that you imported the Admin LTE theme. I just finished my own admin-panel where i had Admin LTE as my inspiration for it. :p Dont know if I should stick with my own now or just go with your implementation :p 

What plans do you have for this repo in the future?
The latest update was big and a lot to chew but it seems like some really nice stuff. I like the administrator management! That is really something that i will use in the future.

And also, I dont know if you saw an earlier post that had trouble with the debuging just like me:
https://github.com/rappasoft/laravel-5-boilerplate/issues/11
Is that also fixed out of the box in this update?

**Comment by rappasoft** [comment]
The admin LTE theme is just in there bare bones so it is easy to swap out, it is not hard coded around anything.

I ended up changing the exception handling, there's a new GeneralException class that is caught by everything, all other Exception's through will get caught by whoops.

I use this for my own projects on a monthly basis, so it is in my best interest to keep it updated as well.

Next on my list is user throttling, then when 5.1 comes out I will do whatever is necessary to bring it up to par with that.

But i'm open to anything if you have suggestions.

**Comment by Krubb** [comment]
Yes, i was glad when i saw that the Admin LTE looked like it was pretty bare but that you have the things included like the admin management. Because of the nice admin-manager i think i will use the theme.
What i miss in Admin LTE is the ability to pull out the menu (in xs mobile) by draging/swiping left and right. I ended up using the [snap.js](https://github.com/jakiestfu/Snap.js/). 

What is user throttling? Got any link where I can read more about it? 

5.1 will be sweet, I hope it wont be too much hard work for you to upgrade it.

**Comment by rappasoft** [comment]
It's like "You tried to login X times with no success, you must wait X minutes to try again." Along those lines.

**Comment by Krubb** [comment]
Okay, so that is against brute force attempts? I thought Laravel's standard login took care of that?

**Comment by override-chaos** [comment]
No Laravel doesn''t offer any brute force protection.

https://github.com/GrahamCampbell/Laravel-Throttle

Is a good package to use for user throttling.

**Comment by Krubb** [comment]
Thanks man!

**Comment by Krubb** [comment]
By the way, do you know what php version that is required for ex. socialite? Could it be a php version issue? I saw that the [Laravel-Throttle](https://github.com/GrahamCampbell/Laravel-Throttle) needed PHP5.5 and my webhost only run 5.4..

**Comment by rappasoft** [comment]
I'm not sure, one way to tell would be to pop it in php storm and change the interpreter to a different version, see if you get any issues.

**Comment by override-chaos** [comment]
Socialite's PHP requirement is PHP 5.4, check the composer.json file.

https://github.com/laravel/socialite/blob/2.0/composer.json#L13

**Comment by Krubb** [comment]
Thanks

**Comment by rappasoft** [comment]
Im gonna close the socialite issues for now because no ones getting anywhere with them. I'll try again soon.

**Comment by Metrakit** [comment]
Hi, you are getting this error simply because you havent activated the "Google+ API" in the Google Developper Console. You need to activate the "oauth API" (enabled by default) and the "Google+ API" (disabled by default) ;)

**Comment by rappasoft** [comment]
I pushed a small fix for socialite implementation, it may have fixed google, i'm not sure.

**Comment by suchayj** [comment]
When user cancels the authorization on any platform i.e. LinkedIn, Facebook, google+, Twitter, it redirect back to application but with "ClientException in RequestException.php line 111:". I triend handling it on guzzle library but i think thats not the correct way to do it. Help will be appreciated.
