### ISSUE TITLE
npm install Linux problem

### ISSUE THREAD

**Issue by Sogl** [rappasoft/laravel-5-boilerplate#90]
Hi!

I use homestead Laravel VM (with Ubuntu 14, npm 3.2.0, node 0.12.7).
After `npm install` command I see this error:
```
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v3.2.0
npm ERR! path /home/vagrant/Code/boilerplate.lar/node_modules/esprima-fb/bin/esvalidate.js
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, chmod '/home/vagrant/Code/boilerplate.lar/node_modules/esprima-fb/bin/esvalidate.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v3.2.0
npm ERR! path npm-debug.log.e55cff66ff2ef52a7f5fc66133bdb68e
npm ERR! code ETXTBSY
npm ERR! errno -26

npm ERR! ETXTBSY, rename 'npm-debug.log.e55cff66ff2ef52a7f5fc66133bdb68e'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/boilerplate.lar/npm-debug.log
```

How to fix?

**Comment by Sogl** [comment]
After 2nd run error gone away. But I can say that with npm 1.14 and node 0.10 (default) I saw a lot of mistakes.

**Comment by odyright** [comment]
hello try it with admin right!

**Comment by idevwebs** [comment]
I installed on homestead as well, and it worked. There was one issue with a particular package, but the installation worked and I don't see any issues. Unfortunately, I don't have note of the package that had the issue any longer.

You do have to run node in admin cmd (I use cmder on win7) and same admin requirement for gulp

**Comment by rappasoft** [comment]
The whole thing is developed on homestead. Sometimes the initial npm fails, but the update seems to always fix it.

**Comment by Sogl** [comment]
>hello try it with admin right!
I use `sudo su` before...

>You do have to run node in admin cmd (I use cmder on win7) and same admin requirement for gulp
I do it via PuTTY in Linux machine.

**Comment by rappasoft** [comment]
Still having problems after npm update?

**Comment by Sogl** [comment]
`npm install` works fine after node/npm update.

Some questions about [installation](https://github.com/rappasoft/laravel-5-boilerplate/wiki/Installation):
* Step 5. Why I need to setup `config/database.php` if I already did it in `.env` file? Migrations work that they should.
* Step 7. File `database/seeds/UserTableSeeder.php` doesn't exist. Correct path is `database/seeds/Access/UserTableSeeder.php`

**Comment by rappasoft** [comment]
1. I guess if you prefer credentials in there instead of an env file.
2. The path for seeders was never a problem for me, it seems to look in the seeds/ folder for all of them. I have them broken down into other folders on projects and not specifying the path never gives me an error, weird that you're the first one to get the error.

You think its best to just specify the full paths?

**Comment by Sogl** [comment]
>I guess if you prefer credentials in there instead of an env file.

Step about creating `.env` goes above =)

>the path never gives me an error, weird that you're the first one to get the error.

I had no mistakes, just path clarification.

>You think its best to just specify the full paths?

Yep, I think accuracy doesn't hurt. Especially for new users like me.

**Comment by rappasoft** [comment]
The reason it shouldn't be erroring is that it is using the ::class syntax to call the seeder, and the seeders are not namespaced.

Usually when I add a new seeder the I have to do a composer dumpautoload -o before laravel recognizes it on db:seed.

Either that or you have a version before I was using the ::class syntax in the seeders?

**Comment by Sogl** [comment]
I don't clearly understand what you talking about, but my `php artisan db:seed` works fine:
```
root@homestead:/home/vagrant/Code/boilerplate.lar# php artisan db:seed
Seeded: UserTableSeeder
Seeded: RoleTableSeeder
Seeded: UserRoleSeeder
Seeded: PermissionTableSeeder
Seeded: AccessTableSeeder
root@homestead:/home/vagrant/Code/boilerplate.lar#
```

>Either that or you have a version before I was using the ::class syntax in the seeders?

I copied your repository yesterday and use last 5.1 Laravel version.

**Comment by rappasoft** [comment]
I'm saying before you altered the paths.

**Comment by Sogl** [comment]
Also `gulp` command not working (gulp installed globally):
```
root@homestead:/home/vagrant/Code/boilerplate.lar# gulp
module.js:338
    throw err;
          ^
Error: Cannot find module '../traversal'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/vagrant/Code/boilerplate.lar/node_modules/laravel-elixir/node_modules/babelify/node_modules/babel-core/lib/transformation/plugin-pass.js:19:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
root@homestead:/home/vagrant/Code/boilerplate.lar#
```

**Comment by Sogl** [comment]
Mistake in frontend:
![screenshot_26](https://cloud.githubusercontent.com/assets/7556290/10009351/b636bf10-611e-11e5-83af-33fcc7f19477.jpg)

Otherwise it looks like everything is working now.

**Comment by rappasoft** [comment]
The space? Not a mistake lol. It's pulling the name from the user, the default admin first name is Admin and last name is Istrator. I guess it's a little confusing. Didn't know what else to put.

**Comment by Sogl** [comment]
I have understood and changed the message =))

**Comment by Sogl** [comment]
>Didn't know what else to put.

* Foo Bar
* Username
* Admin Name
* Firstname Lastname
etc

Tried to install `traversal` module globally, but error not changed:
```
root@homestead:/home/vagrant/Code/boilerplate.lar# npm install -g traversal
traversal@1.2.1 /usr/local/lib/node_modules/traversal
├── debug@2.2.0 (ms@0.7.1)
└── 101@0.14.1 (clone@0.1.19, keypather@1.10.1, deep-eql@0.1.3)
root@homestead:/home/vagrant/Code/boilerplate.lar# gulp
module.js:338
    throw err;
          ^
Error: Cannot find module '../traversal'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/vagrant/Code/boilerplate.lar/node_modules/laravel-elixir/node_modules/babelify/node_modules/babel-core/lib/transformation/plugin-pass.js:19:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
root@homestead:/home/vagrant/Code/boilerplate.lar#
```

**Comment by rappasoft** [comment]
Seems more like a general error. This may help: http://stackoverflow.com/questions/9023672/nodejs-how-to-resolve-cannot-find-module-error
