### ISSUE TITLE
Custom form error user already exists

### ISSUE THREAD

**Issue by SkanderH** [rappasoft/laravel-5-boilerplate#91]
First, thank you for this project! It helps me allot understanding Laravel and Auth in general. I have never used Laravel or a Framework before and this is great for learning.

My problem:

I want to use/change the column "Name" as a Username so it has to be unique. So I added a first name and last name column. The problem is when you want to change your info on edit.blade.php you can't because it will say the "Name" already exits because you are that "Name".

Is there away to bypass this? Say if logged in user is current "Name" you can still save?

Or do I have to make a different edit.blade just for the "Name"?

Files I edit: 
(I made some custom columns in my database and changed this 3 files)

EloquentUserRepository.php

	/**
	 * @param $input
	 * @return mixed
	 * @throws GeneralException
	 */
	public function updateProfile($input) {
		$user = access()->user();
		$user->name = $input['name'];
		$user->first_name = $input['first_name'];
		$user->last_name = $input['last_name'];
        $user->gender = $input['gender'];

		if ($user->canChangeEmail()) {
			//Address is not current address
			if ($user->email != $input['email'])
			{
				//Emails have to be unique
				if (User::where('email', $input['email'])->first())
					throw new GeneralException("That e-mail address is already taken.");

				$user->email = $input['email'];
			}
		}

		return $user->save();
	}

UpdateProfileRequest.php

	/**
	 * Get the validation rules that apply to the request.
	 *
	 * @return array
	 */
	public function rules()
	{
		return [
			'name'	=> 'required|max:15|unique:users',
			'first_name'	=> 'required|max:35',
			'last_name'	=> 'required|max:35',
			'gender'	=> 'required|max:1',
			'email'	=> 'sometimes|required|email',
		];
	}
}

edit.blade.php

				<div class="panel-body">

                       {!! Form::model($user, ['route' => 'frontend.profile.update', 'class' => 'form-horizontal', 'method' => 'PATCH']) !!}

                              <div class="form-group">
                                    {!! Form::label('name', trans('validation.attributes.name'), ['class' => 'col-md-4 control-label']) !!}
                                    <div class="col-md-6">
                                        {!! Form::input('text', 'name', null, ['class' => 'form-control']) !!}
                                    </div>
                              </div>

                              <div class="form-group">
                                    {!! Form::label('first_name', trans('validation.attributes.first_name'), ['class' => 'col-md-4 control-label']) !!}
                                    <div class="col-md-6">
                                        {!! Form::input('text', 'first_name', null, ['class' => 'form-control']) !!}
                                    </div>
                              </div>  

                              <div class="form-group">
                                    {!! Form::label('last_name', trans('validation.attributes.last_name'), ['class' => 'col-md-4 control-label']) !!}
                                    <div class="col-md-6">
                                        {!! Form::input('text', 'last_name', null, ['class' => 'form-control']) !!}
                                    </div>
                              </div>

Is this the right way of doing it?

**Comment by rappasoft** [comment]
This is a problem with using laravels unique validation. I don't know if there's a workaround as of yet, what I usually do is see if what you're updating is what's currently there, if not then check:

```
if ($new_name != $current_name)
    if (//New name already exists in database)
        throw new Exception("That name already exists");
```

**Comment by SkanderH** [comment]
Thanks! Got it working now!

2 more things.

1.  I made a folder "User" and file home.blade.php that's everyone's profile page but how do I get the link of a profile like user/1 and every user you visit you see there info and photos.

2. I saw some Avatar code in your Project is it working? If so do you have to activate it?

**Comment by rappasoft** [comment]
Depends if its on the frontend or backend, you will need to make a 'view profile' route, controller action, and view.

See https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Http/Routes/Backend/Access.php#L23 for a route example.

Then it would point to a function like ```UserController@viewProfile```

```
public function viewProfile($user_id) {
    return view('frontend.user.profile')->withUser($this->users->find($user_id));
}
```

Now the user object is available in your profile view, do what you want with it.

Just be careful you don't give other users access to alter anyone but themselves.
