### ISSUE TITLE
5.5 -- vision and future

### ISSUE THREAD

**Issue by illuminate3** [rappasoft/laravel-5-boilerplate#913]
A quick note to say thank you and that this is looking really good!

I also was wondering what the vision and future is of this project.

**Comment by Shuyinsama** [comment]
That really depends on Laravel.

5.4 to 5.5 has proven to be very time consuming and basically meant a complete rewrite.
Much of the discussion can be found here: https://github.com/rappasoft/laravel-5-boilerplate/issues/788

On that note: The 5.5 version is almost done. We are still putting the final touches on testing and then we'd have to do documentation. So yes a 5.5 version is coming soon.

For the future I am not really sure, since it takes so much spare time from the creator it kind of depends on future contributors so in my own opinion I would love for this project to stay supported and will always try to help when needed.

The vision this project has is that it will deliver a boilerplate where a lot of packages are interchangeable and supported. In the new 5.5 branch we opted for a lot of packages by Spatie since they are always maintained and up to date. We also decided to remove some things in favour of this interchangeability.

If you really need to start a Laravel 5.5 project I'd recommend cloning the 5.5 branch but be warned:
We have not added testing fully yet, we still need to do some rebasing and we do not have documentation yet.

For help you can joining the Slack channel (mentioned in the README)

**Comment by illuminate3** [comment]
Thanks for the long answer.

My question about the "future" was poorly worded. I meant in a "vision" sense and not a "viablility" or will it disappear meaning. Sorry about that.

You also answered the question I had about the timing release that I didn't want to ask since I know many people are wondering. So thank you for filling us in on the progress about that part.

Have you considered what functions might also get included in the future or is this going to be like a feature creep prevention project? I am asking because, I have been toying with the idea of moving things into modules and possibly turning the back end into a vue based one.

**Comment by bloggervista** [comment]
@illuminate3 
Regarding Vue I guess this is general laravel boilerplate so we should not force anyone to use Vue. And many people don't know even vue so I would not recommend it. There is already well maintained boilerplate for vue based backed and we are planning to make react one very soon. So I guess current development is really fine.

**Comment by rappasoft** [comment]
I will do my best to keep this updated as laravel changes, but it seems every release is so different it requires a ground up rebuild, which we're going on 3 months for this one. We even removed features to in place of packages to make it go faster, but it hasn't helped much. 

I rely on the tens of thousands of people that use it to help me keep it updated.

I have no plans for Vue, but it is a skeleton so if you decided to add it you wouldn't have to do anything but build since all the dependencies are there already.

**Comment by illuminate3** [comment]
@bloggervista 
Thanks for your reply. I understand what you are saying about vue. However, react is getting a lot of publicity and many are now abandoning it because of that. Probably the best is just to keep it simple blade and let users do what they want then.

@rappasoft 
Thanks for a great base. I and I am sure many others appreciate your efforts too.

Ah, yeah, the wonderful joy of working with laravel. Every few release end up being so good and so different that a ground up release is necessary. I stayed with 5.1 until just a few days ago when I started tinkering with your 5.5 dev version.

I was looking into moving your code into a module based one. (https://github.com/caffeinated/modules) The reason is so that you could easily drop in functionality if need -- one example would be using react or vue for the admin. But for this project maybe it isn't the best choice unless you were considering to moving towards cogs, backpack or one of the other plug and play solutions out there. To be clear, I am just throwing out ideas and not asking for features.

**Comment by rappasoft** [comment]
Have no plans on doing that yet, seems like it would be a lot of work and then the whole application relies on one package to work in the future.

It will always be a work in progress and never perfect. At this point i've put literally thousands of hours in, with hundreds more put in by the community.

I'm hoping one day i'll have more time to work on it, but it became so much bigger than I even thought it would.

As long as the community is there to help i'll do my best to maintain it.

**Comment by minedun6** [comment]
You can easily setup up some donations or patreon page to support your work and to pay off some of the time you spend on this project.
I use this package too often and I'd be happy to spare some "USD" to help.

**Comment by rappasoft** [comment]
@minedun6 I'm sure I could, but it also feels bad asking for money for an open source project. If enough people were willing I would be able to cancel some side projects and do boilerplate instead.

**Comment by minedun6** [comment]
Ok I'm not gonna compare this project to vue/laravel, but they're basically open source projects and they have some huge donors so the big question is WHY NOT ?
Would you like to work for free ?

**Comment by bloggervista** [comment]
No, I believe they don't have huge donors. And Basically they don't work
for donations . Its just a small support. But developer have to live pay
rents etc.. so they need to work somewhere right they cannot always depend
on opensource. And basically he is maintaining this boilerplate right. I
guess what is doing for us is currently fine.  And Rappasoft has already
said if he got donations regarding support of this package we will leave
his side projects thats really cool.

**Comment by minedun6** [comment]
You know that Taylor is doing Laravel full-time right ?

**Comment by bloggervista** [comment]
Ahh taylor has enough donations and advertisement which this boilerplate
dont have. And i guess its antony to decide what is better for him. And
lets not discuss about it i understand ur concern. Anthony has said if
enough donation he can work full time and i guess such project usually
require low maintanance only due laravel fast release but that will slow
like rails

**Comment by illuminate3** [comment]
Taylor has been releasing different projects which he receives payments for and I wouldn't doubt that possibly Laracon and such give him a "donation" to attend. Jeffery makes money off his laracast and probably projects which is why his videos seem to focus on certain types of things.

I would love to see Anthony do well enough to turn this into a solid part time job. This is why I actually started this thread. I wanted to feel out what is going on before just typing ideas. The current approach is not a business model that would not be enough to be able to depend on for a steady income.

**Comment by mikimaine** [comment]
I am willing to donate.

**Comment by minedun6** [comment]
What I'm saying is that we're willing to help you if you wanna consider more time on this project.
To be honest, this project helped me so much that sometimes I'm like "How can I live without this project ?". It saved us a lot of time and I think that most of people who are contributing to this project have the same kind of thoughts about this project.

**Comment by brentkozjak** [comment]
I use this as the foundation for all my projects, so I would also be willing to donate, for what it's worth.

**Comment by Shuyinsama** [comment]
Donations are always possible. The link is [here](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=JJWUZ4E9S9SFG&lc=US&item_name=Laravel%205%20Boilerplate&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted) and found in the README.

Of course donations are very much appreciated but don't guarantee more and longer work. It definitely makes it more bearable. Nonetheless with donations or not the project will be updated as long as we are able too. Now for me I only stepped in recently but both @rappasoft and me also have full time jobs that can be very erratic. We both average at work days (including this project) of 16 - 18 hours.

So if you can and are willing to, please consider a donation to @rappasoft he is the one that puts the most time into this project and has allowed a lot of our projects to have a very solid base.

**Comment by minedun6** [comment]
I usually don't like paypal to be frank because I got hacked once after using it and I would really like using patreon maybe. Is that something doable ?

**Comment by rappasoft** [comment]
Launching today thanks everyone for the massive amount of help!
