### ISSUE TITLE
Page constantly reloads / refreshes when making (bad) ajax call.

### ISSUE THREAD

**Issue by strixy** [rappasoft/laravel-5-boilerplate#915]
I searched for this, but couldn't find anything. I did a fresh install of the package and I can reproduce the issue (feature?). I mostly want to write this issue report so anyone who might be searching for an answer can find it in the future.

Page constantly reloads when making ajax call. (Specifically when making a bad ajax call).

The location.reload() in .ajaxError makes the page reload constantly for ajax error. This not only makes debugging tricky, but it's a rather unusual result for a bad ajax request. Can we talk about removing it and changing it to an error handler or something instead? I would be happy to PR depending on feedback.

JSBin example
http://jsbin.com/gebasajehe/edit?html,js,output

resources/assets/js/plugins.js (Lines 35-38)
```JS
.ajaxError(function (event, jqxhr, settings, thrownError) {
    $loading.hide();
    location.reload() //THIS LINE HERE
})
```
Maybe something like this instead?

resources/assets/js/plugins.js (Lines 35-38)
```JS
.ajaxError(function (event, jqxhr, settings, thrownError) {
	$loading.hide();
	if($('.phpdebugbar').is(':visible')){
		console.error(thrownError);
	} else {
		location.reload();
	}
})```

**Comment by rappasoft** [comment]
The next version doesn't even have this because datatables were removed. So its your call if you want to change it to something else for now.

**Comment by strixy** [comment]
I'll wait for the next version. 
Cheers!
