### ISSUE TITLE
getItemByColumn() arguments are reversed

### ISSUE THREAD

**Issue by drjekyll** [rappasoft/laravel-5-boilerplate#920]
Greetings,

I am working with the feature/5.5 branch (because I'm really anxious to use bootstrap 4).

If you enable changing of the email address in the user's profile, there is a bug in the Frontend/Auth/UserRepository update() method where it checks the email address for uniqueness.  The arguments in the getItemByColumn() function are reversed.  It currently reads

                if ($this->getItemByColumn($input['email'], 'email')) {
                    throw new GeneralException(__('exceptions.frontend.auth.email_taken'));
                }

This results in a SQL error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'foo@bar.com' in 'where clause' (SQL: select * from `users` where `foo@bar`.`com` = email and `users`.`deleted_at` is null limit 1

If I swap the arguments to:

                if ($this->getItemByColumn('email',$input['email'])) {
                    throw new GeneralException(__('exceptions.frontend.auth.email_taken'));
                }

Then it behaves correctly and returns the message to the UI etc.

I am not wise in the ways of Git and pull requests etc. I do note that there is a current pull request from Vu Quang Tam that fixes this same problem by reversing the arguments in the BaseRepository definition of the getItemByColumn() function itself - which would cause the UserRepository code to work as written.  I guess you will have to decide which is semantically the  correct fix!

**Comment by bloggervista** [comment]
there is pr already for it . hopefully it will be merged or fixed.

**Comment by rappasoft** [comment]
Fixed
