### ISSUE TITLE
Permission Dependencies

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-5-boilerplate#93]
Starting a new feature already: Permission Dependencies

https://github.com/rappasoft/laravel-5-boilerplate/tree/feature/permission_dependencies

Where access to a permission can be dependent on the user needing one or multiple other permissions.

For example, user may have create-user, but if they don't have view-backend and view-access-management, they can never get to the create user page so create-user is dependent on view-backend, and view-access-management.

There will just be a pivot table for both id's and when you create a role or add permissions to anything, checking one will check the dependencies and make them disabled so they have to be submitted.

**Comment by blomdahldaniel** [comment]
And what would be an example of usage for this? Why not just remove the create-user permission from the user? I guess it would be nice when it gets large and user get automatic roles/permissions and ones rights have to be removed but not remove a role? 

I cant see clearly where this would be helpful, do you have a example or has it just been something you have needed in a personal project?

**Comment by rappasoft** [comment]
No i've always had problems with this. When you break permissions down into such small pieces it gets hard. For example you can make one permission called manage users, which gives crud abilities to that user, or you can break it down into 4 different permissions.

In the cast of this project, you can't get into the backend or the access management section without 2 other permissions. So giving the user create-user permission is useless, because the system will never allow them through the proper doors to get to that point.

This section will just auto populate the checkboxes on the permissions needed for another permission.

So when creating a role, or adding single permissions to a user, clicking create-user will also check view-backend and view-permission-management, and make them readonly.

**Comment by blomdahldaniel** [comment]
Aah, I se! Well then it will be verry nice when its added! :)

**Comment by rappasoft** [comment]
![screencapture-l5boilerplate-dev-admin-access-roles-permissions-24-edit-1442972286778](https://cloud.githubusercontent.com/assets/6026504/10036236/97040aea-6172-11e5-9cf8-e899736ddb03.png)
![2](https://cloud.githubusercontent.com/assets/6026504/10036237/9704a4aa-6172-11e5-802d-7dcc91d5816c.png)
![1](https://cloud.githubusercontent.com/assets/6026504/10036238/970e5a04-6172-11e5-8374-8ee620a807d9.png)

**Comment by rappasoft** [comment]
Finished & merged

**Comment by blomdahldaniel** [comment]
Cool! :smile:
