### ISSUE TITLE
Cannot modify users

### ISSUE THREAD

**Issue by SchneiderDe** [rappasoft/laravel-5-boilerplate#937]
Installed the boilerplate on fresh laravel 5.4. 

My system is windows 7, php 7.1.

I can create users but none appear under the management.

Can this be because of the php/OS? If yes, what can be changed to make it work.

Further, immediately after the installation under composer, I get error that there are no commands defined in the package namespace.

Could it be that the installation did not go well, or this would be under the OS?

Under the Dashboard the link to System is not clickable. Is this normal?

**Comment by bloggervista** [comment]
no this is not due to os etc.

And did you clone it or used composer create project while installing?

**Comment by Shuyinsama** [comment]
Can you please add screenshots and or error logs from the `storage/logs` folder so we can have a better look.

Windows 7 and PHP should not really matter but how you spin up a local environment is.
Do you use Vagrant or Homestead?
