### ISSUE TITLE
Backend depending on the roles

### ISSUE THREAD

**Issue by Sogl** [rappasoft/laravel-5-boilerplate#94]
I want to unite frontend and backend based on AdminLTE with AdminLTE login form on www root (in my example - `http://boilerplate.lar`) with this set of ACL functions:
* Tables per role of specified users. For example, Users role and Foo Bar user can edit table, others can't.
* Table columns per role. One role see 5 columns, other only 3.
* Menu per role. Admins can see and use `User Management` section, but users can't.
* Set of buttons per role. One role can edit data, but other only can see it. Admin can do all + delete rows.

Can I do this with your boilerplate? What is the best way to implement this?

**Comment by rappasoft** [comment]
With the remake of the access library merged in yesterday yes you can. But you may have to start fresh with that version. 

Anthony Rappa

**Comment by Sogl** [comment]
How to extend it with my models?

**Comment by rappasoft** [comment]
You can extend any of them. My models extend Model, you can just extend my models.
