### ISSUE TITLE
Unable to Connect to MSSQL from boilerplate

### ISSUE THREAD

**Issue by Docbrown1972** [rappasoft/laravel-5-boilerplate#947]
Hello
I have been attempting to do the simple task of connecting the boilerplate to an MSSQL database but using the same settings I have always used in Laravel 5.4 onwards I cannot get a connection.

SQLSTATE[HY000]: General error: 2812 Could not find stored procedure 'EXPLAIN'. [2812] (severity 16) [(null)]

I am not doing anything crazy. Just a simple second connection to mssql (my primary is a mysql connection that works perfectly)
Is there a new method to connecting to a MSSQL database that differs from the usual way.
I love the boilerplate but I must be able to connect to mssql.
On the same physical server I am using a laravel installation with an MSSQL connection which works perfectly so I know the server / php is all working.
This is part of my database config. (parts removed for security. DOH!)
```
        'mssql' => [
            'driver' => 'sqlsrv',
            'host' => '77.xx.xx.xx',
            'port' => '104',
            'database' => 'LB',
            'username' => 'xxxxxxx',
            'password' => 'xxxxxxx',
            'charset' => 'utf8',
            'prefix' => '',
        ],
```

And a simple route to test the connection.
use App\homesinfo;  (declared correctly)

route::get('/mssql',function() {
   $rs = homesinfo::first();
   dd($rs);
});

But nothing but the error.
Please advise me if I need to use some other connector or if I am declaring something wrong because it all works in a standard laravel install which leads me to believe something in the Boilerplate is blocking it.
Thanks
Neil

**Comment by rappasoft** [comment]
Either turn off laravel debugbar or set this to false: https://github.com/rappasoft/laravel-5-boilerplate/blob/master/config/debugbar.php#L139

**Comment by Docbrown1972** [comment]
Thanks for the incredibly fast response..... and wow. Yes. That does it. All day I have been looking for a reason why. Never thought eh very thing supposed to help was the fault.
When can we see a 5.5 version of boilerplate. I tried to upgrade with no success.
Neil

**Comment by rappasoft** [comment]
feature/5.5 is done feature wise. Just finishing the tests.

**Comment by Docbrown1972** [comment]
So I am basically in the shadow of the Gods here. Thanks for your help.
Neil
