### ISSUE TITLE
Backend visual logic suggestion

### ISSUE THREAD

**Issue by Sogl** [rappasoft/laravel-5-boilerplate#95]
Hi!

The current UX/UI design is very inconvenient and illogical.

I think the better way (on Users example) is:

1. Move `Users` to dropdown menu:
![screenshot_27](https://cloud.githubusercontent.com/assets/7556290/10010920/ac92d478-6135-11e5-8b7e-8cee7eebf707.jpg)
2. In users all categories (deactivated, banned, deleted) must be implement by dropdown filter. Something like this:
![screenshot_29](https://cloud.githubusercontent.com/assets/7556290/10011061/37f59e18-6138-11e5-9441-e4228697c415.jpg)
3. Add `Add User` button on top of the table (screen from [jTable](http://jtable.org/) project):
![screenshot_28](https://cloud.githubusercontent.com/assets/7556290/10010956/59302fc8-6136-11e5-811d-8258fca3ad61.jpg)
4. Edit by [clicking on 1st row column](http://demo.crudkit.com/sql_basic.php?page=sqlite2&action=view_page) or moving edit button to the first column.
5. Multiply deleting by [selecting rows](http://jtable.org/Demo/SelectingRows).

Same with roles, permissions and groups.

What do you think?

**Comment by blomdahldaniel** [comment]
I have a bit hard time understanding what you want to achieve. I will post my examples to see if I understand what you aim for.


To clear things up
## 1. sidebar
you would like the sidebar menu to look like this:
If you click on *Users* redirects to `/access/users`

<img width="150" alt="skarmavbild 2015-09-22 kl 11 52 09" src="https://cloud.githubusercontent.com/assets/10044093/10015433/6de69fa8-6120-11e5-9f2c-df99ab1df7b2.png">


## 2. dropdown filter
*Show all users* is preset, possible to change filter.
The current filter is presented in the button. And/or has active state
<img width="1438" alt="skarmavbild 2015-09-22 kl 12 28 46" src="https://cloud.githubusercontent.com/assets/10044093/10016234/b1e5e358-6125-11e5-9164-fc8c736850a7.png">

## 3. Create new user/permission/role
A direct button to *Create new X* (see the other screenshots for zoomed out view)
<img width="588" alt="skarmavbild 2015-09-22 kl 12 24 13" src="https://cloud.githubusercontent.com/assets/10044093/10016252/d52eb740-6125-11e5-8174-b0188a105014.png">

## 4. Edit button
I definitely think that all action buttons should be grouped together. Having them at the end of the table right now is okay, moving them to the 2nd column (1st is checkbox) would be a nice touch maybe.
This I think is more of taste. *BUT* if it would be a checkbox in 1st column, moving the buttons would be a must.
<img width="1196" alt="skarmavbild 2015-09-22 kl 12 34 50" src="https://cloud.githubusercontent.com/assets/10044093/10016327/6e0635a6-6126-11e5-98f7-6dcd8996d9ab.png">

## 5. Multiple selection and actions
1. Select multiple rows by checkbox
2. Choose action with all selected

This would be a pretty nice improvement i would say.
<img width="1434" alt="skarmavbild 2015-09-22 kl 12 20 29" src="https://cloud.githubusercontent.com/assets/10044093/10016360/b1a16c40-6126-11e5-8e8a-867640374aee.png">


### All together
I do think that you have some nice pointers @Sogl Have I understood what you where meaning?

**Comment by Sogl** [comment]
@blomdahldaniel, So nice and clear! You did a very good job, man!

By points:
1. Right.
2. Right. You can remove the phrase "Show ... Users", because you already in Users controller. Also switching the list should only update the data in the table.
3. Right.
4. Not a good idea. Edit button is always in CRUD tables, but other set looks unclear. You see "Pause button" and thinking about what it was doing? Also with "Close" and "Refresh". If you see this table for the first time, you can guess that these buttons mean? I don't think so. 
Therefore, all the buttons except the editing is better to move up, near "Create User".
5. You don't need your "Actions with selected" dropdown button, if you do my 4 step.

Also a pleasant solution to edit and insert rows in a popup window:
![image](https://cloud.githubusercontent.com/assets/7556290/10017065/d9d90e6e-616e-11e5-8c99-f377b3d05320.png)
The only downside is big dropdown menus in this popup.

I wrote this issue after an unsuccessful struggle with the interface and visual logic =)))

p.s. Sorry for my bad English.

**Comment by blomdahldaniel** [comment]
:+1: 

**4.** You are right man that would be a great solution for the "Action with selected" as you say. The icons is sure quite unclear. Just text buttons with the same colors would be nice. 

Add and insert rows is very pleasant with modals that pop up, definitely! It is pleasant but not as important such as the other ones. 

I am not sure what @rappasoft think of this but i could start fiddeling with some of the features.
A big question will be how much that should be done by ajax and javascript. If its good enough to reload the entire page when filter on "Deleted users". As of now in my opinion it might be good enough to solve it with php but if this gets bigger then a refactor in javascript maybe need to be done.

Heres a suggestion to **4.**
I found some icons that might help understaning the button quicker..?
I think its important to show the text.
I also made the **+ Create user** button just a bit bigger to yield out louder.
<img width="1101" alt="skarmavbild 2015-09-22 kl 14 46 18" src="https://cloud.githubusercontent.com/assets/10044093/10018652/bddb0086-6138-11e5-92a8-3210e565c7e4.png">

**Comment by Sogl** [comment]
Let's do some styling :smiley: 

I just recorded gif with the style of the table, which I like:
![3](https://cloud.githubusercontent.com/assets/7556290/10019428/9473a584-6180-11e5-8f1e-1076f8824d34.gif)

Changes:
* `With selected` buttons group shows ONLY when you select rows. You don't need to see them 90% of time.
* You don't need so much colours. They have nothing to say. Only green on `create user` button and design becomes more lighter.
* Also you don't need to large `Create User` button, because previous change =)))
* Delete `Change password` button. Use this function in editing user. Also I think key looks clearer than the lock. 
* Move deactivate, ban etc to create (left side) and filters stay on the right side.

**Comment by rappasoft** [comment]
The problem is the users actions are different depending on the situation. If they're not confirmed theres a re-send confirmation email button, if they're deactivated theres an activate button, if they're banned theres a banned button, and if they're deleted theres an undo delete or delete permanently. SO it would be hard to make a dropdown of options after selecting multiple because some may not apply.

Other than that I like the ideas, its just going to take a lot of work to implement.

**Comment by rappasoft** [comment]
There will be plenty of ways to make the UI better. I'm a developer now a designer after all, and I was focusing on features and functionality. As soon as I finish this permissions module we can work on UI. The only thing is I don't want the UI to depend on the AdminLTE theme. I used it as an example but I want it to be easy swappable.

**Comment by blomdahldaniel** [comment]
hm.. I see, then i understand it will be different to manage multiple at the same time. Need to think more into that because the feature in itself, to change multiple att once, is something that would be very good.

Something that could be done right away would be the sidebar thing i think?
Break down to 
* Access Management (dropdown)
  * Users
  * Permissions
  * Roles

The active state of the menue (just like Log Viewer) cannot be applied easily right now because the url to permissions is /rules/permission. What is the reason to that or is it just something that made sense with the first versions of the ACL?

**Comment by rappasoft** [comment]
Just the way of relationships. Roles belong to user, permissions belong to roles. I didn't use a nested relationship so I could also apply single permissions to users.

**Comment by blomdahldaniel** [comment]
okey, but i gess now it would make sense to have this aswell? 
No need to stick relationships in the urls? Or is it structured that way?
````
URL
/admin/access/users
/admin/access/permissions
/admin/access/roles
````

**Comment by rappasoft** [comment]
Yes real nested laravel relationships are, example: if I would have structures the routes like:

```resources('user.roles', 'RolesController')```

the route would be user/1/role/2/edit, etc

But I wanted to separate them to have more flexibility, so I tried to keep the url structure. It would be a pain in the ass to change.

**Comment by blomdahldaniel** [comment]
Okey thats fine man! I have never embraced the url structure, i use Controller pointers instead to keep the urls free. Then we will figure out to have the sidebar-items active in another way.

**Comment by Sogl** [comment]
>The only thing is I don't want the UI to depend on the AdminLTE theme. I used it as an example but I want it to be easy swappable.

Can you give an example what is better than current AdminLTE? I was looking for a lot of templates/UI kits and AdminLTE looks the best of them (especially for its free costs).

Otherwise, can we realize at least some of the ideas?

**Comment by rappasoft** [comment]
A couple bucks gets you insanity: https://wrapbootstrap.com/themes/admin

**Comment by Sogl** [comment]
Not such a big difference with AdminLTE

**Comment by rappasoft** [comment]
I beg to differ. You get hundreds of pre-built responsive elements instead of a dozen or two:

http://wrapbootstrap.com/preview/WB0R5L90S

**Comment by Sogl** [comment]
All data tables (we talking about them I think) that INPINA uses are licensed as Open Source... so not a problem to put it into AdminLTE. Also I don't think that we can use paid template in this boilerplate. Correct me if I'm wrong.

**Comment by rappasoft** [comment]
Oh I didn't know you were talking about for use in THIS boilerplate. Then no, not unless I buy the extended license, which i'm not.

AdminLTE is fine for a boilerplate, I'm people may choose not to use it, therefor I tried to structure the views so it would be easy to swap with another admin theme.

**Comment by rappasoft** [comment]
Ok, I think i'm done with creating features for a while. Nows the time to create pull requests for UI improvements, or let me know what you think is best and I can implement if majority rules. This goes for code improvements and clean up as well. Should probably start a fresh thread.
