### ISSUE TITLE
Where is the To email address stored

### ISSUE THREAD

**Issue by Docbrown1972** [rappasoft/laravel-5-boilerplate#954]
Hello.
Probably just very simple to you but not to a newbie on Laravel.
Where do I set the email address I want to send to from the contact form?
I can see settings for the from email address but when someone fills in the contact form and clicks send I want to send it to an email address I specify.
Where is it?
Sorry if this is a simple question but I am still trying to find my way around both laravel and the boilerplate.
Thanks
Neil

**Comment by noxify** [comment]
Hi,

the recipient for the contact form can be defined via the default mail settings in laravel.

The "to" will be defined in:
https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Mail/Frontend/Contact/SendContact.php#L39


As you can see in the `SendContact`, it uses the config for `mail`.
https://github.com/rappasoft/laravel-5-boilerplate/blob/master/config/mail.php#L58-L61

By default, laravel allows us, to define the "from" part inside the `.env` file.
You only have to add the `MAIL_FROM_ADDRESS` in this file.

Btw. I'm not sure, if it's a good idea to use the `from` to receive a email.
In my app, I define the from as `noreply@domain.tld`.

Maybe it's better to define your own config key like:

```
    'contact' => [
        'address' => env('MAIL_CONTACT_ADDRESS', 'hello@example.com'),
    ],
```

in the `config/mail.php`.

Don't forget to replace the the following line inside ( https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Mail/Frontend/Contact/SendContact.php#L39 )

```
        return $this->to(config('mail.from.address'), config('mail.from.name'))
```

**Comment by Docbrown1972** [comment]
Hello. Many thanks.
I shall try that.
Consider it closed.
Neil
