### ISSUE TITLE
5.5 Login As

### ISSUE THREAD

**Issue by bryanrscott** [rappasoft/laravel-5-boilerplate#960]
I can see some code to support the "Login as feature" but I can locate the how to actually do it.   In 5.4 it was under the users listing in admin.   Is it no longer supported or have I just missed where it has moved to.

**Comment by SeoRoman** [comment]
It's there, under User Management, click the "more" button... You cannot do this on the same account that you are logged in on.

**Comment by bryanrscott** [comment]
thanks.   My fault.
