### ISSUE TITLE
Documentation: Update

### ISSUE THREAD

**Issue by SeoRoman** [rappasoft/laravel-5-boilerplate#961]
Documentation 5.5 - Magic Methods

Not technically an "error" but in the documentation you list examples using withFlashSuccess and display the "example" on how it's written out with 'flash_danger' ...

Also, the bullets list: * withUsers not * withUser

**Comment by rappasoft** [comment]
Thanks, the documentation has it's own repo which you are free to make PR's to as well ;)

**Comment by rappasoft** [comment]
Fixed
