### ISSUE TITLE
Question: CoreUI version outdated?

### ISSUE THREAD

**Issue by bellwood** [rappasoft/laravel-5-boilerplate#975]
General question, what version of CoreUI have you integrated into your 5.5 release?

I only ask as I see references to v1.0.0-alpha.6 in the CoreUI resource files which appears to be the projects' initial release from October with several releases since:

https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/releases

**Comment by bambamboole** [comment]
@bellwood , yeah you are right.
The latest version of core ui is 1.0.6 and the one that is included here is v1.0.0-alpha.6

I'll have a look for the upgrade.
