### ISSUE TITLE
'CRUD' index pages not paginating in Boilerplate 5.5

### ISSUE THREAD

**Issue by richardsonsamuel** [rappasoft/laravel-5-boilerplate#981]
Just wondering why the “CRUD” pages for users and roles in the backend dont seem to be paginating? Am I editing the wrong thing? I’ve noticed in App/Repositories/Backend/Auth/UserRespository.php has 25 as the default pagination so when I changed that to 3 and tried adding about 5 users it still isnt paginating? Does anyone know why?

I have tried using both clean install and my own app. and still don't see any pagination.... Is the number i'm using to test with (3) too small?

# What version?
5.5

**Comment by flixart33** [comment]
Change "render" by "links" in index :



     <div class="row">
            <div class="col-7">
                <div class="float-left">
                    {!! $users->total() !!} {{ trans_choice('labels.backend.access.users.table.total', $users->total()) }}
                </div>
            </div>

            <div class="col-5">
                <div class="float-right">
                    {!! $users->links() !!}
                </div>
            </div>

**Comment by richardsonsamuel** [comment]
Didn’t seem to make any difference. What was the reason why you suggest this? Is this what it’s supposed to be ? If so then probably should submit a pull request with the correction....

**Comment by flixart33** [comment]
https://laravel.com/docs/5.5/pagination#paginating-eloquent-results
have you changed in controler the value of paginate to control ?

For me it's good with this, as said it depends on bootstrap css for styling

**Comment by bambamboole** [comment]
@richardsonsamuel is this issue still relevant or did you solve it?

**Comment by richardsonsamuel** [comment]
Still relevant. Just haven’t had another chance to look into it yet. Leave
it open for now and if I solve it I’ll put the solution on here. Do you
have any idea what could be causing the issue? i couldn’t  get it to
paginate even from a fresh install either

**Comment by bambamboole** [comment]
I will give it a shot now. When I can reproduce the issue I will also try to solve it.

**Comment by bambamboole** [comment]
@richardsonsamuel sorry for the delay, but I think I found your "problem":

the method which builds the template is:
```
public function index(ManageUserRequest $request)
    {
        return view('backend.auth.user.index')
            ->withUsers($this->userRepository->getActivePaginated(25, 'id', 'asc'));
    }
```

in the `App\Http\Controllers\Backend\Auth\User\UserController`.

There you have to change the first parameter of getActivePaginated to control the pagination.
I think you had overridden the default value in the UserRepository which does not work because the UserController gives the pagination count to the UserRepository.

For me it worked out of the box replacing the 25 with a 1 in the UserController.

**Comment by rappasoft** [comment]
True, I haven't checked to see if theres anything wrong, but the links will only show up when the amount of items being returned is greater than the amount per page.

**Comment by RVP04** [comment]
Yes it is important update required when we have huge amount data. please help me
