### ISSUE TITLE
Registration error from welcome page

### ISSUE THREAD

**Issue by thavorac** [rappasoft/laravel-5-boilerplate#983]
When trying to register user from welcome page, i got this error:

```
Swift_TransportException (530)
Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required "
```

**Comment by rappasoft** [comment]
You need to set up some type of mail sender probably. It's probably trying to send a confirmation e-mail.

**Comment by thavorac** [comment]
I updated the mail configuration and it works. So that mean, mail configuration is required.
I thought it is option.

By the way, thank you.

**Comment by rappasoft** [comment]
Mail configuration is required if your registration is going to be sending emails. If you turned off account confirmation it would probably work without it. But there are other places in the application that send mail. It's not likely you're going to create a laravel app without sending mail anyway so its pretty much a given.
