### ISSUE TITLE
Yajra datatables removed ? 

### ISSUE THREAD

**Issue by pappu687** [rappasoft/laravel-5-boilerplate#984]
Hi,

Any reason why Yajra datatables is removed for 5.5 boilerplate ?

**Comment by rappasoft** [comment]
So that people could choose their own preferred implementation instead of me forcing one solution on you.

**Comment by pappu687** [comment]
This is why we are using boilerplate, 😈 so that we get a range of components pre-installed and glued together. Most people won't even know that yajra-datatables exists. 

Anyways, you can close this if you want. I'd still opt for having that in. Makes life easier.

**Comment by rappasoft** [comment]
Yeah but some people would rather something like Vue and make their own, some can install datatables. The boilerplate provides enough functionality where things like that can be left up to the user because they're more of a convenience.
