### ISSUE TITLE
Question. Why is unsetClauses used in many places in Base Repository?

### ISSUE THREAD

**Issue by bloggervista** [rappasoft/laravel-5-boilerplate#985]
As title suggest i was reading code is there any reason for using it?

**Comment by bloggervista** [comment]
I mean when i check create method of base repository i wonder why unsetClauses was used? any reason

**Comment by rappasoft** [comment]
Did you read the actual function?

**Comment by bloggervista** [comment]
Yeah it will make those properties empty but still don't know why it was used in create method..
