### ISSUE TITLE
[Question] Where is catched the input for user and password?

### ISSUE THREAD

**Issue by pmirandaarias** [rappasoft/laravel-5-boilerplate#990]
[Question] Where is catched the input for user and password?

I can't find where is been used those inputs to compare them with the database.

I need to use a custom login with Laravel-LDAP and can't see where that happens.

Thanks in advance.

**Comment by pmirandaarias** [comment]
Well, I got it but in a bad way (editing vendor files).

The login() that Laravel-boilerplates calls in `app/Services/Access/Access.php` is this one:

/**
     * @param Authenticatable $user
     * @param bool            $remember
     */
    public function login(Authenticatable $user, $remember = false)
    {
        return auth()->login($user, $remember);
    }

Then in `vendor\laravel\framework\src\Illuminate\Foundation\Auth\AuthenticatesUsers.php` I have edited the `public function login(Request $request)` method like this way:

        if (\Adldap::auth()->attempt(str_replace('@example.com', '', $request->email), $request->password)) {
		   $this->validateLogin($request);

			// If the class is using the ThrottlesLogins trait, we can automatically throttle
			// the login attempts for this application. We'll key this by the username and
			// the IP address of the client making these requests into this application.
			if ($this->hasTooManyLoginAttempts($request)) {
				$this->fireLockoutEvent($request);

				return $this->sendLockoutResponse($request);
			}

			if ($this->attemptLogin($request)) {
				return $this->sendLoginResponse($request);
			}
		}
		else {
			// If the login attempt was unsuccessful we will increment the number of attempts
			// to login and redirect the user back to the login form. Of course, when this
			// user surpasses their maximum number of attempts they will get locked out.
			$this->incrementLoginAttempts($request);

			return $this->sendFailedLoginResponse($request);
		}

It all works fine, but how could I do it without touching this vendor file?

**Comment by bambamboole** [comment]
You could extend this class and insert your logic. It‘s all normal php. You can also read Laravel Docs to get in how to login users.

**Comment by pmirandaarias** [comment]
@bambamboole yeah, that's what I did too, it works. Now I have problems with the validation of the users and stuff, but that's another story. Thanks mate. Done, thread closed now.
