### ISSUE TITLE
Models with traits with HTML embed in PHP code?

### ISSUE THREAD

**Issue by alrik11es** [rappasoft/laravel-5-boilerplate#995]
https://github.com/rappasoft/laravel-5-boilerplate/blob/development/app/Models/Auth/Traits/Attribute/UserAttribute.php

I've been looking this library for it's use in production in specific project. But I've found some flaws on specific parts of the code. In fact the most parts are well written. But I cannot go with the traits with HTML embed on "Models?"

I guess it's done for speed development. But you have a good template engine there. Please use this instead of raw HTML on PHP code. In fact I don't really get the point of the models doing any render or giving any html at all.

    The Eloquent ORM included with Laravel provides a beautiful, simple ActiveRecord implementation for 
    working with your database. Each database table has a corresponding "Model" which is used to interact 
    with that table. Models allow you to query for data in your tables, as well as insert new records into the 
    table.

As an idea you can do a class that you pass a specific instance of the model and use this traits on this new class. It's not probably the best solution but at least you decouple the HTML from the models.

Anyway thanks for all the effort put in this startup-library. Don't let my comments discourage you.

**Comment by rappasoft** [comment]
Sometimes I'm willing to sacrifice 'the norm' for something that makes my life easier. It's using a bastardization of the accessors: https://laravel.com/docs/5.5/eloquent-mutators#defining-an-accessor to make displaying buttons faster.

I'd rather do $user->actions than use an includes file or something.

If people want to change that out then they can.
